### ISSUE TITLE
Missing Waterfall HAR - in Summary pages

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1030]
# Issue/Request

Is the waterfall/har still in works for the summary page(s)... I could not see that waterfall icon appearing in the summary pages like in previous version

# Issue/Bug report

### Setup
**sitespeed.io version**:
**Operating system**:
**Browser version**:

### Steps to reproduce
 1.
 2.
 3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

# Request
We love requests! Let us know what you want sitespeed.io todo. Request is a perfect way to start your PR. Write what you think is needed and we can discuss how you or we could implement it. Lets start by first proposing your idea to other contributors, that way you can get feedback on the idea before taking time to write precious code.

**Comment by beenanner** [comment]
@softwareklinic are you running the latest from npm or are you using a git cloned version of master?

**Comment by softwareklinic** [comment]
Latest from npm

**Comment by soulgalore** [comment]
Hey @softwareklinic 
on the summary pages you need to set <code>--html.showWaterfallSummary</code> because that page can be massive if you make many runs. Maybe we should invert that and call it hide instead so you turn it off instead. @beenanner what's your input?

Best 
Peter

**Comment by beenanner** [comment]
@soulgalore I think we should leave it as is. I prefer the pattern of opt-in for the extra feature/data as we do for things like 3rd vs 1st party. I agree the summary page can and will get very large for multiple runs. @softwareklinic just a note that the individual report page for each run linked off of the summary page will continue to contain the waterfall without passing the `--html.showWaterfallSummary` option.

![screenshot from 2016-06-29 22 43 46](https://cloud.githubusercontent.com/assets/723985/16475303/62af09f0-3e4b-11e6-83f0-2f2e53a0791d.png)

If you still need the waterfall data on the summary page for all runs passing the option @soulgalore posted above should give you what you desire.

**Comment by softwareklinic** [comment]
Im getting no waterfall... any insights...
./bin/sitespeed.js http://www.xxxxxxcom --html.showWaterfallSummary -n 1
./bin/sitespeed.js http://www.xxxxxxcom -n 1
./bin/sitespeed.js http://www.xxxxxxcom --html.showWaterfallSummary -n 1 -b firefox

**Comment by beenanner** [comment]
@softwareklinic can you test using https://www.google.com/ could be related to the HAR parsing of whatever URL you are testing.

**Comment by softwareklinic** [comment]
Right away......

Sent from my iPhone

On Jul 19, 2016, at 9:39 PM, Jonathan Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


@softwareklinic<https://github.com/softwareklinic> can you test using https://www.google.com/ could be related to the HAR parsing of whatever URL you are testing.

**Comment by softwareklinic** [comment]
didnt get for http://www.verizonwireless.com
did get it for http://www.google.com

??? surprised

**Comment by softwareklinic** [comment]
Here is my observation --- for whatever reason -- the browsertime.har.json --- does exist... but due to some kind of folder structure... its unable to show it in the HTML... i tried moving around the inner most folder with page level index.html and i could see some har plotted -- though without CSS special effects.. but looks like there is a BUG in the way HAR is looking for the har json.

e.g.

www.verizon.com/home/fios ---> create a folder www.verizon.com > home > fios > containing data & index.html (NO WF shown in Html)

Now, i moved the data & index.html directly under www.verizon.com --- then I could see the waterfall ofcourse without CSS special effects.... hope this will help you debug the issue...

**Comment by softwareklinic** [comment]
Any updates on waterfall rendering issue on the html summary pages

**Comment by soulgalore** [comment]
I tested now and could reproduce. This one works for me:
<pre>
bin/sitespeed.js http://www.verizonwireless.com --html.showWaterfallSummary -n 1
</pre>

But not with Firefox:
<pre>
bin/sitespeed.js http://www.verizonwireless.com --html.showWaterfallSummary -n 1 -b firefox
</pre>

I'll look into it asap.

**Comment by softwareklinic** [comment]
Also if.you check any pages.eg www.verizonwireless
Com/tablets

Doesn't show waterfall in UI - though the jsin does exist in.folder

Sent from my iPhone

On Aug 17, 2016, at 11:41 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested now and could reproduce. This one works for me:

bin/sitespeed.js http://www.verizonwireless.com --html.showWaterfallSummary -n 1


But not with Firefox:

bin/sitespeed.js http://www.verizonwireless.com --html.showWaterfallSummary -n 1 -b firefox


I'll look into it asap.

**Comment by beenanner** [comment]
@soulgalore appears to be breaking on the parsing of the content type in the perfCascade.js. We may need to submit a patch upstream in perfCascade to handle undefined content types.

**Comment by beenanner** [comment]
Related to https://20736885p.rfihub.com/ca.gif?rb=26563&ca=20736885&_o=26563&_t=20736885&ra=%n which is 302'ing and no content-type header.

**Comment by soulgalore** [comment]
ah great @beenanner :)

**Comment by softwareklinic** [comment]
these are probably 3rd party marketing/vendor tags...

**Comment by beenanner** [comment]
Hmm though strange saving the har from firefox appears to work with PerfCascade standalone. Back to digging into browsertime to see if there is something there we are doing differently.

**Comment by beenanner** [comment]
Filed https://github.com/sitespeedio/browsertime/issues/179 to investigate a bit more as time allows.

**Comment by softwareklinic** [comment]
This was my observation --- 



Here is my observation --- for whatever reason -- the browsertime.har.json --- does exist... but due to some kind of folder structure... its unable to show it in the HTML... i tried moving around the inner most folder with page level index.html and i could see some har plotted -- though without CSS special effects.. but looks like there is a BUG in the way HAR is looking for the har json.

e.g.

www.verizon.com/home/fios ---> creates a folder www.verizon.com > home > fios > containing data & index.html (NO WF shown in Html)

Now, i moved the data & index.html directly under www.verizon.com --- then I could see the waterfall ofcourse without CSS special effects.... hope this will help you debug the issue...

**Comment by soulgalore** [comment]
FYI the HAR is included in the HTML. I get a Javascript error from Perfcascade when it fails.

**Comment by soulgalore** [comment]
The undefined was on thing but maybe it's more @beenanner lets see.

**Comment by soulgalore** [comment]
This works for me in Firefox, would be great if @softwareklinic  can try. You need to test with the master branch.

**Comment by softwareklinic** [comment]
Will check in few

Sent from my iPhone

On Aug 19, 2016, at 11:23 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


This works for me in Firefox, would be great if @softwareklinic<https://github.com/softwareklinic> can try. You need to test with the master branch.

**Comment by softwareklinic** [comment]
Running into some kind of script timeout -- im simply testing a page -- no prescript here...

Keyurs-MacBook-Air:sitespeed.io-master FamilyMac$ bin/sitespeed.js MarkPagesToScan.txt -b firefox -n 1 --html.showWaterfallSummary
[2016-08-20 00:01:40] Versions OS: darwin 15.5.0 nodejs: v5.6.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-20 00:01:41] Will analyse 4 URLs from MarkPagesToScan.txt
[2016-08-20 00:01:41] Starting firefox for analysing https://www.verizonwireless.com/smartphones/ 1 time(s)
[2016-08-20 00:01:41] Testing url https://www.verizonwireless.com/smartphones/ run 1
[2016-08-20 00:02:34] ScriptTimeoutError: timed out
   at WebDriverError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at ScriptTimeoutError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:202:26)
    at Object.throwDecodedError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (node.js:402:9)
    at Driver.schedule (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeAsyncScript (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:651:17)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:181:28
From previous event:

**Comment by softwareklinic** [comment]
My Firefox is 47.0.1 - is that ok?

**Comment by softwareklinic** [comment]
Never mind i updated to 48.0.x - i works with that --- now checking for waterfall

**Comment by softwareklinic** [comment]
No Waterfall still - 

Custom scripts

There are no custom configured scripts.
Waterfall

**Comment by softwareklinic** [comment]
i dont see it creating any HAR files

**Comment by soulgalore** [comment]
can you check the console of the browser and copy/paste the error you get (from the page that should have the HAR).

**Comment by softwareklinic** [comment]
sure getting it

**Comment by softwareklinic** [comment]
This is what i get with 46.0.1 and 47.0.1 --- ERRORS --- with 48.0.1 --- it doesnt run into error-- -but no HAR generated

Keyurs-MacBook-Air:sitespeed.io-master FamilyMac$ bin/sitespeed.js MarkPagesToScan.txt -b firefox -n 1
[2016-08-20 00:42:29] Versions OS: darwin 15.5.0 nodejs: v5.6.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-20 00:42:30] Will analyse 4 URLs from MarkPagesToScan.txt
[2016-08-20 00:42:30] Starting firefox for analysing https://www.verizonwireless.com/smartphones/ 1 time(s)
[2016-08-20 00:42:30] Testing url https://www.verizonwireless.com/smartphones/ run 1
[2016-08-20 00:43:23] ScriptTimeoutError: timed out
    at WebDriverError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at ScriptTimeoutError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:202:26)
    at Object.throwDecodedError (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (node.js:402:9)
    at Driver.schedule (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeAsyncScript (/Users/FamilyMac/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:651:17)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:181:28
From previous event:
    at SeleniumRunner.runAsyncScript (/Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:175:11)
    at FirefoxDelegate.onStopIteration (/Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:55:19)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:39
From previous event:
    at runIteration (/Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:10)
    at /Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/FamilyMac/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/FamilyMac/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/FamilyMac/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/FamilyMac/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/FamilyMac/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/FamilyMac/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/FamilyMac/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by softwareklinic** [comment]
This is with FF 48.0.1

Keyurs-MacBook-Air:sitespeed.io-master FamilyMac$ bin/sitespeed.js MarkPagesToScan.txt -n 1 -b firefox
[2016-08-20 00:50:55] Versions OS: darwin 15.5.0 nodejs: v5.6.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-20 00:50:55] Will analyse 4 URLs from MarkPagesToScan.txt
[2016-08-20 00:50:55] Starting firefox for analysing https://www.verizonwireless.com/smartphones/ 1 time(s)
[2016-08-20 00:50:55] Testing url https://www.verizonwireless.com/smartphones/ run 1
[2016-08-20 00:51:08] Starting firefox for analysing https://www.verizonwireless.com/smartphones/page-2/ 1 time(s)
[2016-08-20 00:51:08] Testing url https://www.verizonwireless.com/smartphones/page-2/ run 1
[2016-08-20 00:51:21] Starting firefox for analysing https://www.verizonwireless.com/smartphones/page-3/ 1 time(s)
[2016-08-20 00:51:21] Testing url https://www.verizonwireless.com/smartphones/page-3/ run 1
[2016-08-20 00:51:34] Starting firefox for analysing https://www.verizonwireless.com/smartphones/samsung-galaxy-note-7/ 1 time(s)
[2016-08-20 00:51:34] Testing url https://www.verizonwireless.com/smartphones/samsung-galaxy-note-7/ run 1
[2016-08-20 00:51:59] Render HTML for 4 page(s) 
[2016-08-20 00:52:05] HTML stored in /Users/FamilyMac/sitespeed.io-master/sitespeed-result/MarkPagesToScan_txt/2016-08-20-00-50-55
[2016-08-20 00:52:05] Finished analysing MarkPagesToScan.txt

**Comment by soulgalore** [comment]
The parsin of the HAR happens in the frontend that's why I need the browser console log :)

**Comment by softwareklinic** [comment]
Let.me.check

Sent from my iPhone

On Aug 20, 2016, at 3:21 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


The parsin of the HAR happens in the frontend that's why I need the browser console log :)

**Comment by soulgalore** [comment]
argh it was my fault, the perfcascade js was wrongly included depending on the path. with latest fix master should work.

**Comment by softwareklinic** [comment]
can i pull it ???

**Comment by softwareklinic** [comment]
Awesome... testing with multiple pages now... worked with 1 page...

**Comment by softwareklinic** [comment]
Works great - maybe we.need better quality.icons for.the.new.tab structure

Sent from my iPhone

On Aug 20, 2016, at 8:45 AM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


argh it was my fault, the perfcascade js was wrongly included depending on the path. with latest fix master should work.

**Comment by soulgalore** [comment]
yes can you share a screenshot?

**Comment by softwareklinic** [comment]
Sure

**Comment by softwareklinic** [comment]
![sitespeed](https://cloud.githubusercontent.com/assets/7537289/17833659/3ba696e0-66e9-11e6-8c8b-9bf9968b552e.png)

**Comment by softwareklinic** [comment]
Can we move the "Custom Script" section to the very bottom --- im not sure how many users will use custom scripts -- but most of my test cases for past year or 2 have never used custom scripts... we might use it in future.. but if max use cases not use it--- we should move thsi section to bottom of this screen.

**Comment by softwareklinic** [comment]
Also, if there is only 1 RUN --- we should show the WatERFALL by default... currently we have to click on the RUN # then only it shows waterfall....

**Comment by soulgalore** [comment]
good idea, lets fix that!

**Comment by beenanner** [comment]
Not sure if we should show the waterfalls by default they are quite heavy and if we show them only for single runs it could cause confusion as well as inconsistency when multiple runs are executed. Maybe changing `--html.showWaterfallSummary` to be `--html.showWaterfall` and default it to false so when passed true it will show both the summary waterfall and the individual runs' waterfalls. For the custom scripts I think we can just hide that section if no custom script exist.

**Comment by softwareklinic** [comment]
That works - well.thought

**Comment by soulgalore** [comment]
I kind of like the idea of showing waterfalls by default, it's more of an implementation constraint showing many on the summary page. I agree @beenanner having different behaviour like it is now, isn't perfect lets change that (again).

Custom metrics: Like the idea of showing that you have not configured anyone so that we highlight that you have the opportunity but maybe we have different behaviour (we don't do it like that with other things) so we should then hide them.

**Comment by softwareklinic** [comment]
ok, i will wait for the changes 👍
