### ISSUE TITLE
Metrics from Browsertime generates error when flattening message for Graphite

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1051]
<pre>
[2016-07-13 18:03:29] Error: Unhandled value type undefined found when flattening data for prefix browserScripts.0.visualMetrics
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:75:17)
    at /Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:58:13
    at Array.forEach (native)
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:57:30)
    at /Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:58:13
    at Array.forEach (native)
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:57:30)
    at /Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:58:13
    at Array.forEach (native)
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:57:30)
    at Object.flattenMessageData (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:80:5)

</pre>

**Comment by tobli** [comment]
Do you have the original message data saved? Should make a good unit test.

**Comment by soulgalore** [comment]
We create the visualMetrics stats even if we have it or not so its an empty node. But I think I've seen it again, lets try out the metrics branch.

**Comment by soulgalore** [comment]
Another example:
<code>
[2016-07-29 18:22:14] Error: Unhandled value type undefined found when flattening data for prefix browserScripts.0.har.log.entries.12.request.cookies.0.path
    at recursiveFlatten (/home/travis/build/sitespeedio/sitespeed.io/lib/support/flattenMessage.js:75:17)
</code>

Let me add the HAR as an example in the test :)

**Comment by soulgalore** [comment]
Closing this reopen if don't work in 4.0.
