### ISSUE TITLE
Sitespeed.io - npm - unable to locate preSample.js

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1056]
I installed sitespeed.io as outlined in the readme.md using npm i -g sitespeed.io@canary

but still im facing the same issue as using the docker container... i have verified the file is having 777 permission and im running everything as root for now... still it is able to find the textfile with urls in it... as below but unable to locate the preSample.js... which is in the same folder as the text file...

$ sitespeed.io /home/ec2-user/sitespeed.io/myvzurllist.txt --preScript /home/ec2-user/sitespeed.io/preSample.js 
[2016-07-15 22:38:46] Versions OS: linux 4.4.14-24.50.amzn1.x86_64 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-alpha.21 coach: 0.24.2
(node:8740) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[2016-07-15 22:38:46] **Will analyse 9 URLs from /home/ec2-user/sitespeed.io/myvzurllist.txt**
[2016-07-15 22:38:46] _Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js_
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
[2016-07-15 22:38:46] Error: Couldn't load task file: /home/ec2-user/sitespeed.io/preSample.js
    at util.toArray.map.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:31:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:27:32)
    at new Engine (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:40:29)
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:87:18)
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:136:27)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
[2016-07-15 22:38:46] Render HTML for 9 page(s) 
[2016-07-15 22:38:47] Error TypeError: /usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/templates/help.pug:26
    24| 
    25|     h2(id='performanceAdvice') Performance advice
  > 26|     each advice, adviceKey in coach.data.coach.pageSummary.advice.performance.adviceList
    27|       h5(id=adviceKey) #{advice.title} (#{adviceKey})
    28|       p #{advice.description}
    29| 

Cannot read property 'data' of undefined
    24| 
    25|     h2(id='performanceAdvice') Performance advice
  > 26|     each advice, adviceKey in coach.data.coach.pageSummary.advice.performance.adviceList
    27|       h5(id=adviceKey) #{advice.title} (#{adviceKey})
    28|       p #{advice.description}
    29| 

Cannot read property 'data' of undefined
    at eval (eval at wrap (/usr/local/lib/node_modules/sitespeed.io/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:130:21)
    at template (eval at wrap (/usr/local/lib/node_modules/sitespeed.io/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:425:185)
    at getTemplate.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:36:27)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
From previous event:
    at Object.renderTemplate (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:36:8)
    at HTMLBuilder._renderSummaryPage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:157:67)
    at Object.keys.map (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:93:27)
    at Array.map (native)
    at HTMLBuilder.renderHTML (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:93:8)
    at Object.close (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:87:29)
    at Promise.resolve.filter.map (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:33:49)
From previous event:
    at runOptionalFunction (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:33:6)
    at runOptionalFunction.then.tap (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:82:32)
From previous event:
    at loader.loadPlugins.then (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:82:16)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:70:12)
From previous event:
    at Object.run (/usr/local/lib/node_modules/sitespeed.io/lib/sitespeed.js:67:8)
    at loader.parsePluginNames.then (/usr/local/lib/node_modules/sitespeed.io/bin/sitespeed.js:24:22)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/sitespeed.io/bin/sitespeed.js:23:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:340:7)
    at startup (bootstrap_node.js:132:9)
    at bootstrap_node.js:455:3

**Comment by softwareklinic** [comment]
Even after trying to run using the local install  by cloning the repo... it was not working... so the only way it works... is if the TEXT file with URLS and the JS file is in same folder where sitespeed.io has been cloned eg.

my sitespeed.io is in /opt/sitespeed.io

so if i run this command and if both my files are present in the sitespeed.io it works fine

 bin/sitespeed.js myvzurllist.txt --preScript preSample.js 

but if the preSample.js is somewhere else on another folder... and even if i give full path.. or i run sitespeed from that other folder as current directory... it doesnt work... this is a difficult situation if i need to CRON this

**Comment by soulgalore** [comment]
Hi @softwareklinic 
let me test it tonight.

Best
Peter

**Comment by softwareklinic** [comment]
Ty

**Comment by soulgalore** [comment]
I tested on my local.
<pre>
sitespeed.io --version
sitespeed.io 4.0.0-alpha.5

sitespeed.io list.txt --preScript git/sitespeed.io/test/prepostscripts/preSample.js -n 1
[2016-07-16 09:10:34] Versions OS: darwin 15.5.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-alpha.21 coach: 0.24.2
[2016-07-16 09:10:35] Will analyse 1 URLs from list.txt
[2016-07-16 09:10:35] Starting chrome for analysing https://www.sitespeed.io 1 time(s)
[2016-07-16 09:10:35] Testing url https://www.sitespeed.io run 1
[2016-07-16 09:10:36] In pretask!!!
...
</pre>
I'll check tonight if I can reproduce.

Best
Peter

**Comment by softwareklinic** [comment]
Ty its working on my.local mac

Just not on aws any os
