### ISSUE TITLE
Docker container - invalid locator

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1058]
root@a5d083bd4549:/sitespeed.io# sitespeed.io myvzurllist.txt -b chrome --preScript ./presample.js
[2016-07-17 05:30:18] Versions OS: linux 4.4.14-24.50.amzn1.x86_64 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-alpha.22 coach: 0.24.2
[2016-07-17 05:30:19] Will analyse 9 URLs from myvzurllist.txt
[2016-07-17 05:30:19] Starting chrome for analysing https://ebillpay.verizonwireless.com/myv/overview/ 3 time(s)
[2016-07-17 05:30:19] Testing url https://ebillpay.verizonwireless.com/myv/overview/ run 1
[2016-07-17 05:30:27] TypeError: Invalid locator
    at Object.check [as checkedLocator] (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/by.js:267:9)
    at Driver.findElement (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver.js:857:18)
    at /sitespeed.io/presample.js:17:35
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
[2016-07-17 05:30:27] Starting chrome for analysing https://ebillpay.verizonwireless.com/vzw/accountholder/payment/displayPaymentHistory

**Comment by softwareklinic** [comment]
I downloaded selenium+xvfb container -- and tried to run without prescript --- it worked fine... but when i add the prescript.... it throws invalid locator.....

Google Chrome 51.0.2704.63 
Mozilla Firefox 46.0.1
Starting Xvfb ...
Set kind of cable connectivity
[2016-07-18 21:20:57] Versions OS: linux 4.4.14-24.50.amzn1.x86_64 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-alpha.22 coach: 0.24.2
[2016-07-18 21:20:58] Starting chrome for analysing http://www.verizonwireless.com 3 time(s)
[2016-07-18 21:20:58] Testing url http://www.verizonwireless.com run 1
[2016-07-18 21:21:29] TypeError: Invalid locator
    at Object.check [as checkedLocator] (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/by.js:267:9)

**Comment by softwareklinic** [comment]
I'm now good running with docker on AWS... only problem is with "invalid locator" @tobli or @beenanner - can u help? 

What is "invalid locator" - is it a problem with the way JS is written... or its unable to find element?

**Comment by beenanner** [comment]
@softwareklinic I would try to trim down your preScript until it works to see which line of code is the culprit.

**Comment by softwareklinic** [comment]
Yes, the error message clearly gives the line and position

at /sitespeed.io/presample.js:17:35

var loginInput = driver.findElement(By.id('IDToken1'));

this is the line of error.... line 17 and position 35 (which is .findElement)

**Comment by softwareklinic** [comment]
Can put the entire script here..... so u probably evaluate?

**Comment by softwareklinic** [comment]
'use strict';
let webdriver = require('selenium-webdriver');
let By = webdriver.By;

function sleep(delay) {
        var start = new Date().getTime();
        while (new Date().getTime() < start + delay);
      }
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('http://www.verizonwireless.com/')
        .then(() => {
          var userName = 'xxxxxxxxx';
          var sq = 'xxxxxxxxx';
          var password = 'xxxxxxxxxx';
sleep(3000);
//          var webdriver = require('selenium-webdriver');
//        var By = webdriver.By;
          // NAVIGATING TO HOME PAGE
          var loginInput = driver.findElement(By.id('IDToken1'));
          loginInput.click();
          loginInput.clear();
          loginInput.sendKeys(userName);

          driver.findElement(By.xpath("(//button[@type='submit'])[4]")).click();
sleep(3000);
          // NAVIGATING TO THE PASSWORD PAGE
          var passwordinput = driver.findElement(By.id('IDToken2'));
          passwordinput.click();
          passwordinput.clear();
          passwordinput.sendKeys(password);
          driver.findElement(By.css("button.o-red-button")).click();
          // NAVIGATES TO THE HOME PAGE - AS SIGNED IN
        });
    })
  }
};

**Comment by softwareklinic** [comment]
this script is certainly running on my MAC using the git cloned 4.0 alpha 5 --- sitespeed.js --- just not on docker

**Comment by soulgalore** [comment]
original issue fixed
