### ISSUE TITLE
npm install 404 error for soprano-saxophone-temp

### ISSUE THREAD

**Issue by rschoessler** [sitespeedio/sitespeed.io#1124]
When trying to npm install latest for #962 I get the following error:

```
c:\sitespeed\sitespeed.io\bin>npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nod
esecurity.io/advisories/130
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolch
ain, use it instead!
\
> soprano-saxophone-temp@0.10.0 install c:\sitespeed\sitespeed.io\node_modules\browsertime
\node_modules\soprano-saxophone-temp
> node install.js


c:\sitespeed\sitespeed.io\node_modules\browsertime\node_modules\soprano-saxophone-temp\ins
tall.js:31
        throw err;
        ^
 HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (c:\sitespeed\sitespeed.io\node_modules\browsertime\node_m
odules\soprano-saxophone-temp\node_modules\download\node_modules\got\index.js:192:24)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Immediate._onImmediate (c:\sitespeed\sitespeed.io\node_modules\browsertime\node_mod
ules\soprano-saxophone-temp\node_modules\download\node_modules\got\index.js:58:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

> alto-saxophone@2.22.0 install c:\sitespeed\sitespeed.io\node_modules\browsertime\node_mo
dules\alto-saxophone
> node install.js

     fetch : http://chromedriver.storage.googleapis.com/2.22/chromedriver_win32.zip
  progress : [====================] 100% 0.0s

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modul
es\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! soprano-saxophone-temp@0.10.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soprano-saxophone-temp@0.10.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the soprano-saxophone-temp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs soprano-saxophone-temp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls soprano-saxophone-temp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\sitespeed\sitespeed.io\bin\npm-debug.log


```

**Comment by soulgalore** [comment]
Ah could it be that you run win32? I see there are no Geckodriver released (yet) for that but there's an issue for fixing this. It shouldn't fail like that however, let me fix that.

**Comment by rschoessler** [comment]
Yes, this was on Windows.

**Comment by rschoessler** [comment]
Looks like I can now do an `npm install` fine now after a `git pull`.

**Comment by XhmikosR** [comment]
@soulgalore: please try and set up AppVeyor and ping me on #123. This error is clearly shown on AppVeyor.

**Comment by soulgalore** [comment]
this should work in 4.0
