### ISSUE TITLE
Error while running Docker 4.0 -alpha 5

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1144]
ubuntu@ip-99-99-99-99-2:~$ sudo docker run --privileged --rm --dns=999.99.999.9 --dns=99.99.99.99 --dns=999.99.999.99 -e "http_proxy=http://proxy.xxxxxxx.com:80/" -e "https_proxy=http://proxy.xxxxx.com:80/" -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:4.0-alpha sitespeed.io http://www.verizonwireless.com --preScript preSample.js -b chrome -n 1
Fri Aug 19 06:34:30 UTC 2016
Google Chrome 51.0.2704.106 
Mozilla Firefox 47.0
Starting Xvfb ...
[2016-08-19 06:34:30] Versions OS: linux 3.13.0-91-generic sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-alpha.22 coach: 0.24.2
[2016-08-19 06:34:31] Starting chrome for analysing http://www.verizonwireless.com 1 time(s)
[2016-08-19 06:34:31] Testing url http://www.verizonwireless.com run 1
[2016-08-19 06:34:44] Err**or: Cannot find module 'selenium-webdriver'**
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /sitespeed.io/preSample.js:9:27
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
[2016-08-19 06:34:44] Render HTML for 1 page(s) 
[2016-08-19 06:34:45] Error TypeError: /usr/lib/node_modules/sitespeed.io/lib/plugins/html/templates/assets.pug:5
    3| 
    4|

**Comment by soulgalore** [comment]
I think with that version you need to install the webdriver yourself if you want to use it. In the coming beta (the fix that was done a week or so) you will get the current webdriver object inside the context object, so you easily can get hold of it.

**Comment by softwareklinic** [comment]
Maybe I can make my own docker image by using the 4.0 alpha 5… and installing seleniuv-webdriver as a part of image creation…??? thoughts

**Comment by soulgalore** [comment]
yes that will work. Plan to release the beta this weekend so then you can use the new version.

**Comment by soulgalore** [comment]
this hopefully works in 4.0
