### ISSUE TITLE
Scripted timeout - for some pages

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1146]
[2016-08-20 09:33:47] ScriptTimeoutError: Timed out
    at WebDriverError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at ScriptTimeoutError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:202:26)
    at Object.throwDecodedError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeAsyncScript (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:651:17)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:181:28
From previous event:
    at SeleniumRunner.runAsyncScript (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:175:11)
    at FirefoxDelegate.onStopIteration (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:55:19)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:39
From previous event:
    at runIteration (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:10)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/xxxxxxxxx/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by softwareklinic** [comment]
Is it configurable? or what could be causing it

**Comment by soulgalore** [comment]
Hey @softwareklinic 
the error comes when the [HAR export trigger](https://github.com/firebug/har-export-trigger) timeouts when we try to get the HAR file (the default timeout is 40 s). I've seen it also. Do you know if it happens all the time with the same URL (=something wrong with the plugin) or sometimes work (=we increase the timeout and it will work).

I'll do two changes right away: I'll add a log statement so it's easier to see that the plugin fails, it will make it easier for people reporting so we know what happens and increase the timeout. 

You can change the timeout right now with <code>--browsertime.timeouts.script 80000<code> (it is in ms) to see if it helps.

**Comment by softwareklinic** [comment]
Sure will use.it.and try.again

Sent from my iPhone

On Aug 20, 2016, at 2:59 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic>
the error comes when the HAR export trigger<https://github.com/firebug/har-export-trigger> timeouts when we try to get the HAR file (the default timeout is 40 s). I've seen it also. Do you know if it happens all the time with the same URL (=something wrong with the plugin) or sometimes work (=we increase the timeout and it will work).

I'll do two changes right away: I'll add a log statement so it's easier to see that the plugin fails, it will make it easier for people reporting so we know what happens and increase the timeout.

You can change the timeout right now with --browsertime.timeouts.script 80000 (it is in ms) to see if it helps.

**Comment by softwareklinic** [comment]
getting different errors @ different point of run @ different runs

**error type 1**

[2016-08-20 16:19:03] Could not load URLUrlLoadError: Failed to load https://www.verizonwireless.com/smartphones/
[2016-08-20 16:19:03] https://www.verizonwireless.com/smartphones/ generated the following error in Browsertime UrlLoadError: Failed to load https://www.verizonwireless.com/smartphones/
    at BrowsertimeError (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/support/errors.js:4:31)
    at UrlLoadError (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/support/errors.js:18:36)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:146:15
From previous event:
    at SeleniumRunner.loadAndWait (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:144:13)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:174:27
From previous event:
    at runIteration (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:174:10)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/v585896/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**error type 2**

[2016-08-20 16:22:47] Testing url https://www.verizonwireless.com/smartphones/samsung-galaxy-s7/ run 1
[2016-08-20 16:22:53] JavascriptError: TypeError: body is null
    at WebDriverError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at JavascriptError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:132:26)
    at Object.throwDecodedError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeScript (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:563:16)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:168:28
From previous event:
    at SeleniumRunner.runScript (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:162:11)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:107:27
From previous event:
    at runScript (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:88:10)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:125:16
From previous event:
    at runScriptInCategory (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:123:22)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:145:20
From previous event:
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:142:26
From previous event:
    at runScripts (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:140:10)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:176:31
From previous event:
    at runIteration (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:175:10)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/v585896/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**error type 3**

[2016-08-20 16:20:42] Testing url https://www.verizonwireless.com/smartphones/samsung/ run 1
[2016-08-20 16:22:22] ScriptTimeoutError: Timed out
    at WebDriverError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at ScriptTimeoutError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:202:26)
    at Object.throwDecodedError (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeAsyncScript (/Users/v585896/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:651:17)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:181:28
From previous event:
    at SeleniumRunner.runAsyncScript (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:175:11)
    at FirefoxDelegate.onStopIteration (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:55:19)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:39
From previous event:
    at runIteration (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:195:10)
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/v585896/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/v585896/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/v585896/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/v585896/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by jessejacob** [comment]
Running 4.0.0-alpha.5, I'm seeing a lot of transient instances of the type 1 error from @softwareklinic above. The frustrating part is that it doesn't fail the run, and often every url after that one from the url list will fail with the same error, so I have some jobs with 8 pages in the results on one run, then 5 in the next, then 1, then 8 again. My team is loving Sitespeed, but we're getting pretty inconsistent results from day to day. Should I start a new issue or is this related? Example:
[valid_url] generated the following error in Browsertime UrlLoadError: Failed to load [valid_url]
    at BrowsertimeError (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\lib\support\errors.js:5:10)
    at UrlLoadError (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\lib\support\errors.js:19:10)
    at c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\lib\core\seleniumRunner.js:131:15
    at tryCatcher (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:679:18)
    at Async._drainQueue (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
---------------------------------------------
    at Async._schedule (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\schedule.js:12:53)
    at Async._queueTick (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\async.js:157:14)
    at AsyncSettlePromises [as settlePromises] (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\async.js:88:10)
    at Promise._fulfill (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:630:19)
    at Promise._resolveCallback (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:423:57)
    at resolve (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\bluebird\js\release\thenables.js:73:17)
    at ManagedPromise.invokeCallback_ (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\selenium-webdriver\lib\promise.js:2775:27
    at c:\program files\sitespeed.io-4.0.0-alpha.5\node_modules\browsertime\node_modules\selenium-webdriver\lib\promise.js:639:7

**Comment by soulgalore** [comment]
Hey @jessejacob ,
if you could share the URLs offlist so we can reproduce that would be great peter [AT] soulgalore [dot] com and share your setup.

We have done some fixes in the coming beta that is ready for release, see if could put it out there today/tomorrow. However, there still could be problems, so lets handover the URLs so we can test, that would be great.

Do you run on Windows? We officially don't support Windows but you can run on Docker.  The reason is that it is too much work for us to keep up with testing and making sure it works on Windows. It may work but it's safer to run using Docker/Linux. It's also easier for us to reproduce.

>  inconsistent results from day to day.

Like failing tests or inconsistent metrics?

Best
Peter

**Comment by soulgalore** [comment]
Hey @jessejacob , I've put your example URLs on DO and get the same on Firefox/Linux, the problem is within Firefox ecosystem (Gecko/Marionette/Firefox/HAR export trigger) but let's change default behaviour so that if the HAR is missing we still get and collect all other metrics: https://github.com/sitespeedio/browsertime/issues/185

Best
Peter

**Comment by soulgalore** [comment]
Closing old issues. Please reopen if you this still is an issue for 4.0.
