### ISSUE TITLE
Script error - for 1 particular page

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1147]
while testing with master branch  -- running into a typical error while testing below page...

[2016-08-20 15:35:51] Testing url https://www.verizonwireless.com/smartphones/samsung-galaxy-s7/ run 1
[2016-08-20 15:35:56] JavascriptError: TypeError: body is null
    at WebDriverError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:26:26)
    at JavascriptError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:132:26)
    at Object.throwDecodedError (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:386:15)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/http.js:328:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Driver.executeScript (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/selenium-webdriver/lib/webdriver.js:563:16)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:168:28
From previous event:
    at SeleniumRunner.runScript (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/seleniumRunner.js:162:11)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:107:27
From previous event:
    at runScript (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:88:10)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:125:16
From previous event:
    at runScriptInCategory (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:123:22)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:145:20
From previous event:
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:142:26
From previous event:
    at runScripts (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:140:10)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:176:31
From previous event:
    at runIteration (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:175:10)
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/browsertime/lib/core/engine.js:231:8)
    at /Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/Users/xxxxxxxxx/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at /Users/xxxxxxxxx/sitespeed.io-master/lib/support/queueHandler.js:157:57
    at drainItem (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/xxxxxxxxx/sitespeed.io-master/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by soulgalore** [comment]
Cannot reproduce it now, it must have been some content that what messing things up, I wonder what it was?

**Comment by softwareklinic** [comment]
we can close this one - focus our energy on what matters
