### ISSUE TITLE
After installed sitespeed，I have meet this exception.

### ISSUE THREAD

**Issue by MichaelMaGG** [sitespeedio/sitespeed.io#1155]
After installed. I try to use sitespeed to test our website, but i met this problem.
I don't know why ,and get nothing from google. Can you help me to solve this problem?

and this is the exception information:

[ziroom@pf-dev bin]$ ./sitespeed.js http://www.ziroom.com
[2016-08-24 14:37:59] Versions OS: linux 2.6.32-642.1.1.el6.x86_64 nodejs: v6.4.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-24 14:37:59] Starting chrome for analysing http://www.ziroom.com 3 time(s)
[2016-08-24 14:37:59] Testing url http://www.ziroom.com run 1
[2016-08-24 14:37:59] http://www.ziroom.com generated the following error in Browsertime BrowserError: File does not exist: /home/ziroom/runtime/sitespeed.io-master/node_modules/.2.23.1@alto-saxophone/vendor/chromedriver
    at BrowsertimeError (/home/ziroom/runtime/sitespeed.io-master/node_modules/.1.0.0-beta.1@browsertime/lib/support/errors.js:5:5)
    at BrowserError (/home/ziroom/runtime/sitespeed.io-master/node_modules/.1.0.0-beta.1@browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/home/ziroom/runtime/sitespeed.io-master/node_modules/.1.0.0-beta.1@browsertime/lib/core/seleniumRunner.js:78:15)
    at tryCatcher (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:681:18)
    at Async._drainQueue (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/async.js:138:16)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/debuggability.js:369:19)
    at Promise._then (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:230:17)
    at Promise.then (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:123:17)
    at Object.analyzeUrl (/home/ziroom/runtime/sitespeed.io-master/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/home/ziroom/runtime/sitespeed.io-master/lib/plugins/browsertime/index.js:138:27)
    at queue.process (/home/ziroom/runtime/sitespeed.io-master/lib/support/queueHandler.js:157:57)
    at drainItem (/home/ziroom/runtime/sitespeed.io-master/node_modules/.7.0.1@concurrent-queue/index.js:92:21)
    at Immediate.drain (/home/ziroom/runtime/sitespeed.io-master/node_modules/.7.0.1@concurrent-queue/index.js:73:84)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
[2016-08-24 14:37:59] Render HTML for 1 page(s) 
[2016-08-24 14:37:59] Error TypeError: /home/ziroom/runtime/sitespeed.io-master/lib/plugins/html/templates/domains.pug:5
    3| 
    4| mixin rows(domainStats)
  > 5|   each domain in domainStats
    6|     tr
    7|       td.url.assetsurl(data-title='Domain') #{domain.domainName}
    8|       +statsCell(domain.blocked, 'Blocked', 'max')

Cannot read property 'length' of undefined
    3| 
    4| mixin rows(domainStats)
  > 5|   each domain in domainStats
    6|     tr
    7|       td.url.assetsurl(data-title='Domain') #{domain.domainName}
    8|       +statsCell(domain.blocked, 'Blocked', 'max')

Cannot read property 'length' of undefined
    at Object.eval (eval at wrap (/home/ziroom/runtime/sitespeed.io-master/node_modules/.2.0.2@pug-runtime/wrap.js:6:10), <anonymous>:88:31)
    at Object.pug_mixins.rows.pug_interp [as rows] (eval at wrap (/home/ziroom/runtime/sitespeed.io-master/node_modules/.2.0.2@pug-runtime/wrap.js:6:10), <anonymous>:149:4)
    at eval (eval at wrap (/home/ziroom/runtime/sitespeed.io-master/node_modules/.2.0.2@pug-runtime/wrap.js:6:10), <anonymous>:294:19)
    at template (eval at wrap (/home/ziroom/runtime/sitespeed.io-master/node_modules/.2.0.2@pug-runtime/wrap.js:6:10), <anonymous>:327:184)
    at getTemplate.then (/home/ziroom/runtime/sitespeed.io-master/lib/plugins/html/renderer.js:36:27)
    at tryCatcher (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:630:18)
    at /home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/nodeback.js:42:21
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/debuggability.js:369:19)
    at Promise._then (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:230:17)
    at Promise.then (/home/ziroom/runtime/sitespeed.io-master/node_modules/.3.4.1@bluebird/js/release/promise.js:123:17)
    at Object.<anonymous> (/home/ziroom/runtime/sitespeed.io-master/bin/sitespeed.js:23:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by MichaelMaGG** [comment]
And another question: 
I use the documention way to run sitespeed
"sitespeed.js -u http://www.ziroom.com" it responed the result like "sitespeed.js -h"

but i used "sitespeed.js http://www.ziroom.com" it responed the exception like my first question.

Does it mean that the 4.0's commond has been changed?

**Comment by MichaelMaGG** [comment]
I have solved the first problem. it said "can not found ... chromedriver" clearly.
but i have a new error.
"generated the following error in BrowserError: Server terminated early with status 127"
google explains it means "command not found"
so i want to know that how can i check what i didn't install?

**Comment by tobli** [comment]
Hi,
You seem to be running the latest code checked out directly from git. This is generally not recommended unless you're working developing sitespeed.io. If you really want to try out the 4.0 alphas, please use:
```sh
npm i -g sitespeed.io@canary
```

To use the stable 3.x version, use:
```sh
npm i -g sitespeed.io
```

That said, there seems to be some issue with installation of dependencies (such as chromedriver). Make sure the ```npm install```step runs without errors (and rerun npm install if package.json have changed after a git pull)

**Comment by MichaelMaGG** [comment]
thank you very much!
But I try to use "npm i -g sitespeed.io" this to install, it always have this error, i make sure i remove all the sitespeed from my server, because i use "find / -name sitespeed.io"

can you tell me the reason?

**the error information:**
execute post install scripts...
[phantomjs-prebuilt@2.1.3] scripts.install: "node install.js" at /usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.2.1.3@phantomjs-prebuilt
Looks like an `npm install -g`; unable to check for already installed version.
Phantom installation failed TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at findSuitableTempDirectory (/usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.2.1.3@phantomjs-prebuilt/install.js:126:30)
    at /usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.2.1.3@phantomjs-prebuilt/install.js:442:19
    at nextTickCallback (/usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.0.7.0@kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at findSuitableTempDirectory (/usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.2.1.3@phantomjs-prebuilt/install.js:126:30)
    at /usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.2.1.3@phantomjs-prebuilt/install.js:442:19
    at nextTickCallback (/usr/local/lib/node_modules/.sitespeed.io_npminstall/node_modules/.0.7.0@kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node install.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by MichaelMaGG** [comment]
thank you！
I succeed！

But i used example commad to try it. I found this. I consider it may cause by something not compatible.

![sitespeed](https://cloud.githubusercontent.com/assets/6170926/17968810/54266120-6b01-11e6-8f3b-6b24632eb6a1.png)

**Comment by MichaelMaGG** [comment]
update the npm,  and can solve the problem!
