### ISSUE TITLE
Issue with Docker & behind VPN/firewall

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1161]
I created a docker image from 4.0 Master branch and was able to run the sitespeed against plain urls and also the urls after signin using preloginscript.js --- but once i logged into the VPN, it just keeps stalling and doesnt work anymore... doesnt move past below point.... 

TUSTX002ML1102V:~ xxxxxxxxx$  docker run --privileged -v /Users/xxxxxxxxx/sitespeed.io:/sitespeed.io vzsitespeed sitespeed.io myvzurllist.txt  -n 1  --preScript preloginscript.js --graphite.host 99.99.99.99 --graphite.namespace MyVZW 
Fri Aug 26 06:16:49 UTC 2016
Google Chrome 52.0.2743.116 
Mozilla Firefox 48.0
Starting Xvfb ...
[2016-08-26 06:16:49] Versions OS: linux 4.4.15-moby nodejs: v4.5.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-26 06:16:50] Will analyse 16 URLs from myvzurllist.txt
[2016-08-26 06:16:50] Starting chrome for analysing https://ebillpay.verizonwireless.com/myv/overview/ 1 time(s)
[2016-08-26 06:16:50] Testing url https://ebillpay.verizonwireless.com/myv/overview/ run 1

**Comment by beenanner** [comment]
what happens if you run it with the --net=host option? I doubt the docker bridge can connect through the VPN, but maybe using the host network it can.

**Comment by softwareklinic** [comment]
I uses --dns=nameserverip and -e "to pass http_proxy" --- and i'm able to use curl -i http://www.google.com and http://www.verizonwireless.com --- from within container BASH

But --- when i run sitespeed io with the same url using the image from my linux host --- it is unable to launch browser.... I have created a docker image myself --- using the sitespeed.io MASTER branch... this setup works perfectly from my MAC (over the internet) --- and also MAC (over the VPN) --- just not working from my AWS linux instance...

Sun Aug 28 16:38:03 UTC 2016
Google Chrome 52.0.2743.116 
Mozilla Firefox 48.0
Starting Xvfb ...
root@9d5a411b5c55:/sitespeed.io# curl -I http://www.google.com
HTTP/1.1 200 OK
Date: Sun, 28 Aug 2016 16:38:15 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Transfer-Encoding: chunked
Accept-Ranges: none
Vary: Accept-Encoding
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Set-Cookie: NID=85=OcXWUM2xQPr7WzFBtgZDx3JpkaoD1BbUag12z3I6CAkxRzyBnIqNd50M1KJ_ohhQKkDANyPxCRp9zq6Gsqk6dsj77x5HlQWfsON45fO-6q1akyixAKHi86UoNz-4HL4VR4wardY412qfVIo; expires=Mon, 27-Feb-2017 16:38:15 GMT; path=/; domain=.google.com; HttpOnly

root@9d5a411b5c55:/sitespeed.io# curl -I http://www.verizonwireless.com
HTTP/1.1 301 Moved Permanently
Location: HTTPS://www.verizonwireless.com/
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Date: Sun, 28 Aug 2016 16:38:23 GMT

BELOW is the ERROR i get while running from the AWS linux host --- using sitespeed docker...

Sun Aug 28 16:30:54 UTC 2016
Google Chrome 52.0.2743.116 
Mozilla Firefox 48.0
Starting Xvfb ...
[2016-08-28 16:30:54] Versions OS: linux 3.10.0-327.3.1.el7.x86_64 nodejs: v4.5.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-08-28 16:30:55] Starting chrome for analysing http://www.verizonwireless.com 1 time(s)
[2016-08-28 16:30:55] Testing url http://www.verizonwireless.com run 1
[2016-08-28 16:31:55] Browser failed to start in time, trying one more time.
[2016-08-28 16:32:55] http://www.verizonwireless.com generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:10)
    at BrowserError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:10)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:78:15
From previous event:
    at SeleniumRunner.start (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:77:13)
From previous event:
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:231:8)
    at /usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:141:27)
    at /usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    at SeleniumRunner.startBrowser (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:36:10)
    at SeleniumRunner.start (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:41:25)
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:158:21)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:233:25
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[2016-08-28 16:32:55] Render HTML for 1 page(s) 
[2016-08-28 16:32:55] Error TypeError: Cannot read property 'score' of undefined
    at module.exports (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/setup/summaryBoxes.js:60:35)
    at HTMLBuilder.renderHTML (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:88:189)
    at Object.close (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:88:29)
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:35:49
From previous event:
    at runOptionalFunction (/usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:35:6)
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:99:32
From previous event:
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:99:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:86:12
    at /usr/lib/node_modules/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at Object.run (/usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:83:8)
    at /usr/lib/node_modules/sitespeed.io/bin/sitespeed.js:24:22
From previous event:
    at Object.<anonymous> (/usr/lib/node_modules/sitespeed.io/bin/sitespeed.js:23:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:

**Comment by softwareklinic** [comment]
I fixed this by passing our own Windows based selenium grid... no need to use the docker internal selenium --- no need to worry about setting all the --dns & http_proxy variables... im good with this..
