### ISSUE TITLE
Firefox HAR export errors on every page with beta 1

### ISSUE THREAD

**Issue by jessejacob** [sitespeedio/sitespeed.io#1216]
Firefox esr latest (45.4.0) works fairly reliably with v4alpha5, but after trying v4beta1 on same machine (Windows 7) the log hangs for 1 min 20 seconds on "Executing async script GET_HAR_SCRIPT", then drops a stacktrace:

```
[2016-09-21 11:01:37] Executing async script GET_HAR_SCRIPT
[2016-09-21 11:02:57] Couldn't generate the HAR from Firefox from the HAR Export Trigger.
[2016-09-21 11:02:57] Telling browser to quit.
[2016-09-21 11:02:57] ScriptTimeoutError: timed out
    at WebDriverError (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\error.js:27:10)
    at ScriptTimeoutError (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\error.js:203:10)
    at Object.throwDecodedError (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\error.js:477:11)
    at parseHttpResponse (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:386:15)
    at c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\http.js:328:11
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.executeScript()
    at Driver.schedule (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:414:17)
    at Driver.executeAsyncScript (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver.js:651:17)
    at c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\lib\core\seleniumRunner.js:186:28
    at tryCatcher (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\method.js:39:29)
    at SeleniumRunner.runAsyncScript (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\lib\core\seleniumRunner.js:180:11)
    at FirefoxDelegate.onStopIteration (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\lib\core\engineDelegate\firefoxDelegate.js:52:19)
    at c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\lib\core\engine.js:195:39
    at PassThroughHandlerContext.finallyHandler (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (c:\program files\sitespeed.io-4.0.0-beta.1\node_modules\browsertime\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```
Rolling back to v4alpha5 still works fine, so I'll keep using that in the meantime.

**Comment by tobli** [comment]
Hi @jessejacob!
Unfortunately Firefox support is kind of shaky right now, due to moving parts out of our control.
- Firefox recently started requiring plugins to be signed, and Har Export Trigger hasn't released a new signed version in a while (see https://github.com/sitespeedio/browsertime/issues/188).
- Firefox also switched from a built in WebDriver server (still in the 45.x version) to a standalone geckodriver process. Newer versions (such as FF 49) only supports the new geckodriver setup.
- To support geckodriver and recent Firefox versions we're using Selenium 3, which is still in beta.

This combined has broken things a number of times in the recent months. We hope things will shake out soon, but it'll be a bumpy ride for a while.

**Comment by soulgalore** [comment]
Using our Docker container is the safest way to know that browsers and dependencies are ok + the only way we can (almost) guatantee that things works on windows!

**Comment by soulgalore** [comment]
Hopefully this will work fine in final 4.0
