### ISSUE TITLE
URL generates error with beta.3 is breaking

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1221]
docker run --privileged --rm -v /Users/xxxxxxxx/:/sitespeed.io sitespeedio/sitespeed.io:4.0-beta.3 https://www.verizonwireless.com -n 1
Google Chrome 52.0.2743.116 
Mozilla Firefox 48.0
Starting Xvfb ...
[2016-09-26 16:08:10] Versions OS: linux 4.4.15-moby nodejs: v6.4.0 sitespeed.io: 4.0.0-beta.3 browsertime: 1.0.0-beta.5 coach: 0.27.0
[2016-09-26 16:08:10] Starting chrome for analysing https://www.verizonwireless.com 1 time(s)
[2016-09-26 16:08:10] Testing url https://www.verizonwireless.com run 1
[2016-09-26 16:08:18] TypeError: Cannot convert undefined or null to object
    at Object.human (/usr/src/app/node_modules/webcoach/lib/har/util.js:75:11)
    at allAdvice.map.reduce.then (/usr/src/app/node_modules/webcoach/lib/har/index.js:47:45)
From previous event:
    at Promise.resolve.map (/usr/src/app/node_modules/webcoach/lib/har/index.js:34:10)
From previous event:
    at Object.module.exports.runAdvice (/usr/src/app/node_modules/webcoach/lib/har/index.js:15:6)
    at Object.runHarAdvice (/usr/src/app/node_modules/webcoach/lib/index.js:84:22)
    at Promise.resolve.each (/usr/src/app/lib/plugins/browsertime/index.js:126:24)
From previous event:
    at processCoachOutput (/usr/src/app/lib/plugins/browsertime/index.js:109:10)
    at analyzer.analyzeUrl.tap.tap (/usr/src/app/lib/plugins/browsertime/index.js:159:24)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:157:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

[2016-09-26 16:08:18] Render HTML for 1 page(s) 
[2016-09-26 16:08:19] HTML stored in /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-09-26-16-08-10
[2016-09-26 16:08:19] Finished analysing https://www.verizonwireless.com

**Comment by soulgalore** [comment]
I don't think it's something Docker related, but there's some content on the page that we don't handle maybe? Lets dig into it.

**Comment by softwareklinic** [comment]
Yes.its not docker issue - i.see.all summary.pages.rendered with no content

Sent from my iPhone

On Sep 26, 2016, at 1:05 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think it's something Docker related, but there's some content on the page that we don't handle maybe? Lets dig into it.
