### ISSUE TITLE
Test failing - with some JS error

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1231]
./bin/sitespeed.js https://www.verizon.com/foryourhome/ordering/UrcIndex.aspx#/checkout --preScript vzurc.js -n 1
[2016-10-06 00:30:30] Versions OS: darwin 15.6.0 nodejs: v5.10.1 sitespeed.io: 4.0.0-beta.4 browsertime: 1.0.0-beta.6 coach: 0.27.1
[2016-10-06 00:30:31] Starting chrome for analysing https://www.verizon.com/foryourhome/ordering/UrcIndex.aspx#/checkout 1 time(s)
[2016-10-06 00:30:31] Testing url https://www.verizon.com/foryourhome/ordering/UrcIndex.aspx#/checkout run 1
Warning: a promise was rejected with a non-error: [object String]
    at Object.processMessage (/Users/xxxxxxxx/sitespeed.io/lib/plugins/browsertime/index.js:114:14)
    at /Users/v585896/sitespeed.io/lib/support/queueHandler.js:157:57
    at drainItem (/Users/xxxxxxxx/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/Users/xxxxxxxx/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

[2016-10-06 00:31:18] Render HTML for 1 page(s)

**Comment by soulgalore** [comment]
Hey @softwareklinic ,
think we need more info to be able to reproduce (+we need to change so we get better logging). See if we can fix the log today/tomorrow.

Best
Peter

**Comment by soulgalore** [comment]
Closing this but if you have more info so we can reproduce please re-open.
