### ISSUE TITLE
About experimental Video

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/sitespeed.io#1250]
Would i get to generate experimental video -- when i provide an external Selenium server URL --- since my site speed setup --- works in our intranet env --- only when i use our own selenium server url -- due to proxy issues... 

i will try out - but wanted to check if there are any limitations or issues expected if I use specific selenium server for generating videos?

**Comment by soulgalore** [comment]
yep, that can only be done on a server with all the things you need for [VisualMetrics](https://github.com/WPO-Foundation/visualmetrics), they are included in the Docker container.

**Comment by softwareklinic** [comment]
docker run --privileged -v /app/sitespeed.io:/sitespeed.io vzsitespeed sitespeed.io https://www.verizonwireless.com -n 1 --browsertime.experimental.video --browsertime.selenium.url http://<ipaddress>:4444/wd/hub
Mon Oct 17 19:48:27 UTC 2016
Google Chrome 52.0.2743.116 
Mozilla Firefox 48.0
Starting Xvfb ...
[2016-10-17 19:48:28] Versions OS: linux 3.10.0-327.3.1.el7.x86_64 nodejs: v4.5.0 sitespeed.io: 4.0.0-alpha.5 browsertime: 1.0.0-beta.1 coach: 0.24.5
[2016-10-17 19:48:29] Starting chrome for analysing https://www.verizonwireless.com 1 time(s)
[2016-10-17 19:48:29] Testing url https://www.verizonwireless.com run 1
[2016-10-17 19:48:51] Error: Command failed: /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/vendor/visualmetrics.py --video /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-10-17-19-48-28/video/www.verizonwireless.com-0.mpg --orange --dir /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-10-17-19-48-28/video/images -q 75 --perceptual --force --json
19:48:51.125 - Input video file /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-10-17-19-48-28/video/www.verizonwireless.com-0.mpg does not exist
19:48:51.125 - No video frames found in /sitespeed.io/sitespeed-result/www.verizonwireless.com/2016-10-17-19-48-28/video/images

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:196:35
From previous event:
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:196:10)
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:233:25
From previous event:
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:232:17
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:231:8)
    at /usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:26
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:90:8)
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:141:27)
    at /usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain [as _onImmediate] (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[2016-10-17 19:48:51] Render HTML for 1 page(s) 
[2016-10-17 19:48:51] Error TypeError: Cannot read property 'score' of undefined
    at module.exports (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/setup/summaryBoxes.js:60:35)
    at HTMLBuilder.renderHTML (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:88:189)
    at Object.close (/usr/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:88:29)
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:35:49
From previous event:
    at runOptionalFunction (/usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:35:6)
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:99:32
From previous event:
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:99:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:86:12
    at /usr/lib/node_modules/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at Object.run (/usr/lib/node_modules/sitespeed.io/lib/sitespeed.js:83:8)
    at /usr/lib/node_modules/sitespeed.io/bin/sitespeed.js:24:22
From previous event:
    at Object.<anonymous> (/usr/lib/node_modules/sitespeed.io/bin/sitespeed.js:23:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by soulgalore** [comment]
I didn't follow, what do you mean by the stack trace? The video is recorded from the XVFB in the current container you run, so that one needs to have/show the browser.

**Comment by softwareklinic** [comment]
But, my selenium is running on a windows server.... so how would xvfb capture screen...? or what type of setup i need if i want to capture video even when selenium server provided is external (on a different machine)

**Comment by soulgalore** [comment]
Hey @softwareklinic ,
XVFB is virtual framebuffer so inside the Docker container that is the display. And FFMPEG that records the video, records from that buffer. So you will always need to run inside the container to be able to record a video. External will not work, sorry!

Best
Peter

**Comment by softwareklinic** [comment]
How can we get visual speed index --- when running external selenium server

**Comment by soulgalore** [comment]
Hey @softwareklinic , with the current solution that will never be possible. What's the reason, is it that you wanna scale it so you can run many tests at the same time? 

Best
Peter

**Comment by softwareklinic** [comment]
For whatever reason - the tests are not running from.container based selenium especially.when we.are on.corporate proxy. Hence.decision to use.external selenium server

Sent from my iPhone

On Oct 22, 2016, at 1:55 PM, Peter Hedenskog <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @softwareklinic<https://github.com/softwareklinic> , with the current solution that will never be possible. What's the reason, is it that you wanna scale it so you can run many tests at the same time?

Best
Peter

-

**Comment by soulgalore** [comment]
Getting video on remote Selenium server will not work.
