### ISSUE TITLE
No WebPageTest Data into Graphite

### ISSUE THREAD

**Issue by CharlesFleurquin** [sitespeedio/sitespeed.io#1281]
Hi there

I have configured a script that fetch metrics and Webpagetest metrics. 
I have a cron set to fire up the sitespeed.io docker container every five minutes and hit 1 URL
I can't see all the metric data into graphite

Here is the script I use : 

/usr/local/bin/docker-compose run sitespeed.io --verbose --webpagetest.host ec2-
***********.eu-west-1.compute.amazonaws.com --webpagetest.key myAPiKey http://www.auchandrive.fr -b chrome -n 3 --graphite.host=graphite --graphite.namespace DriveProd.Home >> /home/ec2-user/auchandrive_prod_command.log

Here is an extract of my log file : 

Google Chrome 54.0.2840.59
Mozilla Firefox 49.0
Starting Xvfb ...
[2016-10-29 14:15:05] Versions OS: linux 4.4.19-29.55.amzn1.x86_64 nodejs: v6.4.0 sitespeed.io: 4.0.0-beta.5 browsertime: 1.0.0-beta.6 coach: 0.28.2
[2016-10-29 14:15:06] Setting up Graphite graphite:2003 for namespace DriveProd.Home
[2016-10-29 14:15:06] Starting chrome for analysing http://www.auchandrive.fr 3 time(s)
[2016-10-29 14:15:06] Sending url http://www.auchandrive.fr to test on ec2-52-19-201-26.eu-west-1.compute.amazonaws.com
[2016-10-29 14:15:06] Testing url http://www.auchandrive.fr run 1
[2016-10-29 14:15:08] Requesting url http://www.auchandrive.fr
[2016-10-29 14:15:11] Waiting for script 'return (function() {try { var end = window.performance.timing.loadEventEnd;return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})()' at most 300000 ms
[2016-10-29 14:15:13] Getting performance logs from Chrome
[2016-10-29 14:15:13] Telling browser to quit.
[2016-10-29 14:15:13] Testing url http://www.auchandrive.fr run 2
[2016-10-29 14:15:14] Requesting url http://www.auchandrive.fr
[2016-10-29 14:15:17] Waiting for script 'return (function() {try { var end = window.performance.timing.loadEventEnd;return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})()' at most 300000 ms
[2016-10-29 14:15:18] Getting performance logs from Chrome
[2016-10-29 14:15:18] Telling browser to quit.
[2016-10-29 14:15:18] Testing url http://www.auchandrive.fr run 3
[2016-10-29 14:15:19] Requesting url http://www.auchandrive.fr
[2016-10-29 14:15:22] Waiting for script 'return (function() {try { var end = window.performance.timing.loadEventEnd;return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})()' at most 300000 ms
[2016-10-29 14:15:24] Getting performance logs from Chrome
[2016-10-29 14:15:24] Telling browser to quit.
[2016-10-29 14:15:24] Send data to Graphite graphite:2003
[2016-10-29 14:15:24] Send data to Graphite graphite:2003
[2016-10-29 14:15:24] Send data to Graphite graphite:2003
[2016-10-29 14:15:25] Send data to Graphite graphite:2003
[2016-10-29 14:15:25] Send data to Graphite graphite:2003
[2016-10-29 14:15:25] Send data to Graphite graphite:2003
[2016-10-29 14:15:25] Render HTML for 1 page(s)
[2016-10-29 14:15:27] HTML stored in /sitespeed.io/sitespeed-result/www.auchandrive.fr/2016-10-29-14-15-05
[2016-10-29 14:15:27] Finished analysing http://www.auchandrive.fr

I can see data into Page Summary and Site Summary for example but nothing into WebPageTest Page Summary or WebPageTest Site Summary

Anyone can help me ?

**Comment by beenanner** [comment]
I will try to take a look later tonight @CharlesFleurquin.

**Comment by soulgalore** [comment]
Hey @CharlesFleurquin ,
just want to check you changed the namespace to DriveProd.Home so you need to update the dashboard. We need to update the documentation so that is clear. By default the key is <code>sitespeed_io.default</code> and all dashboard metrics need to start with sitespeed_io, the second part you can change and still use the same dashboard.

Best
Peter

**Comment by beenanner** [comment]
@CharlesFleurquin I think @soulgalore might be on the right track. Let us know if that's the issue or not. :-)

**Comment by jpvincent** [comment]
Hi there

I had troubles understanding why the WPT plugin was not working and ended up console.logging the errors returned by the WPT wrapper, locally. Do you want me to make a PR ?

It will contain the following code : 

```diff
diff --git i/lib/plugins/webpagetest/index.js w/lib/plugins/webpagetest/index.js
index 8087b60..ec060ae 100644
--- i/lib/plugins/webpagetest/index.js
+++ w/lib/plugins/webpagetest/index.js
@@ -8,6 +8,7 @@ let path = require('path'),
   aggregator = require('./aggregator'),
   forEach = require('lodash.foreach'),
   merge = require('lodash.merge'),
+  log = require('intel').getLogger('plugins.WEBPAGETEST'),
   WebPageTest = require('webpagetest');
 
 const make = messageMaker('webpagetest').make;
@@ -51,16 +52,19 @@ module.exports = {
     if (!options.key) {
       const host = hostRegex.exec(options.host);
       if (host && host[2] === defaultWptHost) {
+        log.error('webpagetest.key needs to be specified when using the public WebPageTest server')
         throw new Error('webpagetest.key needs to be specified when using the public WebPageTest server.');
       }
     }
 
+    log.info('Used options :', this.options)
+
     filterRegistry.registerFilterForType(DEFAULT_METRICS, 'webpagetest.pageSummary');
   },
   processMessage(message, queue) {
+    //log.warn('message', message)
     switch (message.type) {
       case 'url':
-
       {
         const url = message.url;
         const group = message.group;
@@ -90,20 +94,26 @@ module.exports = {
               }));
             })
         }
-
       case 'summarize':
-        {
-          let summary = aggregator.summarize();
-          if (summary && Object.keys(summary.groups).length > 0) {
-            for (let group of Object.keys(summary.groups)) {
-              queue.postMessage(make('webpagetest.summary', summary.groups[group], {
-                connectivity: aggregator.connectivity,
-                location: aggregator.location,
-                group
-              }));
-            }
+      {
+        let summary = aggregator.summarize();
+        if (summary && Object.keys(summary.groups).length > 0) {
+          for (let group of Object.keys(summary.groups)) {
+            queue.postMessage(make('webpagetest.summary', summary.groups[group], {
+              connectivity: aggregator.connectivity,
+              location: aggregator.location,
+              group
+            }));
           }
         }
+      }
+
+      case 'error':
+      {
+        if(message.source === 'webpagetest') {
+          log.error('webpagetest wrapper said', message.data, new Error(message.data))
+        }
+      }
     }
   },
   config: defaultConfig

```

And will display errors this way :  

```
[2016-11-21 21:37:36] [plugins.WEBPAGETEST] webpagetest wrapper said {"statusCode":400,"statusText":"Invalid Location, please try submitting your test request again."} Error: [object Object]
    at Object.processMessage (/Users/jpv/Documents/DEV/github/sitespeed.io/lib/plugins/webpagetest/index.js:114:63)
    at queue.process (/Users/jpv/Documents/DEV/github/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/Users/jpv/Documents/DEV/github/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/Users/jpv/Documents/DEV/github/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

**Comment by tobli** [comment]
Hi!
Configuration errors (such as "webpagetest.key needs to be specified…" should already be printed to the console. For runtime errors however we're currently only collecting them for the generated html site. For batch scenarios there might be other error reporting mechanisms needed. I'm hesitant to solutions that require boilerplate code to be added to all plugins however. I'd rather collect all errors in one place (see the messagelogger plugin).

**Comment by jpvincent** [comment]
Hi @tobli 
It does not look like I have the messages. When everything is OK, I have (edited) : 
```console
[2016-11-22 08:04:19] Sending url http://www.vogue.fr/ to test on http://WPT-INSTANCE/
[2016-11-22 08:05:11] Got http://www.vogue.fr/ analysed from http://WPT-INSTANCE/
```

When webpagetest was not working (key missing, then location name error), I had only 
```
[2016-11-22 08:10:58] Sending url http://www.vogue.fr/ to test on http://WPT-INSTANCE/
````
Sitespeed ends when the browsertime is over and I dont see any error displayed in the console.
Shall I open a separate ticket for this one ?

Thanks for notifying me that the errors are in the HTML, I never noticed the tab !
It actually appears only when there is an error, and I was not expecting WPT to appear here, but it's OK

**Comment by soulgalore** [comment]
I think this is ok now right? else please re-open!
