### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by krukru** [sitespeedio/sitespeed.io#1317]
I'm running sitespeed.io on a windows machine and when using a budget and exporting it to junit I get the error from the title.

The command used to run sitespeed.io
`sitespeed.io.cmd --budget my.budget --budget.output junit -n 1 http://www.sitespeed.io/`

The contents of my.budget
```json
{
  "coach.pageSummary": [{
    "metric": "advice.performance.score",
    "min": 90
  }]
}
```

When switching to tap, I get no error.

Howeven when adding another coach.pageSummary metric to the budget, junit works again.
For example, this budget works:
```json
{
  "coach.pageSummary": [{
    "metric": "advice.performance.score",
    "min": 90
  }, {
    "metric": "advice.info.domElements",
    "max": 2000
  }]
}
```

The contents of the log file generated from the failed report
```js
Versions OS: win32 6.3.9600 nodejs: v6.9.1 sitespeed.io: 4.0.4 browsertime: 1.0.0-beta.9 coach: 0.28.4
Starting chrome for analysing http://www.sitespeed.io/ 1 time(s)
Testing url http://www.sitespeed.io/ run 1
10 requests, 98.48 kb, firstPaint: 0.73s, DOMContentLoaded: 0.65s, Load: 0.79s, rumSpeedIndex: 0.73s
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.exports.writeJunit (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\plugins\budget\junit.js:25:39)
    at Object.close (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\plugins\budget\index.js:38:15)
    at Promise.resolve.filter.map (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:43:49)
From previous event:
    at runOptionalFunction (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:43:6)
    at runOptionalFunction.then.then.tap (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:118:32)
From previous event:
    at loader.loadPlugins.then (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:118:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:103:12)
From previous event:
    at Object.run (C:\Program Files\nodejs\node_modules\sitespeed.io\lib\sitespeed.js:100:8)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\sitespeed.io\bin\sitespeed.js:28:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by soulgalore** [comment]
thank you @krukru for the really detailed bug report! I'll have a look asap.

**Comment by krukru** [comment]
Thanks, that was really fast :D
