### ISSUE TITLE
Issue with sending metrics to graphite

### ISSUE THREAD

**Issue by beenanner** [sitespeedio/sitespeed.io#1358]
ubuntu@ip-172-31-52-178:~$ /usr/bin/docker run --privileged --shm-size=1024m --rm sitespeedio/sitespeed.io:4.0.7 https://www.cnet.com/tech-today/ --mobile --browsertime.connectivity.engine tc -c 3gfast --firstParty ".*(cnet|cbsistatic).*" --plugins.disable html --graphite.host 172.31.28.69 --graphite.namespace sitespeed_io.pwa
Google Chrome 54.0.2840.71
Mozilla Firefox 49.0.2
[2016-12-03 08:45:11] Versions OS: linux 4.4.0-47-generic nodejs: v6.9.1 sitespeed.io: 4.0.7 browsertime: 1.0.0-beta.11 coach: 0.29.0
[2016-12-03 08:45:12] Starting chrome for analysing https://www.cnet.com/tech-today/ 3 time(s)
[2016-12-03 08:45:12] sudo tc qdisc add dev eth0 root netem delay 150ms loss 0% rate 1600kbps
[2016-12-03 08:45:12] Testing url https://www.cnet.com/tech-today/ run 1
[2016-12-03 08:45:19] Testing url https://www.cnet.com/tech-today/ run 2
[2016-12-03 08:45:24] Testing url https://www.cnet.com/tech-today/ run 3
[2016-12-03 08:45:29] 17 requests, 240.29 kb, firstPaint: 1.38s (±40.20ms), DOMContentLoaded: 1.41s (±40.30ms), Load: 1.63s (±39.02ms), rumSpeedIndex: 2063 (±458.93) (3 runs)
[2016-12-03 08:45:29] sudo tc qdisc del dev eth0 root
[2016-12-03 08:45:29] Error: Tried to add undefined to stats
    at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:24:13)
    at Object.pushGroupStats (/usr/src/app/lib/support/statsHelpers.js:32:10)
    at /usr/src/app/lib/plugins/coach/pagexrayAggregator.js:40:24
    at Array.forEach (native)
    at /usr/src/app/lib/plugins/coach/pagexrayAggregator.js:38:22
    at Array.forEach (native)
    at Object.addToAggregate (/usr/src/app/lib/plugins/coach/pagexrayAggregator.js:20:17)
    at Object.processMessage (/usr/src/app/lib/plugins/coach/index.js:54:28)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by tobli** [comment]
Congratulations! Your site only has first party requests! =)
👏

Crashing isn't a very polite way of celebrating though. Both pagexrayAggregator.js and statsHelpers.js are quite hairy, and could use some rewriting to be more readable and resilient.

**Comment by beenanner** [comment]
Ha! Thanks @tobli was going to take a look at this tonight but you beat me to it!
