### ISSUE TITLE
preScript not working

### ISSUE THREAD

**Issue by pixlab** [sitespeedio/sitespeed.io#1375]
Hi,

I'm trying this wonderful tool :) and it works great
but now I've a problem with preScript (I should use it for login in my website)
I've tried to launch the script preSample ( https://github.com/sitespeedio/browsertime/blob/master/test/prepostscripts/preSample.js ), and this is the result:

`>$ sitespeed.io --bowersertime.preScript=/Users/user/Documents/Sitespeed/preSample.js https://www.sitespeed.io
[2016-12-11 12:00:24] Versions OS: darwin 15.6.0 nodejs: v7.1.0 sitespeed.io: 4.1.3 browsertime: 1.0.0-beta.13 coach: 0.29.0
[2016-12-11 12:00:25] Starting chrome for analysing https://www.sitespeed.io 3 time(s)
[2016-12-11 12:00:25] Testing url https://www.sitespeed.io run 1
[2016-12-11 12:00:25] https://www.sitespeed.io generated the following error in Browsertime BrowserError: session not created exception
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"11906.1","frameId":"11906.1","loaderId":"11906.1","timestamp":156647,484291,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
from unknown error: bad inspector message: {"method":"Network.responseReceived","params":{"requestId":"11906.1","frameId":"11906.1","loaderId":"11906.1","timestamp":156647,484291,"type":"Document","response":{"url":"data:,","status":200,000000,"statusText":"OK","headers":{"Access-Control-Allow-Origin":"*","Content-Type":"text/plain;charset=US-ASCII"},"mimeType":"text/plain","connectionReused":false,"connectionId":0,000000,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":-1,000000,"protocol":"data","securityState":"unknown"}}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:284:17)
From previous event:
    at Engine.run (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2016-12-11 12:00:25] Render HTML for 1 page(s)
[2016-12-11 12:00:26] HTML stored in /Users/user/Documents/Sitespeed/sitespeed-result/www.sitespeed.io/2016-12-11-12-00-24
[2016-12-11 12:00:26] Finished analysing https://www.sitespeed.io`

I've tried with docker too, but I receive this:

`>$ docker-compose run sitespeed.io --browsertime.preScript=/Users/user/Documents/Sitespeed/preSample.js https://www.sitespeed.io
Google Chrome 54.0.2840.100
Mozilla Firefox 50.0
[2016-12-11 11:12:39] Versions OS: linux 4.4.27-moby nodejs: v6.9.1 sitespeed.io: 4.1.3 browsertime: 1.0.0-beta.13 coach: 0.29.0
[2016-12-11 11:12:40] Couldn't run pre/post script file: /Users/user/Documents/Sitespeed/preSample.js Error: Cannot find module '/Users/user/Documents/Sitespeed/preSample.js'
[2016-12-11 11:12:40] Error: Couldn't run pre/post script file: /Users/user/Documents/Sitespeed/preSample.js Error: Cannot find module '/Users/user/Documents/Sitespeed/preSample.js'
    at toArray.map.e (/usr/src/app/node_modules/browsertime/lib/core/engine.js:48:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/src/app/node_modules/browsertime/lib/core/engine.js:44:27)
    at new Engine (/usr/src/app/node_modules/browsertime/lib/core/engine.js:75:27)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:73:18)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2016-12-11 11:12:40] Render HTML for 1 page(s)
[2016-12-11 11:12:40] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2016-12-11-11-12-39
[2016-12-11 11:12:40] Finished analysing https://www.sitespeed.io`

Can you help me to understand the reason of these responses? What I do wrong?

thanks
Roberto

**Comment by soulgalore** [comment]
Hey @pixlab thanks for the kind words :)

I think the problem is <code>--bowersertime.preScript</code> the CLI today doesn't give any good feedback if the parameter is wrong. Can you test with <code>--preScript</code>? I tested it and it works for me.

Using Docker you need to mount the volume https://www.sitespeed.io/documentation/sitespeed.io/docker/#more-about-volumes so you inside the container have access to the file. We need to update that example so it's clearer.

Best
Peter

**Comment by pixlab** [comment]
for the command `sitespeed.io --preScript=/Users/user/Documents/Sitespeed/preSample.js https://www.sitespeed.io` now it works removing browsertime and updating chrome to the last version ( https://github.com/sitespeedio/browsertime/issues/223 )

Using docker I don't know if it is the right order of arguments:
`docker-compose run -v /Users/user/Documents/Sitespeed sitespeed.io --preScript preSample.js --graphite.host=graphite https://www.sitespeed.io`
I don't understand the response:
```
Run a one-off command on a service.

For example:

    $ docker-compose run web python manage.py shell

By default, linked services will be started, unless they are already
running. If you do not want to start linked services, use
docker-compose run --no-deps SERVICE COMMAND [ARGS...].
```

**Comment by soulgalore** [comment]
Hey @pixlab ah ok if you run docker-compose, you will need to map the volume in your docker compose file, something like https://github.com/sitespeedio/sitespeed.io/blob/master/docker-compose.yml#L6-L7

If you run docker, you can use the -v flag for mapping a volume into your container!

Best
Peter

**Comment by soulgalore** [comment]
This works for us on dashboard.sitespeed.io, let us know if it is still a problem for you.

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore  , 
Above link  https://github.com/sitespeedio/sitespeed.io/blob/master/docker-compose.yml#L6-L7 is not working. Can you tell me how to run docker-compose and map volume and then use --prescript ?
