### ISSUE TITLE
Unknown command - submit

### ISSUE THREAD

**Issue by cambiph** [sitespeedio/sitespeed.io#1394]
Hello,

I have the following setup:

- Ubuntu 16.04 LTS
- Sitespeed 4.3.0
- nvm 0.32.1
- node 7.3.0

Following modified script from the tutorial on sitespeed.io:
```javascript
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      // Go to Wikipedias login URL
      return driver.get('*********')
        .then(() => {
          // You need to find the form, the login input fiels and the
          // password field. Just add you name and password and submit the form
          // For more docs, checkout the NodeJS Selenium version
          // http://seleniumhq.github.io/selenium/docs/api/javascript/index.html
          // we fetch the selenium webdriver from context
          var webdriver = context.webdriver;
          // before you start, make your username and password
          var userName = '****';
          var password = '****';
          var loginForm = driver.findElement(webdriver.By.name('ldap_login_form'));
          var loginInput = driver.findElement(webdriver.By.id('username'));
          loginInput.sendKeys(userName);
          var passwordInput = driver.findElement(webdriver.By.id('password'));
          passwordInput.sendKeys(password);
          loginForm.submit();
          driver.wait(function () {
              return driver.isElementPresent(webdriver.By.name('****'));
          }, 10000);
          // we search for the customer
          var iklForm = driver.findElement(webdriver.By.name('****'));
          var iklInput = driver.findElement(webdriver.By.name('****'));
          iklInput.sendKeys('60');
          iklForm.submit();
          var tab = driver.findElement(webdriver.By.linkText('****'));
          tab.click();
        });
    })
  }
};
```

I get the following stacktrace when running:
sitespeed.io --preScript login.js http:/**** -b firefox

Sadly enough I cannot get you a working example because it's our internal corporate website.

```
[2016-12-23 09:12:30] UnknownCommandError: POST /session/a6914715-540c-4de3-a7e8-641502f82646/element/63c489ec-f174-41bf-95e0-66bd28526ac3/submit did not match a known command
    at Object.throwDecodedError (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/http.js:499:15)
    at doSend.then.response (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Driver.schedule (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at WebElementPromise.schedule_ (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
    at WebElementPromise.submit (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/webdriver.js:2246:17)
    at driver.get.then (/home/ubuntu/sitespeed/login.js:22:21)
    at ManagedPromise.invokeCallback_ (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/ubuntu/.config/yarn/global/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at runner.start.tap (/home/ubuntu/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:211:28)
From previous event:
    at runIteration (/home/ubuntu/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:211:10)
    at Promise.reduce (/home/ubuntu/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/home/ubuntu/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:284:17)
From previous event:
    at Engine.run (/home/ubuntu/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/home/ubuntu/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.analyzeUrl (/home/ubuntu/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/home/ubuntu/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/home/ubuntu/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/home/ubuntu/.config/yarn/global/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/home/ubuntu/.config/yarn/global/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/home/ubuntu/.config/yarn/global/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[2016-12-23 09:12:30] Render HTML for 1 page(s) 
[2016-12-23 09:12:31] HTML stored in /home/ubuntu/sitespeed/sitespeed-result/****/2016-12-23-09-12-26
[2016-12-23 09:12:31] Finished analysing http://******
```

**Comment by beenanner** [comment]
@cambiph can you give it a shot with the test preScript? The following works fine for me.

`bin/sitespeed.js --preScript test/prepostscripts/preSample.js -b firefox https://www.google.com/`

Also just a thought you may want to tweak the script to use the click function on the submit button directly if you have some javascript that is actually doing the submitting.

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebElement.html#click

**Comment by cambiph** [comment]
I tweaked the script a bit and the click seemed to solve the problem.
However, when going from one page to another, I need to insert an implicit wait.
According to the sitespeed.io docs, the WebdriverJS bindings can be used.
However

```javascript
driver.wait(webdriver.until.titleIs('Search customer'), 1000);
```

returns: 

```
TypeError: webdriver.wait is not a function
```

Are you aware of this problem or do you know a way to circumvent this?

**Comment by beenanner** [comment]
Great! Glad you got it working @cambiph.
