### ISSUE TITLE
html plugin crashes if browsertime plugin has not run

### ISSUE THREAD

**Issue by jpvincent** [sitespeedio/sitespeed.io#1398]
Hi
I tried to NOT execute the browser with this option : ```browsertime.iterations: 0```

I have an execution error preventing the test to be done : 
```console
[2016-12-27 17:46:23] Render HTML for 2 page(s) 
Unhandled rejection TypeError: Cannot read property 'run' of undefined
    at Promise.resolve.map (/usr/src/app/lib/plugins/html/htmlBuilder.js:118:127)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:110:8)
    at Object.close (/usr/src/app/lib/plugins/html/index.js:26:29)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:43:49)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:43:6)
    at runOptionalFunction.then.then.tap (/usr/src/app/lib/sitespeed.js:119:32)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:119:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:103:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:100:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:29:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
It does prevent the script to run. In this case I wanted the test to be made by WPT only

The solution is to actually disable the HTML plugin : ```"plugins.disable":["html", "screenshot"],```

But it's not obvious … could we fix the html plugin, or auto-deactivate it when no test was run from browsertime ?

**Comment by soulgalore** [comment]
Hey @jpvincent let us think about how to do that in the cleanest way!

Best
Peter

**Comment by tobli** [comment]
Hi!
To not run the browser you'd want to disable the browsertime plugin (the screenshot plugin wouldn't matter in that case). Generating an html report or not is a separate matter. It should be possible to have a report without running browsertime, or to run browsertime without generating a report. If any plugin combination that causes a crash that's a bug. In your case it seems you'd want to disable both html and browsertime.

**Comment by soulgalore** [comment]
@tobli yes but have you tried if the rest of the plugins really work without BT, I think the HTML plugin could fail? In theory it could work if everything is lossless coupled but not sure if it do in practice. We need to try.

**Comment by jpvincent** [comment]
If disabling only browsertime, the html plugin still fails :
```
[2016-12-27 20:43:02] [plugins.html] Render HTML for 1 page(s) 
Unhandled rejection TypeError: /Users/jpv/Documents/DEV/github/sitespeed.io/lib/plugins/html/templates/url/index.pug:71
    69| 
    70|         .one-half.column
  > 71|             if d.browsertime.pageSummary.screenshots
    72|               - var width = options.mobile ? 150 : '100%';
    73|               a(href='data/screenshots/0.png')
    74|                 img.screenshot(src='data/screenshots/0.png', width=width, alt='Screenshot of run 0')

Cannot read property 'pageSummary' of undefined
```

So yeah, we have a plugin that depends on another, that's my bug

**Comment by beenanner** [comment]
Looks like we probably will need a lot more sanity checks in the pug templates. :-)

**Comment by beenanner** [comment]
I'll try to work on it a bit this week.

**Comment by beenanner** [comment]
@jpvincent sorry for the delay give the `fix-disabling-browsertime-plugin` branch a quick run to see if that fixes your issue.

**Comment by jpvincent** [comment]
Hi

I switched to the branch but I still have the 2 errors reported.
Have you tested while running a webpagetest test ? I guess the HTML plugin tries to render something anyway

**Comment by soulgalore** [comment]
Hey @jpvincent I tested it by just disablinc the browsertime plugin as in @beenanner example and it worked for me, could it be some config parameter that differs, how did you run?
Best
Peer

**Comment by soulgalore** [comment]
Meaning I did like this:
<pre>bin/sitespeed.js https://www.sitespeed.io/ -n 1 --plugins.disable browsertime --webpagetest.key SECRET_KEY</pre>

The pages was generated for me, but without the browsertime data so we are missing out quite much, but the webpagetest part looked ok.

**Comment by jpvincent** [comment]
Hi
By trying to reproduce it with the command line (` [16:28] jpv@mac-jpv:sitespeed.io (fix-disabling-browsertime-plugin $) $ node bin/sitespeed.js https://dashboard.sitespeed.io --plugins.disable browsertime --graphite.host=localhost --webpagetest.host=http://WPT-SERVER` ), I realized that it DOES work, but that I have the problem only when the option is set in a `.json` configuration file

with `  "plugins.disable":"browsertime", ` or `
and this command :
```
[16:32] jpv@mac-jpv:sitespeed.io (fix-disabling-browsertime-plugin $) $ node bin/sitespeed.js https://dashboard.sitespeed.io --config /Users/jpv/Documents/DEV/SiteSpeed/lexpress/config/config.json  --graphite.host=localhost --webpagetest.host=http://WPT-SERVER
[2017-01-10 16:35:47] [main] Versions OS: darwin 16.1.0 nodejs: v7.0.0 sitespeed.io: 4.3.2 browsertime: 1.0.0-beta.19 coach: 0.30.1
```
I do have the error.

But if I disable the html and set the # of iteration to 0, it works fine
```
   "browsertime.iterations":0,
  "plugins.disable":["html"],
`` `

**Comment by jpvincent** [comment]
Sorry : I just switched back to the master branch, sitespeed V.4.3.6, and disabling only browsertime in the JSON file does work fine now …
