### ISSUE TITLE
BrowserError when running in docker container from RHEL docker server(daemon)

### ISSUE THREAD

**Issue by JaydiptaBiswas** [sitespeedio/sitespeed.io#1402]
I am using RHEL7 as a docker daemon server. And running the below command: 
docker run --privileged --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://www.sitespeed.io/ -b chrome  

also tried adding --shm-size=512m and --no-sandbox but always results same error. Although it is working perfectly in Ubuntu docker daemon.  Please help -

RHEL7 Docker daemon Error log:

Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2017-01-02 02:43:17] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.1 browsertime: 1.0.0-beta.19 coach: 0.30.0
[2017-01-02 02:43:18] Starting chrome for analysing http://www.sitespeed.io/ 3 time(s)
[2017-01-02 02:43:18] Testing url http://www.sitespeed.io/ run 1
[2017-01-02 02:44:18] Browser failed to start in time, trying one more time.
[2017-01-02 02:45:18] http://www.sitespeed.io/ generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 3.10.0-514.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 3.10.0-514.el7.x86_64 x86_64)
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:284:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:37:10)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:42:25)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
[2017-01-02 02:45:18] Render HTML for 1 page(s)
[2017-01-02 02:45:20] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-01-02-02-43-17
[2017-01-02 02:45:20] Finished analysing http://www.sitespeed.io/
[

UBUNTU Docker Daemon Working log:

Digest: sha256:011344b0a4f82585387b14d102cdffdfecb3b97039ebe67b3fb634f89ec7730b
Status: Downloaded newer image for sitespeedio/sitespeed.io:latest
Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2016-12-31 22:08:57] Versions OS: linux 3.13.0-93-generic nodejs: v6.9.1 sitespeed.io: 4.3.1 browsertime: 1.0.0-beta.19 coach: 0.30.0
[2016-12-31 22:08:57] Starting chrome for analysing http://www.sitespeed.io/ 3 time(s)
[2016-12-31 22:08:57] Testing url http://www.sitespeed.io/ run 1
[2016-12-31 22:09:01] Testing url http://www.sitespeed.io/ run 2
[2016-12-31 22:09:05] Testing url http://www.sitespeed.io/ run 3
[2016-12-31 22:09:10] 10 requests, 90.57 kb, firstPaint: 190ms (Â±13.08ms), DOMContentLoaded: 120ms (Â±18.17ms), Load: 186ms (Â±41.84ms), rumSpeedIndex: 193 (Â±14.97) (3 runs)
[2016-12-31 22:09:10] Render HTML for 1 page(s)
[2016-12-31 22:09:12] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2016-12-31-22-08-57
[2016-12-31 22:09:12] Finished analysing http://www.sitespeed.io/
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu# ll
total 72

**Comment by JaydiptaBiswas** [comment]
Using the same command in a Ubuntu docker daemon and it is running perfectly. Please help me resolving this issue.
UBUNTU Docker Daemon log: 

Digest: sha256:011344b0a4f82585387b14d102cdffdfecb3b97039ebe67b3fb634f89ec7730b
Status: Downloaded newer image for sitespeedio/sitespeed.io:latest
Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2016-12-31 22:08:57] Versions OS: linux 3.13.0-93-generic nodejs: v6.9.1 sitespeed.io: 4.3.1 browsertime: 1.0.0-beta.19 coach: 0.30.0
[2016-12-31 22:08:57] Starting chrome for analysing http://www.sitespeed.io/ 3 time(s)
[2016-12-31 22:08:57] Testing url http://www.sitespeed.io/ run 1
[2016-12-31 22:09:01] Testing url http://www.sitespeed.io/ run 2
[2016-12-31 22:09:05] Testing url http://www.sitespeed.io/ run 3
[2016-12-31 22:09:10] 10 requests, 90.57 kb, firstPaint: 190ms (Â±13.08ms), DOMContentLoaded: 120ms (Â±18.17ms), Load: 186ms (Â±41.84ms), rumSpeedIndex: 193 (Â±14.97) (3 runs)
[2016-12-31 22:09:10] Render HTML for 1 page(s)
[2016-12-31 22:09:12] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2016-12-31-22-08-57
[2016-12-31 22:09:12] Finished analysing http://www.sitespeed.io/
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu#
root@ip-172-31-59-19:/home/ubuntu# ll
total 72

**Comment by soulgalore** [comment]
Hey @JaydiptaBiswas 
thanks for the report. Just wanna check, when you tried <code>--no-sandbox</code> did you do the full command <code>--browsertime.chrome.args no-sandbox</code> (the documentation is a little hard to read).

Best
Peter

**Comment by JaydiptaBiswas** [comment]
Hi,
Please check the below command using no sandbox argument. It is giving an 'Could not load URLUrlLoadError'
 This is the result I am getting :- 
[root@myRHELserver jaydip]# docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -b chrome --browsertime.chrome.args no-sandbox http://www.sitespeed.io

Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2017-01-02 21:24:18] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.1 browsertime: 1.0.0-beta.19 coach: 0.30.0
[2017-01-02 21:24:18] Starting chrome for analysing http://www.sitespeed.io 3 time(s)
[2017-01-02 21:24:19] Testing url http://www.sitespeed.io run 1
[2017-01-02 21:24:20] Could not load URLUrlLoadError: Failed to load http://www.sitespeed.io
[2017-01-02 21:24:20] http://www.sitespeed.io generated the following error in Browsertime UrlLoadError: Failed to load http://www.sitespeed.io
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:149:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:147:13)
    at runner.start.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:226:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:226:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:284:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2017-01-02 21:24:20] Render HTML for 1 page(s)
[2017-01-02 21:24:22] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-01-02-21-24-18
[2017-01-02 21:24:22] Finished analysing http://www.sitespeed.io

**Comment by roacobb** [comment]
Any resolution to this issue? I'm using sitespeed.io in CentOS 7 with Docker and my output is =>
```
docker-compose run sitespeed.io https://www.theatlantic.com/ --graphite.host=graphite
Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2017-01-12 18:34:27] Versions OS: linux 3.10.0-514.2.2.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.6 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-12 18:34:28] Starting chrome for analysing https://www.theatlantic.com/ 3 time(s)
[2017-01-12 18:34:28] Testing url https://www.theatlantic.com/ run 1
[2017-01-12 18:35:28] Browser failed to start in time, trying one more time.
[2017-01-12 18:36:28] https://www.theatlantic.com/ generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:284:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:37:10)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:42:25)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
[2017-01-12 18:36:28] Render HTML for 1 page(s)
[2017-01-12 18:36:29] HTML stored in /sitespeed.io/sitespeed-result/www.theatlantic.com/2017-01-12-18-34-27
[2017-01-12 18:36:29] Finished analysing https://www.theatlantic.com/
```

**Comment by soulgalore** [comment]
The no sandbox alternative have worked in the past, @tobli do you see if I added it correctly?

**Comment by cambiph** [comment]
Having the same problem om RHEL 7 x64

`
+ sudo docker run --privileged --shm-size=512m --rm -v /home/pcambie1/workspace/sitespeed-sitespeedio:/sitespeed.io sitespeedio/sitespeed.io -b chrome --browsertime.chrome.args no-sandbox https://www.sitespeed.io/
Google Chrome 55.0.2883.87 
Mozilla Firefox 50.1.0
[2017-01-17 12:23:45] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.7 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-17 12:23:46] Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2017-01-17 12:23:46] Testing url https://www.sitespeed.io/ run 1
[2017-01-17 12:25:10] Could not load URLUrlLoadError: Failed to load https://www.sitespeed.io/
[2017-01-17 12:25:10] https://www.sitespeed.io/ generated the following error in Browsertime UrlLoadError: Failed to load https://www.sitespeed.io/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:149:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:147:13)
    at runner.start.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:226:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:226:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:284:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[2017-01-17 12:25:10] Render HTML for 1 page(s) 
[2017-01-17 12:25:12] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-01-17-12-23-45
[2017-01-17 12:25:12] Finished analysing https://www.sitespeed.io/
`

**Comment by soulgalore** [comment]
I wonder if something has changed for <code>no-sandbox</code>? If I run Chrome standalone with that switch <code>/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --no-sandbox</code> I get that yellow warning, but if I run browsertime I don't get that?

**Comment by cambiph** [comment]
I just had a 'eureka' moment when I realised that the VM I am running the tests on is behind a proxy.
Addinh http_proxy and https_proxy to /etc/environment seems to fix it for me thusfar.

**Comment by soulgalore** [comment]
Hey @cambiph could you test with and without no-sandbox on RHEL so I know what works, then I can update the documentation. Thanks!

**Comment by helirexi** [comment]
hey all, I am running on Archlinux VPS, and this part `--browsertime.chrome.args no-sandbox` finally work for me.

My sample output

```
# docker-compose run sitespeed.io -b chrome --browsertime.chrome.args no-sandbox http://somedomain.com/ --graphite.host graphite
Google Chrome 55.0.2883.87 
Mozilla Firefox 50.1.0
[2017-01-17 22:25:14] Versions OS: linux 4.8.13-1-ARCH nodejs: v6.9.1 sitespeed.io: 4.3.7 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-17 22:25:14] Starting chrome for analysing http://somedomain.com/ 3 time(s)
[2017-01-17 22:25:14] Testing url http://somedomain.com/ run 1
[2017-01-17 22:25:19] Testing url http://somedomain.com/ run 2
[2017-01-17 22:25:22] Testing url http://somedomain.com/ run 3
[2017-01-17 22:25:26] 48 requests, 190.98 kb, firstPaint: 565ms (±10.14ms), DOMContentLoaded: 597ms (±8.29ms), Load: 664ms (±6.96ms), rumSpeedIndex: 565 (±10.14) (3 runs)
[2017-01-17 22:25:26] Send data to Graphite graphite:2003
[2017-01-17 22:25:26] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Send data to Graphite graphite:2003
[2017-01-17 22:25:27] Render HTML for 1 page(s) 
[2017-01-17 22:25:29] HTML stored in /sitespeed.io/sitespeed-result/somedomain.com/2017-01-17-22-25-14
[2017-01-17 22:25:29] Finished analysing http://somedomain.com/

```

before this key I was same error  with Chrome browser. With Firefox not problem at all.

**Comment by soulgalore** [comment]
thanks @helirexi for sharing!

**Comment by cambiph** [comment]
@soulgalore I can confirm that the no-sandbox switch is needed on RHEL running docker to get it working.
Here's the logfile:

```
[***@****~]$ docker run --privileged --shm-size=512m --rm -v /home/*****/workspace/sitespeed-sitespeedio:/sitespeed.io sitespeedio/sitespeed.io -b chrome --browsertime.chrome.args no-sandbox https://www.sitespeed.io/
Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2017-01-18 08:45:16] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.7 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-18 08:45:18] Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2017-01-18 08:45:19] Testing url https://www.sitespeed.io/ run 1
[2017-01-18 08:45:32] Testing url https://www.sitespeed.io/ run 2
[2017-01-18 08:45:36] Testing url https://www.sitespeed.io/ run 3
[2017-01-18 08:45:46] 9 requests, 92.91 kb, firstPaint: 741ms (±153.94ms), DOMContentLoaded: 593ms (±151.44ms), Load: 733ms (±128.45ms), rumSpeedIndex: 741 (±153.94) (3 runs)
[2017-01-18 08:45:47] Render HTML for 1 page(s)
[2017-01-18 08:45:50] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-01-18-08-45-16
[2017-01-18 08:45:50] Finished analysing https://www.sitespeed.io/

[****@**** ~]$ docker run --privileged --shm-size=512m --rm -v /home/****/workspace/sitespeed-sitespeedio:/sitespeed.io sitespeedio/sitespeed.io -b chrome https://www.sitespeed.io/
Google Chrome 55.0.2883.87
Mozilla Firefox 50.1.0
[2017-01-18 08:46:21] Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.9.1 sitespeed.io: 4.3.7 browsertime: 1.0.0-beta.23 coach: 0.30.4
[2017-01-18 08:46:24] Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2017-01-18 08:46:24] Testing url https://www.sitespeed.io/ run 1
[2017-01-18 08:47:24] Browser failed to start in time, trying one more time.
[2017-01-18 08:48:24] https://www.sitespeed.io/ generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.10.0-514.el7.x86_64 x86_64)
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:284:17)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:283:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:37:10)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:42:25)
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:210:21)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:285:25)
[2017-01-18 08:48:25] Render HTML for 1 page(s)
[2017-01-18 08:48:26] HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2017-01-18-08-46-21
[2017-01-18 08:48:26] Finished analysing https://www.sitespeed.io/


```

**Comment by soulgalore** [comment]
thank you @cambiph I'll update the docs tonight.

**Comment by soulgalore** [comment]
Fixed.
