### ISSUE TITLE
Configuring metrics timings fails

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1412]
I know, this isnt something that we actually want people to use, however it shouldn't break. If I list all the configurable metrics, one of them is  pagexray.pageSummary.assets.*.timing but configuring fails. Pushing all metrics works (I only tested that before).

<pre>
$ bin/sitespeed.js https://www.sitespeed.io -n 1 --graphite.port 56109 --graphite.host localhost --metrics.filter pagexray.pageSummary.assets.*.timing
</pre>

Generates the following error:

<pre>
[2017-01-06 23:01:39] TypeError: Cannot read property 'replace' of undefined
    at toSafeKey (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:10:13)
    at Object.keys.forEach (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:70:67)
    at Array.forEach (native)
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:62:30)
    at Object.keys.forEach (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:73:15)
    at Array.forEach (native)
    at recursiveFlatten (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:62:30)
    at Object.flattenMessageData (/Users/peter/git/sitespeed.io/lib/support/flattenMessage.js:101:5)
    at GraphiteDataGenerator.dataFromMessage (/Users/peter/git/sitespeed.io/lib/plugins/graphite/data-generator.js:64:27)
    at Object.processMessage (/Users/peter/git/sitespeed.io/lib/plugins/graphite/index.js:46:35)
    at queue.process (/Users/peter/git/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/Users/peter/git/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/Users/peter/git/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
</pre>

**Comment by beenanner** [comment]
Source says "coach", but type is "pagexray.pageSummary"?

![error-object-state](https://cloud.githubusercontent.com/assets/723985/21747684/44b52d24-d53d-11e6-8818-44e63f147a60.png)

**Comment by beenanner** [comment]
Looks like it's part of the flattenMessage from the assets. They are numeric indices. Line here is the cause: https://github.com/sitespeedio/sitespeed.io/blob/master/lib/support/flattenMessage.js#L70

**Comment by beenanner** [comment]
Looks like it's coming from coach using `--plugins.disable coach` and it doesn't throw the error.

**Comment by beenanner** [comment]
Ok tracked it all the way back to pagexray :-p.

See here: https://github.com/sitespeedio/pagexray/blob/master/lib/index.js#L71

**Comment by soulgalore** [comment]
Hey @beenanner yes sorry I didn't write a full description. Some time ago I did a fix for hacking in URLs in lists https://github.com/sitespeedio/sitespeed.io/commit/705d2c854d8cbad793a34d10056599525ede880b and it kind of works if you send all metrics but not if you add a specific metric. That part is kind of hacky, I can look into it since it's my mess from the beginning :)

**Comment by beenanner** [comment]
So probably a fix with the way coach is aggregating the assets. They appear to only have timing values in the indices

![needs-url-exposed](https://cloud.githubusercontent.com/assets/723985/21748127/a09d1ae0-d54a-11e6-8874-e34eb9978838.png)

**Comment by soulgalore** [comment]
Since it hasn't been fixed since 2017 I think this is a minor issue and will never be fixed.
