### ISSUE TITLE
Template error when running sitespeed in NodeJS script

### ISSUE THREAD

**Issue by ronderksen** [sitespeedio/sitespeed.io#1444]
We have been using Sitespeed.io v3 in a NodeJS script and that worked just fine. I wanted to upgrade to v4 (v4.3.9 to be exact) so I adapted the script to match the changes in the Sitespeed api.

The tests are run without an issue, but then it fails on rendering the HTML report.
Here's the error (I've removed any personal information and changed the test url)

```
TypeError: node_modules/sitespeed.io/lib/plugins/html/templates/pages.pug:8
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://example.com/' of undefined
    6|     - p = pageInfo.data.pagexray ? pageInfo.data.pagexray.pageSummary : {}
    7|     - t = p.contentTypes || {javascript: {transferSize: ''}, css: {transferSize: ''}, image: {transferSize: ''}}
  > 8|     - display = options.urlsMetaData[url] ? options.urlsMetaData[url].alias : url
    9|     tr
    10|       td.url.pagesurl(data-title='URL')
    11|         a(href= pageInfo.path + 'index.html')= decodeURIComponent(display)

Cannot read property 'https://winkelmand.nl.wehkamp.dev.blaze-public.ps/' of undefined
    at Object.eval (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:144:31)
    at Object.pug_interp [as rows] (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:4)
    at eval (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:320:19)
    at template (eval at wrap (/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:184)
    at Object.renderTemplate (/node_modules/sitespeed.io/lib/plugins/html/renderer.js:28:37)
    at HTMLBuilder._renderSummaryPage (/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:196:67)
    at Object.keys.map (/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:27)
    at Array.map (native)
    at HTMLBuilder.render (/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:104:8)
    at Object.close (/node_modules/sitespeed.io/lib/plugins/html/index.js:26:29)
    at Promise.resolve.filter.map (/node_modules/sitespeed.io/lib/sitespeed.js:43:49)
    at tryCatcher (/node_modules/sitespeed.io/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/node_modules/sitespeed.io/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/node_modules/sitespeed.io/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/node_modules/sitespeed.io/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/node_modules/sitespeed.io/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/node_modules/sitespeed.io/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/node_modules/sitespeed.io/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/node_modules/sitespeed.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

I've tried figuring out where the urlsMetaData property would be set, and as far as I can tell it should be an empty object. However it just doesn't exist.

I compared my code to the grunt plugin and I don't see any implementation difference. I call Sitespeed with the following line (we are using ES2015 syntax):

```js
Sitespeed.run({ urls, resultBaseDir, outputFolder }))
```

urls is an array, resultBaseDir and outputFolder are strings, so that should all be okay. I've tried to debug it myself, but I couldn't figure out where the problem is.

**Comment by soulgalore** [comment]
Hey @ronderksen thanks for the report it looks like bug to me,
can you you show me the exact CLI params (but change the URL if you wanna keep it secret) so I'm sure I do exact as you when I'll try to reproduce.

Thanks!
Peter

**Comment by ronderksen** [comment]
Here's the script that we use:

```js
import path from 'path';
import url from 'url';
import rimraf from 'rimraf';
import fetch from 'isomorphic-fetch';
import Sitespeed from 'sitespeed.io/lib/sitespeed';

/**
 * Supported arguments:
 * --base=http://localhost:8000 Base URL
 * --dirname=<current datetime> Output directory name
 */
const args = process.argv.filter(arg => arg.indexOf('--') === 0).reduce((acc, arg) => {
  const [key, val] = arg.slice(2).split('=');
  return {
    ...acc,
    [key]: val
  };
}, {});

function start() {
  const baseUrl = args.base || 'https://example.com';
  const resultBaseDir = path.join(__dirname, 'reports');
  const outputFolder = args.dirname || new Date().toISOString();
  const { hostname } = url.parse(baseUrl);

  const urls = ['/'].map(urlPath => `${baseUrl}${urlPath}`);

  checkUrls(urls)
    .then(() => clearOutputDir(resultBaseDir, hostname, outputFolder))
    .then(() => Sitespeed.run({ urls, resultBaseDir, outputFolder }))
    .then((results) => {
      if (results.error.length > 0) {
        throw new Error(results.error);
      }
    })
    .catch((err) => {
      console.error(err); // eslint-disable-line no-console
      process.exit(1);
    });
}

function clearOutputDir(baseDir, hostname, outputFolder) {
  return new Promise((resolve, reject) => {
    rimraf(path.join(baseDir, hostname, outputFolder, '*'), err => err ? reject(err) : resolve());
  });
}

function checkUrls(urls) {
  return Promise.all(urls.map((url) => {
    return new Promise((resolve, reject) => fetch(url).then((res) => {
      if (res.ok) {
        console.log(`Loaded ${url}, now processing..`);
        resolve();
      } else {
        console.error(`URL failed to resolve: ${url}`);
        reject();
      }
    }));
  }));
}

start();

This is started with a simple `node ./sitespeed.js` command.

**Comment by soulgalore** [comment]
@beenanner do you feel you wanna take a look? If not, no pressure I can look at before next release. I think the problem was introduced with alias and that we take the CLI options but it breaks if we run without the CLI. We should add a small test for Travis-ci where we also run it like that.

**Comment by beenanner** [comment]
@ronderksen feel free to try out template-error-1444 branch for now. We should be releasing a new version this weekend so the fix will land in the next version. Thanks for reporting.

**Comment by ronderksen** [comment]
@beenanner Justed wanted to report that the fix is working for me when using the master branch now. Hope you can release a new version including this fix soon :)

**Comment by beenanner** [comment]
Great to hear @ronderksen! We are wrapping up some last minute issues and should be releasing soon. I'll give you a heads up once it's released.
