### ISSUE TITLE
Error at module.js:341

### ISSUE THREAD

**Issue by zacharybrady** [sitespeedio/sitespeed.io#1477]
When running any sitespeed.io command from the Terminal receive:

`module.js:341
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/sitespeed.io/lib/support/cli.js:3:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
`

I'm running macOs 10.12.3

I've seen other similar issues as well but this is the current one I'm getting. I got this version of sitespeed.io from this repository which seems to be different from the one on npm; which also has issues although completely different issues involving missing files.

**Comment by soulgalore** [comment]
Hey @zacharybrady thanks for reporting. In npm we have the latest release, master is coming release.

You didn't get any error when you run npm install (or do you use yarn)? If you cleanup your node_modules and reinstall, do you get the same? Can you share the install log?

Best
Peter

**Comment by soulgalore** [comment]
@zacharybrady is this still an issue? I wan't able to reproduce it. Please re-open if is still an issue for you.
