### ISSUE TITLE
Got error while trying to run on Jenkins

### ISSUE THREAD

**Issue by sakonachhoeurng** [sitespeedio/sitespeed.io#1478]
Hi, Please help me to see this problem. I need you to support because now it blocking me 1 day.

When I run on my ci sitespeed.io https://www.web-essentials.asia/
I do not know what it cause from.

Here are the error that reproduce:

```
[2017-02-28 12:54:23] Versions OS: linux 3.13.0-32-generic nodejs: v6.10.0 sitespeed.io: 4.4.2 browsertime: 1.0.0-beta.25 coach: 0.31.0

[2017-02-28 12:54:23] Starting chrome for analysing https://www.web-essentials.asia/ 3 time(s)
[2017-02-28 12:54:23] Testing url https://www.web-essentials.asia/ run 1
[2017-02-28 12:54:24] https://www.web-essentials.asia/ generated the following error in Browsertime BrowserError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-32-generic x86_64)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-32-generic x86_64)
    at BrowsertimeError (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:201:21)
    at Promise.reduce (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:279:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:278:17)
From previous event:
    at Engine.run (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:277:8)
    at engine.start.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
[2017-02-28 12:54:24] Render HTML for 1 page(s) 
[2017-02-28 12:54:25] HTML stored in /home/jenkins/jenkins-slave/sitespeed-result/www.web-essentials.asia/2017-02-28-12-54-23
[2017-02-28 12:54:25] Finished analysing https://www.web-essentials.asia/
```

**Comment by soulgalore** [comment]
See https://github.com/sitespeedio/browsertime/issues/282

**Comment by tobli** [comment]
Looking at #1471, it seems we can close this one, and sitespeedio/browsertime#282.
