### ISSUE TITLE
s3.region var - Cannot set property 'region' of undefined

### ISSUE THREAD

**Issue by jjethwa** [sitespeedio/sitespeed.io#1486]
Related to
Issue: https://github.com/sitespeedio/sitespeed.io/issues/1468
PR: https://github.com/sitespeedio/sitespeed.io/pull/1469

I think if we go back to what I had originally, but replace us-standard with us-east-1 it should work.  I poked around the AWS S3 docs and us-east-1 is the default region now.  Makes sense considering the us-east-1 outage the other day 😛 

I'll submit a new PR.  Hopefully it'll work for you as well, @soulgalore 😄 

```
[2017-03-01 23:04:13] TypeError: Cannot set property 'region' of undefined
    at getClient (/usr/src/app/lib/plugins/s3/index.js:26:31)
    at Object.postClose (/usr/src/app/lib/plugins/s3/index.js:50:20)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap.tap (/usr/src/app/lib/sitespeed.js:119:32)
    at Request._callback (/usr/src/app/node_modules/node-slack/slack.js:44:23)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:198:22)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:119:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:102:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:99:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:29:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by soulgalore** [comment]
Ah I see now my mistake, let me move out the options out of the creation face, that will make it cleaner, and then we keep the default of not setting anything.

**Comment by jjethwa** [comment]
Thanks, @soulgalore :smiley:
