### ISSUE TITLE
Fatal Error while running Jenkins + Docker + Sitespeedio

### ISSUE THREAD

**Issue by lapa182** [sitespeedio/sitespeed.io#1500]
I'm currently running sitespeedio using Docker in Jenkins and I'm getting the following error:

```
[2017-03-08 23:49:40] Send data to Graphite grafana.tribalddb.co.uk:2003
[2017-03-08 23:49:44] Send data to Graphite grafana.tribalddb.co.uk:2003

<--- Last few GCs --->

28945574 ms: Mark-sweep 1803.2 (2082.5) -> 1797.8 (2082.5) MB, 4214.9 / 0.0 ms [allocation failure] [GC in old space requested].
28949510 ms: Mark-sweep 1797.8 (2082.5) -> 1797.6 (2082.5) MB, 3935.1 / 0.0 ms [allocation failure] [GC in old space requested].
28954112 ms: Mark-sweep 1797.6 (2082.5) -> 1805.1 (2052.5) MB, 4601.8 / 0.0 ms [last resort gc].
28958766 ms: Mark-sweep 1805.1 (2052.5) -> 1812.8 (2052.5) MB, 4653.8 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x359c834cfb51 <JS Object>
    1: fromString(aka fromString) [buffer.js:~186] [pc=0x3346ca95e60] (this=0x359c83404381 <undefined>,string=0x327acabd6449 <Very long string[500043]>,encoding=0x359c834dd361 <String[4]: utf8>)
    2: from [buffer.js:~91] [pc=0x3346d652b36] (this=0xef7746c9891 <JS Function Buffer (SharedFunctionInfo 0xfec424f7311)>,value=0x327acabd6449 <Very long string[500043]>,encodingOrOffset=0x359c834dd361...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x1098b2c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [node]
12: 0x3346d6d74b4
/start.sh: line 30:    55 Aborted                 (core dumped) exec node --max-old-space-size=$MAX_OLD_SPACE_SIZE /usr/src/app/bin/sitespeed.js "$@"
time="2017-03-08T23:50:22Z" level=debug msg="[hijack] End of stdout" 
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/workspace/output to /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/htmlreports/Sitespeed.io_Report
Triggering a new build of REBOOT_JENKINS_SERVER
Finished: FAILURE
```

Sitespeedio version = 4.5.1
Command runned: `docker -l=debug -D run --privileged --shm-size=1g --rm -v /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/workspace:/sitespeed.io sitespeedio/sitespeed.io:4.5.1 --outputFolder output http://www.volkswagen.co.uk -b chrome -d 2 -n 2 --speedIndex --slack.hookUrl xxx--graphite.host grafana.tribalddb.co.uk -e MAX_OLD_SPACE_SIZE=4096`

If you want the full log I can attach here as well.

**Comment by soulgalore** [comment]
Hi @lapa182 ,
the MAX_OLD_SPACE_SIZE is in the wrong place, that needs to go to the Docker container, when we start sitespeed.io checkout https://github.com/sitespeedio/sitespeed.io/blob/master/docker/scripts/start.sh#L23-L25 

so change the <code>e</code> parameter to the beginning of the line (after docker) and it should work (now it goes to sitespeed.io)!

Best
Peter

**Comment by lapa182** [comment]
Hey @soulgalore, I will give it a try now. So would be `docker -e MAX_OLD_SPACE_SIZE -l=debug ...`, right?

**Comment by soulgalore** [comment]
cool, let me know if it works!

**Comment by lapa182** [comment]
Now I'm getting this:

```
[2017-03-09 11:35:51] {"cause":{"code":"ECONNRESET"},"isOperational":true,"code":"ECONNRESET"}
    at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at TLSSocket.Readable.on (_stream_readable.js:687:35)
    at tickOnSocket (_http_client.js:560:10)
    at onSocketNT (_http_client.js:580:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ClientRequest.onSocket (_http_client.js:572:11)
    at _http_agent.js:164:11
    at oncreate (_http_agent.js:235:5)
    at Agent.createSocket (_http_agent.js:197:5)
    at Agent.addRequest (_http_agent.js:157:10)
    at new ClientRequest (_http_client.js:160:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/usr/src/app/node_modules/request/request.js:793:30)
    at Request.write (/usr/src/app/node_modules/request/request.js:1390:10)
    at end (/usr/src/app/node_modules/request/request.js:550:16)
    at Immediate.<anonymous> (/usr/src/app/node_modules/request/request.js:578:7)
From previous event:
    at Object.close (/usr/src/app/lib/plugins/slack/index.js:61:20)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap (/usr/src/app/lib/sitespeed.js:118:32)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:118:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:102:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:99:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:29:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
    at Request.init (/usr/src/app/node_modules/request/request.js:200:10)
    at new Request (/usr/src/app/node_modules/request/request.js:140:8)
    at request (/usr/src/app/node_modules/request/index.js:55:10)
    at Function.post (/usr/src/app/node_modules/request/index.js:63:12)
    at Slack.send (/usr/src/app/node_modules/node-slack/slack.js:38:21)
    at Object.close (/usr/src/app/lib/plugins/slack/index.js:61:20)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
time="2017-03-09T11:35:52Z" level=debug msg="[hijack] End of stdout" 
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/workspace/output to /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/htmlreports/Sitespeed.io_Report
Triggering a new build of REBOOT_JENKINS_SERVER
Finished: FAILURE
```

**Comment by soulgalore** [comment]
Hey @lapa182 we had another issue with that exact thing for Slack? We have Slack up and running on dashboard.sitespeed.io but I haven't seen that error there. Can you disable Slack first to check that everything works ok? Then try to run sitespeed.io standalone outside of Jenkins and check that Slack works for you. Start local and then on the Jenkins server, to see if we can nail down the issue. 

Thanks
Peter

**Comment by lapa182** [comment]
So it worked without Slack, I'm going to give it a try to run outside of Jenkins, as soon is possible!

**Comment by soulgalore** [comment]
So it's some kind of Slack vs Jenkins thing? Hmm, let me know how it worked out!

**Comment by soulgalore** [comment]
@lapa182 did you find out anything more about this?

**Comment by lapa182** [comment]
I'm having issues to run Xvfb in Jenkins, so I can't test it properly :/. But seems that without the slackUrl is working as expected.

**Comment by soulgalore** [comment]
@lapa182 any luck that you can change to Docker then you get the XVFB for free?

**Comment by lapa182** [comment]
@soulgalore via docker it works without the slackUrl.

**Comment by soulgalore** [comment]
Closing this, please re-open if it is still a problem.
