### ISSUE TITLE
Browsertime BrowserError: Server terminated early with status 127

### ISSUE THREAD

**Issue by salt-lick** [sitespeedio/sitespeed.io#1546]
Followed the install instructions to clone from git

issued : bin/sitespeed.js http://www.sitespeed.io
issued: sitespeed.io http://www.sitespeed.io

node : v6.9.4 / v7.7.4
npm : v3.10.10 / 4.1.2

```[2017-03-23 19:20:37] ERROR: [plugin.browsertime] http://www.sitespeed.io generated the following error in Browsertime BrowserError: Server terminated early with status 127
    at BrowsertimeError (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/engine.js:205:21)
    at Promise.reduce (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/engine.js:283:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/engine.js:282:17)
From previous event:
    at Engine.run (/usr/local/nginx/npm/sitespeed.io/node_modules/browsertime/lib/core/engine.js:281:8)
    at engine.start.then (/usr/local/nginx/npm/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Object.analyzeUrl (/usr/local/nginx/npm/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/local/nginx/npm/sitespeed.io/lib/plugins/browsertime/index.js:131:34)
    at /usr/local/nginx/npm/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/local/nginx/npm/sitespeed.io/lib/plugins/browsertime/index.js:131:14)
    at queue.process (/usr/local/nginx/npm/sitespeed.io/lib/support/queueHandler.js:155:57)
    at drainItem (/usr/local/nginx/npm/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/nginx/npm/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by soulgalore** [comment]
Hey @salt-lick thanks for reporting, what OS, what Chrome version are you using? Does it work with Firefox?

Best
Peter

**Comment by tobli** [comment]
Also, is there a particular reason for cloning from git, and not installing via npm (or use the Docker image)? Cloning from git is meant for development, and if you run off master you might hit a revision that's not stable.

It'd be very helpful if you could provide the untruncated log output.

Thanks,
Tobias

**Comment by salt-lick** [comment]
- npm install -g sitespeed.io
 - CentOS Linux release 7.3.1611 (Core)

```
[root@ip-172-30-0-191 tmp]# sitespeed.io https://google.com
[2017-03-23 22:08:16] Versions OS: linux 3.10.0-514.10.2.el7.x86_64 nodejs: v6.9.4 sitespeed.io: 4.7.0 browsertime: 1.0.0-beta.31 coach: 0.31.0
[2017-03-23 22:08:17] Starting chrome for analysing https://google.com 3 time(s)
[2017-03-23 22:08:17] Testing url https://google.com run 1
[2017-03-23 22:08:17] https://google.com generated the following error in Browsertime BrowserError: Server terminated early with status 127
    at BrowsertimeError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:205:21)
    at Promise.reduce (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:283:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:282:17)
From previous event:
    at Engine.run (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:281:8)
    at engine.start.then (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Object.analyzeUrl (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:131:34)
    at /usr/lib/node_modules/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:131:14)
    at queue.process (/usr/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
[2017-03-23 22:08:17] Render HTML for 1 page(s)
[2017-03-23 22:08:18] HTML stored in /tmp/sitespeed-result/google.com/2017-03-23-22-08-16
[2017-03-23 22:08:18] Finished analysing https://google.com

```

[install_log_for_sitespeed.txt](https://github.com/sitespeedio/sitespeed.io/files/866353/install_log.txt)

**Comment by soulgalore** [comment]
Hey @salt-lick I didn't see what Chrome version you are running (to see that it match the Chromedriver). 

For some Linux versions you need to start Chrome with no-sandbox directive https://www.sitespeed.io/faq/#chrome-doesnt-work-on-rhel7-or-some-other-nix-flavor maybe it could be that? 

Else as @tobli said, we prefer the Docker container since it's easier for us to reproduce if there's any bug.

Best
Peter

**Comment by salt-lick** [comment]
@soulgalore : 

Google Chrome 57.0.2987.98
Mozilla Firefox 52.0

The --browsertime.chrome.args no-sandbox flag did not help

passing -b firefox does allow me to get things working

---------------------


Using 
```
docker run --privileged --shm-size=512m --rm -v "$wd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ -b chrome

docker run --privileged --shm-size=512m --rm -v "$wd)":/sitespeed.io sitespeedio/sitespeed.io https://www.sitespeed.io/ -b firefox
``` 
works as expected

**Comment by salt-lick** [comment]
@tobli : there was no reason to use the git version over the docker or npm versions. this was already failing so I thought I would give the git versions a try.

**Comment by tobli** [comment]
Check. Getting Chrome running on Linux has been an issue more than once, and we don't have a bulletproof solution to that. Docker has proven to work really well for providing a controlled environment for running all components. I hope that can work for you.

**Comment by soulgalore** [comment]
Ok so this is some Chrome/CentOS thing then and I think there's nothing we can do about it in the project, good that Docker worked out.
