### ISSUE TITLE
--webpagetest.private crashes sitespeed.io

### ISSUE THREAD

**Issue by JeroenVdb** [sitespeedio/sitespeed.io#1607]
When using the `--webpagetest.private` flag with a value of `0` this crashes sitespeed.io.

```
./bin/sitespeed.js --webpagetest.host my.host.com --webpagetest.key XXXX --webpagetest.private 0 --webpagetest.includeRepeatView true --webpagetest.median SpeedIndex --webpagetest.medianrun fa
stest --webpagetest.runs 9 --webpagetest.location eu-west-1:Chrome --webpagetest.label wpm.desktop.homepage --webpagetest.timeout 0 --webpagetest.connectivity Native --webpagetest.mobile 0 http://www.demorgen.be

/Users/jvandenberghe/Projects/sitespeed.io/lib/support/cliUtil.js:8
    urls = urls.map((url) => url.trim());
                                 ^
TypeError: url.trim is not a function
    at urls.map (/Users/jvandenberghe/Projects/sitespeed.io/lib/support/cliUtil.js:8:34)
    at Array.map (native)
    at Object.getURLs (/Users/jvandenberghe/Projects/sitespeed.io/lib/support/cliUtil.js:8:17)
    at Object.parseCommandLine (/Users/jvandenberghe/Projects/sitespeed.io/lib/support/cli.js:615:19)
    at Object.<anonymous> (/Users/jvandenberghe/Projects/sitespeed.io/bin/sitespeed.js:22:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

For some reason the value of `argv._` is: `[ 0, 'http://www.demorgen.be' ]` and you can't `trim()`a number. I guess this is a bug with yargs and will open an issue there.

If OK I'll send a PR with an extra check in sitespeed.io until this is fixed in yargs.

**Comment by soulgalore** [comment]
Hey @JeroenVdb and it doesn't work with `--webpagetest.private false`?  Did a fix a while ago for that. 

Best
Peter

**Comment by JeroenVdb** [comment]
Yes indeed, that works fine it looks like. I had not tried it because I thought I tried that earlier tries of that didn't work.
