### ISSUE TITLE
Fresh npm install of v5.1.0: chromedriver bin not found

### ISSUE THREAD

**Issue by fhemberger** [sitespeedio/sitespeed.io#1612]
Not sure this actually is a sitespeed.io issue rather than an npm thing:

```
sitespeed.io --plugins.list https://en.wikipedia.org/wiki/Barack_Obama


[2017-05-14 23:53:06] INFO: Versions OS: darwin 15.6.0 nodejs: v6.10.0 sitespeed.io: 5.1.0 browsertime: 1.2.5 coach: 0.34.1
[2017-05-14 23:53:06] INFO: The following plugins are enabled: assets, browsertime, budget, coach, datacollector, domains, harstorer, html, metrics, screenshot, text, tracestorer
[2017-05-14 23:53:07] INFO: Starting chrome for analysing https://en.wikipedia.org/wiki/Barack_Obama 3 time(s)
[2017-05-14 23:53:07] INFO: Testing url https://en.wikipedia.org/wiki/Barack_Obama run 1
[2017-05-14 23:53:07] INFO: Browser failed to start, trying one more time. Error: The specified executable path does not exist: /usr/local/lib/node_modules/sitespeed.io/node_modules/alto-saxophone/vendor/chromedriver
    at Error (native)
    at ServiceBuilder.<anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:329:13)
    at ServiceBuilder (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/chrome.js:208:5)
    at Object.module.exports.configureBuilder (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/webdriver/chrome.js:65:26)
    at Object.module.exports.createWebDriver (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/webdriver/index.js:32:14)
    at Promise.try (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:34:40)
From previous event:
    at SeleniumRunner.startBrowser (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:34:25)
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:43:25)
    at Promise.resolve.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:242:27)
From previous event:
    at runIteration (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:242:10)
    at Promise.reduce (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:326:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:325:17)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Engine.run (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:324:8)
    at engine.start.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
From previous event:
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:134:34)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:134:14)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:155:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Had to manually run
```
cd /usr/local/lib/node_modules/sitespeed.io/node_modules/alto-saxophone/
node install.js
```

**Comment by soulgalore** [comment]
Hi @fhemberger ok, hmm, and you didn't get any failures or error when installing? Maybe there's something missing when do install, that we should throw an error if something goes wrong. Let me check that later on.

Best
Peter

**Comment by fhemberger** [comment]
@soulgalore Updated from 4.x, update went through without any errors. As I said: Not sure this is really related to sitespeed.io, may as well have been an npm hiccup. Just wanted to document it, in case anybody else stumbles over this issue.

**Comment by beenanner** [comment]
Thanks for the report @fhemberger I've seen this before with `npm install` where it just "forgets" to install one of the dependencies. I just haven't seen it in a while. I think last time I just ran `npm install` again and it installed the second time. :'(

**Comment by beenanner** [comment]
This is another reason we are pushing for using the docker image and be the default preferred install method, that way you don't have to worry about stuff not installing correctly. ;-)

**Comment by beenanner** [comment]
Closing as it appears this was a npm install hiccup with the chrome driver and alto-saxophone module. Feel free to reopen if this somehow becomes reproducible.
