### ISSUE TITLE
summary option TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by gamerlv** [sitespeedio/sitespeed.io#1622]
When using just the `--summary` option pagespeed.io does not print any result or write any html files.
It does throws out a backtrace listed below.

Either I'm using the argument wrong or this is a bug, either way since it throws out an backtrace I decided to report it.

This was discovered using the official docker container.

I tried older versions but got the same result each time. I've seen this backtrace in versions `5.0.0`, `5.1.0`, `5.1.1`

Command: `docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://leviv.nu --summary`

Full console output: 
```                                                                                                         
Google Chrome 58.0.3029.81 
Mozilla Firefox 53.0
[2017-05-23 11:20:04] INFO: Versions OS: linux 4.4.0-72-generic nodejs: v6.9.1 sitespeed.io: 5.1.1 browsertime: 1.2.6 coach: 0.34.1
[2017-05-23 11:20:04] INFO: Starting chrome for analysing http://leviv.nu 3 time(s)
[2017-05-23 11:20:04] INFO: Testing url http://leviv.nu run 1
[2017-05-23 11:20:07] INFO: Testing url http://leviv.nu run 2
[2017-05-23 11:20:11] INFO: Testing url http://leviv.nu run 3
[2017-05-23 11:20:14] INFO: 7 requests, 119.94 kb, backEndTime: 105ms (±8.22ms), firstPaint: 202ms (±10.25ms), DOMContentLoaded: 142ms (±6.94ms), Load: 244ms (±8.39ms), rumSpeedIndex: 227 (±8.78) (3 runs)
[2017-05-23 11:20:14] INFO: Render HTML for 1 page(s) 
[2017-05-23 11:20:15] ERROR: TypeError: Cannot read property 'label' of undefined
    at getBoxes.map (/usr/src/app/lib/plugins/text/textBuilder.js:64:26)
    at Array.map (native)
    at renderBriefSummary (/usr/src/app/lib/plugins/text/textBuilder.js:63:30)
    at Object.close (/usr/src/app/lib/plugins/text/index.js:15:12)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap (/usr/src/app/lib/sitespeed.js:121:32)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:121:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:103:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:100:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

LSB: `Linux levi-workmachine 4.4.0-72-generic #93~14.04.1-Ubuntu SMP Fri Mar 31 15:05:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Docker version: 
```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:01:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by soulgalore** [comment]
Hi @gamerlv thanks for reporting, it's a bug lets fix that asap.

Best
Peter

**Comment by soulgalore** [comment]
Thanks @gamerlv for the detailed bug report, I've fixed it now in master, new release coming up.
