### ISSUE TITLE
--speedIndex flag crashes sitespeed.io command line

### ISSUE THREAD

**Issue by xavier-medioni** [sitespeedio/sitespeed.io#1634]
Hi Sitespeed team !

I wanted to report a quite annoying issue, i.e. the speedIndex does not work when adding the cli flag.

The required installations to use the speedIndex flag are OK, as:
<pre style="border: 1px solid #AAA; padding: 10px; background-color: #DDD;">
python visualmetrics.py --check
ffmpeg:   OK
convert:  OK
compare:  OK
Pillow:   OK
SSIM:     OK
</pre>

The following script runs perfectly as expected:

<pre style="border: 1px solid #AAA; padding: 10px; background-color: #DDD;">
#!/usr/bin/env bash

sitespeed.io \
                    https://en.wikipedia.org/wiki/Main_Page \
                    --outputFolder output/sitespeed-direct/ \
                    --browsertime.viewPort 1366x768 \
                    --plugins.load analysisstorer \
                    --plugins.disable html \
                    -b chrome \
                    -c native \
                    -n 1 \
                    --metrics.list \
                    1> output/sitespeed-direct/stdout.log \
                    2> output/sitespeed-direct/stderr.log
</pre>

And this one, only adding the speedIndex flag, does not work:

<pre style="border: 1px solid #AAA; padding: 10px; background-color: #DDD;">
#!/usr/bin/env bash

sitespeed.io \
                    https://en.wikipedia.org/wiki/Main_Page \
                    --outputFolder output/sitespeed-direct/ \
                    --browsertime.viewPort 1366x768 \
                    --plugins.load analysisstorer \
                    --plugins.disable html \
                    -b chrome \
                    -c native \
                    -n 1 \
                    --metrics.list \
                    --speedIndex \
                    1> output/sitespeed-direct/stdout.log \
                    2> output/sitespeed-direct/stderr.log
</pre>

The logs look like this:
- stdout:
<pre style="border: 1px solid #AAA; padding: 10px; background-color: #DDD;">
[2017-06-02 11:04:07] INFO: Versions OS: linux 4.4.0-78-generic nodejs: v7.0.0 sitespeed.io: 5.2.1 browsertime: 1.2.7 coach: 0.34.1
[2017-06-02 11:04:07] INFO: Starting chrome for analysing https://en.wikipedia.org/wiki/Main_Page 1 time(s)
[2017-06-02 11:04:07] INFO: Testing url https://en.wikipedia.org/wiki/Main_Page run 1
[2017-06-02 11:04:10] INFO: Finished analysing https://en.wikipedia.org/wiki/Main_Page
</pre>

- stderr:
<pre style="border: 1px solid #AAA; padding: 10px; background-color: #DDD;">
[2017-06-02 11:04:10] ERROR: Error: Command failed: ffmpeg -hide_banner -an -y -framerate 60 -probesize 1M -video_size 1366x702 -f x11grab -draw_mouse 0 -i :99.0+0,66 -c:v libx264 -pix_fmt yuv420p -profile:v main -movflags faststart -preset ultrafast /home/xavier/workspace/sitespeed/tests/speedline/output/sitespeed-direct/pages/en.wikipedia.org/wiki/Main_Page/data/video/0.mp4
[x11grab @ 0x264d300] Cannot open display :99.0+0,66, error 1.
:99.0+0,66: Input/output error

    at Promise.all.then.arr (/usr/lib/node_modules/sitespeed.io/node_modules/execa/index.js:208:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at startRecording (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/video/ffmpegRecorder.js:52:18)
    at Object.startRecordingX11 (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/video/ffmpegRecorder.js:75:12)
    at driver.get.then.then.then.then.then (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/support/video/scripts/startVideo.js:43:40)
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/promise.js:1384:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/usr/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /usr/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/promise.js:676:7
</pre>

As execution behaviour, the browser opens, with an orange background, and then immediately closes (without page loading).

I am not really sure about what to do / to test to make it work.

Thanks by advance !

Xavier

**Comment by soulgalore** [comment]
Hey @xavier-medioni I think the problem right now is that xvfb is hardcoded for Docker https://github.com/sitespeedio/browsertime/blob/2ba765e9562ae27ede83a86a6bf49c40ec34a1d5/lib/support/video/xvfb.js#L8 so you need to set it up exactly like that for it to work. We can fix that later on.

Best
Peter

**Comment by soulgalore** [comment]
And as always: it is best to run the Docker container :)

**Comment by soulgalore** [comment]
In 6.0 you can choose display number (check the docs for Browsertime), I think that fixes the problem, else please re-open.
