### ISSUE TITLE
Unable to run on Chrome 59 

### ISSUE THREAD

**Issue by vijaycs** [sitespeedio/sitespeed.io#1665]
Hi,

After updating chrome to latest version, I'm getting the below error. could you help me to reslove it.

I'm using sitespeed.io on MAC system.

generated the following error in Browsertime BrowserError: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64)
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.11.6 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:81:15)
From previous event:
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:80:13)
    at runIteration (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:211:21)
    at Promise.reduce (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:289:25)
From previous event:
    at Promise.resolve.tap.tap.tap (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:288:17)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Engine.run (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine.js:287:8)
    at engine.start.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:26)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
From previous event:
    at Object.analyzeUrl (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:76:8)
    at storageManager.createDirForUrl.then.then (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:34)
From previous event:
    at Object.processMessage (/usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:132:14)
    at queue.process (/usr/local/lib/node_modules/sitespeed.io/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by soulgalore** [comment]
Hi @vijaycs what version of sitespeed.io are you using? I see that your Chromedriver is outdated (2.27), latest sitespeed.io uses 2.30.

Also in the Docker version, we rolled forward to Chrome 60 beta, since Chrome 59 has a bug that makes video/SpeedIndex not work for us: https://bugs.chromium.org/p/chromium/issues/detail?id=727046

Best
Peter

**Comment by vijaycs** [comment]
Hi Peter,

Thank you for looking into this.

I have updated to chrome browser to 60 and also i have updated to chrome driver 2.30.***. Also my sitespeed.io version is 4.4.0. 

But when i run the sitespeed.io command it's taking the older version of chrome driver as mentioned in the above. Please help to solve this.

Thanks,
Vijay M

**Comment by vijaycs** [comment]
Hi Peter,

Issue got resolved by updating sitespeed.io to 5.4.1.

Thank you for helping :)
