### ISSUE TITLE
Intermittently missing data for largestassets.summary

### ISSUE THREAD

**Issue by julrich** [sitespeedio/sitespeed.io#1676]
Since switching to 5.4.1 we've had some (seemingly random) failures on some test-runs relating to `largestassets.summary`.

The error displayed is the following:
```
[2017-07-19 08:07:37] ERROR: Error: No data to send to graphite for message:
{
  "uuid": "83a5a939-92e0-4a3a-9d69-cc768b712e4a",
  "type": "largestassets.summary",
  "timestamp": "2017-07-19T08:07:37+00:00",
  "source": "assets",
  "data": {
    "plain": []
  },
  "group": "url.that.was.tested
[20170719-sitespeedio-error-log.txt](https://github.com/sitespeedio/sitespeed.io/files/1158767/20170719-sitespeedio-error-log.txt)

"
}
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:59:29)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:155:57)
From previous event:
    at queue.process (/usr/src/app/lib/support/queueHandler.js:155:42)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

A full log is attached, too [1]. Just re-running the failed one fixes it in all cases that happened so far (probably because the chance of failure itself is relatively low, we run ~30-50 tests per day).

[1][20170719-sitespeedio-error-log.txt](https://github.com/sitespeedio/sitespeed.io/files/1158768/20170719-sitespeedio-error-log.txt)

**Comment by soulgalore** [comment]
Thanks @julrich for reporting. @tobli or @beenanner do you see whats wrong? I can have a look later if you don't have time!

**Comment by beenanner** [comment]
Possible related to the code waiting for the first of a type before classifying remaining assets? The initial HTML page doesn't show up as the largest of it's kind for testing against https://www.sitespeed.io

https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/assets/aggregator.js#L36

**Comment by soulgalore** [comment]
@beenanner you are right, seems like a bug, I think I've missed checking in something in the past, the constructor misses some parameters, let me fix that.

**Comment by soulgalore** [comment]
Released this today, I'll close it now but please re-open @julrich if you still see it in the logs after upgrading to 5.4.4.

**Comment by julrich** [comment]
Perfect, will give this a spin... and report back!

**Comment by julrich** [comment]
About 30-50 scans later, error gone 💯  :)

**Comment by soulgalore** [comment]
thanks @julrich for reporting back!
