### ISSUE TITLE
WebDriverError when testing some pages

### ISSUE THREAD

**Issue by kchoi01** [sitespeedio/sitespeed.io#1684]
Running from latest docker.
Getting this error when testing www.flipkart.com. Please see the following dump.

Google Chrome 60.0.3112.66 beta
Mozilla Firefox 54.0
[2017-07-28 21:17:44] INFO: Versions OS: linux 4.4.0-1018-aws nodejs: v6.11.1 si                                                 tespeed.io: 5.4.4 browsertime: 1.5.4 coach: 0.34.1
[2017-07-28 21:17:45] INFO: Starting chrome for analysing https://www.flipkart.c                                                 om/ 3 time(s)
[2017-07-28 21:17:45] INFO: Testing url https://www.flipkart.com/ run 1
[2017-07-28 21:17:48] INFO: Catched a WebDriverError [unknown error: session del                                                 eted because of page crash
from tab crashed
  (Session info: chrome=60.0.3112.66)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b                                                 57),platform=Linux 4.4.0-1018-aws x86_64)]. Try one more time.WebDriverError: un                                                 known error: session deleted because of page crash
from tab crashed
  (Session info: chrome=60.0.3112.66)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b                                                 57),platform=Linux 4.4.0-1018-aws x86_64)
[2017-07-28 21:17:49] ERROR: WebDriverError:WebDriverError: no such session
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b                                                 57),platform=Linux 4.4.0-1018-aws x86_64)
[2017-07-28 21:17:49] ERROR: Could not load URLUrlLoadError: Failed to load http                                                 s://www.flipkart.com/, cause: no such session
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b                                                 57),platform=Linux 4.4.0-1018-aws x86_64)
[2017-07-28 21:17:49] ERROR: https://www.flipkart.com/ generated the following e                                                 rror in Browsertime UrlLoadError: Failed to load https://www.flipkart.com/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/error                                                 s.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js                                                 :19:5)
    at getUrl.then.then.catch.catch (/usr/src/app/node_modules/browsertime/lib/c                                                 ore/seleniumRunner.js:150:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/cor                                                 e/seleniumRunner.js:148:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertim                                                 e/lib/core/engine.js:261:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:26                                                 1:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:                                                 326:25)
From previous event:
    at Promise.resolve.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/li                                                 b/core/engine.js:325:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:324:                                                 8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26                                                 )
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browse                                                 rtime/index.js:178:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:178:                                                 12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:8                                                 4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-07-28 21:17:49] ERROR: TypeError: Cannot read property 'getItems' of undef                                                 ined
    at Object.summarize (/usr/src/app/lib/plugins/assets/aggregator.js:103:49)
    at Object.processMessage (/usr/src/app/lib/plugins/assets/index.js:40:36)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:8                                                 4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by soulgalore** [comment]
Hey @kchoi01 thanks for the report. The pages crashes in Chrome, usually, that happens when there's not enough memory. How much memory do you have on the server that runs sitespeed.io?

Best
Peter

**Comment by kchoi01** [comment]
Hi, the node is an AWS EC2 C4.large so 3.75GB mem. Also, this is the only page that crashes. Even other pages from the same site have no issues.

**Comment by soulgalore** [comment]
Hi @kchoi01 this works for me. Please re-open if this is still a problem for you.
