### ISSUE TITLE
SitespeedIO + Webpagetest(private instance) First View: Test Data missing 

### ISSUE THREAD

**Issue by goblinbomb** [sitespeedio/sitespeed.io#1698]
Hi There,
I am trying to run a webpagetest script (contains user journey) using sitespeedio against a private webpagetest instance and keep getting the following error message(stacktrace below).  I have masked the key  host, API key, website name etc.  Below is the docker command to run webpagetest via sitespeed, script & stacktrace.

**_command:_** docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --webpagetest.host xxxxx  --webpagetest.key xxxx --webpagetest.location xxxx --webpagetest.connectivity Cable --webpagetest.runs 3 --webpagetest.private false --webpagetest.file /sitespeed.io/search.txt urlxxxx

**_search.txt:_**
setEventName	HomePage
navigate	{{{URL}}}
exec	document.getElementById('SimpleSearchForm_SearchTerm').value = 'shirts'
setEventName	SearchList
execAndWait	$('#SimpleSearchForm_SearchTerm').keyup()
setEventName	SearchResult
clickAndWait	name=Search
setEventName	ProductPage
execAndWait	window.location=document.getElementsByClassName("item-img")[1].getElementsByTagName('a')[0].href

**_Stacktrace:_**
Google Chrome 60.0.3112.78
Mozilla Firefox 54.0
[2017-08-31 01:25:00] INFO: Versions OS: linux 4.4.30-32.54.amzn1.x86_64 nodejs: v6.11.1 sitespeed.io: 5.5.0 browsertime: 1.6.1 coach: 0.36.0
[2017-08-31 01:25:00] INFO: Sending url urlxxxx to test on xxxxx
[2017-08-31 01:25:00] INFO: Starting chrome for analysing urlxxxx 3 time(s)
[2017-08-31 01:25:01] Testing url urlxxxx run 1
[2017-08-31 01:25:12] Testing url urlxxxx run 2
[2017-08-31 01:25:21] Testing url urlxxxx run 3
[2017-08-31 01:25:31] 206 requests, 2543.57 kb, backEndTime: 117ms (Â±16.45ms), firstPaint: 1.34s (Â±32.46ms), DOMContentLoaded: 1.98s (Â±64.46ms), Load: 5.07s (Â±100.32ms), rumSpeedIndex: 1550 (Â±40.33) (3 runs)
[2017-08-31 01:25:51] INFO: Got urlxxxx analysed with id 170831_xxxx_x from xxxxx
[2017-08-31 01:25:52] ERROR: First View: Test Data Missing
[2017-08-31 01:25:52] INFO: Render HTML for 1 page(s)
Unhandled rejection TypeError: /usr/src/app/lib/plugins/html/templates/url/webpagetest/index.pug:193
    191|       table(data-sortable, id='contentSize')
    192|         +rowHeading(['Type', 'size', 'size uncompressed', 'requests'])
  > 193|         each value, contentType in median.breakdown
    194|           tr
    195|             td(data-title='Content Type') #{contentType}
    196|             +sizeCell('Size', median.breakdown[contentType].bytes)

Cannot read property 'length' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4042:31)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4079:4)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4714:4)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4997:184)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder._renderUrlPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:229:16)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:166:19)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:137:69)
    at Object.close (/usr/src/app/lib/plugins/html/index.js:21:29)
    at Promise.resolve.filter.map.plugin (/usr/src/app/lib/sitespeed.js:45:47)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap.errors (/usr/src/app/lib/sitespeed.js:152:15)
From previous event:
    at loader.loadPlugins.then.plugins (/usr/src/app/lib/sitespeed.js:151:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then.pluginNames (/usr/src/app/lib/sitespeed.js:129:48)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:128:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[2017-08-31 01:25:55] ERROR: TypeError: /usr/src/app/lib/plugins/html/templates/url/webpagetest/index.pug:193
    191|       table(data-sortable, id='contentSize')
    192|         +rowHeading(['Type', 'size', 'size uncompressed', 'requests'])
  > 193|         each value, contentType in median.breakdown
    194|           tr
    195|             td(data-title='Content Type') #{contentType}
    196|             +sizeCell('Size', median.breakdown[contentType].bytes)

Cannot read property 'length' of undefined
    191|       table(data-sortable, id='contentSize')
    192|         +rowHeading(['Type', 'size', 'size uncompressed', 'requests'])
  > 193|         each value, contentType in median.breakdown
    194|           tr
    195|             td(data-title='Content Type') #{contentType}
    196|             +sizeCell('Size', median.breakdown[contentType].bytes)

Cannot read property 'length' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4042:31)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4079:4)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4714:4)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4997:184)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder._renderUrlPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:229:16)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:166:19)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:137:69)
    at Object.close (/usr/src/app/lib/plugins/html/index.js:21:29)
    at Promise.resolve.filter.map.plugin (/usr/src/app/lib/sitespeed.js:45:47)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap.errors (/usr/src/app/lib/sitespeed.js:152:15)
From previous event:
    at loader.loadPlugins.then.plugins (/usr/src/app/lib/sitespeed.js:151:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then.pluginNames (/usr/src/app/lib/sitespeed.js:129:48)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:128:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by soulgalore** [comment]
Hi @goblinbomb and thanks for the report.

Ok, I think there's a couple of things we could fix on our side. The first error in the log comes from that the WebPageTest data is missing fullyLoaded: 
https://github.com/sitespeedio/sitespeed.io/blob/c9c2f607d24966161c0cc992ad01dd78f6aec694/lib/plugins/webpagetest/aggregator.js#L31

We added that check because for some larger websites like cnet/nytimes some WebPageTest runs fails (no data is collected but still return error code ok). But I guess in your case the fullyLoaded haven't happend before you do the search, can you confirm that?

Then we need to add some checks in the front end that the WPT data really exists, let me fix that during the weekend.

Does everything looks ok on your result page on WebPageTest? If you could share a run or exact how to reproduce I can fix it faster :)

Best
Peter

**Comment by goblinbomb** [comment]
Hi @soulgalore, yes everything looks ok on the result page for the webpagetest. Unfortunately, I am not able to share the webpage private instance information or result (after discussing with our security team). However is there any other information that I can share that could help you?

**Comment by soulgalore** [comment]
I've pushed one change in master and the other one I wanna have @beenanner check first. Can you run from a specific branch to test? Else if you look at the JSON from the WebPageTest API and confirm that fullyLoaded is 0, that would be cool.

But I'm not really sure fully understand what you want to measure? Like what metrics are important to you when you access multiple URLs? The total time?

**Comment by goblinbomb** [comment]
Hi @soulgalore, I am trying to get timing & resource information for a user journey across different pages. I am mainly looking for Load time, first byte, start render time and stats for document complete & Fully loaded. 

In the above case, I have a user that
1: Navigates to our website home page
2: Types a search item and gets an auto suggested dropdown list
3: He then selects one of the item from the list, which then displays category page
4: The user then selects the first product on the category page and therefore takes him to the product page.

By running this way, I am trying to get page timing and then sending this information to influxdb & plot it using grafana. This will allow us to track any degradation/improvement over time due to changes we make to the website.

**Comment by soulgalore** [comment]
Yes but do you get that separated in the JSON from WebPageTest? Like do you get TTFB for the first or the second page, or is that separated in the JSON from WebPageTest? I  don't think we handle that today in sitespeed.io. I think it will probably only work "right" if you turn off/on metrics with *logData*. But I could be wrong :)

**Comment by soulgalore** [comment]
Closing, please re-open if this is still an issue.
