### ISSUE TITLE
Error when using sitespeed.io

### ISSUE THREAD

**Issue by mizbanpaytakht** [sitespeedio/sitespeed.io#1701]
Hi,

I installed sitespeed.io by using npm and yarn but its not working !

`[root@sitespeed ~]# sitespeed.io -b chrome --browsertime.chrome.args no-sandbox http://google.com
[2017-09-03 07:02:24] INFO: Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.11.1 sitespeed.io: 5.5.0 browsertime: 1.6.1 coach: 0.36.0
[2017-09-03 07:02:24] INFO: Starting chrome for analysing http://google.com 3 time(s)
[2017-09-03 07:02:24] Testing url http://google.com run 1
(node:2210) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Server terminated early with status 1
(node:2210) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[2017-09-03 07:02:24] Browser failed to start, trying one more time. Error: Server terminated early with status 1
    at Error (native)
    at earlyTermination.catch.e (/usr/local/share/.config/yarn/global/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Function.createSession (/usr/local/share/.config/yarn/global/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/local/share/.config/yarn/global/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/usr/local/share/.config/yarn/global/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/share/.config/yarn/global/node_modules/selenium-webdriver/index.js:642:16)
    at Promise.try (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/webdriver/index.js:45:36)
From previous event:
    at Object.module.exports.createWebDriver (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/webdriver/index.js:45:21)
    at Promise.try (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:36:17)
From previous event:
    at SeleniumRunner.startBrowser (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:35:25)
    at SeleniumRunner.start (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:27)
From previous event:
    at runIteration (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:10)
    at Promise.reduce (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:357:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:354:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:353:8)
    at engine.start.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:32)
    at /usr/local/share/.config/yarn/global/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:12)
    at queue.process.message (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
(node:2210) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Server terminated early with status 1
(node:2210) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[2017-09-03 07:02:25] ERROR: http://google.com generated the following error in Browsertime BrowserError: Server terminated early with status 1
    at BrowsertimeError (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch.e (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:92:15)
From previous event:
    at SeleniumRunner.start (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:91:13)
    at Promise.resolve.tap (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:27)
From previous event:
    at runIteration (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:10)
    at Promise.reduce (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:357:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:354:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:353:8)
    at engine.start.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:32)
    at /usr/local/share/.config/yarn/global/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:12)
    at queue.process.message (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-03 07:02:25] ERROR: TypeError: Cannot read property 'getItems' of undefined
    at Object.summarize (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/assets/aggregator.js:103:49)
    at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/assets/index.js:40:36)
    at queue.process.message (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-03 07:02:25] INFO: Render HTML for 1 page(s)
[2017-09-03 07:02:26] INFO: HTML stored in /root/sitespeed-result/google.com/2017-09-03-07-02-24
[2017-09-03 07:02:26] INFO: Finished analysing http://google.com
`

[root@sitespeed ~]# sitespeed.io -V
sitespeed.io 5.5.0

**Comment by soulgalore** [comment]
HI @mizbanpaytakht 
thanks for the report. What OS and what Chrome version are you using? I've seen the error before when Chromedriver (that starts/drives Chrome) miss-match the Chrome version.

Best
Peter

**Comment by mizbanpaytakht** [comment]
OS: CentOS 7.3.1611 x64
ChromeDriver: 2.29 on port 9515
SeLinux: Disabled
Google Chrome: 60.0.3112.113

**Comment by soulgalore** [comment]
Ok, and you run XVFB or do you have a screen (just making sure that everything is setup correctly).

**Comment by mizbanpaytakht** [comment]
I'm using sitespeed via command line and start Xvfb by this command
nohup Xvfb :99 > /dev/null 2>&1 &
also tried
xvfb-run --server-args='-screen 0' sitespeed.io -b chrome http://google.com

**Comment by soulgalore** [comment]
Hi @mizbanpaytakht sorry for not getting back. I haven't had time to test on CentOS. Are you able to test if it works with Firefox (then we know if it is a Chrome issue) or better to run in Docker, that's our recommended way.

Best
Peter

**Comment by mizbanpaytakht** [comment]
Hi Again,
since I want to get the data by PHP code its not possible for me to run it via Docker.

`[root@sitespeed ~]# xvfb-run --server-args='-screen 0' sitespeed.io -b chrome h^Cp://google.com
[root@sitespeed ~]# nohup Xvfb :99 > /dev/null 2>&1 &
[1] 25179
[root@sitespeed ~]# xvfb-run --server-args='-screen 0' sitespeed.io -b firefox http://google.com
[2017-09-18 07:25:00] INFO: Versions OS: linux 3.10.0-514.el7.x86_64 nodejs: v6.11.1 sitespeed.io: 5.5.0 browsertime: 1.6.1 coach: 0.36.0
[2017-09-18 07:25:01] INFO: Starting firefox for analysing http://google.com 3 time(s)
[2017-09-18 07:25:01] Testing url http://google.com run 1
[2017-09-18 07:26:01] Browser failed to start, trying one more time. TimeoutError: Failed to start browser in 60 seconds.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at SeleniumRunner.startBrowser (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:39:9)
    at SeleniumRunner.start (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:27)
From previous event:
    at runIteration (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:10)
    at Promise.reduce (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:357:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:354:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:353:8)
    at engine.start.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:32)
    at /usr/local/share/.config/yarn/global/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:179:12)
    at queue.process.message (/usr/local/share/.config/yarn/global/node_modules/sitespeed.io/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/local/share/.config/yarn/global/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at SeleniumRunner.startBrowser (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:39:9)
    at SeleniumRunner.start (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/local/share/.config/yarn/global/node_modules/browsertime/lib/core/engine.js:260:27)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
`

**Comment by soulgalore** [comment]
Hi @mizbanpaytakht m
you can run from PHP shell I think?

If both browsers fail, then it seems to be something with XVFB, that is my guess.

Best
Peter

**Comment by kamilkrzeminski** [comment]
I had the same issue on Ubuntu 14.04, while I hadn't installed Chrome/Firefox yet ;)

**Comment by soulgalore** [comment]
Please re-open if this is still an issue for you.
