### ISSUE TITLE
Browsertime Docker image --preScript error "Couldn't run pre/post script file: /login.js Error: Cannot find module '/login.js'"

### ISSUE THREAD

**Issue by pi-bjl** [sitespeedio/sitespeed.io#1703]
It seems like the --preScript option is parsed differently in the browsertime Docker image compared to the sitespeed.io one. I have a login.js for using with preScript which works with sitespeed.io but with browsertime it says it has prepended a '/' and can't find the file.

```
bjl@BJL-PC:~/workspace/sitespeedio$ ls
login.js  sitespeed-result
bjl@BJL-PC:~/workspace/sitespeedio$ sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --preScript login.js  https://10.100.22.35/patients -n 1
Google Chrome 60.0.3112.78 
Mozilla Firefox 54.0
[2017-09-07 03:50:42] INFO: Versions OS: linux 4.4.0-87-generic nodejs: v6.11.1 sitespeed.io: 5.5.0 browsertime: 1.6.1 coach: 0.36.0
[2017-09-07 03:50:42] INFO: Starting chrome for analysing https://10.100.22.35/patients 1 time(s)
[2017-09-07 03:50:42] Testing url https://10.100.22.35/patients run 1
[2017-09-07 03:50:47] 60 requests, 565.61 kb, backEndTime: 61ms, firstPaint: 146ms, DOMContentLoaded: 140ms, Load: 144ms, rumSpeedIndex: 213
[2017-09-07 03:50:47] INFO: Render HTML for 1 page(s) 
[2017-09-07 03:50:48] INFO: HTML stored in /sitespeed.io/sitespeed-result/10.100.22.35/2017-09-07-03-50-42
[2017-09-07 03:50:48] INFO: Finished analysing https://10.100.22.35/patients
bjl@BJL-PC:~/workspace/sitespeedio$ sudo docker run --shm-size=1g --rm -v "$(pwd)":/browsertime-results sitespeedio/browsertime --video --speedIndex --preScript login.js https://10.100.22.35/patients -b chrome -n 1
Google Chrome 60.0.3112.78 
Mozilla Firefox 54.0
[2017-09-07 03:51:14] Couldn't run pre/post script file: /login.js Error: Cannot find module '/login.js'
/usr/src/app/lib/core/engine.js:131
      throw e;
      ^

Error: Couldn't run pre/post script file: /login.js Error: Cannot find module '/login.js'
    at util.toArray.map.e (/usr/src/app/lib/core/engine.js:44:13)
    at Array.map (native)
    at loadPrePostScripts (/usr/src/app/lib/core/engine.js:40:32)
    at new Engine (/usr/src/app/lib/core/engine.js:127:27)
    at run (/usr/src/app/bin/browsertime.js:39:16)
    at Object.<anonymous> (/usr/src/app/bin/browsertime.js:137:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Thanks for providing these interesting tools :)

**Comment by soulgalore** [comment]
Hi @pi-bjl  I think we should change the workdir for Browserime in Docker (right now it is / so it's hard to link as a volume). Right now in your example, the result dir is mapped as a volume. This should be a browsertime issue, I can create one later this week and link it here.

Eh was that understandable? I agree it is kind of strange as it is now, and we should change it, thanks or letting us know!

Best
Peter

**Comment by pi-bjl** [comment]
That sounds great, thanks @soulgalore!

**Comment by soulgalore** [comment]
Merged in Browsertime, think we can roll it out early next week.

**Comment by soulgalore** [comment]
Released BT yesterday with the fix.
