### ISSUE TITLE
Unable to enable chrome data compression proxy

### ISSUE THREAD

**Issue by debopambhattacherjee** [sitespeedio/sitespeed.io#1713]
I am unable to load urls using chrome with the data compression proxy enabled although there exists a flag for doing so. I am using --browsertime.chrome.args for setting the flag. Below is the command followed by the output.

COMMAND:

sudo docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --speedIndex -n 1 -b chrome --browsertime.chrome.args enable-spdy-proxy-auth http://www.washington.edu

LOG:

Google Chrome 60.0.3112.78 
Mozilla Firefox 54.0
[2017-09-17 12:35:59] INFO: Versions OS: linux 4.4.0-93-generic nodejs: v6.11.1 sitespeed.io: 5.5.0 browsertime: 1.6.1 coach: 0.36.0
[2017-09-17 12:35:59] INFO: Starting chrome for analysing http://www.washington.edu 1 time(s)
[2017-09-17 12:35:59] Testing url http://www.washington.edu run 1
[2017-09-17 12:36:59] Browser failed to start, trying one more time. TimeoutError: Failed to start browser in 60 seconds.
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:39:9)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:260:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:260:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:357:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:354:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:353:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:179:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:179:12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:39:9)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:260:27)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-17 12:37:59] ERROR: http://www.washington.edu generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at BrowserError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:13:5)
    at startBrowser.call.catch.tap.tap.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:92:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:91:13)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:260:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:357:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:354:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:353:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:179:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:179:12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at SeleniumRunner.startBrowser (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:39:9)
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:49:8)
    at Promise.resolve.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:260:27)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-17 12:37:59] ERROR: TypeError: Cannot read property 'getItems' of undefined
    at Object.summarize (/usr/src/app/lib/plugins/assets/aggregator.js:103:49)
    at Object.processMessage (/usr/src/app/lib/plugins/assets/index.js:40:36)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:183:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-09-17 12:37:59] INFO: Render HTML for 1 page(s) 
[2017-09-17 12:38:00] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.washington.edu/2017-09-17-12-35-59
[2017-09-17 12:38:00] INFO: Finished analysing http://www.washington.edu

**Comment by soulgalore** [comment]
Hi @debopambhattacherjee ahh sorry, this isn't documented, let's see if we can fix this automatically: When you run in Docker [we set no-sandbox](https://github.com/sitespeedio/sitespeed.io/blob/master/Dockerfile#L4) to Chrome in the Docker file and that one is overwritten when you add extra Chrome args. If you **add --browsertime.chrome.args no-sandbox** to your parameters it will work.

Best
Peter

**Comment by debopambhattacherjee** [comment]
Thanks! It worked like a charm!
