### ISSUE TITLE
problem with median.customcus in webpagetest/index.pug

### ISSUE THREAD

**Issue by meetri** [sitespeedio/sitespeed.io#1737]
I'm getting the following error on this latest docker version of sitespeed/sitespeed.io:5.6.3 
I can't give you the url as these are part of internal tests but I can certainly do any debugging required to help solve this problem.

Looking at the code it seems a bit weird since it shouldn't even get to this part of the code, it may be related to the fix for https://github.com/sitespeedio/sitespeed.io/issues/1722

https://github.com/sitespeedio/sitespeed.io/commit/134acffa5943f2c7016850e2e7f31b77379ae5f9

The stack trace is the following:
[2017-10-10 17:04:06] INFO: 93 requests, 466.34 kb, backEndTime: 245ms (±20.53ms), firstPaint: 735ms (±40.31ms), firstVisualChange: 811ms (±28.27ms), DOMContentLoaded: 1.77s (±55.15ms), Load: 2.36s (±22.4
0ms), speedIndex: 1998 (±48.16), visualComplete85: 2.34s (±180.25ms), lastVisualChange: 6.15s (±37.80ms), rumSpeedIndex: 2010 (±40.84) (3 runs)
Unhandled rejection TypeError: /usr/src/app/lib/plugins/html/templates/url/webpagetest/index.pug:181
    179|         table
    180|           th(colspan='2') Custom metrics
  > 181|           each key in median.customcus
    182|             tr
    183|               td #{key}
    184|               td.break #{median[key]}

Cannot read property 'length' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4026:31)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4057:4)
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4798:4)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5081:184)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder._renderUrlPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:232:16)
    at Promise.resolve.map.url (/usr/src/app/lib/plugins/html/htmlBuilder.js:169:19)
From previous event:
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:137:69)
    at Object.close (/usr/src/app/lib/plugins/html/index.js:21:29)
    at Promise.resolve.filter.map.plugin (/usr/src/app/lib/sitespeed.js:45:47)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap.errors (/usr/src/app/lib/sitespeed.js:152:15)
From previous event:
    at loader.loadPlugins.then.plugins (/usr/src/app/lib/sitespeed.js:151:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then.pluginNames (/usr/src/app/lib/sitespeed.js:129:48)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:128:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by soulgalore** [comment]
Hi @meetri ,
thanks for reporting! 

Yep it is the check for custom metrics for WPT that fails, I'll look into it tonight or early tomorrow and do a fix release.

Best
Peter

**Comment by meetri** [comment]
cool, let me know if you'd like me to test it.

**Comment by soulgalore** [comment]
I've pushed the fix in the 5.x branch yesterday, I'll release it tonight.

**Comment by soulgalore** [comment]
Pushed 5.6.4 today. It works for me but please verify when you have time @meetri !
