### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by moehlone** [sitespeedio/sitespeed.io#1738]
Hi,

I get the following output/error after some tests ran successfully:

```
> sitespeed_measurements@1.0.0 all_mobile_chrome_lte_video /**hidden**/sitespeed.io
> npm run all_mobile_chrome_lte_video_firstView && npm run all_mobile_chrome_lte_video_repeatedView


> sitespeed_measurements@1.0.0 all_mobile_chrome_lte_video_firstView /**hidden**/sitespeed.io
> npm run async_mobile_chrome_lte_video_firstView && npm run defer_mobile_chrome_lte_video_firstView && npm run original_mobile_chrome_lte_video_firstView && npm run preload_mobile_chrome_lte_video_firstView


> sitespeed_measurements@1.0.0 async_mobile_chrome_lte_video_firstView /**hidden**/sitespeed.io
> sitespeed.io --config mobile_chrome_lte_video_firstView.json urls_async.txt

[2017-10-12 09:53:19] INFO: Versions OS: darwin 16.7.0 nodejs: v6.11.1 sitespeed.io: 5.6.4 browsertime: 1.9.4 coach: 0.36.0
[2017-10-12 09:53:20] INFO: Starting chrome for analysing https://**hidden**.cloudfront.net/async_test/sf/index.html 5 time(s)
[2017-10-12 09:53:20] INFO: Testing url https://**hidden**.cloudfront.net/async_test/sf/index.html run 1
[2017-10-12 09:53:27] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 09:53:45] INFO: Converting video to 60 fps
[2017-10-12 09:55:01] INFO: Testing url https://**hidden**.cloudfront.net/async_test/sf/index.html run 2
[2017-10-12 09:55:08] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 09:55:28] INFO: Converting video to 60 fps
[2017-10-12 09:56:47] INFO: Testing url https://**hidden**.cloudfront.net/async_test/sf/index.html run 3
[2017-10-12 09:56:53] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 09:57:10] INFO: Converting video to 60 fps
[2017-10-12 09:58:06] INFO: Testing url https://**hidden**.cloudfront.net/async_test/sf/index.html run 4
[2017-10-12 09:58:12] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 09:58:28] INFO: Converting video to 60 fps
[2017-10-12 09:59:30] INFO: Testing url https://**hidden**.cloudfront.net/async_test/sf/index.html run 5
[2017-10-12 09:59:36] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 09:59:51] INFO: Converting video to 60 fps
[2017-10-12 10:00:46] INFO: 86 requests, 945.37 kb, backEndTime: 1.09s (±160.96ms), firstPaint: 2.48s (±269.93ms), firstVisualChange: 2.99s (±279.82ms), DOMContentLoaded: 3.02s (±274.48ms), Load: 5.66s (±830.07ms), speedIndex: 4650 (±276.36), visualComplete85: 7.62s (±302.22ms), lastVisualChange: 9.16s (±1.08s), rumSpeedIndex: 3252 (±418.47) (5 runs)
[2017-10-12 10:00:48] INFO: Starting chrome for analysing https://**hidden**.cloudfront.net/async_test/mes/index.html 5 time(s)
[2017-10-12 10:00:48] INFO: Testing url https://**hidden**.cloudfront.net/async_test/mes/index.html run 1
[2017-10-12 10:00:54] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:01:12] INFO: Converting video to 60 fps
[2017-10-12 10:02:07] INFO: Testing url https://**hidden**.cloudfront.net/async_test/mes/index.html run 2
[2017-10-12 10:02:12] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:02:27] INFO: Converting video to 60 fps
[2017-10-12 10:03:10] INFO: Testing url https://**hidden**.cloudfront.net/async_test/mes/index.html run 3
[2017-10-12 10:03:15] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:03:30] INFO: Converting video to 60 fps
[2017-10-12 10:04:11] INFO: Testing url https://**hidden**.cloudfront.net/async_test/mes/index.html run 4
[2017-10-12 10:04:17] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:04:32] INFO: Converting video to 60 fps
[2017-10-12 10:05:16] INFO: Testing url https://**hidden**.cloudfront.net/async_test/mes/index.html run 5
[2017-10-12 10:05:22] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:05:36] INFO: Converting video to 60 fps
[2017-10-12 10:06:20] INFO: 84 requests, 848.94 kb, backEndTime: 769ms (±37.55ms), firstPaint: 1.94s (±58.67ms), firstVisualChange: 2.18s (±51.68ms), DOMContentLoaded: 2.14s (±55.49ms), Load: 4.25s (±569.04ms), speedIndex: 3218 (±65.22), visualComplete85: 2.80s (±63.98ms), lastVisualChange: 6.99s (±124.45ms), rumSpeedIndex: 2590 (±655.82) (5 runs)
[2017-10-12 10:06:22] INFO: Starting chrome for analysing https://**hidden**.cloudfront.net/async_test/pl/index.html 5 time(s)
[2017-10-12 10:06:22] INFO: Testing url https://**hidden**.cloudfront.net/async_test/pl/index.html run 1
[2017-10-12 10:06:28] INFO: Start screenrecord on device 04157df4ea453f2f
[2017-10-12 10:06:42] INFO: Converting video to 60 fps
(node:51133) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: ffmpeg -i /**hidden**/sitespeed.io/results_mobile_chrome_lte_video_firstView/pages/**hidden**.cloudfront.net/async_test/pl/index.html/data/video/0.mp4 -r 60 /**hidden**/sitespeed.io/results_mobile_chrome_lte_video_firstView/pages/**hidden**.cloudfront.net/async_test/pl/index.html/data/video/tmp.mp4
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libfreetype --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fb895802c00] moov atom not found
/**hidden**/sitespeed.io/results_mobile_chrome_lte_video_firstView/pages/**hidden**.cloudfront.net/async_test/pl/index.html/data/video/0.mp4: Invalid data found when processing input
```

**mobile_chrome_lte_video_firstView.json**

```
{
  "browsertime": {
    "chrome": {
      "args": "",
      "android": {
        "package": "com.android.chrome"
      }
    },
    "connectivity": {
      "engine": "external",
      "profile": "3gfast"
    },
    "iterations": 5,
    "video": true,
    "speedIndex": true
  },
  "graphite": {
    "host": "localhost",
    "port": "2003",
    "httpPort": **hidden**,
    "webHost": **hidden**,
    "namespace": **hidden**,
    "arrayTags": true
  },
  "plugins": {
    "load": "analysisstorer"
  },
  "utc": true,
  "resultBaseURL": "http://localhost:8080",
  "outputFolder": "results_mobile_chrome_lte_video_firstView"
}
```

**urls_async.txt**

```
https://**hidden**.cloudfront.net/async_test/sf/index.html **hidden**
https://**hidden**.cloudfront.net/async_test/mes/index.html **hidden**
https://**hidden**.cloudfront.net/async_test/pl/index.html **hidden**
https://**hidden**.cloudfront.net/async_test/ads/index.html **hidden**
```

Does anybody had this problem before?
Is this the correct relation: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/638 ?

Thank you and best regards
Philipp

PS:

The error occures only sometimes, rerunning the test at this step is a workaround. It could be also better if the tests continue instead of failing hard.

**Comment by soulgalore** [comment]
Hi @moehlone ,
I wonder if it is that the video isn't there (not moved from the phone to desktop)? Or is the video there, if that's the case and you could share it, it would be super.

Yep, I agree we should at least catch it, does it fail hard for all runs or just that one (=do you get the data from the other runs)?

Best
Peter

**Comment by moehlone** [comment]
I`m not sure if the movie for this run was within the data folder or not, because this was a infrequent problem and I directly restarted the execution again. When the error happens again (just started new runs with video) I will look and provide it here. But definitely the process hang when this happened and no other runs were executed afterwards.

Best regards
Philipp

**Comment by moehlone** [comment]
Good morning,

the previous described error did not occured again, but I got another one:

```
[2017-10-13 15:17:40] INFO: [sitespeedio] Versions OS: darwin 16.7.0 nodejs: v6.11.1 sitespeed.io: 5.6.4 browsertime: 1.9.4 coach: 0.36.0
[2017-10-13 15:17:41] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing https://**hidden**.cloudfront.net/preload_test/sf/index.html 1 time(s)
[2017-10-13 15:17:41] INFO: [root] Testing url https://**hidden**.cloudfront.net/preload_test/sf/index.html run 1
[2017-10-13 15:17:46] INFO: [root] Start screenrecord on device 04157df4ea453f2f
[2017-10-13 15:18:01] INFO: [root] Converting video to 60 fps
[2017-10-13 15:18:44] INFO: [root] 79 requests, 943.04 kb, backEndTime: 633ms, firstPaint: 1.29s, firstVisualChange: 1.87s, DOMContentLoaded: 1.43s, Load: 2.59s, speedIndex: 3623, visualComplete85: 6.97s, lastVisualChange: 6.97s, rumSpeedIndex: 1453
[2017-10-13 15:18:44] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing https://d15kp8l6vv8tti.cloudfront.net/preload_test/mes/index.html 1 time(s)
[2017-10-13 15:18:44] INFO: [root] Testing url https://d15kp8l6vv8tti.cloudfront.net/preload_test/mes/index.html run 1
[2017-10-13 15:18:53] INFO: [root] Start screenrecord on device 04157df4ea453f2f
[2017-10-13 15:18:55] INFO: [root] Catched a WebDriverError [chrome not reachable
  (Session info: chrome=60.0.3112.116)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)]. Try one more time.WebDriverError: chrome not reachable
  (Session info: chrome=60.0.3112.116)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
[2017-10-13 15:18:56] ERROR: [root] WebDriverError:WebDriverError: chrome not reachable
  (Session info: chrome=60.0.3112.116)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
[2017-10-13 15:18:56] ERROR: [root] Could not load URLUrlLoadError: Failed to load https://**hidden**.cloudfront.net/preload_test/mes/index.html, cause: chrome not reachable
  (Session info: chrome=60.0.3112.116)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
[2017-10-13 15:18:57] ERROR: [plugin.browsertime] https://**hidden**.cloudfront.net/preload_test/mes/index.html generated the following error in Browsertime UrlLoadError: Failed to load https://d15kp8l6vv8tti.cloudfront.net/preload_test/mes/index.html
    at BrowsertimeError (/**hidden**/sitespeed.io/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/**hidden**/sitespeed.io/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch.e (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:175:15)
From previous event:
    at SeleniumRunner.loadAndWait (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:173:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/engine.js:333:27)
From previous event:
    at runIteration (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/engine.js:333:10)
    at Promise.reduce (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/engine.js:409:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/engine.js:406:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/**hidden**/sitespeed.io/node_modules/browsertime/lib/core/engine.js:405:8)
    at engine.start.then (/**hidden**/sitespeed.io/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/**hidden**/sitespeed.io/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/**hidden**/sitespeed.io/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:173:32)
    at /**hidden**/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/**hidden**/sitespeed.io/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:173:12)
    at queue.process.message (/**hidden**/sitespeed.io/node_modules/sitespeed.io/lib/support/queueHandler.js:192:32)
    at drainItem (/**hidden**/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/**hidden**/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-10-13 15:18:57] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing https://**hidden**.cloudfront.net/preload_test/pl/index.html 1 time(s)
[2017-10-13 15:18:57] INFO: [root] Testing url https://**hidden**.cloudfront.net/preload_test/pl/index.html run 1
[2017-10-13 15:19:05] INFO: [root] Start screenrecord on device 04157df4ea453f2f
[2017-10-13 15:19:20] INFO: [root] Converting video to 60 fps
```

The mobile device was fine and stopped loading the next page at this point.
The video was in this case not there, only a 0 byte `tmp.mp4`.

Best
Philipp

**Comment by soulgalore** [comment]
Hi Philipp,
usually "chrome not reachable" is a miss match between Chrome and Chromedriver (but it looks ok in your case). Have you turned you off as much as possible of other apps on your phone (and turned on Stay awake/stay alive etc)? Maybe you also have a list of more things we should add to https://www.sitespeed.io/documentation/sitespeed.io/mobile-phones/? We usually do a retry when we get an error but it seems that we don't catch that error.

I've only been testing on a low end Huawei phone and so far I've only got problem when I got miss match between drivers and when my screen went black but of course there can be other problems out there.

Best
Peter

**Comment by moehlone** [comment]
The phone (Samsung Galaxy S6) is only a test device with no apps installed except Chrome and Stay alive. The list worked great for me and I got the tests up and running within 15 minutes. But I think it would be useful (timesaving) to list this repo for the requirements: https://github.com/WPO-Foundation/visualmetrics, because the python file with command `$ python visualmetrics.py --check` was good to check against. I think that you already added the fact of combining OS X, Docker and Mobile Chrome metioned in #1708.

Best
Philipp

**Comment by soulgalore** [comment]
Good point, I'll add that the python check for the docs, that's good to verify that all works.

Ok, did the problem with Chrome happens once or do it continue to happen?

Best
Peter

**Comment by moehlone** [comment]
It continued at this point. Since then I stopped the measurements so I can not say if it comes again :/ At the weekend I can start some more.

**Comment by moehlone** [comment]
Didn't had any time yet ;(

**Comment by moehlone** [comment]
The problem with Chrome appears from time to time and it seems, that the video is not copied completely :/

**Comment by soulgalore** [comment]
@moehlone next week I'll work on the project. I'll add a task for tightening video handling for mobile,

**Comment by soulgalore** [comment]
Ok I've released some better checks now, but I think the original problem could still be there. 

There's a hidden feature where you can increase the time to wait for the video to be ready (default is 5 seconds) **--browsertime.videoParams.androidVideoWaitTime 5000**. If you can try that and increase the time and report back if that helped, that would be super!

**Comment by soulgalore** [comment]
I've changed this in BT 3.0 and sitespeed.io 7.0, please re-open if this is still an issue.
