### ISSUE TITLE
Failed to load URL behind a corporate firewall

### ISSUE THREAD

**Issue by bharat129** [sitespeedio/sitespeed.io#1757]
1. Running Docker composed sitespeed.io using
https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-5-minutes
2. Sitespeed.io is able to launch **Public URLs** using docker commands but not able to launch the run for the **application hosted behind the firewall & inside same Env**. 
3. Linux  VM can curl the application & also can ping the host.

Using below command to run , same command worked fine for public URL

>
`docker-compose run sitespeed.io https://xxx.xx.xxx/ --browsertime.browser=firefox --browsertime.iterations=1 --browsertime.timeouts.script=80000 --browsertime.proxy.http=proxy.xxx.xxx.com:80 --browsertime.proxy.https=proxy.xxx.xxx.com:80 --graphite.host=graphite`
**Error:**
`[2017-10-27 12:58:07] INFO: Catched a WebDriverError []. Try one more time.WebDriverError
[2017-10-27 12:58:09] ERROR: WebDriverError:WebDriverError
[2017-10-27 12:58:09] ERROR: Could not load URLUrlLoadError: Failed to load https://xxx.xx.xxx/, cause:
[2017-10-27 12:58:09] ERROR: https://xxx.xx.xxx/ generated the following error in Browsertime UrlLoadError: Failed to load https://xxx.xx.xxx/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:175:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:173:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:409:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:406:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:405:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:173:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:173:12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:192:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

What is the issue here?

**Comment by soulgalore** [comment]
Hi @bharat129 can you try running with `--net=host` (Docker then share the same network as the host). It could be you need add it in your Docker compose file (I usually don't run sitespeed in docker compose).

best
Peter

**Comment by bharat129** [comment]
@soulgalore : Thanks for replying. But adding `--net=host` did not work. 

Could it be the reason? 
The insecure cert on that application node is why I cant hit it with sitespeed
https://bugs.chromium.org/p/chromium/issues/detail?id=721739
its an open bug against the major headless browsers, not sitespeeds fault

I get SSL error (our connection is not secure) due to invalid certificate in browser. Can we have any option to ignore SSL errors?

**Comment by soulgalore** [comment]
@bharat129 before at least Chrome had --ignore-certificate-errors (not sure if it's there in the current version. You can try with --browsertime.chrome.args ignore-certificate-errors

Best
Peter

**Comment by bharat129** [comment]
@soulgalore , Chrome option did not work.

Firefox version : 54.0

Still, Production URL for the same application is working but the application URL hosted within client network does not work.

Something to do with network connectivity or anything else?

**Comment by soulgalore** [comment]
Ah sorry I thought you where running Chrome! Did you find the corresponding config for Firefox?

**Comment by bharat129** [comment]
@soulgalore , No config seems to be working for Firefox.

For Chrome, I happen to get it working 1-2 time only with page is not loading it seems in browsers. Results shows only 2 requests in dashboard with no resources loaded.
Command : `docker-compose run sitespeed.io https://xxx.xxx.com/ -n 1 --graphite.host=graphite`

**Comment by soulgalore** [comment]
In latest browsertime we added` --firefox.acceptInsecureCerts` for Firefox, if you use it from sitespeed.io use `--browsertime.firefox.acceptInsecureCerts`.

**Comment by jagyandeep** [comment]
try adding proxy in the command:
-e http_proxy=http://xxxxx:xxxx -e https_proxy=https://xxxxxx:xxxx

**Comment by soulgalore** [comment]
If you have problems testing within your network, I think it's easiest just to deploy sitespeed.io outside of your network.

**Comment by arifkhanaj** [comment]
I am also seeing an error while executing sitespeed test behind firewall.

I execute this simple command:
docker run -v ${WORKSPACE}:/sitespeed.io sitespeedio/sitespeed.io --outputFolder output url -n 1 -d 1


And this is the error I get:

[2019-02-07 08:22:59] ERROR: Failed to wait BrowserError: Running page complete check 
return (function(waitTime) {
    try { 
        var end = window.performance.timing.loadEventEnd;
        return (end > 0) && (Date.now() > end + waitTime);
    } catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long 
[2019-02-07 08:22:59] ERROR: Could not load URLUrlLoadError: Failed to wait 
[2019-02-07 08:22:59] ERROR: UrlLoadError: Failed to load urlxxxxxx
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:216:13)
[2019-02-07 08:23:00] ERROR: TypeError: Cannot read property 'replace' of null
    at /usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:40:37
    at Array.forEach (<anonymous>)
    at module.exports (/usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:39:18)
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:176:19)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:143:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I am seeing same error for chrome as well as firefox

**Comment by soulgalore** [comment]
@arifkhanaj I think that's the error you get if the URL is unreachable. If you have a proxy setting when use your browser on your desktop, try that, else the best way is to run the tests outside of your network.

**Comment by arifkhanaj** [comment]
@soulgalore I can see Linux VM can curl the application & also can ping the host. But when run Sitespeed command from same, it throws this error.

**Comment by soulgalore** [comment]
Chrome/Firefox run their own settings for DNS etc than curl, so it's not the same. Check what you do on your laptop to access outside of your firewall and try mimic that.

**Comment by arifkhanaj** [comment]
Thanks for your prompt response. I connect to VPN and then execute Sitespeed commands and they run successfully from my machine. 
Now the Linux VM reside within the same network so it doesn't need any connectivity with VPN etc. and have access to the web I am trying to execute Sitespeed commands on. But the Sitespeed command still doesn't work.

**Comment by soulgalore** [comment]
So you say that you docker container don't need to use the VPN and the server is on the same network that the URL that you try to test? Am I right? And the test server and the server it tries to reach are not behind the firewall? What does your URL look like?

**Comment by arifkhanaj** [comment]
Yes! Exactly, you are right.

It's a simple http url just like any other web url.

**Comment by soulgalore** [comment]
Ok! Then please create a new issue (since this has nothing to do with being behind a firewall) and follow https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue !

Thanks
Peter
