### ISSUE TITLE
Browsertime UrlLoadError: Failed to load

### ISSUE THREAD

**Issue by radum** [sitespeedio/sitespeed.io#1809]
Hello

I'm using the latest version docker mode and for some websites that I run sitespeed I get a `Browsertime UrlLoadError: Failed to load`

Here is a good example:

```bash
docker run --privileged --shm-size=2g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --browsertime.chrome.collectTracingEvents --html.showAllWaterfallSummary=true --gzipHAR -n 3 -c 3gfast -b chrome --browsertime.viewPort 412x732 --browsertime.userAgent "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3169.0 Mobile Safari/537.36" --firstParty=".*renault.*" --speedIndex --video https://www.renault.fr/
```

And the output:

```bash
Google Chrome 60.0.3112.78
Mozilla Firefox 54.0
[2017-11-20 09:46:03] INFO: Versions OS: linux 4.9.49-moby nodejs: v6.11.1 sitespeed.io: 5.6.5 browsertime: 1.9.4 coach: 0.36.0
[2017-11-20 09:46:03] INFO: Starting chrome for analysing https://www.renault.fr/ 3 time(s)
[2017-11-20 09:46:03] INFO: Testing url https://www.renault.fr/ run 1
[2017-11-20 09:46:05] ERROR: Could not load URLUrlLoadError: Failed to load https://www.renault.fr/
[2017-11-20 09:46:05] ERROR: https://www.renault.fr/ generated the following error in Browsertime UrlLoadError: Failed to load https://www.renault.fr/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:175:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:173:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:409:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:406:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:405:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:173:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:173:12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:192:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-11-20 09:46:06] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.renault.fr/2017-11-20-09-46-03
[2017-11-20 09:46:06] INFO: Finished analysing https://www.renault.fr/
```

The same setting was working fine before, not sure to be honest what version I had before I upgraded.

**Hardware:**
MacBook Pro with macOS Sierra
Cabled networked connection
Docker version: Version 17.09.0-ce-mac35 (19611)

**Comment by radum** [comment]
Testing with default settings it gives me the same results:

```bash
docker run --privileged --shm-size=2g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 3 --speedIndex --video https://www.renault.fr/
```

result:

```bash
Google Chrome 60.0.3112.78
Mozilla Firefox 54.0
[2017-11-20 09:52:21] INFO: Versions OS: linux 4.9.49-moby nodejs: v6.11.1 sitespeed.io: 5.6.5 browsertime: 1.9.4 coach: 0.36.0
[2017-11-20 09:52:21] INFO: Starting chrome for analysing https://www.renault.fr/ 3 time(s)
[2017-11-20 09:52:22] INFO: Testing url https://www.renault.fr/ run 1
[2017-11-20 09:52:24] ERROR: Could not load URLUrlLoadError: Failed to load https://www.renault.fr/
[2017-11-20 09:52:24] ERROR: https://www.renault.fr/ generated the following error in Browsertime UrlLoadError: Failed to load https://www.renault.fr/
    at BrowsertimeError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:5:5)
    at UrlLoadError (/usr/src/app/node_modules/browsertime/lib/support/errors.js:19:5)
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:175:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:173:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:409:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:406:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:405:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:95:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:173:32)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:173:12)
    at queue.process.message (/usr/src/app/lib/support/queueHandler.js:192:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2017-11-20 09:52:25] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.renault.fr/2017-11-20-09-52-21
[2017-11-20 09:52:25] INFO: Finished analysing https://www.renault.fr/
```

**Comment by radum** [comment]
@soulgalore You are correct. There seems to be a problem when I'm running the tests over my cable connection. If I switch to WIFI in my Mac it works ok.

Thank you for your quick reply. If I find something other might be able to use with the same issue I will add a comment.
