### ISSUE TITLE
Budget errors

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1823]
Running grunt-sitespeed.io https://github.com/sitespeedio/grunt-sitespeedio/tree/master/test generated the following errors:

```
[2017-11-24 01:10:39] ERROR: TypeError: Cannot read property 'browsertime.pageSummary' of undefined
    at verify (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/plugins/budget/verify.js:37:16)
    at Object.processMessage (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/plugins/budget/index.js:23:9)
    at queue.process.message (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/Users/peter/git/grunt-sitespeedio/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/peter/git/grunt-sitespeedio/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
[2017-11-24 01:10:39] ERROR: TypeError: Cannot read property 'pagexray.pageSummary' of undefined
    at verify (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/plugins/budget/verify.js:37:16)
    at Object.processMessage (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/plugins/budget/index.js:23:9)
    at queue.process.message (/Users/peter/git/grunt-sitespeedio/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/Users/peter/git/grunt-sitespeedio/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/peter/git/grunt-sitespeedio/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

We need to check if the grunt config is old/wrong or if there's an error in the budget plugin.

**Comment by soulgalore** [comment]
This was broken/changed in 4.4
