### ISSUE TITLE
 pageCompleteCheck does not work

### ISSUE THREAD

**Issue by Nuoky** [sitespeedio/sitespeed.io#1858]
Hi.

After adding the pageCompleteCheck parameter test failed to work properly.

run:
```
sudo docker run -it --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://test.com --browsertime.pageCompleteCheck "return (function() {try { return (Date.now() - window.performance.timing.loadEventEnd) > 2000;} catch(e) {} return true;})()" --speedIndex --video -n 1 -b chrome -v
```

output:
```
Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1

/usr/src/app/lib/cli/util.js:32
            throw new Error(`Couldn't find url file at ${filePath}`);
                  ^
Error: Couldn't find url file at /sitespeed.io/(function()
    at Object.getURLs (/usr/src/app/lib/cli/util.js:32:19)
    at Object.parseCommandLine (/usr/src/app/lib/cli/cli.js:725:19)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:22:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Thanks!

**Comment by soulgalore** [comment]
Thanks @Nuoky for reporting, let me fix it during the day.

**Comment by soulgalore** [comment]
I've pushed a fix now, I tried and it worked for me but would always want to verify that it works for you too @Nuoky before I close the issue.

**Comment by Nuoky** [comment]
@soulgalore The problem is solved, thanks!
