### ISSUE TITLE
How to run sitespeedio/sitespeed.io docker container on Docker Jenkins slave (jenkinsci/jnlp-slave)

### ISSUE THREAD

**Issue by loheswaran** [sitespeedio/sitespeed.io#1863]
I am trying to run sitespeedio/sitespeed.io inside a jenkins slave agent docker container, but I am not getting any result/error.  Could you please help me in fixing this? 

Please find below for the console output :

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.2 https://www.google.com/ --browsertime.proxy.http=test.test.com:8080 --browsertime.proxy.https=test.test.com:8080 --outputFolder=reports`

Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1

**Comment by soulgalore** [comment]
Hi @loheswaran do you run the Jenkins slave as a Docker container too (like it's Docker in Docker?)? The log output is from the start script in the Docker container where we just run browsers with --version. 

If you try to run as simple as possible, do you get the same output then?
`docker run --shm-size=1g --rm sitespeedio/sitespeed.io:6.2.2 https://www.google.com/ `

Best
Peter

**Comment by loheswaran** [comment]
Hi @soulgalore, Yes I am running the Jenkins slave as a Docker container.

I am getting the report when I run sitespeed.io as a standalone container. Please find below for the logs

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.2.2 https://www.google.com/ --browsertime.proxy.http=test.test.com:8080 --browsertime.proxy.https=test.test.com:8080 --outputFolder=reports

Google Chrome 63.0.3239.84 
Mozilla Firefox 54.0.1
[2017-12-27 18:10:01] INFO: Versions OS: linux 4.9.49-moby nodejs: v8.9.1 sitespeed.io: 6.2.2 browsertime: 2.1.2 coach: 1.1.1
[2017-12-27 18:10:02] INFO: Starting chrome for analysing https://www.google.com/ 3 time(s)
[2017-12-27 18:10:02] INFO: Testing url https://www.google.com/ run 1
[2017-12-27 18:10:18] INFO: Testing url https://www.google.com/ run 2
[2017-12-27 18:10:29] INFO: Testing url https://www.google.com/ run 3
[2017-12-27 18:10:40] INFO: 18 requests, 584.40 kb, backEndTime: 158ms (±6.42ms), firstPaint: 321ms (±3.32ms), firstVisualChange: 389ms (±7.78ms), DOMContentLoaded: 376ms (±3.63ms), Load: 529ms (±91.22ms), speedIndex: 477 (±9.23), visualComplete85: 422ms (±7.90ms), lastVisualChange: 2.65s (±137.82ms), rumSpeedIndex: 321 (±3.32) (3 runs)
[2017-12-27 18:10:43] INFO: HTML stored in /sitespeed.io/reports
[2017-12-27 18:10:43] INFO: Finished analysing https://www.google.com/

**Comment by soulgalore** [comment]
@loheswaran I haven't tried Jenkins with Docker slaves but could this be what you are looking for (or maybe you already did like this): https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution

**Comment by loheswaran** [comment]
@soulgalore, Yes I tried that too.  

I tried with -vvv --debug=true also but its not showing any debug/error log.  Is there any other option to print the error logs?

**Comment by soulgalore** [comment]
Hmm I still think that's there something fishy with running the agent as Docker with another container. You are sure the -v flag was for the agent/master (running on Linux)? Just want to make sure :) I don't think debug level will help for sitespeed.io, there's something in the environment that stops it from starting.

**Comment by loheswaran** [comment]
Do you see any issues in using the sitespeed.io node module inside a container? Does the node module has all the feautres of docker image?

**Comment by soulgalore** [comment]
everything works the same except that you need to install all the dependencies for yourself (follow the Docker container and all it inherits), but I still hope/think it would be possible to make work in an agent.  If you have a short list on what I need to do to replicate the problem, I could probably have a go the coming days.

**Comment by loheswaran** [comment]
This is what I am doing
1. Jenkins master is running as a separate service in Kubernetes ACS cluster
2. I have a job in master which spins up the slave agent dynamically in the same Kubernetes ACS cluster.
3. Execute sitespeed.io in the newly created slave agent and publish the report in the master jenkins

**Comment by soulgalore** [comment]
@loheswaran maybe you can find some info from how GitLab runs docker in docker with sitespeed.io: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor and https://docs.gitlab.com/ee/ci/examples/browser_performance.html

**Comment by loheswaran** [comment]
@soulgalore, Thanks for sharing the reference links.

I am using sitespeed.io node module to run the performance test in headless chrome but getting the below error. Could you please share the config to run in the headless chrome?

Command : 
`sitespeed.io --config=test/performance/sitespeed-io-config.json https://www.sitespeed.io/`

Config : 

```
{
    "browsertime": {
        "iterations": 2,
        "browser": "chrome",
        "selenium" : {
            "url": "http://127.0.0.1:4444/wd/hub"
        },
        "chrome": {
            "args": [
                "--no-sandbox",
                "--headless",
                "--disable-gpu",
                "--window-size=1280,1024"
            ]
        }
    }
}
```

**Comment by soulgalore** [comment]
To run it you only need to turn on headless (browsertime fix the rest of the configuration for Chrome):
`sitespeed.io --browsertime.headless true https://www.sitespeed.io`

When you run headless, Chrome will not work with browser extensions (you get some error with an extension right). I personally use xvfb instead of Chrome headless (but then you need to run on Linux).

Best
Peter

**Comment by loheswaran** [comment]
Does `sitespeed.io --browsertime.headless true https://www.sitespeed.io` work with xvfb?
If not, could please share the document or an example to refer for executing sitespeed.io with xvfb in linux?

**Comment by soulgalore** [comment]
If you don't use the Docker container you need to install [xvfb](https://en.wikipedia.org/wiki/Xvfb) on Linux and then you can run it like:
`sitespeed.io --browsertime.xvfb true https://www.sitespeed.io ` and starting and stopping xvfb will happen automatically.

Best
Peter

**Comment by loheswaran** [comment]
Thanks for the quick reply.  Will try this option and let you know.

**Comment by loheswaran** [comment]
@soulgalore ,

Tried the xvfb option but got the bellow error.

Command :

`bin/sitespeed.js --browsertime.xvfb=true https://www.sitespeed.io/`

Error log :

```
[2017-12-29 16:54:27] INFO: Versions OS: linux 4.11.0-1016-azure nodejs: v8.9.3 sitespeed.io: 6.2.3 browsertime: 2.1.2 coach: 1.1.2
[2017-12-29 16:54:27] INFO: Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2017-12-29 16:54:27] INFO: Testing url https://www.sitespeed.io/ run 1
[2017-12-29 16:55:27] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2017-12-29 16:56:27] ERROR: https://www.sitespeed.io/ generated the following error in Browsertime BrowserError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.11.0-1016-azure x86_64)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.11.0-1016-azure x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch.e (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:93:15)
From previous event:
    at SeleniumRunner.start (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:92:13)
From previous event:
    at runIteration (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/engine.js:229:10)
    at Promise.reduce (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:26)
From previous event:
    at Object.analyzeUrl (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/lib/plugins/browsertime/index.js:202:22)
    at /home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/lib/plugins/browsertime/index.js:201:12)
    at queue.process.message (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at SeleniumRunner.startBrowser (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:40:9)
    at SeleniumRunner.start (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:50:8)
    at Promise.resolve.tap (/home/jenkins/workspace/vpd-perf-test/sitespeed.io/node_modules/browsertime/lib/core/engine.js:229:27)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
Xvfb installation test :

```
Xvfb :1 -screen 0 800x600x16
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
```

**Comment by soulgalore** [comment]
@loheswaran what Chrome version have you installed, Chromedriver can be picky if you don't use the latest.  If you run on Azure I think you can use the Docker version, it will be less hazzle.

**Comment by loheswaran** [comment]
@soulgalore, 
If you run on Azure I think you can use the Docker version, it will be less hazzle
[ANS] As I said earlier, the docker version of sitespeed.io is not working in inside a container so I am trying with node module.

I am trying run sitespeed.io with xvfb in a container.  Could you please share the setup document to refer?

**Comment by loheswaran** [comment]
@soulgalore,
It's working now. Thanks.  Could you please let me know if you get chance to make sitespeed.io docker image to work with the jenkins jnlp slave docker image?

**Comment by soulgalore** [comment]
Maybe @stephendonner has some practical experience? If you wanna run a Docker container in your Docker Jenkins slave, what do you actually need to do? Is this the way https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution or what's best practice ( I have no experience at all).

**Comment by beenanner** [comment]
@loheswaran it can get a bit tricky with Docker with Docker on Jenkins agents. The biggest issue is if you use volume mounting for your reports you would need to volume mount the host path to the sitespeed container vs using the path within the Jenkins agent. Unless your Jenkins agents map one to one on the host you won't be able to use Jenkins variables like ${WORKSPACE} etc since those will return paths from within the Jenkins agent and not the correct host path outside of the Jenkins agent.

**Comment by litterbugkid** [comment]
> Hey @litterbugkid it depends how you map your file system from your server to inside the container. By default we write to /sitespeed.io inside the container, so when you start Docker, you need to map a dir outside of the container.
> 
> `-v "$(pwd)":/sitespeed.io`
> Means map you current directory (running pwd on Linux) to the /sitespeed.io inside of the container. So if you add that, the files will be created in your current dir.
> 
> Best
> Peter

@soulgalore Thanks for that. Does this mean that if the docker is torn down after all 'work' has completed, we're deleting the logs too?

**Comment by soulgalore** [comment]
hey @litterbugkid sorry I'm a little slow today, how do you mean? You run sitespeed.io inside your own Docker or? Can you show?
Thanks
Peter

**Comment by soulgalore** [comment]
People usually have a problem running Docker in Docker. GitLab uses that and run sitespeed.io so I think people interested in running Jenkins should have look there.
