### ISSUE TITLE
Resources exhaustion running multiple urls with video

### ISSUE THREAD

**Issue by kkopachev** [sitespeedio/sitespeed.io#1865]
I am running sitespeed.io version 6.2.3 using docker. I supplied list of urls to check and set repeat 3 times for each url.
After a few firs urls from the list processed, all the sudden job shows that it could not fetch another page. From that moment all following urls are also failing with same output
```
[2018-01-05 00:07:49] ERROR: https://example.com/something-something generated the following error in Browsertime UrlLoadError: Failed to load https://example.com/something-something
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:202:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:201:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

At that moment host is overloaded with many ffmpeg processess. Looking at urls at the end of ffmpeg commands, they all from different previous urls already processed.

![image](https://user-images.githubusercontent.com/2279051/34590278-9c9ab6b8-f16a-11e7-9110-336734acca7f.png)

These of them with nice of 10 might be forks of ffmpegs with nice=0.

**Comment by kkopachev** [comment]
Looks like when sitespeed reports error saying could not fetch url, ffmpeg process still running for that page  and it adds up since each next page request creates another ffmpeg.

**Comment by soulgalore** [comment]
Hey @kkopachev thanks for the report. There's kind of a bad implementation that we have at the moment where use the pre/post tasks to jack in FFmpeg, that's why at the moment we can have these scenarios. Let me look at it early next week, think we can fix it with a hack for now and then make better changes to the structure later on.

Best
Peter

**Comment by soulgalore** [comment]
BTW do you have more info about the original issue, the URLs that isn't working? Wanna look into that too.

**Comment by kkopachev** [comment]
Thanks for your reply, @soulgalore. 
Apart from zombie ffmpeg processes, It seem weird that after some time it could not reach the network anymore. Sometimes it could not resolve dns name to report to graphite, sometimes it could not find credentials to upload to s3 (instance profile credentials), sometimes it fails to resolve s3.amazonaws.com. 
So it's not that site is down, but more like network stack is misbehaving. 
I tried to run ping from within the container to see if at some point it just loses connection with outside world, but ping was good, while sitespeed was failing to fetch url and submit data to graphite.

Now I am trying to run it with default docker network without throttling.

**Comment by kkopachev** [comment]
Original issue about urls not working is not related to sitespeed.io. It's puppet on host machine every once in a while kills iptables rule.

**Comment by soulgalore** [comment]
Aha I see. The FFMPEG problem, I'll see if I can do something for the promise flow, it's kind of hard right now. The long term fix is to rewrite Browsertime with more async/await and try to make the code easier to understand and to handle different flows.

**Comment by soulgalore** [comment]
For now I think when your host kills the ip tables, you need to kill ffmpeg too. It kind of sucks but I don't I have time for fix this week and next I'm 100% busy. The long term fix should be to rewrite parts of Browsertime, but that is more work than just a couple of hours.

**Comment by kkopachev** [comment]
That's fine. I solved iptables thing, so it works better now.
However, when browser times out (often happens with FF), will it kill FFMpeg process?

**Comment by soulgalore** [comment]
I think that could be an issue that we need to solve. So it times out on getting the HAR or do you remember what you could see in the logs?

**Comment by kkopachev** [comment]
It's very inconsistent and sometimes happens on Chrome as well. 
<details><summary>logs look like this</summary>

```
[2018-01-09 13:25:29] ERROR: ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/usr/src/app/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/usr/src/app/node_modules/browsertime/lib/core/engine.js:282:37)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:282:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:202:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:201:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

And similar with Chrome 
```
generated the following error in Browsertime UrlLoadError: Failed to load https://www.popsugar.com/fitness/Standing-Pilates-10-Minute-Butt-Workout-Video-42991173?no_ads=t0ps3cr3t4dfr33
    at getUrl.then.then.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:202:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:201:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

</details>


Let's keep this issue for ffmpeg process remaining when there is an error. I'll create issue on timeout if it becomes a problem.

**Comment by soulgalore** [comment]
This has changed in Bt 3 and sitespeed.io 7.0, please re-open if this is still an issue.
