### ISSUE TITLE
Frequently getting TypeError: Cannot read property 'response' of undefined

### ISSUE THREAD

**Issue by senthilr2k** [sitespeedio/sitespeed.io#1906]
I am using the latest sitespeed available in docker. I am getting the below error very frequently. Could you please help

[2018-02-07 11:23:24] INFO: 131 requests, 2769.84 kb, backEndTime: 1.14s, firstVisualChange: 5.27s, DOMContentLoaded: 3.73s, Load: 7.49s, speedIndex: 5272, visualComplete85: 5.27s, lastVisualChange: 9.73s, rumSpeedIndex: 3844
[2018-02-07 11:23:24] ERROR: TypeError: Cannot read property 'response' of undefined
    at har.log.entries.forEach.entry (/usr/src/app/node_modules/pagexray/lib/index.js:97:41)
    at Array.forEach (<anonymous>)
    at Object.convert (/usr/src/app/node_modules/pagexray/lib/index.js:84:21)
    at Object.processMessage (/usr/src/app/lib/plugins/pagexray/index.js:74:40)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-02-07 11:23:24] ERROR: TypeError: Cannot read property 'response' of undefined
    at har.log.entries.forEach.entry (/usr/src/app/node_modules/pagexray/lib/index.js:97:41)
    at Array.forEach (<anonymous>)
    at Object.convert (/usr/src/app/node_modules/pagexray/lib/index.js:84:21)
    at Promise.resolve.then.harJson (/usr/src/app/node_modules/webcoach/lib/index.js:28:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at processCoachOutput (/usr/src/app/lib/plugins/browsertime/index.js:108:54)
    at storageManager.createDirForUrl.then.then.tap.tap.tap.tap.tap.tap.results (/usr/src/app/lib/plugins/browsertime/index.js:314:22)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:312:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by soulgalore** [comment]
Hi @senthilr2k there's some content on the site that we don't handle, can you provide the URL so we can reproduce? 

Thanks
Peter

**Comment by senthilr2k** [comment]
[2018-02-07 11:26:08] INFO: Testing url https://www.verizonwireless.com/devices run 1

**Comment by soulgalore** [comment]
This was fixed some time ago and should just work in 7.x
