### ISSUE TITLE
Cannot find chrome binary

### ISSUE THREAD

**Issue by juniorriau** [sitespeedio/sitespeed.io#1922]
hi

i install the sitespeed.io by clone git repo. then i try to run without docker
i got error cannot find chrome binary
`[root@server sitespeed.io]# bin/sitespeed.js https://riaucybersolution.net/
[2018-02-28 15:12:09] INFO: Versions OS: linux 3.10.0-229.1.2.el7.x86_64 nodejs: v8.9.4 sitespeed.io: 6.3.5 browsertime: 2.2.2 coach: 1.2.0
[2018-02-28 15:12:09] INFO: Starting chrome for analysing https://riaucybersolution.net/ 3 time(s)
[2018-02-28 15:12:09] INFO: Testing url https://riaucybersolution.net/ run 1
[2018-02-28 15:12:09] INFO: Browser failed to start, trying one more time: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.10.0-229.1.2.el7.x86_64 x86_64)
[2018-02-28 15:12:09] ERROR: https://riaucybersolution.net/ generated the following error in Browsertime BrowserError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.10.0-229.1.2.el7.x86_64 x86_64)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.10.0-229.1.2.el7.x86_64 x86_64)
    at startBrowser.call.catch.tap.tap.catch.catch.e (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:93:15)
From previous event:
    at SeleniumRunner.start (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:92:13)
    at Promise.resolve.tap (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:248:27)
From previous event:
    at runIteration (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:248:10)
    at Promise.reduce (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:26)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Object.analyzeUrl (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/index.js:209:22)
    at /home/webmetric.id/public_html/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/home/webmetric.id/public_html/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/home/webmetric.id/public_html/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/home/webmetric.id/public_html/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-02-28 15:12:10] INFO: HTML stored in /home/webmetric.id/public_html/sitespeed.io/sitespeed-result/riaucybersolution.net/2018-02-28-15-12-09
[2018-02-28 15:12:10] INFO: Finished analysing https://riaucybersolution.net/
[root@server sitespeed.io]`

**Comment by soulgalore** [comment]
Hi @juniorriau just wanted to verify that you have Chrome installed? Can you check where (if that's the case) and report which OS you are using.
Best
Peter

**Comment by juniorriau** [comment]
![image](https://user-images.githubusercontent.com/3606652/36813375-ed2109bc-1d06-11e8-8722-c2362078ffa6.png)
chrome driver installed, i use centos 7.4

**Comment by tobli** [comment]
Hi @juniorriau,
You don't need to have chromedriver installed (it's comes bundled with sitespeed.io). You do however need to have Chrome, the actual browser, installed.

Best regards,
/Tobias

**Comment by passwordleak** [comment]
Same problem. Ironically I'm viewing this with Chrome. Windows 10

**Comment by juniorriau** [comment]
@tobli i got another error
`[root@server sitespeed.io]# bin/sitespeed.js https://riaucybersolution.net/
[2018-02-28 22:40:30] INFO: Versions OS: linux 3.10.0-229.1.2.el7.x86_64 nodejs: v8.9.4 sitespeed.io: 6.3.5 browsertime: 2.2.2 coach: 1.2.0
[2018-02-28 22:40:30] INFO: Starting chrome for analysing https://riaucybersolution.net/ 3 time(s)
[2018-02-28 22:40:30] INFO: Testing url https://riaucybersolution.net/ run 1
[2018-02-28 22:41:30] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2018-02-28 22:42:30] ERROR: https://riaucybersolution.net/ generated the following error in Browsertime BrowserError: Failed to start browser in 60 seconds.
    at startBrowser.call.catch.tap.tap.catch.catch.e (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:93:15)
From previous event:
    at SeleniumRunner.start (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:92:13)
From previous event:
    at runIteration (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:248:10)
    at Promise.reduce (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:26)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Object.analyzeUrl (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/index.js:209:22)
    at /home/webmetric.id/public_html/sitespeed.io/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/home/webmetric.id/public_html/sitespeed.io/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/home/webmetric.id/public_html/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/home/webmetric.id/public_html/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/home/webmetric.id/public_html/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at SeleniumRunner.startBrowser (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:40:9)
    at SeleniumRunner.start (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:50:8)
    at Promise.resolve.tap (/home/webmetric.id/public_html/sitespeed.io/node_modules/browsertime/lib/core/engine.js:248:27)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-02-28 22:42:30] INFO: HTML stored in /home/webmetric.id/public_html/sitespeed.io/sitespeed-result/riaucybersolution.net/2018-02-28-22-40-30
[2018-02-28 22:42:30] INFO: Finished analysing https://riaucybersolution.net/
[root@server sitespeed.io]# 
`

**Comment by soulgalore** [comment]
@juniorriau first make sure that the user you use can run Chrome (do you have a screen or will you use xvfb?). Then I think you need to add no-sandbox to Chrome as an arg: `--browsertime.chrome.args no-sandbox`. Else use the Docker container it just works :)

**Comment by juniorriau** [comment]
Hi

this output when i run as normal user
![image](https://user-images.githubusercontent.com/3606652/36829649-c144885e-1d52-11e8-9fa9-2bf4d31f0bff.png)

**Comment by soulgalore** [comment]
yep you don’t have display. You can use xvfb (you need to install it) and start it. Or you can use Docker and it just works :)

**Comment by juniorriau** [comment]
ok i'll try, i don't have any experience using docker.
