### ISSUE TITLE
Error - Cannot  read property start for 'undefined'

### ISSUE THREAD

**Issue by profhase** [sitespeedio/sitespeed.io#1926]
As I cannot use docker on my vm, I installed sitespeed manually with 
npm 5.6.0 on node 8.9.4

for testing reasons I have installed it locally on /root and run as root
I ve executed:

     Xvfb :99 -shmem -screen 0 1366x768x16
     export DISPLAY=:99
     export $(dbus-launch)

    ./node_modules/.bin/sitespeed.io --browser=firefox https://www.google.de -v
    
First it takes a long while, then it exits with:

   ```
 [2018-03-07 10:48:03] INFO: [sitespeedio] Versions OS: linux 4.4.0-042stab127.2 nodejs: v8.9.4 
sitespeed.io: 6.3.5 browsertime: 2.1.4 coach: 1.2.0
[2018-03-07 10:48:03] INFO: [sitespeedio.plugin.browsertime] Starting firefox for analysing https://www.google.de 3 time(s)
[2018-03-07 10:48:03] INFO: [root] Testing url https://www.google.de run 1
[2018-03-07 10:48:06] DEBUG: [root] Requesting url https://www.google.de
[2018-03-07 10:48:07] DEBUG: [root] Waiting for script 'return (function() {try { var end = window.performance.timing.loadEventEnd;return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})()' at most 300000 ms
[2018-03-07 10:49:29] DEBUG: [root] Telling browser to quit.
[2018-03-07 10:49:30] ERROR: [sitespeedio.queuehandler] ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/root/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/root/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/root/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/root/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/root/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/root/node_modules/browsertime/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/root/node_modules/browsertime/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/root/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/root/node_modules/browsertime/lib/core/engine.js:282:37)
From previous event:
    at runIteration (/root/node_modules/browsertime/lib/core/engine.js:282:10)
    at Promise.reduce (/root/node_modules/browsertime/lib/core/engine.js:330:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/root/node_modules/browsertime/lib/core/engine.js:327:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/root/node_modules/browsertime/lib/core/engine.js:326:8)
    at engine.start.then (/root/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:26)
    at emitNone (events.js:106:13)
From previous event:
    at Object.analyzeUrl (/root/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/root/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:207:22)
    at /root/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/root/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:206:12)
    at queue.process.message (/root/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/root/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/root/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-03-07 10:49:30] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2018-03-07 10:49:30] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2018-03-07 10:49:30] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2018-03-07 10:49:30] DEBUG: [sitespeedio.plugin.html] Render HTML for 0 page(s) 
[2018-03-07 10:49:30] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2018-03-07 10:49:30] ERROR: [sitespeedio.queuehandler] TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/root/node_modules/pug-parser/index.js:776:24)
    at Parser.parseExpr (/root/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/root/node_modules/pug-parser/index.js:112:25)
    at parse (/root/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/root/node_modules/pug-load/index.js:45:21)
    at compileBody (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:216:25)
    at Object.exports.compileFile (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:357:10)
    at getTemplate (/root/node_modules/sitespeed.io/lib/plugins/html/renderer.js:19:32)
    at Object.renderTemplate (/root/node_modules/sitespeed.io/lib/plugins/html/renderer.js:27:12)
    at HTMLBuilder._renderSummaryPage (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:339:16)
    at Object.keys.map.name (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/root/node_modules/sitespeed.io/lib/plugins/html/index.js:198:35)
    at queue.process.message (/root/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/root/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/root/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-03-07 10:49:30] INFO: [sitespeedio] Finished analysing https://www.google.de
```

**Comment by soulgalore** [comment]
Hi @profhase which Firefox version are you using? Since Firefox 55 the Har Export Trigger is broken, that's why we use 54 in our Docker container. If you wanna run with newer Firefox (until 60 or 61 is released) you need to skip the HAR file. Add  `--browsertime.skipHar ` to do that.

Best
Peter

**Comment by profhase** [comment]
```
firefox --version
Mozilla Firefox 58.0.2

```

**Comment by awildings** [comment]
I'm also getting this using chrome...
```
~ sitespeed.io -b chrome --browsertime.chrome.args no-sandbox http://bukalapak.com
[2018-03-07 16:48:20] INFO: Versions OS: darwin 17.4.0 nodejs: v8.10.0 sitespeed.io: 6.3.5 browsertime: 2.1.4 coach: 1.2.0
[2018-03-07 16:48:21] INFO: Starting chrome for analysing http://bukalapak.com 3 time(s)
[2018-03-07 16:48:21] INFO: Testing url http://bukalapak.com run 1
[2018-03-07 16:48:32] INFO: Testing url http://bukalapak.com run 2
[2018-03-07 16:48:41] INFO: Testing url http://bukalapak.com run 3
[2018-03-07 16:48:51] INFO: 175 requests, 2408.09 kb, backEndTime: 774ms (±75.67ms), firstPaint: 1.44s (±61.22ms), DOMContentLoaded: 2.39s (±49.71ms), Load: 4.60s (±326.24ms), rumSpeedIndex: 1443 (±61.13) (3 runs)
[2018-03-07 16:48:55] ERROR: TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:776:24)
    at Parser.parseExpr (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:112:25)
    at parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-load/index.js:45:21)
    at compileBody (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:216:25)
    at Object.exports.compileFile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:357:10)
    at getTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:19:32)
    at Object.renderTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:27:12)
    at HTMLBuilder._renderSummaryPage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:339:16)
    at Object.keys.map.name (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:198:35)
    at queue.process.message (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-03-07 16:48:55] INFO: Finished analysing http://bukalapak.com
```

**Comment by profhase** [comment]
Thank you very much, the skipHar option helped, now I can see the three runs:

```
node_modules/.bin/sitespeed.io --browser=firefox https://www.google.de --browsertime.skipHar
[2018-03-07 11:03:37] INFO: Versions OS: linux 4.4.0-042stab127.2 nodejs: v8.9.4 sitespeed.io: 6.3.5 browsertime: 2.1.4 coach: 1.2.0
[2018-03-07 11:03:37] INFO: Starting firefox for analysing https://www.google.de 3 time(s)
[2018-03-07 11:03:37] INFO: Testing url https://www.google.de run 1
[2018-03-07 11:03:44] INFO: Testing url https://www.google.de run 2
[2018-03-07 11:03:51] INFO: Testing url https://www.google.de run 3
[2018-03-07 11:03:57] INFO: 0, backEndTime: 161ms (±6.16ms), firstPaint: 263ms (±5.17ms), DOMContentLoaded: 259ms (±1.31ms), Load: 1.80s (±426.41ms), rumSpeedIndex: 171 (±7.19) (3 runs)
[2018-03-07 11:03:57] ERROR: TypeError: Cannot read property 'start' of undefined
    at Parser.parseExtends (/root/node_modules/pug-parser/index.js:776:24)
    at Parser.parseExpr (/root/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/root/node_modules/pug-parser/index.js:112:25)
    at parse (/root/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/root/node_modules/pug-load/index.js:45:21)
    at compileBody (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:216:25)
    at Object.exports.compileFile (/root/node_modules/sitespeed.io/node_modules/pug/lib/index.js:357:10)
    at getTemplate (/root/node_modules/sitespeed.io/lib/plugins/html/renderer.js:19:32)
    at Object.renderTemplate (/root/node_modules/sitespeed.io/lib/plugins/html/renderer.js:27:12)
    at HTMLBuilder._renderSummaryPage (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:339:16)
    at Object.keys.map.name (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/root/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/root/node_modules/sitespeed.io/lib/plugins/html/index.js:198:35)
    at queue.process.message (/root/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/root/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/root/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-03-07 11:03:57] INFO: Finished analysing https://www.google.de
```

Unfortunately there is still the error in the end. Do you have an idea?

**Comment by soulgalore** [comment]
Yep it's the same as https://github.com/sitespeedio/sitespeed.io/issues/1927, I will look into that today.

**Comment by soulgalore** [comment]
@profhase can you try installing latest 6.4.1, I can at least not reproduce with that version.
