### ISSUE TITLE
Error parsing report

### ISSUE THREAD

**Issue by awildings** [sitespeedio/sitespeed.io#1927]
Hello,
does anyone know about this error? 

~ sitespeed.io -b chrome --browsertime.chrome.args no-sandbox http://bukalapak.com
```[2018-03-07 16:48:20] INFO: Versions OS: darwin 17.4.0 nodejs: v8.10.0 sitespeed.io: 6.3.5 browsertime: 2.1.4 coach: 1.2.0
[2018-03-07 16:48:21] INFO: Starting chrome for analysing http://bukalapak.com 3 time(s)
[2018-03-07 16:48:21] INFO: Testing url http://bukalapak.com run 1
[2018-03-07 16:48:32] INFO: Testing url http://bukalapak.com run 2
[2018-03-07 16:48:41] INFO: Testing url http://bukalapak.com run 3
[2018-03-07 16:48:51] INFO: 175 requests, 2408.09 kb, backEndTime: 774ms (±75.67ms), firstPaint: 1.44s (±61.22ms), DOMContentLoaded: 2.39s (±49.71ms), Load: 4.60s (±326.24ms), rumSpeedIndex: 1443 (±61.13) (3 runs)
[2018-03-07 16:48:55] **ERROR: TypeError: Cannot read property 'start' of undefined**
    at Parser.parseExtends (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:776:24)
    at Parser.parseExpr (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:218:21)
    at Parser.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:112:25)
    at parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-load/index.js:45:21)
    at compileBody (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:243:16)
    at handleTemplateCache (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:216:25)
    at Object.exports.compileFile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:357:10)
    at getTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:19:32)
    at Object.renderTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:27:12)
    at HTMLBuilder._renderSummaryPage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:339:16)
    at Object.keys.map.name (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:198:35)
    at queue.process.message (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-03-07 16:48:55] INFO: Finished analysing http://bukalapak.com```

**Comment by soulgalore** [comment]
Hi @awildings thanks for reporting, hmm let me look into it.

Best
Peter

**Comment by awildings** [comment]
@soulgalore do you know why this is happening? is there any quick way to prevent this? should I downgrade?

**Comment by soulgalore** [comment]
Hi @awildings can you install latest 6.4.1 (latest)? I upgraded the pug lib that we use to 2.0.0. from 2.0.0-rc4 and now I cannot reproduce. However it happened for me when I installed globally with npm, not installing globally from local, that is strange.

Yeah, we prefer using our Docker version, then we are sure the environment is ok.

Please let me know if the latest version work for you or not! 
Best
Peter

**Comment by awildings** [comment]
@soulgalore it's working fine after upgrading into 6.4.1. Thanks brother!!
