### ISSUE TITLE
Z_BUF_ERROR when getting WebPagetest result

### ISSUE THREAD

**Issue by mkreidenweis** [sitespeedio/sitespeed.io#1928]
We use sitespeed.io 6.3.5 inside Docker regularly to trigger WebPagetest. Unfortunately we quite often get errors like these, which we cannot really explain: 
```
...
[2018-03-07 01:15:04] INFO: Got [...] analysed with id [...] from http://[...].compute.amazonaws.com
[2018-03-07 01:16:19] ERROR: Error creating WebPageTest result  {"cause":{"errno":-5,"code":"Z_BUF_ERROR"},"isOperational":true,"errno":-5,"code":"Z_BUF_ERROR"}
    at Unzip.zlibOnError (zlib.js:153:15)
From previous event:
    at /usr/src/app/lib/plugins/webpagetest/analyzer.js:62:12
    at resultsCallback (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:352:7)
    at WebPageTest.poll (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:365:7)
    at callbackYield (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:159:14)
    at WebPageTest.apiCallback (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:228:7)
    at unzip (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:136:15)
    at Unzip.onEnd (zlib.js:131:5)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/webpagetest/analyzer.js:24:57)
    at Object.processMessage (/usr/src/app/lib/plugins/webpagetest/index.js:174:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at Unzip.Readable.on (_stream_readable.js:772:35)
    at zlibBuffer (zlib.js:98:10)
    at Object.unzip (zlib.js:598:14)
    at IncomingMessage.onEnd (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:132:16)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at IncomingMessage.Readable.on (_stream_readable.js:772:35)
    at ClientRequest.getResponse (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:120:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
[2018-03-07 01:16:21] INFO: Got [...] analysed with id [...] from [...].compute.amazonaws.com
...
```

It happens for all kinds of different test runs (different URLs). Unfortunately the error gives us very little information on what went wrong, so we cannot really determine for which tests it failed. 
Any ideas? 

Our configuration for this example looks like that: 
```

{
  "plugins": {
    "remove": ["browsertime", "html", "screenshot"]
  },
  "influxdb": {
    "protocol": "https",
    "host": "[private]"
  },
  "webpagetest": {
    "host": "http://[private].compute.amazonaws.com",
    "key": "[private]",
    "location": "eu-central-1:Chrome",
    "connectivity": "Cable",
    "runs": 3,
    "includeRepeatView": true,
    "video": 1,
    "private": false,
    "timeout": 3600,
    "timeline": 1,
    "duration": 35
  },
  "utc": true
}
```

**Comment by soulgalore** [comment]
Hi @mkreidenweis thanks for reporting. 
Hmm it comes from the WebPageTest API right: https://github.com/marcelduran/webpagetest-api/blob/master/lib/webpagetest.js#L132 or something there.

Either it's an NodeJS issue (it has been in older versions) or could it be something like missing encoding from the WebPageTest server? 

Either if you can create an upstream issue in the WebPageTest API or ping Pat in the WebPageTest repo, maybe he knows what it is.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since I don't see that I can do something here.
