### ISSUE TITLE
throttling on non-docker throws errors

### ISSUE THREAD

**Issue by profhase** [sitespeedio/sitespeed.io#1933]
On an ubuntu 16.10 server with sitespeed and throttle manually installed with npm:

    node_modules/.bin/throttle --up 330 --down 1000

gives

```
Started throttler: Down:1000kbit/s Up:330kbit/s RTT:200ms 
(node:615) UnhandledPromiseRejectionWarning: Error: Command failed: sudo ip link add ifb0 type ifb
RTNETLINK answers: Operation not supported


    at Promise.all.then.arr (/root/node_modules/@sitespeed.io/throttle/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by soulgalore** [comment]
Hi @profhase could it be an issue with if you run with cable vs wifi? Let me have a look tonight, I wanna update the lib to use async/await anyway to get rid of promises.

Best
Peter

**Comment by profhase** [comment]
Thank you for the quick answer, I guess I figured out the problem: my kernel does not support `tc`(missing module) I suppose this is the reason

**Comment by soulgalore** [comment]
Let us add a check for that in throttle.
