### ISSUE TITLE
Help Headless

### ISSUE THREAD

**Issue by awildings** [sitespeedio/sitespeed.io#1941]
Hello, previously I able to run browsertime headlessly
but for this URL I wasn't able.
I got this error
$ browsertime https://bbm.webcomics.co.id --chrome.args no-sandbox --headless
```[2018-03-12 20:44:04] Running chrome for url: https://bbm.webcomics.co.id
[2018-03-12 20:44:04] Testing url https://bbm.webcomics.co.id run 1
[2018-03-12 20:44:08] Could not load URLUrlLoadError: Failed to load https://bbm.webcomics.co.id
[2018-03-12 20:44:08] Error running browsertime UrlLoadError: Failed to load https://bbm.webcomics.co.id
    at getUrl.then.then.catch.catch.e (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/seleniumRunner.js:176:15)
From previous event:
    at SeleniumRunner.loadAndWait (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/seleniumRunner.js:174:13)
    at Promise.resolve.tap.tap.tap.tap.tap (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:256:27)
From previous event:
    at runIteration (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:256:10)
    at Promise.reduce (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Engine.run (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:332:8)
    at /Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:63:21
From previous event:
    at run (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:62:6)
    at Object.<anonymous> (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:138:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3```

**Comment by soulgalore** [comment]
Hi @awildings 
it's a redirect that it seems like headless mode doesn't handle on that page right?  I think it's a Chrome issue somehow because running Firefox in headless works for me.

(FYI you can skip using **--chrome.args no-sandbox** !).

Best
Peter

**Comment by awildings** [comment]
@soulgalore I tried using firefox browser I ended up with this error
```
Error running browsertime ScriptTimeoutError: Timed out
    at Object.throwDecodedError (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Driver.schedule (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at Promise.try (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/seleniumRunner.js:225:26)
From previous event:
    at SeleniumRunner.runAsyncScript (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/seleniumRunner.js:219:23)
    at FirefoxDelegate.onStopIteration (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engineDelegate/firefoxDelegate.js:46:36)
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:298:37)
From previous event:
    at runIteration (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:298:10)
    at Promise.reduce (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Engine.run (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/lib/core/engine.js:332:8)
    at /Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:63:21
From previous event:
    at run (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:62:6)
    at Object.<anonymous> (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/browsertime/bin/browsertime.js:138:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3```

**Comment by soulgalore** [comment]
@awildings what Firefox version are you using? Since 55 the HAR Export trigger is broken so you need to run with --skipHar. There are a new version out there that works with Firefox 60, when it's in beta on Linux we can soon release it.

**Comment by awildings** [comment]
@soulgalore thanks! it's working fine

**Comment by awildings** [comment]
@soulgalore I got an error both my server and my local machine...
sitespeed.io https://google.com -b chrome
```
ERROR: Error: `line` is not an integer
    at Parser.initBlock (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:156:36)
    at Parser.emptyBlock (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:168:17)
    at Parser.parseInclude (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:853:71)
    at Parser.parseExpr (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:220:21)
    at Parser.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:112:25)
    at parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:125:22)
    at Function.loadString [as string] (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug-load/index.js:45:21)
    at compileBody (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:242:16)
    at handleTemplateCache (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:215:25)
    at Object.exports.compileFile (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/pug/lib/index.js:356:10)
    at getTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:19:32)
    at Object.renderTemplate (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/renderer.js:27:12)
    at HTMLBuilder._renderSummaryPage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:339:16)
    at Object.keys.map.name (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:150:12)
    at Array.map (<anonymous>)
    at HTMLBuilder.render (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/htmlBuilder.js:149:54)
    at Object.processMessage (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/plugins/html/index.js:198:35)
    at queue.process.message (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:210:32)
    at drainItem (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/nicholasfrederick/.nvm/versions/node/v8.10.0/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-03-13 15:40:18] INFO: Finished analysing https://google.com
```

**Comment by soulgalore** [comment]
Do you run the latest version (I’ve missed the version number in the report)? There was some pug dependency problems before but I thought that was fixed. Always safest to run the latest Docker container :)

**Comment by awildings** [comment]
@soulgalore Yes I have latest version.
```[2018-03-13 16:57:49] INFO: Versions OS: darwin 17.4.0 nodejs: v8.10.0 sitespeed.io: 6.4.1 browsertime: 2.2.2 coach: 1.2.0```

**Comment by awildings** [comment]
I solve it by using the repo version. it works well

**Comment by soulgalore** [comment]
I think something is still broken in pug, let me open an issue for that.

**Comment by soulgalore** [comment]
Closing this but adding https://github.com/sitespeedio/sitespeed.io/issues/1944 as follow up for problem number two.
