### ISSUE TITLE
Not able to use --requestHeader (-r) option

### ISSUE THREAD

**Issue by rockerdata** [sitespeedio/sitespeed.io#1947]
Hi,

I am using latest docker version of Sitespeed. I would like to add dynatrace headers in my request. Following is the command that I am using.

sudo docker run \
--privileged \
--shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io  \
-b chrome  \
--browsertime.proxy.http=http://somproxy.com:8080  \
--browsertime.proxy.https=http://somproxy.com:8080 \
-r x-dynaTrace:HomePage \
-n 1 \
https://somesite.com

As I am checking in output har, not able to see this request header being added. Let me know if I am doing some thing wrong in this case here. Please help in this.

**Comment by soulgalore** [comment]
Hi @rockerdata hmm it should work. when I test it I usually try on one of those sites that pront out the headers in the repsonse. I can help you after the weekend when I’m back.
Best
Peter

**Comment by rockerdata** [comment]
Sure @soulgalore  , will wait till you are back.

**Comment by soulgalore** [comment]
@rockerdata can you try this:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io -n 1 -r x-dynaTrace:HomePage https://httpbin.org/headers`

and check the screenshot if you see the header there (that works for me). And then try with the proxy you are using and see what it looks like.

**Comment by rockerdata** [comment]
Peter Thank you for your response. As you suggested I tried hitting 'https://httpbin.org/headers' URL with --browsertime.requestheader parameter. Below is the command which I have used.

sudo docker run \
-e http_proxy=http://someproxy.com:8080 -e https_proxy=http://someproxy.com:8080 \
--privileged \
--shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io  \
-b chrome  \
--browsertime.proxy.http=http://someproxy:8080 \
--browsertime.proxy.https=http://someproxy:8080 \
--browsertime.requestheader "x-dynaTrace:HomePage" \
-n 1 \
https://httpbin.org/headers

When I checked screenshot, this header is still not there.
![0](https://user-images.githubusercontent.com/31253387/37600812-c56f981e-2b5e-11e8-9f9c-938d99c43cee.png)

Similarly when I am trying with CURL command, I am able to get added header as response.

curl --header "x-dynatrace:Homepage" https://httpbin.org/headers
{
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.29.0",
    "X-Dynatrace": "Homepage"
  }
}

Please let me know if there is any way to debug this.

**Comment by soulgalore** [comment]
Hi @rockerdata so they proxy removes the header? Can you run without it or do you need it to be able to access outside of your environment?

Best
Peter

**Comment by rockerdata** [comment]
Right I cant access to outside environment without proxy. But is curl also using similar proxy. So as per you who is removing this header, org proxy or browsertime?

**Comment by soulgalore** [comment]
Could it be then that Chrome doesn't send the extra header if you are using a proxy? What does it look like if you are using Firefox?

**Comment by rockerdata** [comment]
Hey Peter,

I have been using only Chrome browser till now. As I tried to use Firefox but I am getting following error. Please help if you know resolution to this.
We have just used docker-compose.yml file to configure Sitespeed.

[2018-03-19 15:30:08] ERROR: https://requestb.in/127m2h51 generated the following error in Browsertime BrowserError: InvalidArgumentError: Expected [object Null] null to be an integer
    at startBrowser.call.catch.tap.tap.catch.catch.e (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:93:15)
From previous event:
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:92:13)
    at Promise.resolve.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:248:27)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:248:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:209:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by soulgalore** [comment]
Proxy problems is out of sitespeed.io scope.
