### ISSUE TITLE
Firefox with a pre-script for logging in have issues with redirects

### ISSUE THREAD

**Issue by Pe4enie** [sitespeedio/sitespeed.io#1948]
Hey,

got another issue with firefox. When I run pre-script to login the user, I consistently following error (for Chrome the same setup works just fine):

```
[2018-03-14 17:02:37] INFO: Versions OS: linux 4.4.0-93-generic nodejs: v8.9.4 sitespeed.io: 6.4.1 browsertime: 2.2.2 coach: 1.2.0
[2018-03-14 17:02:38] INFO: Starting firefox for analysing https://checkout.mytoys.de/checkout/notepad 5 time(s)
[2018-03-14 17:02:38] INFO: Testing url https://checkout.mytoys.de/checkout/notepad run 1
[2018-03-14 17:02:48] ERROR: UnknownCommandError: POST /session/cd6b727c-2a84-455d-91b6-fc65fd124c71/element/b0a3f2e4-7368-4fb8-8d63-be2c6aac16e6/submit did not match a known command
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElementPromise.schedule_ (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElementPromise.submit (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:2338:17)
    at driver.get.then (/sitespeed.io/login-script.js:15:21)
    at ManagedPromise.invokeCallback_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /usr/src/app/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From previous event:
    at Promise.resolve.tap.tap (/usr/src/app/node_modules/browsertime/lib/core/engine.js:250:19)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:249:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:209:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
Versions used are in the log above on first line. Docker is running on Ubuntu 16.04.3 LTS.

Here is a script, which runs all the stuff (only for firefox, others omitted):
```
#!/bin/bash
DOCKER_CONTAINER=sitespeedio/sitespeed.io:6.4.1
DOCKER_SETUP="-e MAX_OLD_SPACE_SIZE=3072 --privileged --shm-size=1g --rm -v /home/sitespeed/sitespeed-config:/sitespeed.io -v /home/sitespeed/results:/result -v /etc/localtime:/etc/localtime:ro --name sitespeed-container"
THREEG="--network 3g"
CABLE="--network cable"
SITESPEED="/sitespeed.io"
CONFIG="--config $SITESPEED/default.json"
NO_LOGIN_URLS="$SITESPEED/no-login-urls.txt"
LOGIN_URLS="$SITESPEED/login-urls.txt"
MOBILE="-c 3g --mobile true"
PRELOAD_URL="--preURL https://checkout.mytoys.de/basketOverview"
LOGIN_SCRIPT="--preScript $SITESPEED/login-script.js"
NAMESPACE_PREFIX="--graphite.namespace sitespeed_io"

docker run $CABLE $DOCKER_SETUP $DOCKER_CONTAINER -b firefox --browsertime.skipHar $LOGIN_SCRIPT $CONFIG $NAMESPACE_PREFIX.desktopLoggedIn $LOGIN_URLS >> /tmp/s.log 2>&1
```

default.json:
```
{
  "browsertime": {
    "connectivity": {
      "engine": "tc",
      "profile": "cable"
    },
    "iterations": 5,
    "browser": "chrome",
    "speedIndex": true
  },
  "graphite": {
    "host": "checkout-graphite.shopdev.mytoys.de",
    "httpPort": "8081",
    "namespace": "sitespeed_io.desktop",
    "auth": "root:root"
  },
  "resultBaseURL": "http://checkout-sitespeed-results.s3-website.eu-central-1.amazonaws.com",
  "gpsi": {
    "key": "%key%"
  },
  "video": true,
  "gzipHAR": true,
  "html": {
    "fetchHARFiles": true
  },
  "s3": {
    "key": "%key%",
    "secret": "%secret%",
    "bucketname": "checkout-sitespeed-results",
    "removeLocalResult": true
  },
  "firstParty": "checkout.mytoys.de"
}
```

And finally here's prescript itself:
```
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('https://checkout.mytoys.de/checkout/login')
        .then(() => {
          const webdriver = context.webdriver;
          const until = webdriver.until;
          const By = webdriver.By;

          const userName = '%username%';
          const password = '%password%';
          const loginForm = driver.findElement(By.id('loginCommand'));
          driver.findElement(By.id('login')).sendKeys(userName);
          driver.findElement(By.id('password')).sendKeys(password);
          loginForm.submit();

          return driver.wait(function() {
            return driver.getTitle().then(function(title) {
              return title.indexOf('Login') == -1;
            });
          }, 1000);
        });
    })
  }
};
```
If you need credentials, I can provide some with an email of something. Looks like the issue is independent from url which is accessed afterwards, since this error exists for all, which i'm trying to test.

And some more background, maybe it will help investigating - we currently redirect user to get his session state setup (you earlier fixed the other [bug|https://github.com/sitespeedio/sitespeed.io/issues/1861] caused by this redirect chain)

**Comment by soulgalore** [comment]
Hi @Pe4enie I think you use a Selenium command that actually just work in Chrome and that is not a webdriver standard (I also did the same before). I think the example login script in Browsertime for Wikipedia works for both browsers, check it out! 

I’m away a couple of days without my computer so can’t give you the exact link sorry!

Best 
Peter

**Comment by Pe4enie** [comment]
Hi @soulgalore, I'll try that out, but the only difference I see between my script and your documentation (that's the [right link](https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/), right?) is that you no longer submit the form, but just click the button.

Btw, this line in documentation
`const loginForm = driver.findElement(By.name('userlogin'));`
is no longer needed ;)

**Comment by Pe4enie** [comment]
Hi @soulgalore, you were totally right, clicking the button instead of submitting the form works in both Chrome and Firefox! You can close the issue then, I guess. Thanks! :)
