### ISSUE TITLE
Error while recording visual metrics

### ISSUE THREAD

**Issue by Pe4enie** [sitespeedio/sitespeed.io#1949]
Hi again,

here is another issue i'm currently having in my setup. All the configs are the same as in [other issue I just reported](https://github.com/sitespeedio/sitespeed.io/issues/1948).

docker run command is:
```
docker run $CABLE $DOCKER_SETUP $DOCKER_CONTAINER $LOGIN_SCRIPT $CONFIG $NAMESPACE_PREFIX.desktopLoggedInWithCache $PRELOAD_URL $LOGIN_URLS >> /tmp/s.log 2>&1
```

And the error:
```
[2018-03-12 17:13:12] INFO: Versions OS: linux 4.4.0-93-generic nodejs: v8.9.4 sitespeed.io: 6.4.1 browsertime: 2.2.2 coach: 1.2.0
[2018-03-12 17:13:13] INFO: Starting chrome for analysing https://checkout.mytoys.de/checkout/notepad 5 time(s)
[2018-03-12 17:13:13] INFO: Testing url https://checkout.mytoys.de/checkout/notepad run 1
[2018-03-12 17:13:20] INFO: Accessing preURL https://checkout.mytoys.de/basketOverview
[2018-03-12 17:13:43] INFO: Testing url https://checkout.mytoys.de/checkout/notepad run 2
[2018-03-12 17:13:52] INFO: Accessing preURL https://checkout.mytoys.de/basketOverview
[2018-03-12 17:14:13] INFO: Testing url https://checkout.mytoys.de/checkout/notepad run 3
[2018-03-12 17:14:20] INFO: Accessing preURL https://checkout.mytoys.de/basketOverview
[2018-03-12 17:14:40] INFO: Testing url https://checkout.mytoys.de/checkout/notepad run 4
[2018-03-12 17:14:48] INFO: Accessing preURL https://checkout.mytoys.de/basketOverview
[2018-03-12 17:15:06] ERROR: Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir /sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-03-12-17-13-12/pages/checkout.mytoys.de/checkout/notepad/data/video/images/3 --video /sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-03-12-17-13-12/pages/checkout.mytoys.de/checkout/notepad/data/video/3.mp4 --orange --perceptual --force --startwhite --renderignore 5 --json -q 75
ffmpeg version 3.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-10) 20171112
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-03-12-17-13-12/pages/checkout.mytoys.de/checkout/notepad/data/video/3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:05.40, start: 0.000000, bitrate: 235 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 231 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-03-12-17-13-12/pages/checkout.mytoys.de/checkout/notepad/data/video/images/3/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.362x    
video:279kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
17:15:06.210 - No video frames found in /sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-03-12-17-13-12/pages/checkout.mytoys.de/checkout/notepad/data/video/images/3

    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:208:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From previous event:
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.run (/usr/src/app/node_modules/browsertime/lib/support/video/scripts/runVisualMetrics.js:13:8)
    at Promise.mapSeries.postScript (/usr/src/app/node_modules/browsertime/lib/core/engine.js:302:31)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.tap.tap.tap.tap.tap.tap.tap.results (/usr/src/app/node_modules/browsertime/lib/core/engine.js:300:19)
From previous event:
    at runIteration (/usr/src/app/node_modules/browsertime/lib/core/engine.js:299:10)
    at Promise.reduce (/usr/src/app/node_modules/browsertime/lib/core/engine.js:336:27)
From previous event:
    at Promise.resolve.tap.tap.tap.tap.result (/usr/src/app/node_modules/browsertime/lib/core/engine.js:333:17)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine.js:332:8)
    at engine.start.then (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:26)
    at /usr/src/app/node_modules/xvfb/index.js:55:28
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
From previous event:
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:8)
    at storageManager.createDirForUrl.then.then (/usr/src/app/lib/plugins/browsertime/index.js:209:22)
    at /usr/src/app/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:208:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:210:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Unfortunately, it's not consistent, but from last runs I did, appears at least once each time.
As you can say from docker run command, I expect browser to login, and then to access a page to heat the cache.

Here's a preload script:
```
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('https://checkout.mytoys.de/checkout/basketOverview');
    });
  }
};
```

**Comment by soulgalore** [comment]
One hack you could try in your login script is that after the login has finished, empty the body of the HTML document so it’s all white (I don’t think we do that today). We changed that in the coming 3.0 of browsertime so it will be more automagical things, but let me have a look early next week.

Best
Peter

**Comment by soulgalore** [comment]
Do this work for you @Pe4enie in 7.x?

**Comment by Pe4enie** [comment]
Hi @soulgalore, sorry for taking so long to answer. This error doesn't appear anymore, but I do have the same issue as described [here](https://github.com/sitespeedio/sitespeed.io/issues/2062) now. Only for runs with a 'login' preScript

**Comment by soulgalore** [comment]
ok @Pe4enie do you run with any [connectivity setup](https://www.sitespeed.io/documentation/sitespeed.io/connectivity/)?

**Comment by Pe4enie** [comment]
Hi @soulgalore, yes, I do run it with connectivity. Exactly same config as in the one you just linked.

**Comment by soulgalore** [comment]
ok thanks @Pe4enie . And the problem is the exactly "Invalid duration specification for ss: NaN"? Just wanted to be 100% sure :) Thanks.

**Comment by Pe4enie** [comment]
@soulgalore , just to make sure ran it right now, here's the output:
```
[2018-09-02 19:24:15] ERROR: {"frames":[{"tags":{"lavfi.signalstats.SATAVG":"3.18015"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17621"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18002"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18002"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18009"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17621"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18009"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18009"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18015"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17621"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18002"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18002"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18009"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17621"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18014"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18014"}},{"tags":{"lavfi.signalstats.SATAVG":"3.1802"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17626"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17626"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17626"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17626"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17626"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18395"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18395"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18408"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17616"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17616"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17616"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17616"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17601"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18371"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18371"}},{"tags":{"lavfi.signalstats.SATAVG":"3.18384"}},{"tags":{"lavfi.signalstats.SATAVG":"3.17589"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14644"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14644"}},{"tags":{"lavfi.signalstats.SATAVG":"3.1465"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14644"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14959"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14958"}},{"tags":{"lavfi.signalstats.SATAVG":"3.14971"}},{"tags":{"lavfi.signalstats.SATAVG":"5.54745"}},{"tags":{"lavfi.signalstats.SATAVG":"5.54793"}},{"tags":{"lavfi.signalstats.SATAVG":"5.54797"}},{"tags":{"lavfi.signalstats.SATAVG":"5.54797"}},{"tags":{"lavfi.signalstats.SATAVG":"5.54798"}},{"tags":{"lavfi.signalstats.SATAVG":"5.43462"}},{"tags":{"lavfi.signalstats.SATAVG":"5.43468"}},{"tags":{"lavfi.signalstats.SATAVG":"5.43468"}},{"tags":{"lavfi.signalstats.SATAVG":"5.4346"}},{"tags":{"lavfi.signalstats.SATAVG":"5.43423"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03692"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03689"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03668"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03699"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03696"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03685"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03686"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03699"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03707"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03697"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03698"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03704"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03713"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03704"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03703"}},{"tags":{"lavfi.signalstats.SATAVG":"8.037"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03708"}},{"tags":{"lavfi.signalstats.SATAVG":"8.037"}},{"tags":{"lavfi.signalstats.SATAVG":"8.037"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03699"}},{"tags":{"lavfi.signalstats.SATAVG":"8.03692"}},{"tags":{"lavfi.signalstats.SATAVG":"8.04021"}},{"tags":{"lavfi.signalstats.SATAVG":"8.04645"}},{"tags":{"lavfi.signalstats.SATAVG":"8.05274"}},{"tags":{"lavfi.signalstats.SATAVG":"8.0534"}},{"tags":{"lavfi.signalstats.SATAVG":"8.05607"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06279"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06364"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06437"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06527"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06523"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06533"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06523"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06506"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06499"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06509"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06499"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06507"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06498"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06509"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06498"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06505"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06466"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06466"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06466"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06459"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06466"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06469"}},{"tags":{"lavfi.signalstats.SATAVG":"8.06446"}}]}
[2018-09-02 19:24:15] ERROR: Error: Command failed: ffmpeg -nostdin -ss NaN -t NaN -i /sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-09-02-19-23-38/pages/checkout.mytoys.de/checkout/notepad/data/video/1.mp4 -c:v libx264 -an -vf drawtext=timecode='00\:00\:00\:00':rate=30: x=(w-280)/2: y=H-60:fontcolor=white:fontsize=48:box=1:boxcolor=0x000000AA,drawtext=enable='between(t,0.737,30)':x=(w-tw)/2: y=H-230:fontcolor=white:fontsize=26:box=1:boxcolor=0x000000AA:boxborderw=2:text='DOMContentLoaded 737',drawtext=enable='between(t,1.367,30)':x=(w-tw)/2: y=H-200:fontcolor=white:fontsize=26:box=1:boxcolor=0x000000AA:boxborderw=2:text='FirstVisualChange 1367',drawtext=enable='between(t,1.574,30)':x=(w-tw)/2: y=H-170:fontcolor=white:fontsize=26:box=1:boxcolor=0x000000AA:boxborderw=2:text='SpeedIndex 1574',drawtext=enable='between(t,1.7,30)':x=(w-tw)/2: y=H-140:fontcolor=white:fontsize=26:box=1:boxcolor=0x000000AA:boxborderw=2:text='VisualComplete85 1700',drawtext=enable='between(t,1.734,30)':x=(w-tw)/2: y=H-110:fontcolor=white:fontsize=26:box=1:boxcolor=0x000000AA:boxborderw=2:text='LastVisualChange 1734' -y /sitespeed.io/sitespeed-result/checkout.mytoys.de/2018-09-02-19-23-38/pages/checkout.mytoys.de/checkout/notepad/data/video/tmp.mp4
ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Invalid duration specification for ss: NaN


ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Invalid duration specification for ss: NaN


    at makeError (/usr/src/app/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by soulgalore** [comment]
Thanks @Pe4enie ! Ok, something goes wrong when we try to determine the start of the video, is it possibel for you to share either the original video or the URL and setup so  I can test (easier to fix if I can reproduce). You can email me at: peter [AT] soulgalore [dot] com

Thanks!

**Comment by Pe4enie** [comment]
Hi @soulgalore , sent you all required information on an email.

Thanks!

**Comment by soulgalore** [comment]
Hey @Pe4enie I've just pushed 7.4.0 that includes the fix. It works for me now ... but let keep this open until you have time to confirm that it works for you. Thanks again for sharing the full setup, that helps so much!!

Best
Peter

**Comment by Pe4enie** [comment]
Hey @soulgalore, had few successful full runs without any issues now. Thank you!
