### ISSUE TITLE
Error: Tried to add null to stats for path firstView,custom,Images

### ISSUE THREAD

**Issue by JamesHawking** [sitespeedio/sitespeed.io#1958]
Hi Guys,

I've been trying to use sitespeed.io to get data from WPT, but it fails.

Here is my command: 
`docker-compose run sitespeed.io http://project43.wikia.com/wiki/SyntheticTests/VUAP/ResolvedState --graphite.host=graphite --webpagetest.host www.webpagetest.org --webpagetest.key ABC --webpagetest.location 'Dulles_MotoG4:Moto G4 - Chrome' --webpagetest.connectivity 3GFast --webpagetest.runs 5`

The error is:
` ERROR: Error creating WebPageTest result  Error: Tried to add null to stats for path firstView,custom,Images`

Stack trace:
`at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:27:13)
    at Object.pushGroupStats (/usr/src/app/lib/support/statsHelpers.js:35:10)
    at metricName (/usr/src/app/lib/plugins/webpagetest/aggregator.js:79:26)
    at arrayEach (/usr/src/app/node_modules/lodash.foreach/index.js:35:9)
    at forEach (/usr/src/app/node_modules/lodash.foreach/index.js:290:10)
    at forEach (/usr/src/app/lib/plugins/webpagetest/aggregator.js:77:9)
    at /usr/src/app/node_modules/lodash.foreach/index.js:221:11
    at baseForOwn (/usr/src/app/node_modules/lodash.foreach/index.js:153:20)
    at /usr/src/app/node_modules/lodash.foreach/index.js:190:14
    at forEach (/usr/src/app/node_modules/lodash.foreach/index.js:290:10)
    at forEach (/usr/src/app/lib/plugins/webpagetest/aggregator.js:47:7)
    at /usr/src/app/node_modules/lodash.foreach/index.js:221:11
    at baseForOwn (/usr/src/app/node_modules/lodash.foreach/index.js:153:20)
    at /usr/src/app/node_modules/lodash.foreach/index.js:190:14
    at forEach (/usr/src/app/node_modules/lodash.foreach/index.js:290:10)
    at Aggregator.addToAggregate (/usr/src/app/lib/plugins/webpagetest/aggregator.js:34:5)
    at analyzer.analyzeUrl.tap.result (/usr/src/app/lib/plugins/webpagetest/index.js:219:29)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/webpagetest/index.js:175:12)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at Unzip.Readable.on (_stream_readable.js:772:35)
    at zlibBuffer (zlib.js:99:10)
    at Object.unzip (zlib.js:598:14)
    at IncomingMessage.onEnd (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:132:16)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at IncomingMessage.Readable.on (_stream_readable.js:772:35)
    at ClientRequest.getResponse (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:120:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)`

Any tips?

**Comment by JamesHawking** [comment]
Okay, in next run it was fine, but data wasn't added to Grafana, any ideas?

**Comment by soulgalore** [comment]
Hey @JamesHawking , the first error is probably some metrics that's missing in the JSON from WebPageTest. I can have a try on that the coming days. In the past different browsers/phones etc has had missing values, we need to catch it.

About the data missing in Graphite/Grafana, what setup are you running? Did you get any metrics or none at all? 

Best
Peter

**Comment by JamesHawking** [comment]
So if i go with:
`docker-compose run sitespeed.io http://project43.wikia.com/wiki/SyntheticTests/VUAP/ResolvedState --graphite.host=graphite`

Data points are added to Gafana dashboard. However if i go with WebPageTest onyly data is not added.

`docker-compose run sitespeed.io http://project43.wikia.com/wiki/SyntheticTests/VUAP/ResolvedState --graphite.host=graphite --webpagetest.host www.webpagetest.org --webpagetest.key ABC --webpagetest.location 'Dulles_MotoG4:Moto G4 - Chrome' --webpagetest.connectivity 3GFast --webpagetest.runs 1 --plugins.remove browsertime`

**Comment by soulgalore** [comment]
No it should work out of the box. Hmm I’ll have a look first thing tonorrow, maybe we missed converting the spaces in the location? When I debug, I start the tcp server in the /tools dir in the sitespeed repo and then point sitespeed to that to see the exact keys that are received and then run in trace debug log to see whixh metrics that is sent. But can you try first with Dulles:Chrome (or one location without spaces)?

**Comment by soulgalore** [comment]
Ah I see now: The first errors is miss-match between the WebPageTest and the WebPageTest api, the same as https://github.com/sitespeedio/sitespeed.io/issues/1928 and reported upstream in https://github.com/marcelduran/webpagetest-api/issues/108.

For the metrics not coming into Graphite, the problem is the space in the location. Let me fix that asap.

**Comment by soulgalore** [comment]
I've pushed 6.5.1 with a fix for spaces in location. It works for me but please get back an verify that it works.

I remember in the late 90's when I was doing Java on Windows. Java was by default installed in the folder "Program Files" but Java couldn't handle spaces in folders, so as soon as you tried to write to disk in that folder it failed. I guess we should have moved on since that ... sorry I missed locations could have spaces :)

**Comment by JamesHawking** [comment]
I confirm that this fixes the problem and issue can be closed. 

Thanks a lot for taking care of that asap, it's funny that nobody noticed before, probably most users run on private instances of WPT. :)

**Comment by soulgalore** [comment]
Great! It's only some phones that uses spaces in the name I think.
