### ISSUE TITLE
Screenshot error (Firefox)

### ISSUE THREAD

**Issue by suratovvlad** [sitespeedio/sitespeed.io#1965]
Hi!
I've found very old and strange site (http://www.arngren.net) for tests and sitespeed.io fails when it tryes to save screenshot (Firefox only) with this logs:

[2018-03-29 17:04:33] INFO: Starting firefox for analysing http://www.arngren.net 1 time(s)
[2018-03-29 17:04:33] INFO: Testing url http://www.arngren.net run 1
[2018-03-29 17:05:27] INFO: 361 requests, 3200.90 kb, backEndTime: 386ms, firstVisualChange: 600ms, DOMContentLoaded: 2.13s, Load: 12.60s, speedIndex: 4814, visualComplete85: 11.40s, lastVisualChange: 12.63s, rumSpeedIndex: 712
[2018-03-29 17:05:27] ERROR: Error: Input buffer contains unsupported image format
    at storeScreenshots (/usr/src/app/lib/plugins/screenshot/index.js:28:18)
    at Object.processMessage (/usr/src/app/lib/plugins/screenshot/index.js:79:16)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[2018-03-29 17:05:29] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.arngren.net/2018-03-29-17-04-33
[2018-03-29 17:05:29] INFO: Finished analysing http://www.arngren.net

The parameters for sitespeed:

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.5.1 --browser firefox -n 1 --plugins.list --graphite.namespace 'test_1234567' --graphite.host "192.168.112.24" --graphite.port 12003  http://www.arngren.net`

**Comment by soulgalore** [comment]
Hi @suratovvlad wow amazing site :)

Ok, hmm, could it be this error https://github.com/lovell/sharp/issues/578

I'll down prio this for now but will look into it later on.

Best
Peter

**Comment by soulgalore** [comment]
This Is still a issue with Firefox, works in Chrome.

**Comment by soulgalore** [comment]
Closing since I don't see that Mozilla gonna fix it.

**Comment by suratovvlad** [comment]
I'm wondering, what was the reason? ;)
