### ISSUE TITLE
Is "Throttle" supported in the docker container?

### ISSUE THREAD

**Issue by marty90** [sitespeedio/sitespeed.io#1979]
Hi!
Thank U for sitespeed.io, it's a great tool!
My question: is the Throttle engine supported in the docker container?

I tried running:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --browsertime.connectivity.engine throttle -c cable https://www.google.com `

but I got several errors!

**Comment by soulgalore** [comment]
Hi @marty90 thanks for the kind words. Let me update the docs (https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#throttle) the coming days, it is a little bit unclear.

It works like this: If you run throttle inside your container,  the base OS needs to be Linux and you need to set the right `sudo modprobe ifb numifbs=1` and then also give the container the privileges for the network: `--cap-add=NET_ADMIN`

For example, if you run on Ubuntu, you need to first run `sudo modprobe ifb numifbs=1` and then `docker run --shm-size=1g --cap-add=NET_ADMIN ...`.

If you use Docker on Mac it will not work. To be able to set the connectivity, you then need to run throttle outside of the container, see the last example here:

https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#throttle

Best
Peter

**Comment by marty90** [comment]
Thank You!
However when I try (on my Ubuntu 16):
```
sudo modprobe ifb numifbs=1
sudo docker run --cap-add=NET_ADMIN --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --browsertime.connectivity.engine throttle -c cable https://www.google.com/
```
I get this output (containing errors):
```
Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
[2018-04-16 19:16:01] INFO: Versions OS: linux 4.13.0-37-generic nodejs: v8.9.4 sitespeed.io: 6.5.3 browsertime: 2.5.0 coach: 1.3.0
[2018-04-16 19:16:02] INFO: Starting chrome for analysing https://www.repubblica.it 3 time(s)
[2018-04-16 19:16:02] INFO: Changing network interfaces needs sudo rights.
[2018-04-16 19:16:02] INFO: Testing url https://www.repubblica.it run 1
(node:57) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: /bin/sh -c sudo route | grep '^default' | grep -o '[^ ]*$'
sudo: route: command not found


(node:57) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-04-16 19:16:20] INFO: Testing url https://www.repubblica.it run 2
[2018-04-16 19:16:35] INFO: Testing url https://www.repubblica.it run 3
[2018-04-16 19:16:47] INFO: 79 requests, 736.37 kb, backEndTime: 488ms (±9.57ms), firstPaint: 866ms (±31.89ms), firstVisualChange: 933ms (±36.03ms), DOMContentLoaded: 1.26s (±19.07ms), Load: 1.84s (±44.11ms), speedIndex: 1301 (±33.52), visualComplete85: 1.59s (±41.60ms), lastVisualChange: 2.37s (±40.82ms), rumSpeedIndex: 1066 (±36.76) (3 runs)
[2018-04-16 19:16:47] ERROR: Error: Command failed: sudo tc qdisc del dev ifb0 root
Cannot find device "ifb0"


    at Promise.all.then.arr (/usr/src/app/node_modules/@sitespeed.io/throttle/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-04-16 19:16:48] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.repubblica.it/2018-04-16-19-16-01
[2018-04-16 19:16:48] INFO: Finished analysing https://www.repubblica.it
```

It looks like the `route` command is not found. Would adding the installation of `net-tools` package in the Dockerfile help?

**Comment by soulgalore** [comment]
Aha yep it looks like a mistake from me, missed adding route.  Could it be that I missed that for the sitespeed.io container but it's there for Browsertime? Let me fix that for the next release.

Best
Peter

**Comment by marty90** [comment]
I confirm that manually installing `net-tools` in the container, and then running `sitespeed` executes with no error!
Also the image of `Browsertime` does not have `route` installed.

**Comment by marty90** [comment]
Great!

**Comment by marty90** [comment]
Oh just a last question ;) Running multiple docker containers with different throttle settings (on the same machine) may create inconsistent traffic shaping?
I noticed a similar warning in the [WPT agent docker readme ](https://github.com/WPO-Foundation/wptagent/blob/master/docs/docker.md)

**Comment by soulgalore** [comment]
@marty90 correct,  that will not work. You can setup different docker networks as in https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#docker-networks but in practice, I haven't seen anyone showing that running multiple browser instances will not affect each other, so I always run one test/URL at a time.

**Comment by soulgalore** [comment]
Pushed in 6.5.4

**Comment by soulgalore** [comment]
This runs now on our DO environment.
