### ISSUE TITLE
How to include multiple testcases?

### ISSUE THREAD

**Issue by jzlshitian** [sitespeedio/sitespeed.io#1983]
Currently I am testing with 6.5.3 and I met some problems with multiple test cases.

```
"testCases": [
            {
                "path": "?paneId=manage",
                "budget": {
                    "custom.cache": [
                        {
                            "metric": "dynamicCacheHeader",
                            "enable": true,
                            "max": 5,
                            "exclude": []
                        },
                        {
                            "metric": "staticCacheHeader",
                            "enable": true,
                            "max": 8,
                            "exclude": []
                        }
                    ],
                    "coach.pageSummary": [
                        {
                            "metric": "advice.performance.score",
                            "min": 59
                        }
                    ]
                }
            },
            {
                "path": "?paneId=usage",
                "budget": {
                    "custom.cache": [
                        {
                            "metric": "dynamicCacheHeader",
                            "enable": true,
                            "max": 5,
                            "exclude": []
                        }
                    ],
                    "coach.pageSummary": [
                        {
                            "metric": "advice.performance.score",
                            "min": 59
                        }
                    ]
                }
            }
        ]
```

Every path represents a test case. If there is only one test case, everything just works fine. If there are more than one, than errors will occur.

```
[2018-04-17 14:43:59] ERROR: Error: Multiple summary messages of type aggregateassets.summary and group total
    at validateSummaryMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:78:13)
    at validateMessageFormat (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:87:3)
    at QueueHandler.postMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:194:5)
    at Object.processMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/plugins/assets/index.js:46:19)
    at queue.process.message (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:208:32)
    at drainItem (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-04-17 14:43:59] ERROR: Error: Multiple summary messages of type browsertime.summary and group total
    at validateSummaryMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:78:13)
    at validateMessageFormat (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:87:3)
    at QueueHandler.postMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:194:5)
    at Object.processMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:340:19)
    at queue.process.message (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:208:32)
    at drainItem (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-04-17 14:43:59] ERROR: Error: Multiple summary messages of type coach.summary and group total
    at validateSummaryMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:78:13)
    at validateMessageFormat (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:87:3)
    at QueueHandler.postMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:194:5)
    at Object.processMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/plugins/coach/index.js:65:19)
    at queue.process.message (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:208:32)
    at drainItem (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-04-17 14:43:59] ERROR: Error: Multiple summary messages of type domains.summary and group total
    at validateSummaryMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:78:13)
    at validateMessageFormat (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:87:3)
    at QueueHandler.postMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:194:5)
    at Object.processMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/plugins/domains/index.js:37:19)
    at queue.process.message (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:208:32)
    at drainItem (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-04-17 14:43:59] ERROR: Error: Multiple summary messages of type pagexray.summary and group localhost
    at validateSummaryMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:78:13)
    at validateMessageFormat (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:87:3)
    at QueueHandler.postMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:194:5)
    at Object.processMessage (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/plugins/pagexray/index.js:96:19)
    at queue.process.message (/Users/jiangzhuoli/Desktop/my-web/node_modules/sitespeed.io/lib/core/queueHandler.js:208:32)
    at drainItem (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/Users/jiangzhuoli/Desktop/my-web/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Anyone have ideas? Thanks

**Comment by soulgalore** [comment]
Hi @jzlshitian can you show me how you run, I don't follow the config, do you use something on top of sitespeedio? One problem could be that maybe the query parameter isn't handled correctly if you can show me how you run, it's easier to reproduce.

Best
Peter

**Comment by jzlshitian** [comment]
It has been fixed. You are right. Something on top of sitespeedio went wrong. Thank you for your hint. :)
