### ISSUE TITLE
Issue with --browsertime.pageCompleteCheck

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2022]
Hi,

I've got a problem with the --browsertime.pageCompleteCheck option.  It seems that when building the docker image myself from the published dockerfile, this option is not working:

As you can see from the below the JQ is not wrapped by single quotes (bold) and thus gives the error 

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeedio sitespeed.io/urls.txt --browsertime.viewPort 1334x750 --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1" -n 1 --browsertime.requestheader Pragma:akamai-x-cache-on --html.showAllWaterfallSummary true --video --har --browsertime.pageCompleteCheck 'return (!$("#fullScreenBackground").hasClass("game-background-scaling visuallyhidden"))' --verbose`

Google Chrome 66.0.3359.33 beta
Mozilla Firefox 61.0a1
[2018-05-07 14:25:02] INFO: [sitespeedio] Versions OS: linux 4.9.87-linuxkit-aufs nodejs: v8.9.4 sitespeed.io: 6.5.3 browsertime: 3.0.0-alpha.13 coach: 1.3.1
[2018-05-07 14:25:03] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing https://UrlRemoved 1 time(s)
[2018-05-07 14:25:03] INFO: [root] Testing url https://UrlRemoved iteration 1
[2018-05-07 14:25:07] DEBUG: [root] Configuring browser plugin via http://127.0.0.1:41411?rh=Pragma%3Aakamai-x-cache-on
[2018-05-07 14:25:08] DEBUG: [root] Waiting for script return (function() {try { var end = window.performance.timing.loadEventEnd;return (end > 0) && (Date.now() > end + 2000);} catch(e) {return true;}})() at most 300000 ms
[2018-05-07 14:25:10] DEBUG: [root] Change background color to orange
[2018-05-07 14:25:12] DEBUG: [root] Started ffmpeg with -hide_banner -video_size 1334x684 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /tmp/browsertime-QEAREl/x11.mp4
**[2018-05-07 14:25:13] DEBUG: [root] Waiting for script return (!$("#fullScreenBackground").hasClass("game-background-scaling visuallyhidden")) at most 300000 ms
[2018-05-07 14:25:16] ERROR: [root] Could not load URLWebDriverError: unknown error: $ is not defined**
  (Session info: chrome=66.0.3359.33)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.9.87-linuxkit-aufs x86_64)
[2018-05-07 14:25:16] ERROR: [root] UrlLoadError: Failed to load https://UrlRemoved
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:169:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-05-07 14:25:16] DEBUG: [root] Kill all processes ffmpeg
[2018-05-07 14:25:16] DEBUG: [root] Telling browser to quit.
[2018-05-07 14:25:16] INFO: [root] 0
[2018-05-07 14:25:16] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2018-05-07 14:25:16] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2018-05-07 14:25:16] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2018-05-07 14:25:16] DEBUG: [sitespeedio.plugin.html] Render HTML for 1 page(s) 
[2018-05-07 14:25:16] DEBUG: [sitespeedio.plugin.html] Render summary page errors
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page index
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page detailed
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page domains
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page assets
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page toplist
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render summary page help
[2018-05-07 14:25:17] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2018-05-07 14:25:18] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-result/UrlRemoved/2018-05-07-14-25-02
[2018-05-07 14:25:18] INFO: [sitespeedio] Finished analysing https://UrlRemoved

If i pull the latest image from docker hub it works:

`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io sitespeed.io/urls.txt --browsertime.viewPort 1334x750 --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1" -n 1 --browsertime.requestheader Pragma:akamai-x-cache-on --html.showAllWaterfallSummary true --video --har --browsertime.pageCompleteCheck 'return (!$("#fullScreenBackground").hasClass("game-background-scaling visuallyhidden"))' --verbose`

Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
[2018-05-07 14:26:40] INFO: [sitespeedio] Versions OS: linux 4.9.87-linuxkit-aufs nodejs: v8.9.4 sitespeed.io: 6.5.4 browsertime: 2.5.0 coach: 1.3.0
[2018-05-07 14:26:40] INFO: [sitespeedio.plugin.browsertime] Starting chrome for analysing https://UrlRemoved 1 time(s)
[2018-05-07 14:26:40] INFO: [root] Testing url https://UrlRemoved run 1
[2018-05-07 14:26:41] DEBUG: [root] Configuring browser plugin via http://127.0.0.1:40763?rh=Pragma%3Aakamai-x-cache-on
[2018-05-07 14:26:43] DEBUG: [root] [x11grab @ 0x58d4d40] 
[2018-05-07 14:26:43] DEBUG: [root] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':99.0+0,66':
  Duration: N/A, start: 1525703203.823120, bitrate: N/A

[2018-05-07 14:26:43] DEBUG: [root]     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1334x684, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc

[2018-05-07 14:26:43] DEBUG: [root] Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264rgb))
Press [q] to stop, [?] for help

[2018-05-07 14:26:43] DEBUG: [root] Started ffmpeg with -hide_banner -video_size 1334x684 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast /sitespeed.io/sitespeed-result/UrlRemoved/2018-05-07-14-26-40/pages/UrlRemoved/query-9dc77463/data/video/0.mp4
[2018-05-07 14:26:43] DEBUG: [root] [libx264rgb @ 0x58df200] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

[2018-05-07 14:26:43] DEBUG: [root] [libx264rgb @ 0x58df200] profile High 4:4:4 Predictive, level 3.2, 4:4:4 8-bit

[2018-05-07 14:26:43] DEBUG: [root] [libx264rgb @ 0x58df200] 264 - core 152 r19 ba24899 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=0 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc=cqp mbtree=0 qp=0
Output #0, mp4, to '/sitespeed.io/sitespeed-result/UrlRemoved/2018-05-07-14-26-40/pages/UrlRemoved/query-9dc77463/data/video/0.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (libx264rgb) (avc1 / 0x31637661), bgr0, 1334x684, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264rgb
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

[2018-05-07 14:26:43] DEBUG: [root] Requesting url https://UrlRemoved
[2018-05-07 14:26:44] DEBUG: [root] frame=   18 fps=0.0 q=0.0 size=       0kB time=00:00:00.43 bitrate=   0.9kbits/s speed=0.837x    
[2018-05-07 14:26:44] DEBUG: [root] frame=   33 fps= 32 q=0.0 size=       0kB time=00:00:00.93 bitrate=   0.4kbits/s speed=0.917x    
[2018-05-07 14:26:45] DEBUG: [root] frame=   48 fps= 32 q=0.0 size=       0kB time=00:00:01.43 bitrate=   0.3kbits/s speed=0.944x    
[2018-05-07 14:26:45] DEBUG: [root] frame=   64 fps= 31 q=0.0 size=     256kB time=00:00:01.96 bitrate=1066.5kbits/s speed=0.958x    
[2018-05-07 14:26:46] DEBUG: [root] frame=   80 fps= 31 q=0.0 size=     256kB time=00:00:02.50 bitrate= 839.0kbits/s speed=0.967x    
[2018-05-07 14:26:46] DEBUG: [root] frame=   96 fps= 31 q=0.0 size=     256kB time=00:00:03.03 bitrate= 691.5kbits/s speed=0.973x    
[2018-05-07 14:26:47] DEBUG: [root] frame=  111 fps= 31 q=0.0 size=     256kB time=00:00:03.53 bitrate= 593.6kbits/s speed=0.977x    
[2018-05-07 14:26:47] DEBUG: [root] frame=  126 fps= 31 q=0.0 size=     512kB time=00:00:04.03 bitrate=1040.0kbits/s speed=0.979x    
[2018-05-07 14:26:48] DEBUG: [root] frame=  142 fps= 31 q=0.0 size=     512kB time=00:00:04.56 bitrate= 918.5kbits/s speed=0.982x    
[2018-05-07 14:26:49] DEBUG: [root] frame=  157 fps= 30 q=0.0 size=     512kB time=00:00:05.06 bitrate= 827.9kbits/s speed=0.983x    
[2018-05-07 14:26:49] DEBUG: [root] frame=  173 fps= 30 q=0.0 size=    1792kB time=00:00:05.60 bitrate=2621.5kbits/s speed=0.985x    
[2018-05-07 14:26:50] DEBUG: [root] frame=  189 fps= 30 q=0.0 size=    1792kB time=00:00:06.13 bitrate=2393.5kbits/s speed=0.986x    
**[2018-05-07 14:26:50] DEBUG: [root] Waiting for script 'return (!$("#fullScreenBackground").hasClass("game-background-scaling visuallyhidden"))' at most 300000 ms**
[2018-05-07 14:26:50] DEBUG: [root] frame=  205 fps= 30 q=0.0 size=    1792kB time=00:00:06.66 bitrate=2202.0kbits/s speed=0.988x    
[2018-05-07 14:26:51] DEBUG: [root] frame=  221 fps= 30 q=0.0 size=    2048kB time=00:00:07.20 bitrate=2330.2kbits/s speed=0.989x    
[2018-05-07 14:26:51] DEBUG: [root] frame=  236 fps= 30 q=0.0 size=    2048kB time=00:00:07.70 bitrate=2178.9kbits/s speed=0.989x    
[2018-05-07 14:26:52] DEBUG: [root] frame=  251 fps= 30 q=0.0 size=    2048kB time=00:00:08.20 bitrate=2046.0kbits/s speed=0.99x    
[2018-05-07 14:26:52] DEBUG: [root] frame=  266 fps= 30 q=0.0 size=    3072kB time=00:00:08.70 bitrate=2892.6kbits/s speed=0.99x    
[2018-05-07 14:26:53] DEBUG: [root] frame=  282 fps= 30 q=0.0 size=    3072kB time=00:00:09.23 bitrate=2725.6kbits/s speed=0.991x    
[2018-05-07 14:26:53] DEBUG: [root] frame=  298 fps= 30 q=0.0 size=    3072kB time=00:00:09.76 bitrate=2576.7kbits/s speed=0.992x    
[2018-05-07 14:26:54] DEBUG: [root] frame=  313 fps= 30 q=0.0 size=    3072kB time=00:00:10.26 bitrate=2451.2kbits/s speed=0.99x    
[2018-05-07 14:26:54] DEBUG: [root] frame=  329 fps= 30 q=0.0 size=    3328kB time=00:00:10.80 bitrate=2524.4kbits/s speed=0.992x    
[2018-05-07 14:26:55] DEBUG: [root] frame=  344 fps= 30 q=0.0 size=    3328kB time=00:00:11.30 bitrate=2412.7kbits/s dup=3 drop=0 speed=0.991x    
[2018-05-07 14:26:55] DEBUG: [root] frame=  362 fps= 30 q=0.0 size=    3328kB time=00:00:11.90 bitrate=2291.0kbits/s dup=8 drop=6 speed=0.999x    
[2018-05-07 14:26:56] DEBUG: [root] frame=  377 fps= 30 q=0.0 size=    3328kB time=00:00:12.40 bitrate=2198.6kbits/s dup=8 drop=6 speed=0.999x    
[2018-05-07 14:26:56] DEBUG: [root] frame=  391 fps= 30 q=0.0 size=    3328kB time=00:00:12.86 bitrate=2118.9kbits/s dup=8 drop=6 speed=0.996x    
[2018-05-07 14:26:57] DEBUG: [root] frame=  407 fps= 30 q=0.0 size=    3328kB time=00:00:13.40 bitrate=2034.6kbits/s dup=9 drop=6 speed=0.991x    
[2018-05-07 14:26:57] DEBUG: [root] frame=  423 fps= 30 q=0.0 size=    3584kB time=00:00:13.93 bitrate=2107.2kbits/s dup=9 drop=7 speed=0.993x    
[2018-05-07 14:26:58] DEBUG: [root] frame=  441 fps= 30 q=0.0 size=    4096kB time=00:00:14.53 bitrate=2308.8kbits/s dup=9 drop=7 speed=0.999x    
[2018-05-07 14:26:58] DEBUG: [root] Getting performance logs from Chrome
[2018-05-07 14:26:59] DEBUG: [root] frame=  457 fps= 30 q=0.0 size=    4352kB time=00:00:15.06 bitrate=2366.3kbits/s dup=9 drop=7 speed=0.999x    
[2018-05-07 14:26:59] DEBUG: [root] Stop ffmpeg recording
[2018-05-07 14:26:59] DEBUG: [root] frame=  466 fps= 30 q=-1.0 Lsize=    4390kB time=00:00:15.50 bitrate=2320.0kbits/s dup=9 drop=7 speed=   1x    
video:4387kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.061707%

[2018-05-07 14:26:59] DEBUG: [root] [libx264rgb @ 0x58df200] frame I:2     Avg QP: 0.00  size:570200
[libx264rgb @ 0x58df200] frame P:464   Avg QP: 0.00  size:  7223
[libx264rgb @ 0x58df200] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264rgb @ 0x58df200] mb P  I16..4: 38.7%  0.0%  0.0%  P16..4:  0.1%  0.0%  0.0%  0.0%  0.0%    skip:61.2%
[libx264rgb @ 0x58df200] coded y,u,v intra: 1.6% 2.0% 1.7% inter: 0.1% 0.1% 0.1%
[libx264rgb @ 0x58df200] i16 v,h,dc,p: 99%  1%  0%  0%
[libx264rgb @ 0x58df200] kb/s:2313.33

[2018-05-07 14:26:59] DEBUG: [root] Stopped ffmpeg
[2018-05-07 14:26:59] DEBUG: [root] Converting video to viewable format.
[2018-05-07 14:27:05] DEBUG: [root] Running visualMetrics
[2018-05-07 14:27:39] DEBUG: [root] Collected metrics {"SpeedIndex":7497,"PerceptualSpeedIndex":12742,"FirstVisualChange":2400,"LastVisualChange":14167,"VisualProgress":"0=0%, 2400=20%, 2433=20%, 2467=20%, 2500=20%, 2533=20%, 2567=20%, 2600=20%, 2633=20%, 2667=20%, 2700=20%, 2733=20%, 2767=20%, 2800=20%, 2833=20%, 2867=20%, 2900=20%, 2933=20%, 2967=20%, 3000=20%, 3033=20%, 3067=20%, 3100=20%, 3133=20%, 3167=20%, 3500=20%, 3767=20%, 4000=20%, 4433=20%, 4500=20%, 4633=20%, 4767=20%, 4900=20%, 4933=26%, 5000=26%, 5067=26%, 5133=26%, 5233=26%, 5267=26%, 5433=69%, 5500=69%, 5600=69%, 5733=69%, 5767=69%, 5833=69%, 5900=69%, 5967=69%, 6033=69%, 6100=69%, 6200=69%, 6267=69%, 6333=69%, 6467=69%, 6567=69%, 6600=69%, 6633=69%, 6667=69%, 6733=69%, 6800=69%, 6867=69%, 6933=69%, 7000=69%, 7067=69%, 7133=69%, 7200=69%, 7267=69%, 7333=69%, 7600=69%, 7633=69%, 7700=69%, 7767=69%, 7833=69%, 7867=69%, 7933=69%, 8000=69%, 8067=69%, 8133=69%, 8200=69%, 8267=69%, 8333=69%, 8400=69%, 8533=69%, 8600=69%, 8633=69%, 8700=69%, 8767=69%, 8833=69%, 8900=69%, 8967=69%, 9000=69%, 9067=69%, 9133=69%, 9200=69%, 9400=69%, 9500=69%, 9533=69%, 9600=69%, 9633=69%, 9700=69%, 9767=69%, 9800=69%, 9867=69%, 9900=69%, 9933=69%, 9967=69%, 10033=69%, 10067=69%, 10100=69%, 10133=69%, 10167=69%, 10233=69%, 10267=69%, 10333=69%, 10367=69%, 10400=69%, 10533=69%, 10600=69%, 10667=69%, 10733=69%, 10800=69%, 10867=69%, 10900=69%, 10933=69%, 11000=69%, 11067=69%, 11133=69%, 11167=69%, 11233=69%, 11300=69%, 11400=69%, 11433=69%, 11533=69%, 12900=69%, 12967=69%, 13033=69%, 13100=69%, 13367=69%, 13433=69%, 13567=69%, 13633=69%, 13700=69%, 13767=69%, 13800=69%, 13867=69%, 13900=69%, 13967=69%, 14133=88%, 14167=100%"}
[2018-05-07 14:27:52] DEBUG: [root] Telling browser to quit.
[2018-05-07 14:27:53] INFO: [root] 271 requests, 20651.60 kb, backEndTime: 432ms, firstPaint: 1.74s, firstVisualChange: 2.40s, DOMContentLoaded: 1.72s, Load: 3.79s, speedIndex: 7497, visualComplete85: 14.13s, lastVisualChange: 14.17s, rumSpeedIndex: 7085
[2018-05-07 14:27:53] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2018-05-07 14:27:53] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2018-05-07 14:27:53] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render HTML for 1 page(s) 
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page index
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page detailed
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page domains
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page assets
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page toplist
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render summary page help
[2018-05-07 14:27:54] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2018-05-07 14:27:55] DEBUG: [sitespeedio.plugin.html] Render URL run page 0
[2018-05-07 14:27:55] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-result/UrlRemoved/2018-05-07-14-26-40
[2018-05-07 14:27:55] INFO: [sitespeedio] Finished analysing https://UrlRemoved

Unfortunately i've had to remove the URLs, but i think you can still see what i mean.

Many thanks!

**Comment by soulgalore** [comment]
Hey @scabenga did this work out for you? Else could you please add exact how you run so we can reproduce. 
Thanks
Peter

**Comment by scabenga** [comment]
Sorted!
