### ISSUE TITLE
Node.Js Windows 10 x11grab x11grab dont work on windows 

### ISSUE THREAD

**Issue by GeekZebre** [sitespeedio/sitespeed.io#2027]
Hello,

**This is the error.**

> [2018-05-10 21:44:02] INFO: [root] Testing url https://url-to-test.com iteration 1
[2018-05-10 21:44:06] DEBUG: [root] Change background color to orange
[2018-05-10 21:44:07] TRACE: [root] Unknown input format: 'x11grab'

    at Socket.readableStream.on.data (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\ffmpegRecorder.js:43:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:772:35)
    at Promise (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\ffmpegRecorder.js:42:22)
    at new Promise (<anonymous>)
    at waitForRecording (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\ffmpegRecorder.js:41:12)
    at startRecording (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\ffmpegRecorder.js:63:39)
    at Object.startRecordingX11 (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\ffmpegRecorder.js:106:12)
    at X11Recorder.start (C:\sitespeed.io\node_modules\browsertime\lib\video\screenRecording\desktop\x11recorder.js:39:37)
    at <anonymous>
> [2018-05-10 21:44:07] ERROR: [root] Error: Command failed: ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast C:\Users\MyUser\AppData\Local\Temp\browsertime-xGgYxo\x11.mp4
Unknown input format: 'x11grab'

Unknown input format: 'x11grab'

    at makeError (C:\sitespeed.io\node_modules\browsertime\node_modules\execa\index.js:172:9)
    at Promise.all.then.arr (C:\sitespeed.io\node_modules\browsertime\node_modules\execa\index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [2018-05-10 21:44:07] DEBUG: [root] Telling browser to quit.

**The explanation :** 

https://stackoverflow.com/questions/6766333/capture-windows-screen-with-ffmpeg
-> NB: x11grab dont work on windows (it's specifically for Linux/X11) 

**WHAT I HAVE DO**
I have use :
https://github.com/felixrieseberg/windows-build-tools
> npm -add-python-to-path install --global windows-build-tools

https://github.com/WPO-Foundation/visualmetrics
and install all dependencies

> $ python visualmetrics.py --check
ffmpeg:   OK
convert:  OK
compare:  OK
Pillow:   OK
SSIM:     OK

I read documentation and I don't found option to change x11grab.
It's because in line https://github.com/sitespeedio/browsertime/blob/909a72a0499bceb8717fbdd1e5cb547bcd24908e/lib/video/screenRecording/desktop/ffmpegRecorder.js#L19 the argument x11grab is hard coded.

Thanks.

**Comment by soulgalore** [comment]
Hey @GeekZebre 
we only support Windows through Docker (https://www.sitespeed.io/documentation/sitespeed.io/installation/#windows-1). The reason is that we don't have a core contributor that runs Windows.

Best
Peter

**Comment by GeekZebre** [comment]
I understand.

Since those few days, I'm trying to run on Windows 10 with NodeJs.

I can contribute my work but I think I need help to finish.
I can not determine the expected results of ffmeg commands.

What a core contributor must do ? 

Thanks.

**Comment by GeekZebre** [comment]
Hello @soulgalore 

I now run browsertime on Windows with NodeJs. (with chrome and firefox)

But now, I have an issue : 
Windows NodeJs visualmetrics.py ffmpeg Segmentation fault
https://github.com/sitespeedio/browsertime/issues/595

I close this issue.
