### ISSUE TITLE
Slack Summary - ERROR: Error: read ECONNRESET

### ISSUE THREAD

**Issue by idristarwala** [sitespeedio/sitespeed.io#2036]
I am trying to run the following command :- 
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.5.4 https://www.sitespeed.io/ --slack.hookUrl <WEB HOOK URL> --slack.type summary

and I am running into the following errors :- 
at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)
    at TLSSocket.Readable.on (_stream_readable.js:772:35)
    at tickOnSocket (_http_client.js:640:10)
    at onSocketNT (_http_client.js:670:5)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at ClientRequest.onSocket (_http_client.js:658:11)
    at handleSocketCreation_Inner (_http_agent.js:338:15)
    at oncreate (_http_agent.js:234:5)
    at Agent.createSocket (_http_agent.js:239:5)
    at Agent.addRequest (_http_agent.js:190:10)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Request.start (/usr/src/app/node_modules/request/request.js:748:32)
    at Request.write (/usr/src/app/node_modules/request/request.js:1498:10)
    at end (/usr/src/app/node_modules/request/request.js:546:18)
    at Immediate._onImmediate (/usr/src/app/node_modules/request/request.js:575:7)
From previous event:
    at send (/usr/src/app/lib/plugins/slack/index.js:73:8)
    at Object.processMessage (/usr/src/app/lib/plugins/slack/index.js:143:18)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at Request.init (/usr/src/app/node_modules/request/request.js:188:10)
    at new Request (/usr/src/app/node_modules/request/request.js:128:8)
    at request (/usr/src/app/node_modules/request/index.js:53:10)
    at Function.post (/usr/src/app/node_modules/request/index.js:61:12)
    at Slack.send (/usr/src/app/node_modules/node-slack/slack.js:38:21)
    at send (/usr/src/app/lib/plugins/slack/index.js:73:8)
    at Object.processMessage (/usr/src/app/lib/plugins/slack/index.js:143:18)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

we have a proxy for connecting to slack, which I have already set globally and my curl POST to the WEB HOOK URL are working.. not sure why the sitespeed.io docker container is failing.

Any help would be great appreciated.

**Comment by soulgalore** [comment]
Hi @idristarwala 

> we have a proxy for connecting to slack, which I have already set globally 

Inside the Docker container? Is your configuration pointing to localhost? Localhost inside your container means only in the container, not the physical server. Or what does your config look like?

Best
Peter

**Comment by idristarwala** [comment]
so I am setting following environment variable :- 
export http_proxy=<proxy>
export https_proxy=<proxy>
but for some reason the slack API within the container is not picking up the proxy ... I was referring to the guide on https://slackapi.github.io/node-slack-sdk/web_api section #Custom agent for proxy support... I am not sure though how to apply it to sitespeed package.. I am quite new to this please excuse my terminologies if incorrect

**Comment by soulgalore** [comment]
I think you can think about the container as an isolated world: things you have set on the host machine isn't reachable. You need either feed the container the configuration at startup.

Also in the example you need install a custom library:  `npm install --save https-proxy-agent` and that needs to also happens in the container + you need to modify the code right? 

`const web = new WebClient(token, { agent: new HttpsProxyAgent(proxyUrl) });`

So to get this to work (as I understand it) is to create your own Slack plugin with the proxy functionality.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since it's a proxy issue.
