### ISSUE TITLE
Error with graphite

### ISSUE THREAD

**Issue by gpapis** [sitespeedio/sitespeed.io#2038]
Hi, I created a VM with Ubuntu 17.10. On this VM I installed sitespeed.io and work correctly. Unfortunately, my VM arrived to the max of memory and I can't extend it. So I've delete folders with results... Now I've a problem when I launch the command 
`sudo docker-compose run sitespeed.io http://www.google.com --graphite.host=graphite --cacheClearRaw`

I've this error (and I don't understand why?): 

`Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
[2018-05-14 12:09:39] INFO: Versions OS: linux 4.13.0-39-generic nodejs: v8.9.4 sitespeed.io: 6.5.3 browsertime: 2.5.0 coach: 1.3.0
[2018-05-14 12:09:40] INFO: Starting chrome for analysing http://www.google.com 3 time(s)
[2018-05-14 12:09:40] INFO: Testing url http://www.google.com run 1
[2018-05-14 12:10:06] INFO: Testing url http://www.google.com run 2
[2018-05-14 12:10:30] INFO: Testing url http://www.google.com run 3
[2018-05-14 12:10:54] INFO: 73 requests, 1105.35 kb, backEndTime: 100ms (±13.96ms), firstPaint: 627ms (±31.36ms), firstVisualChange: 1.59s (±156.41ms), DOMContentLoaded: 2.34s (±80.81ms), Load: 2.83s (±85.22ms), speedIndex: 3411 (±67.76), visualComplete85: 3.93s (±62.36ms), lastVisualChange: 3.93s (±62.36ms), rumSpeedIndex: 779 (±71.36) (3 runs)
[2018-05-14 12:10:55] ERROR: Error: getaddrinfo ENOTFOUND graphite graphite:2003
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
From previous event:
    at GraphiteSender.send (/usr/src/app/lib/plugins/graphite/sender.js:16:12)
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:74:26)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at Socket.Readable.on (_stream_readable.js:772:35)
    at Promise (/usr/src/app/lib/plugins/graphite/sender.js:22:14)
    at GraphiteSender.send (/usr/src/app/lib/plugins/graphite/sender.js:16:12)
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:74:26)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

Do you have an idea to solve the problem ?

**Comment by soulgalore** [comment]
Sorry I accidentally closed the issue. Can you check if Graphite is running? `docker ps`

Best
Peter

**Comment by gpapis** [comment]
Hi, I have no container

**Comment by soulgalore** [comment]
so hou run Graphite standalone without Docker or how do you mean? Or is not the Graphite container started?

**Comment by gpapis** [comment]
The Graphite container is not started

**Comment by soulgalore** [comment]
Ah I see. You need to start that first with Docker compose. But first I think you should read https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#production-guidelines - that's guidelines, things to think about when you setup to collect metrics.

Best
Peter

**Comment by gpapis** [comment]
Ok, I'm going to see your link, but why can't I use this method ?
[https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes](https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes)

**Comment by soulgalore** [comment]
Ok, then follow the instructions and start Graphite :)

First make sure that you have started Graphite/Grafana etc 
`docker-compose up -d`

Verify that they are running with `docker ps`. If they do not run, you cannot send metrics to it.

Then fetch metrics and send them to Graphite:
`docker-compose run sitespeed.io https://www.sitespeed.io/ --graphite.host=graphite
`

**Comment by gpapis** [comment]
I have a new error when made :-(
`docker-compose up -d`

`ERROR: for graphite  Cannot start service graphite: driver failed programming external connectivity on endpoint test_graphite_1 (14f9c2bf85d04adc259cfe1cec94024cdbb31b5e872eb2f4d1fa1371646abe50): Bind for 0.0.0.0:2003 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.`

It's good for the first : test_sitespeed.io_1

**Comment by gpapis** [comment]
It's good now, I've changed ports in docker compose file.
Thank you very much for your help
