### ISSUE TITLE
[Resolved]Trouble launching sitespeed.io just after install

### ISSUE THREAD

**Issue by Kristy59** [sitespeedio/sitespeed.io#2088]
Hi guys, i installed this package just now. So maybe it's a trouble with the way i install it, but well i'm having this error when i try the sample command and i don't understand what can i do for fixing it. I googled it and don't find anything, so i'm posting this out here,  so maybe someone can help me.

`root@webp02:~# sitespeed.io http://www.google.com
/root/.nvm/versions/node/v6.10.0/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:58
  async processMessage(message, queue) {
        ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.10.0/lib/node_modules/sitespeed.io/lib/cli/cli.js:13:62)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
`

I install sitespeed this way, maybe due to something there :S : 
`
root@webp02:# nvm use 6.10.0
Now using node v6.10.0 (npm v6.1.0)
root@webp02:# npm install -g sitespeed.io
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
/root/.nvm/versions/node/v6.10.0/bin/sitespeed.io -> /root/.nvm/versions/node/v6.10.0/lib/node_modules/sitespeed.io/bin/sitespeed.js
\+ sitespeed.io@7.1.3
updated 1 package in 22.195s
`

I know installing nodeJS as root is bad etc... but well, i don't care because this environment isn't exposed.
Here is all my information about my nodeJS installation if needed:

`root@webp02:~# whereis npm
npm: /root/.nvm/versions/node/v6.10.0/bin/npm
root@webp02:~# which npm
/root/.nvm/versions/node/v6.10.0/bin/npm
root@webp02:~# whereis node
node: /usr/bin/node /root/.nvm/versions/node/v6.10.0/bin/node
root@webp02:~# which node
/root/.nvm/versions/node/v6.10.0/bin/node
root@webp02:~# echo $PATH
/root/.nvm/versions/node/v6.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

P.S: os is debian stretch (9.4)
uname -a: Linux webp02 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by soulgalore** [comment]
Hi @Kristy59 you need to update your node version to latest version 8 https://nodejs.org/en/download/ . We moved to 8 when it became LTS (it makes our code easier to understand).

Best
Peter

**Comment by Kristy59** [comment]
Hi @soulgalore thanks for your quick reply.
I reinstall it with nodejs 8.11.1 and now install is OK.
I'm facing some issue with chrome doesn't starting, but well i guess i need to install some X-env there.

**Comment by soulgalore** [comment]
Great!

**Comment by maherAbuyounes** [comment]
Hi all I am facing same issue and I have installed lastest node JS veriosn 10.15.3

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadScript (/Users/user/Documents/sitesppedio/sitespeed.io/node_modules/browsertime/lib/support/engineUtils.js:23:16)
    at Engine.runMultiple (/Users/user/Documents/sitesppedio/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:207:34)
    at Object.analyzeUrl (/Users/user/Documents/sitesppedio/sitespeed.io/lib/plugins/browsertime/analyzer.js:115:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-29 01:09:09] INFO: HTML stored in /Users/user/Documents/sitesppedio/sitespeed.io/sitespeed-result/viewpage_js/2019-05-29-01-09-08

**Comment by soulgalore** [comment]
Hi @maherAbuyounes  I think that means that the script isn't valid, can you lint it and check that it is correct?

Best
Peter

**Comment by maherAbuyounes** [comment]
Hi @soulgalore I checked by using this websit and it valid 
http://esprima.org/demo/validate.html

module.exports = async function(context, commands) {
 await commands.measure.start('*******');
 try {
await commands.addText.byid('******','username');
await commands.wait.byTime(1000);
await commands.addText.byid('********','password');
await commands.click.byid('validateLogin');
await commands.click.byLinkTextAndWait('Dropship Orders');
await commands.click.byLinkTextAndWait('View orders');

 await commands.measure.stop();
 } catch (e) {
 }
};

**Comment by maherAbuyounes** [comment]
@soulgalore Am I using right command to run ?
bin/sitespeed.js viewPagecopy.js --multi

Could you please share valid JS file and command with me

**Comment by soulgalore** [comment]
Try one of the simpler ones like: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure-multiple-pages
