### ISSUE TITLE
ERROR: Error: Tried to add NaN to stats for path contentSize

### ISSUE THREAD

**Issue by primehaxor** [sitespeedio/sitespeed.io#2097]
Hello, when I try to run the sitespeed with the Firefox browser sometimes it receives this error, I've created one script to workaround it retrying if I receive some error but even with this error the data has been sent to graphite messing with the metrics.

**Docker command**
`docker run --privileged --network=3gslow --shm-size=1g --rm -v /opt/sitespeed/utils:/sitespeed.io sitespeedio/sitespeed.io --cookie Skipbanner=true -n1 --video --graphite.host 172.18.0.1 --browsertime.firefox.args disk-cache-dir=/dev/null --browsertime.viewPort 360x640 -c 3gslow`

```
SpeedIndex: 2827 (±232.35), visualComplete85: 2.71s (±151.13ms), lastVisualChange: 11.59s (±2.76s), rumSpeedIndex: 1714 (±35.09) (3 runs)
[2018-07-01 08:15:18] ERROR: Error: Tried to add NaN to stats for path contentSize
    at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:27:13)
    at Object.pushGroupStats (/usr/src/app/lib/support/statsHelpers.js:35:10)
    at /usr/src/app/lib/plugins/pagexray/pagexrayAggregator.js:22:22
    at Array.forEach (<anonymous>)
    at /usr/src/app/lib/plugins/pagexray/pagexrayAggregator.js:21:20
    at Array.forEach (<anonymous>)
    at Object.addToAggregate (/usr/src/app/lib/plugins/pagexray/pagexrayAggregator.js:19:17)
    at Object.processMessage (/usr/src/app/lib/plugins/pagexray/index.js:76:30)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
[2018-07-01 08:15:18] ERROR: TypeError: Cannot read property 'image' of undefined
    at module.exports (/usr/src/app/lib/plugins/html/setup/summaryBoxes.js:111:28)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:73:26)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:199:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by soulgalore** [comment]
Thanks @primehaxor for opening the issue! Hopefully this will be fixed by https://github.com/sitespeedio/sitespeed.io/pull/2096

**Comment by soulgalore** [comment]
Fixed on our side I mean, the original issue will still be there in Firefox.

**Comment by soulgalore** [comment]
@primehaxor this should be fixed in 7.2.1, let me know if you have time to upgrade and if you still see it.
Best
Peter

**Comment by primehaxor** [comment]
Hello, @soulgalore I leave it running for 2 hours and I didn't see any problem related to this issue.
But now I'm seeing this one.

```
[2018-07-20 09:52:33] INFO: Versions OS: linux 4.9.87-linuxkit-aufs nodejs: v8.11.1 sitespeed.io: 7.2.1 browsertime: 3.2.1 coach: 2.0.6
[2018-07-20 09:52:34] INFO: Starting firefox for analysing https://www.mysite.com 3 time(s)
[2018-07-20 09:52:34] INFO: Testing url https://www.mysite.com iteration 1
[2018-07-20 09:52:43] ERROR: UrlLoadError: Failed to load/verify https://www.mysite.com uri:data:text/html;charset=utf-8,
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:194:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
`[2018-07-20 09:32:31] WARN: Non-finite number 'NaN' found at path 'contentSize' for 'pagexray.pageSummary' message (url = undefined)
`
During the test time i saw this error two times

**Comment by soulgalore** [comment]
Hi @primehaxor it's unrelated, but I've seen the error myself, I'll create an issue in Browsertime tonight and ping you in the issue. I think there could be a timeout issue on our side when we run on a too small instance but I'm not 100% sure, let me look into it.

Best
Peter

**Comment by soulgalore** [comment]
@primehaxor pushed a fix for https://github.com/sitespeedio/sitespeed.io/issues/2097#issuecomment-406567113 in 7.2.2. Closing this since the original issue seems fixed, but please ping https://github.com/sitespeedio/browsertime/issues/622 if you still see the new problem.

Best
Peter
