### ISSUE TITLE
sitespeed.io ERROR: ElementNotVisibleError: element not visible: Element is not currently visible and may not be manipulated

### ISSUE THREAD

**Issue by mdasifazhar** [sitespeedio/sitespeed.io#2105]
Hi I'm new to sitespeed and trying to run prescript .
Which actually select the value from the drop down and click on submit button. I've tested on my local windows machine using chrome driver and its able to identify the xpath.
Sample Code:-
--------------------------------------------------
System.setProperty("webdriver.chrome.driver", driverPath + "chromedriver.exe");
ChromeOptions chromeOptions = new ChromeOptions();
driver = new ChromeDriver(chromeOptions);
driver.navigate().to("my_application_url");
/*drop down selection*/
driver.findElement(By.xpath("//select[@class='form-control wag-form-control wag-change-store-input wag-srx-choose-address statelist statelist-desk mr10']//option[2]")).click();
/*button click*/
driver.findElement(By.xpath("//*[@id='test']/div[2]/button")).click();
--------------------------------------------------
When I tried on OS: linux 4.15.0-1014-azure nodejs: v8.9.4 sitespeed.io: 7.0.0 browsertime: 3.0.13 coach: 2.0.2 with headless browser I'm getting the below error.
ERROR: ElementNotVisibleError: element not visible: Element is not currently visible and may not be manipulated.

**here is my configuration:-**
{
	"browsertime": {
	"iterations": 2,
	"browser": "chrome",
	"visualMetrics" : true,
	"connectivity" :{
		"profile" : "3gfast"
		}
	},
	"xvfb": true,
	"chrome": {
			"args": [
				"no-sandbox"
			]
		},
	"html": {
		"showAllWaterfallSummary": true
	},
	"outputFolder": "test/performance/reports",
	"mobile": true,
	"budget": {
		"configPath": "test/performance/budget.json",
		"output": "tap"
	},
	"utc": true
}

**Commnad**:-
/usr/src/app/bin/sitespeed.js --config=test/performance/config.json my_app_url

What could be possible reason to fail? 
How can I fix?

Plz let me know if any further information is needed from my side

**Comment by soulgalore** [comment]
Hi @mdasifazhar just want to verify that you checked the [example code](https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#login-example) for logging in to Wikipedia?

When I debug I add things [to the log](https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/#debuglog-from-your-script) from the Selenium script and try to verify step by step that I select the right element, so I can see that everything works as expected.

Let me update the documentation tonight to make it a little bit cleaner ( I see that we missed what is actually passed in the context to the prescript today): https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/ 

Best
Peter

**Comment by mdasifazhar** [comment]
Hi @soulgalore 
I'm following the same here is my node module and prescript.
I'm still getting the same error.


**command**
/usr/src/app/bin/sitespeed.js --preScript test/performance/myScript.js  
--config=test/performance/config.json my_application_url

**myScrupt.js:**
-----------------------------------------------------------------------
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('my_application_url')
        .then(() => {
          var webdriver = context.webdriver;
          var until = webdriver.until;
          var By = webdriver.By;
         var sel=driver.findElement(webdriver.By.xpath("//select[@class='form-control wag-form-control 
                  wag-change-store-input wag-srx-choose-address statelist statelist-desk mr10']//option[2]"));
		  sel.click();	  
var goButton=driver.findElement(webdriver.By.xpath("//*[@id='medicaid_newplan']/div[2]/button"));
		  goButton.click();
		
		  driver.sleep(5000);
          return driver.wait(until.elementLocated(webdriver.By.id("//section/p[@class='m0 mb20 result-heading wag-hn-lt-55roman']")), 3000);
        });
    })
  }
};
-----------------------------------------------------------------------

**config:-**
-----------------------------------------------------------------------
{
	"browsertime": {
	"iterations": 2,
	"browser": "chrome",
	"visualMetrics" : true,
	"connectivity" :{
		"profile" : "3gfast"
		}
	},
	"xvfb": true,
	"chrome": {
			"args": [
				"no-sandbox"
			]
		},
	"html": {
		"showAllWaterfallSummary": true
	},
	"outputFolder": "test/performance/reports",
	"mobile": true,
	"budget": {
		"configPath": "test/performance/budget.json",
		"output": "tap"
	},
	"utc": true
}

**Comment by soulgalore** [comment]
Hi @mdasifazhar I think the best way is to:
* log what you get back from Selenium (verify that each findElement works)
* Record a video of the full run (including your pre script). Do that by adding `--browsertime.videoParams.combine` and then check your video: is the page(s) loading as they should?

Best
Peter

**Comment by mdasifazhar** [comment]
Hi @soulgalore 

I've tried after enabling capture video option for prescript, found video did not get captured. 
	"videoParams": {
		"combine": true
		}
	},.

I can see logger info and tried printing the WebElement content. pasted below for the ref..


[2018-07-22 02:00:12] INFO: Versions OS: linux 4.15.0-1014-azure nodejs: v8.9.4 sitespeed.io: 7.0.0 browsertime: 3.0.13 coach: 2.0.2
[2018-07-22 02:00:12] INFO: Starting chrome for analysing https://dotcom-acs-dev.walgreens.com/medicaid/v1/pharmacy/medicaid 2 time(s)
[2018-07-22 02:00:12] INFO: Testing url https://dotcom-acs-dev.walgreens.com/medicaid/v1/pharmacy/medicaid iteration 1

**Logger Info**
**[2018-07-22 02:00:14] INFO: page got refresh**
**[2018-07-22 02:00:14] INFO: find drop down select**
**Printing WebElement Object**
[2018-07-22 02:00:14] INFO: {"driver_":{"flow_":{"propagateUnhandledRejections_":true,"activeQueue_":{"name_":"TaskQueue::130","flow_":"[Circular]","tasks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":{"flow_":"[Circular]","stack_":null,"parent_":null,"callbacks_":null,"state_":"fulfilled","handled_":true,"value_":"3cb221842ae94ddd7724090ce9e83b4f","queue_":{"name_":"TaskQueue::14","flow_":"[Circular]","tasks_":[],"interrupts_":null,"pending_":null,"subQ_":null,"state_":"finished","unhandledRejections_":{}}},"callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":false},"[Circular]",{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.navigate().refresh()","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.sleep(5000)","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":false},"[Circular]",{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.findElement(By(xpath, //select[@class='form-control wag-form-control wag-change-store-input wag-srx-choose-address statelist statelist-desk mr10']//option[2]))","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.sleep(15000)","queue":"[Circular]","userTask_":true,"blocked":false}],"interrupts_":null,"pending_":null,"subQ_":null,"state_":"new","unhandledRejections_":{}},"taskQueues_":{},"shutdownTask_":null,"hold_":{"_called":false,"_idleTimeout":2147483647,"_idlePrev":{"_idleNext":"[Circular]","_idlePrev":"[Circular]","_timer":{"_list":"[Circular]"},"_unrefed":false,"msecs":2147483647,"nextTick":false},"_idleNext":"[Circular]","_idleStart":3120,"_repeat":2147483647,"_destroyed":false}},"session_":"[Circular]","executor_":{"w3c":false,"customCommands_":{},"log_":{"name_":"webdriver.http.Executor","level_":null,"parent_":{"name_":"webdriver.http","level_":null,"parent_":{"name_":"webdriver","level_":null,"parent_":{"name_":"","level_":{"name_":"OFF","value_":null},"parent_":null,"handlers_":null},"handlers_":null},"handlers_":null},"handlers_":null}},"fileDetector_":null},"id_":{"flow_":"[Circular]","stack_":null,"parent_":null,"callbacks_":null,"state_":"fulfilled","handled_":false,"value_":"unused","queue_":"[Circular]"}}
[2018-07-22 02:00:14] INFO: {"flow_":{"propagateUnhandledRejections_":true,"activeQueue_":{"name_":"TaskQueue::130","flow_":"[Circular]","tasks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":{"flow_":"[Circular]","stack_":null,"parent_":null,"callbacks_":null,"state_":"fulfilled","handled_":true,"value_":"3cb221842ae94ddd7724090ce9e83b4f","queue_":{"name_":"TaskQueue::14","flow_":"[Circular]","tasks_":[],"interrupts_":null,"pending_":null,"subQ_":null,"state_":"finished","unhandledRejections_":{}}},"callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":false},"[Circular]",{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.navigate().refresh()","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.sleep(5000)","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":false},"[Circular]",{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"WebDriver.findElement(By(xpath, //select[@class='form-control wag-form-control wag-change-store-input wag-srx-choose-address statelist statelist-desk mr10']//option[2]))","queue":"[Circular]","userTask_":true,"blocked":false},{"promise":{"flow_":"[Circular]","stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"WebDriver.sleep(15000)","queue":"[Circular]","userTask_":true,"blocked":false},"[Circular]","[Circular]",{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":[{"promise":{"flow_":"[Circular]","stack_":null,"parent_":"[Circular]","callbacks_":null,"state_":"pending","handled_":false,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":true}],"state_":"pending","handled_":true,"queue_":null},"description":"then","queue":"[Circular]","userTask_":false,"blocked":false},"[Circular]",{"promise":"[Circular]","description":"WebElement.getText()","queue":"[Circular]","userTask_":true,"blocked":false}],"interrupts_":null,"pending_":null,"subQ_":null,"state_":"new","unhandledRejections_":{}},"taskQueues_":{},"shutdownTask_":null,"hold_":{"_called":false,"_idleTimeout":2147483647,"_idlePrev":{"_idleNext":"[Circular]","_idlePrev":"[Circular]","_timer":{"_list":"[Circular]"},"_unrefed":false,"msecs":2147483647,"nextTick":false},"_idleNext":"[Circular]","_idleStart":3120,"_repeat":2147483647,"_destroyed":false}},"stack_":{"name":"Task"},"parent_":null,"callbacks_":null,"state_":"pending","handled_":false,"queue_":null}
**[2018-07-22 02:00:37] ERROR: ElementNotVisibleError: element not visible: Element is not currently visible and may not be manipulated**
  (Session info: chrome=66.0.3359.33)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1014-azure x86_64)
  (Session info: chrome=66.0.3359.33)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-1014-azure x86_64)
    at Object.checkLegacyResponse (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebElement.click()
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElementPromise.schedule_ (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElementPromise.click (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
    at driver.get.then (/home/jenkins/workspace/medicaid/medicaid-ui-perf-test-feature/medicaid/test/performance/medicaidPlan.js:26:17)
    at ManagedPromise.invokeCallback_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/src/app/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /usr/src/app/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-07-22 02:00:37] INFO: Testing url https://dotcom-acs-dev.walgreens.com/medicaid/v1/pharmacy/medicaid iteration 2

Regards
Md Asif Azhar

**Comment by soulgalore** [comment]
Hi @mdasifazhar ah maybe I missed that you don't run video on by default? The setting also need to be in the browsertime context: `--browsertime.videoParams.combine` in your config file that corresponds to something like this:
```
"browsertime": {
  "videoParams": {
    "combine": true
   },
  "video": true
}
```

The logging from Selenium was more for your help :) If there's problem getting the right element, the Selenium slack channel och Selenium forums is the best place for Selenium questions. But before that it's always best to verify that the page loads and that everything looks right (by looking at the video). Hope that helps!
Peter

**Comment by soulgalore** [comment]
I see, the best there is to try to look into each step and see what could be wrong. We stay out of Selenium since there hopefully is a big community that can help, but what's weird is that it works for you standalone right but not in sitespeed.io, that's why I suspected the page wasn't loading correctly.

**Comment by mdasifazhar** [comment]
could it be an issue of headlesss browser for ElementNotVisibleError?

**Comment by mdasifazhar** [comment]
@soulgalore ,
Thank you for your support and guideline.
I'm closing the discussion as its not the issue with sitespeed.
I'm working with selenium team to get this fix.
Regards
