### ISSUE TITLE
Error on pageCompleteCheck

### ISSUE THREAD

**Issue by scabenga** [sitespeedio/sitespeed.io#2115]
Hi Guys,

I wonder if you can assist with this, i'm using the following code to stop a test:

`--browsertime.pageCompleteCheck "return (((Date).getTime() - window.performance.timing.loadEventEnd > 3000 ) && (document.getElementsByClassName("logo").length == 0 ))"`

The idea here is that it will return true once both conditions are met.

However i'm receiving the following error:

`TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at module.exports (/usr/src/app/lib/core/resultsStorage/index.js:32:28)
    at Object.run (/usr/src/app/lib/sitespeed.js:52:44)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

Any assistance would be greatly appreciated.

Thank you

**Comment by soulgalore** [comment]
Hi @scabenga best way to debug is to add the verbose flag, then you can check if all params in to sitespeed.io looks ok (all options will be in the log). You can add `-vv` and then you will get something like this in the log: ` ... VERBOSE: [sitespeedio] Config options ...`  with all the options logged.

In your case the the CLI handling doesn't understand when your string ends since you also use " inside of your JavaScript. I think this will fix your original problem but you might wanna finetune your script:
` "return (((Date).getTime() - window.performance.timing.loadEventEnd > 3000 ) && (document.getElementsByClassName('logo').length == 0 ))"`

Best
Peter

**Comment by scabenga** [comment]
Hi @soulgalore, many thanks for your reply.

I am using the verbose tag, however it errors right away.

`docker run --shm-size=1g --rm -v /Users/xxx/:/sitespeed.io sitespeedio/sitespeedio sitespeed.io/urls-1.txt --browsertime.viewPort 960x640 --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1" -n 1  --html.showAllWaterfallSummary true --video --har --browsertime.timeouts.pageLoad 60000 --browsertime.pageCompleteCheck "return (((Date).getTime() - window.performance.timing.loadEventEnd > 3000 ) && (document.getElementsByClassName('logo').length == 0 ))" --plugins.remove coach -vv
Google Chrome 66.0.3359.170 
Mozilla Firefox 61.0
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at module.exports (/usr/src/app/lib/core/resultsStorage/index.js:32:28)
    at Object.run (/usr/src/app/lib/sitespeed.js:52:44)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by soulgalore** [comment]
So what did you see in the log where the *Config options* does the pageCompleteCheck look like how you configure it?

For me this works (except that the JavaScript that you configured for the complete check gives errors:
`docker run --shm-size=1g --rm sitespeedio/sitespeed.io:7.3.0 https://www.sitespeed.io --browsertime.viewPort 960x640 --browsertime.userAgent "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0 like Mac OS X) AppleWebKit/602.1.38 (KHTML, like Gecko) Version/10.0 Mobile/14A5297c Safari/602.1" -n 1  --html.showAllWaterfallSummary true --video --har --browsertime.timeouts.pageLoad 60000 --browsertime.pageCompleteCheck "return (((Date).getTime() - window.performance.timing.loadEventEnd > 3000 ) && (document.getElementsByClassName('logo').length == 0 ))" --plugins.remove coach -vv
`
```
....
[2018-07-26 07:28:52] ERROR: [root] Could not load URLWebDriverError: unknown error: Date.getTime is not a function
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.87-linuxkit-aufs x86_64)
[2018-07-26 07:28:52] ERROR: [root] UrlLoadError: Failed to load https://www.sitespeed.io
....

```

**Comment by scabenga** [comment]
Thanks @soulgalore, i've resolved my issues and it is working as expected.

Apologies for waisting time.

**Comment by soulgalore** [comment]
Np, great that it worked out!
