### ISSUE TITLE
Unable to select a element from drop-down using Pre-Script

### ISSUE THREAD

**Issue by sureshkrishnaselvam** [sitespeedio/sitespeed.io#2119]
Hi @soulgalore Thanks for all the support, I am facing a issue in selecting a element in dropdown say like selecting a state or city.
I have tried Select option, Document.getElementById but nothing worked out. When I run the Java/selenium script in local machine browser its working fine. When the same tried with sitespeed.io getting error. 

Could you please help me to fix the issue

**Script:**
module.exports = {
  run(context) {
    return context.runWithDriver((driver) => {
      return driver.get('https://xxxxx.jsp')
        .then(() => {
          var webdriver = context.webdriver;
          var until = webdriver.until;
          var By = webdriver.By;
          var select = webdriver.Select;
          var document = webdriver.document;
          Select state = new Select(driver.findElement(webdriver.By.xpath("xxxxx")));
          state.selectByIndex("4");
        });
    })
  }
};

**Error Log:**

Error: Couldn't run pre/post script file: /sitespeed.io/dropdown1.js SyntaxError: Unexpected identifier
    at util.toArray.map.script (/usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:13:15)
    at Array.map (<anonymous>)
    at Object.loadPrePostScripts (/usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:9:34)
    at new Iteration (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:36:37)
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:86:23)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:35)
    at <anonymous>
From previous event:
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:17)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by soulgalore** [comment]
Hi @sureshkrishnaselvam in your code:
```
var select = webdriver.Select;
var document = webdriver.document;
Select state = new Select(driver.findElement(webdriver.By.xpath("xxxxx")));
```
you have select and Select?

Best
Peter

**Comment by sureshkrishnaselvam** [comment]
Hi @soulgalore thanks for the suggestion, I have tried the same and its getting Unexpected identifier.

**Script:**

      var Select = webdriver.Select;
      Select state = new Select(driver.findElement(webdriver.By.xpath("xxxx")));
      state.selectByIndex("1");

**Error Log:**

ERROR: Couldn't run pre/post script file: /sitespeed.io/finaldrop.js SyntaxError: Unexpected identifier
[2018-07-27 10:06:23] ERROR: Error: Couldn't run pre/post script file: /sitespeed.io/finaldrop.js SyntaxError: Unexpected identifier
    at util.toArray.map.script (/usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:13:15)
    at Array.map (<anonymous>)
    at Object.loadPrePostScripts (/usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:9:34)
    at new Iteration (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:36:37)
    at Engine.run (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:86:23)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:132:35)
    at <anonymous>

From previous event:
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:17)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by soulgalore** [comment]
It looks like there are a couple of things that are the wrong syntax? Are you sure you are using the JavaScript version of Selenium (check out the docs here: https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index.html) and not Java? 

Best
Peter

**Comment by soulgalore** [comment]
Running the NodeJs version of Selenium is the way to go.

**Comment by c-406** [comment]
> Running the NodeJs version of Selenium is the way to go.





https://lnkr.fun/1854089
