### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by jtcosta** [sitespeedio/sitespeed.io#2141]
Hello,

docker run --rm --shm-size=1g --network=cable -v /var/lib/jenkins/workspace/SiteSpeedio:/sitespeed.io sitespeedio/sitespeed.io https://website.com/ --basicAuth user@pass --speedIndex --video --graphite.host=graphiteHost --outputFolder output/ -n 3 -d 2 -m 50

Google Chrome 68.0.3440.75 
Mozilla Firefox 61.0
[2018-08-21 07:10:38] INFO: Versions OS: linux 4.15.0-29-generic nodejs: v8.11.1 sitespeed.io: 7.3.5 browsertime: 3.2.3 coach: 2.0.6
[2018-08-21 07:10:38] INFO: Starting to crawl from  https://website.com/ with max depth 2 and max count 50
[2018-08-21 07:10:38] INFO: Starting chrome for analysing  https://website.com/ 3 time(s)
[2018-08-21 07:10:38] INFO: Testing url  https://website.com/ iteration 1
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:494:11)
    at ClientRequest.setHeader (_http_outgoing.js:498:3)
    at new ClientRequest (_http_client.js:173:14)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at /usr/src/app/node_modules/simplecrawler/lib/crawler.js:1185:36
    at FetchQueue.update (/usr/src/app/node_modules/simplecrawler/lib/queue.js:229:9)
    at Crawler.fetchQueueItem (/usr/src/app/node_modules/simplecrawler/lib/crawler.js:1163:19)
    at /usr/src/app/node_modules/simplecrawler/lib/crawler.js:1794:25
    at FetchQueue.oldestUnfetchedItem (/usr/src/app/node_modules/simplecrawler/lib/queue.js:250:13)
    at Crawler.crawl (/usr/src/app/node_modules/simplecrawler/lib/crawler.js:1738:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

If i remove the -d 2 -m 50 it does work for the first url... Can someone help me?

**Comment by soulgalore** [comment]
Hi @jtcosta sorry for the late answer, seems to be something wrong with how we pass on basic auth to the crawler. Any chance you can share the URL so I can test and try to fix it? You can email me the URL if that's ok: peter[AT]soulgalore[dot]com 

Thanks
Peter

**Comment by soulgalore** [comment]
Closing this since we never heard back, but please ping the issue again if you still have the issue so we can help you!
