### ISSUE TITLE
Performance report is broken with sitespeed.io v7.5.x

### ISSUE THREAD

**Issue by skhilko** [sitespeedio/sitespeed.io#2180]
The new sitespeed.io v7.5.x is not working for me.

I use `sitespeedio/sitespeed.io:7.5.1` docker container.

Configuration file:
```
{
  "firstParty": ".xxx.com",
  "preScript": "/sitespeed.io/login.js",
  "postScript": "/sitespeed.io/logout.js",
  "browsertime": {
    "iterations": 10,
    "viewPort": "1400x1024"
  }
}
```

## Error
Getting this error at the end of the execution. The report file is broken.
```
ERROR: TypeError: Cannot read property 'response' of undefined
    at Object.getDocumentRequests (/usr/src/app/node_modules/pagexray/lib/util.js:117:20)
    at entries.forEach.entry (/usr/src/app/node_modules/pagexray/lib/index.js:96:31)
    at Array.forEach (<anonymous>)
    at Object.convert (/usr/src/app/node_modules/pagexray/lib/index.js:94:13)
    at Promise.resolve.then.harJson (/usr/src/app/node_modules/webcoach/lib/index.js:28:14)
From previous event:
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:17)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by soulgalore** [comment]
Hi @skhilko 
it looks like it's content related (=something on the URL that breaks), any chance you can show me which URL that gives the error? It's super helpful for us if you can make the bug reproducible see https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

I can see from the stack trace that it's a redirect that somehow causes the problem but it would if I can reproduce, or if you can share the HAR file from the run (then I can reproduce it).

Best
Peter
