### ISSUE TITLE
Not working on fresh ubuntu

### ISSUE THREAD

**Issue by marty90** [sitespeedio/sitespeed.io#2183]
Hi, just installed sitespeedio with npm.
I have Ubuntu 16.04.5 LTS
Nodejs v8.12.0

I get the following error:
```
sleep: using busy loop fallback
module.js:550
    throw err;
    ^

Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/martino/Desktop/adb/sitespeed.io/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/martino/Desktop/adb/sitespeed.io/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/martino/Desktop/adb/sitespeed.io/node_modules/browsertime/lib/screenshot/index.js:3:15)
    at Module._compile (module.js:653:30)
```

**Comment by soulgalore** [comment]
Hi @marty90 I wonder if this could be a temporary glitch in npm (seen that before)? Did you see anything more when you run `npm install`? Any chance you can try again?

Best
Peter

**Comment by marty90** [comment]
Hi,
tried again on a different machine and I get the same output :(
Installed with:
```
sudo npm install -g browsertime
```

**Comment by soulgalore** [comment]
Hi @marty90 let me try on AWS. I usually always use the Docker container (and haven't seen that failed when we create it). 

Do you get an error for that module (sharp) when you run npm install?

Best
Peter

**Comment by marty90** [comment]
Running without sudo made it work.
Thank You

**Comment by soulgalore** [comment]
This worked so let us close it.
