### ISSUE TITLE
visualmetrics.py fails

### ISSUE THREAD

**Issue by marty90** [sitespeedio/sitespeed.io#2199]
Hi,
I'm running browsertime (updated version from `git`) on Ubuntu 16, and collecting data from an Android emulated phone. The test works fine, but it fails in calculating visual metrics.
My command line `browsertime/bin/browsertime.js --visualMetrics -n 1 --chrome.android.package com.android.chrome https://www.repubblica.it`

And my output:
```
[2018-11-02 12:43:08] INFO: Running chrome for url: https://www.repubblica.it
[2018-11-02 12:43:08] INFO: Testing url https://www.repubblica.it iteration 1
[2018-11-02 12:43:29] INFO: Converting video to 30 fps
[2018-11-02 12:43:41] ERROR: Error: Command failed: /home/martino/Bureau/mobile_tests/qoe_att/browsertime/vendor/visualmetrics.py --dir /home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/images/1 --video /home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --startwhite -q 75
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:09.97, start: 0.000000, bitrate: 391 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 387 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, image2, to '/home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/images/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    Stream #0:0(eng): Video: png, rgb24, 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 png
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A    
video:45kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown


ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:09.97, start: 0.000000, bitrate: 391 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1080x1920 [SAR 1:1 DAR 9:16], 387 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, image2, to '/home/martino/Bureau/mobile_tests/qoe_att/browsertime-results/www.repubblica.it/2018-11-02T124307+0100/video/images/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    Stream #0:0(eng): Video: png, rgb24, 1080x1920 [SAR 1:1 DAR 9:16], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 png
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A    
video:45kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown


    at makeError (/home/martino/Bureau/mobile_tests/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/martino/Bureau/mobile_tests/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-11-02 12:43:41] INFO: 139 requests, 1280.71 kb, backEndTime: 327ms, firstPaint: 1.56s, DOMContentLoaded: 1.83s, Load: 6.66s, rumSpeedIndex: 1711
[2018-11-02 12:43:41] INFO: Wrote data to browsertime-results/www.repubblica.it/2018-11-02T124307+0100
```

The output generated, including the video:
[2018-11-02T124307+0100.zip](https://github.com/sitespeedio/sitespeed.io/files/2542294/2018-11-02T124307%2B0100.zip)

**Comment by soulgalore** [comment]
Hi @marty90 thanks for creating the issue!

Can you make one more run and add `--videoParams.keepOriginalVideo ` then the original video from the phone is kept, and I can use that to recreate the issue with visual metrics (and create an upstream issue).

Thanks
Peter
