### ISSUE TITLE
selenium.url doesn't work

### ISSUE THREAD

**Issue by chrischjh** [sitespeedio/sitespeed.io#2204]
Hi, I'm trying out the sitespeed.io with Docker in my Windows 10 PC, I'm using version 7.7.2 pulled from dockerhub, as I need to run the browser in Windows env thus bring up a selenium standalone server in my local, and configured with "selenium.url", but got error when try to run a test, Here's my config.json:

```
{
    "browsertime": {
        "iterations": 1,
        "browser": "firefox",
        "selenium.url": "http://146.222.43.200:4444/wd/hub"
    },
    "graphite": {
        "host": "graphite"
    },
    "html": {
        "showAllWaterfallSummary": true,
        "logDownloadLink": true
    },
    "verbose": true,
    "utc": true
}
```

Error message:

```
PS D:\sitespeed> docker-compose run --rm sitespeed.io --config /sitespeed.io/config.json https://www.google.com
Google Chrome 70.0.3538.67
Mozilla Firefox 63.0
[2018-11-13 08:55:08] INFO: [sitespeedio] Versions OS: linux 4.9.93-linuxkit-aufs nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2018-11-13 08:55:09] DEBUG: [sitespeedio.plugin.graphite] Setting up Graphite graphite:2003 for namespace sitespeed_io.default
[2018-11-13 08:55:09] INFO: [sitespeedio.plugin.browsertime] Starting firefox for analysing https://www.google.com 1 time(s)
[2018-11-13 08:55:09] INFO: [browsertime] Testing url https://www.google.com iteration 1
[2018-11-13 08:55:10] INFO: [browsertime] Browser failed to start, trying one more time: Failed to start browser /usr/local/bin/firefox: no such file or directory
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'CHENCH3-W10', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: driver.version: unknown
remote stacktrace:
[2018-11-13 08:55:12] INFO: [browsertime] Browser failed to start, trying one more time: Failed to start browser /usr/local/bin/firefox: no such file or directory
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'CHENCH3-W10', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: driver.version: unknown
remote stacktrace:
[2018-11-13 08:55:13] INFO: [browsertime] Browser failed to start, trying one more time: Failed to start browser /usr/local/bin/firefox: no such file or directory
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'CHENCH3-W10', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: driver.version: unknown
remote stacktrace:
[2018-11-13 08:55:13] ERROR: [browsertime] BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-11-13 08:55:13] WARN: [browsertime] BrowserError: Failed to take screenshot
    at SeleniumRunner.takeScreenshot (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:224:13)
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:197:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-11-13 08:55:13] DEBUG: [browsertime] Kill all processes ffmpeg
[2018-11-13 08:55:13] INFO: [browsertime] 0
```

**Comment by soulgalore** [comment]
Hi @chrischjh 
could it be a miss match between Firefox and Geckodriver? What version of Firefox are you using on the hub?

If you use a Selenium hub you need to turn off the video. FFMPEG runs on the local computer, so that will not work.

Best
Peter

**Comment by chrischjh** [comment]
hi @soulgalore , thanks for your reply. I further digged more, here are some findings:

1. It donesn't look like a Geckodriver and Firefox mismatch issue since it works when I direcitly run webdriver tests with the same Selenium hub
2. The same sitespeed setting can drive Chrome behind the Selenium hub without problem
3. In the error message output by sitespeed, it prompts that "Failed to start browser /usr/local/bin/firefox: no such file or directory", this is a Linux path and likely not returned by my Selenium hub on Windows 10

PS: 
Selenium Hub: selenium-server-standalone-3.141.5.jar
Firefox: 60.2.0esr (32-bit)

**Comment by soulgalore** [comment]
Aha ok lets see then. I've checked the code and Chrome and Firefox setup the webdriver URL on the same place, so if it works for Chrome it should be the same for Firefox.

For Firefox we set the binary here:
https://github.com/sitespeedio/browsertime/blob/master/lib/firefox/webdriver/index.js#L102-L117

I wonder if it could wrong there or if we shouldn't set the binary at all if we use a selenium.url? Do you have time to check webdriver/Selenium docs and see what's right?

Best
Peter

**Comment by chrischjh** [comment]
@soulgalore I overwrite the binary path in config and works now

```
"browsertime": {
        "browser": "firefox",
        "selenium.url": "http://chench3-w10:4444/wd/hub",
        "firefox.binaryPath": "C:/Program Files (x86)/Mozilla Firefox/firefox.exe"
    }
```
But got another error, I'm using Firefox `60.2.0esr (32-bit)`
```
ERROR: [browsertime.firefox] Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
```

**Comment by soulgalore** [comment]
Closing but please let us know if latest Firefox doesn't work.
