### ISSUE TITLE
docker-compose run vs docker run 

### ISSUE THREAD

**Issue by balajir2016** [sitespeedio/sitespeed.io#2231]
I followed the steps on your website to setup docker and configure sitespeed, graphite and grafana. The base setup works like a charm.

The below command works and I see relevant grafana dashboard:
docker-compose run sitespeed.io https://www.botanics.co.uk/-n=15 --graphite.host=graphite 

But when I try to run the command using docker run it does not work.

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://www.botanics.co.uk/about-us  -n 1 --graphite.host=graphite

Error I see is as below:

[2018-12-13 12:12:57] ERROR: Error: getaddrinfo ENOTFOUND graphite graphite:2003
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
From previous event:
    at GraphiteSender.bulk (/usr/src/app/lib/plugins/graphite/graphite-sender.js:15:12)
    at GraphiteSender.send (/usr/src/app/lib/plugins/graphite/sender.js:23:50)
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:92:26)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Socket.Readable.on (_stream_readable.js:772:35)
    at Promise (/usr/src/app/lib/plugins/graphite/graphite-sender.js:25:14)
    at GraphiteSender.bulk (/usr/src/app/lib/plugins/graphite/graphite-sender.js:15:12)
    at GraphiteSender.send (/usr/src/app/lib/plugins/graphite/sender.js:23:50)
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:92:26)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:208:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
[2018-12-13 12:12:59] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.botanics.co.uk/2018-12-13-12-12-39

Question : How do I expose graphite host which is a docker container to my host so that I can write to the graphite db.

I am using docker on mac Version 2.0.0.0-mac81 (29211), docker engine: 18.09.0

**Comment by soulgalore** [comment]
Hi @balajir2016 if you wanna run to collect metrics for usage where the metrics is important, you should separate sitespeed.io and Graphite/Grafana https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#setup-important

Meaning you need to use _docker run_ and then use host/ip when you send the metrics. On your local for testing you can use compose. Else if you wanna use the run, use your local IP.

Best
Peter

**Comment by balajir2016** [comment]
Awesome, your solution worked. Thanks Peter for swift reply.
