### ISSUE TITLE
Output folder syntax is not clear. I am getting exceptions.

### ISSUE THREAD

**Issue by balajir2016** [sitespeedio/sitespeed.io#2232]
Hi Peter,

Good Day !! Thanks for addressing my issue yesterday very swiftly. I am running into another issue today with regards to output folder. I am getting an exception when I follow the syntax mentioned in the documentation. I am getting a "Couldn't find url file at ${filePath}". Please see below. I am not sure what URL path is being sought here ? Please help.

CHMB105416:~ balaji_rama$ cd sspeed/
CHMB105416:sspeed balaji_rama$ ls
mytest
CHMB105416:sspeed balaji_rama$ ls -al
total 0
drwxr-xr-x   3 balaji_rama  PHOTONINT\Domain Users    96 Dec 14 17:34 .
drwxr-xr-x+ 71 balaji_rama  PHOTONINT\Domain Users  2272 Dec 14 17:26 ..
drwxr-xr-x   2 balaji_rama  PHOTONINT\Domain Users    64 Dec 14 17:34 mytest
CHMB105416:sspeed balaji_rama$ cd
CHMB105416:~ balaji_rama$ docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --outputFolder /Users/balaji_rama/sspeed "mytest" https://www.sitespeed.io/
Google Chrome 70.0.3538.67 
Mozilla Firefox 63.0

/usr/src/app/lib/cli/util.js:33
            throw new Error(`Couldn't find url file at ${filePath}`);
                  ^
Error: Couldn't find url file at /sitespeed.io/mytest
    at Object.getURLs (/usr/src/app/lib/cli/util.js:33:19)
    at Object.parseCommandLine (/usr/src/app/lib/cli/cli.js:986:19)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:22:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
CHMB105416:~ balaji_rama$

When use the syntax as below. I **removed** "mytest" argument, the error is gone, but **nothing** gets stored in the output folder.

CHMB105416:~ balaji_rama$ docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --outputFolder /Users/balaji_rama/sspeed  https://www.sitespeed.io/
Google Chrome 70.0.3538.67 
Mozilla Firefox 63.0
[2018-12-14 12:17:05] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2018-12-14 12:17:06] INFO: Starting chrome for analysing https://www.sitespeed.io/ 3 time(s)
[2018-12-14 12:17:06] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2018-12-14 12:17:15] INFO: BackEndTime: 243 DomInteractiveTime: 303 DomContentLoadedTime: 303 FirstPaint: 444 PageLoadTime: 463
[2018-12-14 12:17:15] INFO: VisualMetrics FirstVisualChange: 500 SpeedIndex: 500 PerceptualSpeedIndex: 500 LastVisualChange: 500
[2018-12-14 12:17:15] INFO: Testing url https://www.sitespeed.io/ iteration 2
[2018-12-14 12:17:23] INFO: BackEndTime: 172 DomInteractiveTime: 205 DomContentLoadedTime: 205 FirstPaint: 349 PageLoadTime: 356
[2018-12-14 12:17:23] INFO: VisualMetrics FirstVisualChange: 334 SpeedIndex: 340 PerceptualSpeedIndex: 340 LastVisualChange: 367
[2018-12-14 12:17:23] INFO: Testing url https://www.sitespeed.io/ iteration 3
[2018-12-14 12:17:31] INFO: BackEndTime: 157 DomInteractiveTime: 213 DomContentLoadedTime: 213 FirstPaint: 349 PageLoadTime: 367
[2018-12-14 12:17:31] INFO: VisualMetrics FirstVisualChange: 400 SpeedIndex: 400 PerceptualSpeedIndex: 400 LastVisualChange: 400
[2018-12-14 12:17:31] INFO: 9 requests, 130.12 kb, backEndTime: 191ms (±21.66ms), firstPaint: 381ms (±25.86ms), firstVisualChange: 411ms (±39.40ms), DOMContentLoaded: 240ms (±25.65ms), Load: 395ms (±27.75ms), speedIndex: 413 (±38.10), visualComplete85: 422ms (±32.65ms), lastVisualChange: 422ms (±32.65ms), rumSpeedIndex: 381 (±25.86) (3 runs)
[2018-12-14 12:17:33] INFO: HTML stored in /Users/balaji_rama/sspeed
[2018-12-14 12:17:33] INFO: Finished analysing https://www.sitespeed.io/
CHMB105416:~ balaji_rama$ cd sspeed/
CHMB105416:sspeed balaji_rama$ ls -al
total 0
drwxr-xr-x   2 balaji_rama  PHOTONINT\Domain Users    64 Dec 14 17:40 .
drwxr-xr-x+ 71 balaji_rama  PHOTONINT\Domain Users  2272 Dec 14 17:26 ..
CHMB105416:sspeed balaji_rama$ pwd
/Users/balaji_rama/sspeed

**Comment by balajir2016** [comment]
Thanks for patiently explaining Peter. Totally appreciate your support.
