### ISSUE TITLE
Video recording throws error when using Firefox

### ISSUE THREAD

**Issue by csvn** [sitespeedio/sitespeed.io#2234]
Yesterday, our performance job in the CI was working. Today when we merged to `master`, the performance test in Firefox threw an error that made the job fail. No changes since yesterday that should affect this job, and as far as I can see the docker `latest` image for sitespeed.io has not been updated in two months.

The commands below were ran on my local machine (Windows 10). If I add `--video false` to the command, it finishes without errors. Our CI that got the initial error runs on Google cloud Kubernetes, and got the same error (as afar as I could see) but used a different URL.

**Version:** 7.7.2 (`latest` docker image)
**OS:** Windows 10 Docker

```shell
PS C:\Dev> docker pull sitespeedio/sitespeed.io:latest
latest: Pulling from sitespeedio/sitespeed.io
Digest: sha256:18b1393acc074445bcfa5234a6edded87350d2341905c54d5fd9f838f36ef0e3
Status: Image is up to date for sitespeedio/sitespeed.io:latest

PS C:\Dev> docker run --shm-size=2g --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io:latest --debug -b firefox --outputFolder performance-firefox https://sitespeed.io
```

<details>
  <summary><strong>Output</strong></summary>
  <div>

```
Google Chrome 70.0.3538.67
Mozilla Firefox 63.0
[2018-12-21 11:37:27] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v8.12.0 sitespeed.io: 7.7.2 browsertime: 3.11.1 coach: 2.4.0
[2018-12-21 11:37:27] INFO: {
  "uuid": "baf83f3b-e9a4-4d1e-a3be-33a5f0b5b94d",
  "type": "sitespeedio.setup",
  "timestamp": "2018-12-21T11:37:27+00:00",
  "source": "queueHandler"
}
[2018-12-21 11:37:27] INFO: {
  "uuid": "a4d67083-76bf-4021-8085-3686f0d8baa9",
  "type": "browsertime.setup",
  "timestamp": "2018-12-21T11:37:27+00:00",
  "source": "browsertime"
}
[2018-12-21 11:37:27] INFO: {
  "uuid": "308973c6-cf60-424e-a01d-8487b699f119",
  "type": "browsertime.config",
  "timestamp": "2018-12-21T11:37:27+00:00",
  "source": "browsertime",
  "data": "{...}"
}
[2018-12-21 11:37:27] INFO: {
  "uuid": "394410f4-604d-4549-a029-5290792a5507",
  "type": "browsertime.config",
  "timestamp": "2018-12-21T11:37:27+00:00",
  "source": "coach",
  "data": "{...}"
}
[2018-12-21 11:37:27] INFO: {
  "uuid": "2a908aaf-ab5c-45c3-9c01-0f34093c1f0c",
  "type": "url",
  "timestamp": "2018-12-21T11:37:27+00:00",
  "source": "url-reader",
  "data": {},
  "url": "https://sitespeed.io",
  "group": "sitespeed.io"
}
[2018-12-21 11:37:27] INFO: Starting firefox for analysing https://sitespeed.io 3 time(s)
[2018-12-21 11:37:27] INFO: Testing url https://sitespeed.io iteration 1
[2018-12-21 11:37:38] INFO: Waiting on har-export-trigger to collect the HAR
[2018-12-21 11:37:41] ERROR: Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1 --video /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --startwhite -q 75
ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.70, start: 0.000000, bitrate: 256 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 251 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.513x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:37:41.346 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.70, start: 0.000000, bitrate: 256 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 251 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.513x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:37:41.346 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/1/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


    at makeError (/usr/src/app/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-12-21 11:37:42] INFO: BackEndTime: 806 DomInteractiveTime: 870 DomContentLoadedTime: 898 FirstPaint: 909 PageLoadTime: 1094
[2018-12-21 11:37:42] INFO: Testing url https://sitespeed.io iteration 2
[2018-12-21 11:37:52] INFO: Waiting on har-export-trigger to collect the HAR
[2018-12-21 11:37:53] ERROR: Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2 --video /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/2.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --startwhite -q 75
ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.53, start: 0.000000, bitrate: 267 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 263 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=1.09x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:37:53.208 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.53, start: 0.000000, bitrate: 267 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 263 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=1.09x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:37:53.208 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/2/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


    at makeError (/usr/src/app/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-12-21 11:37:54] INFO: BackEndTime: 773 DomInteractiveTime: 838 DomContentLoadedTime: 882 FirstPaint: 899 PageLoadTime: 1023
[2018-12-21 11:37:54] INFO: Testing url https://sitespeed.io iteration 3
[2018-12-21 11:38:01] INFO: Waiting on har-export-trigger to collect the HAR
[2018-12-21 11:38:02] ERROR: Error: Command failed: /usr/src/app/node_modules/browsertime/vendor/visualmetrics.py --dir /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3 --video /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/3.mp4 --orange --perceptual --force --renderignore 5 --json --viewport --startwhite -q 75
ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.57, start: 0.000000, bitrate: 264 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 260 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=1.11x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:38:02.549 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


ffmpeg version 4.0.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:00:03.57, start: 0.000000, bitrate: 264 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x540, 260 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: png, rgb24, 1366x540, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.18.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=1.11x
video:28kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
11:38:02.549 - No video frames found in /sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3
mogrify-im6.q16: unable to open image `/sitespeed.io/performance-firefox/pages/sitespeed.io/data/video/images/3/ms_*.png': No such file or directory @ error/blob.c/OpenBlob/2701.


    at makeError (/usr/src/app/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/src/app/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2018-12-21 11:38:03] INFO: BackEndTime: 818 DomInteractiveTime: 885 DomContentLoadedTime: 916 FirstPaint: 933 PageLoadTime: 1046
[2018-12-21 11:38:03] INFO: 11 requests, 151.20 kb, backEndTime: 799ms (±10.98ms), firstPaint: 914ms (±8.24ms), DOMContentLoaded: 899ms (±8.02ms), Load: 1.05s (±17.08ms), rumSpeedIndex: 802 (±10.61)
(3 runs)
[2018-12-21 11:38:03] INFO: {
  "uuid": "9738d0a0-ad2f-46d9-bd3a-4c2a1b4c8231",
  "type": "browsertime.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 0,
  "iteration": 1
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "c8edcc72-867f-45a7-8c71-13cf7a214cfc",
  "type": "coach.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 0,
  "iteration": 1
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "b6593f1a-1084-4d8f-9670-128f78cb38f7",
  "type": "browsertime.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 1,
  "iteration": 2
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "69ec92c2-0a4a-4d24-8830-472eb6fc1375",
  "type": "coach.pageSummary",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "coach",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io"
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "17af995b-2e62-46c2-976a-426c808e7e18",
  "type": "coach.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 1,
  "iteration": 2
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "49f3f858-c839-4b67-8e1d-ada456af77dd",
  "type": "browsertime.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 2,
  "iteration": 3
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "a9ce25d3-4979-410f-adde-6fc76c5e31f2",
  "type": "coach.run",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io",
  "runIndex": 2,
  "iteration": 3
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "95f8cede-49d7-42f6-a218-c199a6ab884f",
  "type": "browsertime.pageSummary",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io"
}
[2018-12-21 11:38:03] INFO: {
  "uuid": "c6e7452c-523c-4684-8254-a235b151e795",
  "type": "browsertime.har",
  "timestamp": "2018-12-21T11:38:03+00:00",
  "source": "browsertime",
  "data": "{...}",
  "url": "https://sitespeed.io",
  "group": "sitespeed.io"
```

</div>
</details>

**Comment by soulgalore** [comment]
Hi @csvn thanks for filing the issue. I could reproduce with (I always try with a specific tagged version):

`docker run --shm-size=2g --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io:7.7.2 --debug -b firefox --outputFolder performance-firefox https://sitespeed.io`

Trying with master works for me but then it's a later version of Firefox. Something goes wrong when using VisualMetrics to analyse the video. Since there has been no change, I wonder if something is wrong with Firefox. Strange. I'll look into it tonight. Easiest way is to verify that the video is ok is to add `--browsertime.videoParams.keepOriginalVideo` and check the video.

Best
Peter

**Comment by soulgalore** [comment]
<img width="484" alt="screen shot 2018-12-21 at 16 20 36" src="https://user-images.githubusercontent.com/540757/50349524-6ad48500-053c-11e9-9489-648c9fa6d59b.png">

Hmm I thought we had config that removed every popup. Let me check with someone at Mozilla if I've missed something and then I can rollforward a release tonight with a browser update for FF.

**Comment by soulgalore** [comment]
@csvn I've just pushed 7.7.3 with latest version of Firefox (also updated latest tag). That works for me. I'll do the same for Browsertime the coming hour. Also contacted a friend at Mozilla but no luck yet. https://twitter.com/soulislove/status/1076136969741189121

**Comment by soulgalore** [comment]
I've pushed Browsertime to and added more preferences for disabling update but will need to get info from Mozilla if there are more disabling that needs to be done.

**Comment by csvn** [comment]
Thanks for looking into it @soulgalore! I'll try the latest version
