### ISSUE TITLE
UrlLoadError for sitespeed docker execution

### ISSUE THREAD

**Issue by senz79** [sitespeedio/sitespeed.io#2237]
Hello 
I am getting the below error, although I am new to docker, please help me to find the root cause.

Error log with Firefox Browser
=======================
Google Chrome 71.0.3578.80
Mozilla Firefox 64.0
[2018-12-30 12:10:49] INFO: Versions OS: linux 3.10.0-957.1.3.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0
[2018-12-30 12:10:49] INFO: Starting firefox for analysing https://www.sitespeed.io 3 time(s)
[2018-12-30 12:10:49] INFO: Testing url https://www.sitespeed.io iteration 1
[2018-12-30 12:11:46] ERROR: UrlLoadError: Failed to load/verify https://www.sitespeed.io uri:data:text/html;charset=utf-8,
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:200:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-12-30 12:11:47] INFO: Testing url https://www.sitespeed.io iteration 2

Error log with Chrome Browser
======================
Google Chrome 71.0.3578.80
Mozilla Firefox 64.0
[2018-12-30 12:09:18] INFO: Versions OS: linux 3.10.0-957.1.3.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0
[2018-12-30 12:09:19] INFO: Starting chrome for analysing https://www.sitespeed.io 3 time(s)
[2018-12-30 12:09:19] INFO: Testing url https://www.sitespeed.io iteration 1
[2018-12-30 12:11:30] ERROR: UrlLoadError: Failed to load/verify https://www.sitespeed.io uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:200:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

My Docker commands are for which i am getting the same error
=============================================
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io  sitespeedio/sitespeed.io:7.7.3 https://www.sitespeed.io

docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3 --browsertime.chrome.args ignore-certificate-errors https://www.sitespeed.io

 docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3 -b firefox --browsertime.firefox.acceptInsecureCerts https://www.sitespeed.io
	
Let me know how to gather more information for the debug.

**Comment by soulgalore** [comment]
Hi @senz79 thanks for reporting! And you get the same with other URLs (so that there wasn't a problem with our domain at the moment (we use netlify and there has been some problems the last weeks)? I tested locally on my Mac and it worked there for me, hmm. What's your base OS? 

Best
Peter

**Comment by soulgalore** [comment]
And you get the same for all URLs you test? Can you reach the URL with wget/curl? :)

**Comment by senz79** [comment]
Yes i get the same issue for all the urls. I am able to get the sitespeed.io page while i do the wget.

**Comment by senz79** [comment]
![image](https://user-images.githubusercontent.com/12895992/50547324-e5e51c00-0c5d-11e9-8909-3d99f59a1247.png)

**Comment by soulgalore** [comment]
My guess is that there's some problem with the DNS between your host and your container, checkout https://forums.docker.com/t/dns-resolution-not-working-in-containers/36246 and look more in the Docker forums see if you can find a workaround.

**Comment by senz79** [comment]
The issue was with the proxy setting. I added --browsertime.proxy.http and --browsertime.proxy.https keys and the issue was resolved. Thanks a lot for the direction.
