### ISSUE TITLE
ERROR: TypeError: result.browserScripts is not iterable

### ISSUE THREAD

**Issue by cuixilong** [sitespeedio/sitespeed.io#2261]
hi，I run v7.7.3 on Ubuntu18，but it can not work and have some errors like this：

```
cuixilong@cuixilong-VirtualBox:~/sitespeed.io$ bin/sitespeed.js https://www.baidu.com -b firefox -n 1
[2019-01-22 23:43:08] INFO: Versions OS: linux 4.15.0-29-generic nodejs: v10.15.0 sitespeed.io: 7.7.3 browsertime: ^4.0.2 coach: ^3.1.1
[2019-01-22 23:43:08] INFO: Starting firefox for analysing https://www.baidu.com 1 time(s)
[2019-01-22 23:43:08] INFO: Running tests using Firefox - 1 iteration(s)
[2019-01-22 23:43:17] INFO: Testing url https://www.baidu.com iteration 1
[2019-01-22 23:43:26] INFO: Waiting on har-export-trigger to collect the HAR
[2019-01-22 23:43:28] INFO: https://www.baidu.com/ 17 requests, 227.98 kb, backEndTime: 606ms, firstPaint: 941ms, DOMContentLoaded: 1.65s, Load: 2.52s, rumSpeedIndex: 680
[2019-01-22 23:43:28] ERROR: TypeError: result.browserScripts is not iterable
    at Object.processMessage (/home/cuixilong/sitespeed.io/lib/plugins/browsertime/index.js:133:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at queue.process.message (/home/cuixilong/sitespeed.io/lib/core/queueHandler.js:208:17)
    at drainItem (/home/cuixilong/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/home/cuixilong/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-01-22 23:43:29] INFO: HTML stored in /home/cuixilong/sitespeed.io/sitespeed-result/www.baidu.com/2019-01-22-23-43-08
[2019-01-22 23:43:29] INFO: Finished analysing https://www.baidu.com
```
Do you seen this error before，thank you！

**Comment by soulgalore** [comment]
Hi @cuixilong no not that I remember. I did a quick test on master (later version than you) on my local machine and there it works. Any change you can update or try run our Docker version?

Best
Peter

**Comment by cuixilong** [comment]
@soulgalore Hi，thank you ,I use a later version and it works very well
