### ISSUE TITLE
ERROR: Error: Tried to add NaN to stats for path score

### ISSUE THREAD

**Issue by ckhampus** [sitespeedio/sitespeed.io#2265]
I get an error when I run the following command:
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.3-plus1 https://www.expressen.se -b chrome -n 1 --config mobile.json
```

With the following config:
```json
{
    "mobile": true,
    "firstParty": "(.dn.se|cached-images.bonnier.news|cdn01.dn-static.se)"
}
```

Output:
```
Google Chrome 71.0.3578.80
Mozilla Firefox 64.0
[2019-01-23 10:27:49] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 8.0.3 browsertime: 4.0.2 coach: 3.1.1
[2019-01-23 10:27:50] INFO: Will run Lighthouse tests after Browsertime has finished
[2019-01-23 10:27:50] INFO: Sending url https://www.expressen.se to test on Page Speed Insights
[2019-01-23 10:27:50] INFO: Running tests using Chrome - 1 iteration(s)
[2019-01-23 10:27:51] INFO: Testing url https://www.expressen.se iteration 1
[2019-01-23 10:27:59] INFO: Got https://www.expressen.se analysed from Google Page Speed Insights
[2019-01-23 10:28:08] INFO: https://www.expressen.se/ 90 requests, 843.29 kb, backEndTime: 404ms, firstPaint: 490ms, firstVisualChange: 1.40s, DOMContentLoaded: 946ms, Load: 1.47s, speedIndex: 1400, visualComplete85: 1.40s, lastVisualChange: 6.23s, rumSpeedIndex: 490
[2019-01-23 10:28:08] ERROR: Error: Tried to add NaN to stats for path score
    at Object.pushStats (/usr/src/app/lib/support/statsHelpers.js:27:13)
    at Object.pushGroupStats (/usr/src/app/lib/support/statsHelpers.js:35:10)
    at Object.addToAggregate (/usr/src/app/lib/plugins/coach/aggregator.js:16:18)
    at Object.processMessage (/usr/src/app/lib/plugins/coach/index.js:58:20)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-01-23 10:28:08] INFO: Will collect Lighthouse metrics for https://www.expressen.se
[2019-01-23 10:29:02] INFO: Got Lighthouse metrics
[2019-01-23 10:29:04] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.expressen.se/2019-01-23-10-27-49
```

The issue seems to be the `firstParty` property. Because if I run the command again but test against a different domain it works:
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.3-plus1 https://www.dn.se -b chrome -n 1 --config mobile.json
```

**Comment by soulgalore** [comment]
Hi @ckhampus thanks for filing the issue! I think there's a bug in the Coach when it tries to calculate privacy rules and the first party regex is not matching any domains at all. I'll fix that later on and I think you should fine-tune the the expression so matches some requests.

Best
Peter

**Comment by soulgalore** [comment]
This is in master and will go out in the next release.

**Comment by ckhampus** [comment]
Awesome! Thanks again for the quick work 👍

**Comment by soulgalore** [comment]
Released this yesterday.
