### ISSUE TITLE
Server terminated early with status 127

### ISSUE THREAD

**Issue by tcope25** [sitespeedio/sitespeed.io#2266]
Versions OS: linux 4.15.0-36-generic nodejs: v8.10.0 sitespeed.io: 8.0.3 browsertime: 4.0.2 coach: 3.1.1

Installed sitespeedio using `npm i -g sitespeed.io` on Ubuntu 18. Installed fine.

When I try to run `sitespeed.io example.com` I get the status 127 error:

[2019-01-23 17:51:00] INFO: Running tests using Chrome - 3 iteration(s)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate te.js process with a non-zero exit code.
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
[2019-01-23 17:51:00] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:82:13)
    at <anonymous>
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
[2019-01-23 17:51:00] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:82:13)
    at <anonymous>
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 8)
(node:2325) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 127
    at earlyTermination.catch.e (/usr/local/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catck, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[2019-01-23 17:51:00] INFO: Browser failed to start, trying one more time: Server terminated early with status 127
[2019-01-23 17:51:00] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:82:13)
    at <anonymous>
(node:2325) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 9)

**Comment by soulgalore** [comment]
Hi @tcope25 have you installed Chrome on the machine? Do you use xvfb or do you have a monitor? These errors are usually either missing installing Chrome or running without xvfb without a monitor.

Best
Peter

**Comment by tcope25** [comment]
I thought Chrome is installed via the sitespeed.io npm. Is that only if I run the Docker container? I'm running this via command line.

**Comment by soulgalore** [comment]
Yes you are correct: If you install via npm you need to install Chrome/Firefox yourself and if you run on a system without a screen, you need to use XVFB. If you use the Docker container it's bundled with Chrome/Firefox/XVFB + ffmpeg that's needed to record the video. If you can use Docker that should make things easier.

Best
Peter
