### ISSUE TITLE
Error: Unknown connectivity profile true ?

### ISSUE THREAD

**Issue by donwalling** [sitespeedio/sitespeed.io#2270]
With sitespeed 8.0.6 we're getting an error on a config.json that works with 7.7.2:

$ docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.0.6 -config config.json https://<myurlhere.com>

[2019-01-28 18:28:02] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 8.0.6 browsertime: 4.0.5 coach: 3.1.2
[2019-01-28 18:28:02] ERROR: Error: Unknown connectivity profile true
    at Object.parseTrafficShapeConfig (/usr/src/app/node_modules/browsertime/lib/connectivity/trafficShapeParser.js:53:15)
    at removeConnectivity (/usr/src/app/node_modules/browsertime/lib/connectivity/index.js:40:40)
    at Engine.stop (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:185:7)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:126:20)

I haven't found an issue in the config.json itself - it seems any config.json results in the error. The config.json is this:
{
    "browsertime": {
        "iterations": 3,
        "browser": "chrome",
        "chrome.timeline": true,
        "preScript": "login.js",
        "script": ["cxClickTime.js","folderClickTime.js"],
        "viewPort": "1200x2400",
        "connectivity.profile": "native",
        "pageCompleteCheck": "pageCompleteCheck.js"
    }
}

It appears I can set all the options on the command line. But that's a bit of a non-starter due to the number of tests we've already created.

Is anyone else seeing issues when using --config config.json on the command line?

**Comment by donwalling** [comment]
nevermind. this was user error
