### ISSUE TITLE
ERROR: UrlLoadError: Failed to load/verify when trying to test something on localhost

### ISSUE THREAD

**Issue by marimeireles** [sitespeedio/sitespeed.io#2284]
Hi
I'm getting the following error if I try to run speedtest.io to test a local site:

```
Google Chrome 71.0.3578.80
Mozilla Firefox 64.0
[2019-02-02 19:50:35] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 7.7.3 browsertime: 3.11.1 coach: 2.4.0
[2019-02-02 19:50:35] INFO: Starting chrome for analysing http://localhost:5000/issues/44 8 time(s)
[2019-02-02 19:50:35] INFO: Testing url http://localhost:5000/issues/44 iteration 1
[2019-02-02 19:50:39] ERROR: UrlLoadError: Failed to load/verify http://localhost:5000/issues/44 uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:200:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I ran speedtest with the following command: `docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:7.7.3 --config config.json http://localhost:5000/issues/44`

My config.json file has the following configs:
```
{
  "browsertime": {
    "iterations": 8,
    "browser": "chrome"
  },
  "utc": true,
  "outputFolder": "edited_chrome"
}
```

If I try to test a website like google.com or anything else in the web, this configuration works fine.

My OS is a Mojave and I'm using Chrome Version 71.0.3578.98 (Official Build) (64-bit).

Thanks!

**Comment by soulgalore** [comment]
Hi @marimeireles ! When you use **localhost**  inside the Docker container,  it will mean localhost inside the container (and not localhost on your computer). 

On Mac there is an easy way to access localhost using Docker if you are running a later version of Docker: https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost

Best
Peter

**Comment by marimeireles** [comment]
Oops.
That works.
Thanks @soulgalore! :)

**Comment by LeXuanKhanh** [comment]
how about window ? is there a way to access local host ?

**Comment by soulgalore** [comment]
I think windows for Docker implemented the same @LeXuanKhanh else check the Docker documentation.
