### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by donwalling** [sitespeedio/sitespeed.io#2289]
We're trying to measure button-click navigation on an SPA, but getting an exception similar to issue 2287, but not fixed in 8.2.2. I'm able to reproduce on a modified version of the sitespeed example:

$ docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.2.2 --multi --spa -n 2 script.js 

where script.js is:

```
module.exports = async function(context, commands) {
    await commands.measure.start('https://www.sitespeed.io');

    await commands.measure.start('docs');
    return commands.click.byXpathAndWait('//a[contains(.,"Documentation")]');
};
```

produces:
Google Chrome 72.0.3626.81 
Mozilla Firefox 65.0
[2019-02-05 15:20:57] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 8.2.2 browsertime: 4.2.4 coach: 3.2.0
[2019-02-05 15:20:58] INFO: Running tests using Chrome - 2 iteration(s)
[2019-02-05 15:20:59] INFO: Testing url https://www.sitespeed.io iteration 1
[2019-02-05 15:21:06] INFO: Start to measure docs
[2019-02-05 15:21:15] INFO: https://www.sitespeed.io/ BackEndTime: 68 DomInteractiveTime: 91 DomContentLoadedTime: 131 FirstPaint: 258 PageLoadTime: 242
[2019-02-05 15:21:15] INFO: VisualMetrics FirstVisualChange: 33 SpeedIndex: 270 PerceptualSpeedIndex: 158 LastVisualChange: 300
[2019-02-05 15:21:15] ERROR: TypeError: Cannot read property 'replace' of null
    at /usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:40:37
    at Array.forEach (<anonymous>)
    at module.exports (/usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:39:18)
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:176:19)
[2019-02-05 15:21:16] INFO: HTML stored in /sitespeed.io/sitespeed-result/script_js/2019-02-05-15-20-57

**Comment by soulgalore** [comment]
Hi @donwalling ah sorry maybe the documentation isn't clear, I'll update it tonight: If you start a measurement you also need to stop it:

```
module.exports = async function(context, commands) { 
  await commands.measure.start('https://www.sitespeed.io'); 
  await commands.measure.start('docs'); 
  await commands.click.byXpathAndWait('//a[contains(.,"Documentation")]');
  return commands.measure.stop();
};
```

Best
Peter

**Comment by soulgalore** [comment]
Start without giving it a URL I mean.

**Comment by donwalling** [comment]
@soulgalore I'll give it a try today. I thought the ...AndWait() methods did the stop automatically.

**Comment by donwalling** [comment]
@soulgalore yes, this is solved. Thank you for the info, and quick response. Our actual test script is now getting a different exception that happens only when n>1. But its probably a different issue. I'll close this and see if I can isolate the new issue

[2019-02-05 16:43:36] INFO: VisualMetrics FirstVisualChange: 100 SpeedIndex: 10510 PerceptualSpeedIndex: 2327 LastVisualChange: 15533
[2019-02-05 16:43:36] ERROR: TypeError: Cannot read property 'timings' of undefined
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:70:27)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:164:7)
