### ISSUE TITLE
 ERROR: LHError: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by MaximSergeichik** [sitespeedio/sitespeed.io#2300]
I'm trying to run sitespeed with the following command:
`docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io -v "/disk2/result":/sitespeed.io/sitespeed-result sitespeedio/sitespeed.io:8.3.0-plus1 -b chrome https://www.schneider-electric.com/ww/en/`

OS: centos7

The output log is following:
Google Chrome 72.0.3626.81
Mozilla Firefox 65.0
[2019-02-11 16:56:41] INFO: Versions OS: linux 3.10.0-957.1.3.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 8.3.0 browsertime: 4.3.0 coach: 3.2.1
[2019-02-11 16:56:41] INFO: Will run Lighthouse tests after Browsertime has finished
[2019-02-11 16:56:42] INFO: Sending url https://www.schneider-electric.com/ww/en/ to test on Page Speed Insights
[2019-02-11 16:56:42] INFO: Running tests using Chrome - 3 iteration(s)
[2019-02-11 16:56:42] INFO: Got https://www.schneider-electric.com/ww/en/ analysed from Google Page Speed Insights
[2019-02-11 16:56:43] INFO: Testing url https://www.schneider-electric.com/ww/en/ iteration 1
[2019-02-11 16:57:00] INFO: https://www.schneider-electric.us/en/ BackEndTime: 160 DomInteractiveTime: 838 DomContentLoadedTime: 838 FirstPaint: 614 PageLoadTime: 979
[2019-02-11 16:57:00] INFO: VisualMetrics FirstVisualChange: 433 SpeedIndex: 1569 PerceptualSpeedIndex: 2058 LastVisualChange: 3233
[2019-02-11 16:57:01] INFO: Testing url https://www.schneider-electric.com/ww/en/ iteration 2
[2019-02-11 16:57:16] INFO: https://www.schneider-electric.us/en/ BackEndTime: 165 DomInteractiveTime: 858 DomContentLoadedTime: 858 FirstPaint: 601 PageLoadTime: 1023
[2019-02-11 16:57:16] INFO: VisualMetrics FirstVisualChange: 533 SpeedIndex: 1714 PerceptualSpeedIndex: 2200 LastVisualChange: 3333
[2019-02-11 16:57:17] INFO: Testing url https://www.schneider-electric.com/ww/en/ iteration 3
[2019-02-11 16:57:32] INFO: https://www.schneider-electric.us/en/ BackEndTime: 236 DomInteractiveTime: 930 DomContentLoadedTime: 931 FirstPaint: 726 PageLoadTime: 1087
[2019-02-11 16:57:32] INFO: VisualMetrics FirstVisualChange: 400 SpeedIndex: 1399 PerceptualSpeedIndex: 2130 LastVisualChange: 3366
[2019-02-11 16:57:32] INFO: https://www.schneider-electric.us/en/ 146 requests, 3920.88 kb, backEndTime: 187ms (±20.04ms), firstPaint: 647ms (±32.40ms), firstVisualChange: 455ms (±32.65ms), DOMContentLoaded: 876ms (±23.08ms), Load: 1.03s (±25.60ms), speedIndex: 1561 (±74.32), visualComplete85: 3.31s (±32.65ms), lastVisualChange: 3.31s (±32.65ms), rumSpeedIndex: 647 (±32.40) (3 runs)
[2019-02-11 16:57:32] INFO: Will collect Lighthouse metrics for https://www.schneider-electric.com/ww/en/
[2019-02-11 16:58:50] ERROR: LHError: PROTOCOL_TIMEOUT
    at Timeout.setTimeout [as _onTimeout] (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:277:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[2019-02-11 16:58:50] ERROR: Error: ENOENT: no such file or directory, scandir '/sitespeed.io/sitespeed-result/www.schneider-electric.com/2019-02-11-16-56-41/pages/www.schneider-electric.com/ww/en/data/video/images/1'

When I'm trying to run sitespeed with the same command for https://www.sitespeed.io all goes fine.

**Comment by soulgalore** [comment]
Hi @MaximSergeichik thanks for creating the issue. It seems to be two errors here: 1st it's the redirect (tracked in #2281), I've had time to fix that yet. If you add --multi to your run it will work for now. The other thing is an error for Lighthouse. We should at least catch that better. I'll do that in this issue, and then that URL should be reported to Lighthouse (an upstream issue for us).

Best
Peter

**Comment by soulgalore** [comment]
@MaximSergeichik I've pushed 8.4.0 that fixes the redirect problem + so we catch Lighthouse errors within the Lighthouse plugin. I'm gonna close this, but please let me know if you still have the issue. If there's an issue with testing the URL in Lighthouse, create a upstream issue at https://github.com/GoogleChrome/lighthouse/issues/new/choose

Best
Peter
