### ISSUE TITLE
[Ubuntu] ERROR: BrowserError: unknown error: failed to change window state to normal, current state is maximized

### ISSUE THREAD

**Issue by rockmax-rajat** [sitespeedio/sitespeed.io#2325]
While running this command from terminal, we are getting below mentioned error very frequently:
Command: $ sitespeed.io https://www.adobe.com

[2019-02-20 15:56:48] INFO: Versions OS: linux 4.15.0-43-generic nodejs: v10.6.0 sitespeed.io: 8.6.2 browsertime: 4.4.6 coach: 3.2.1
[2019-02-20 15:56:49] INFO: Running tests using Chrome - 3 iteration(s)
[2019-02-20 15:56:49] ERROR: BrowserError: unknown error: failed to change window state to normal, current state is maximized
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
    at SeleniumRunner.start (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:118:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-02-20 15:56:50] ERROR: BrowserError: unknown error: failed to change window state to normal, current state is maximized
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
    at SeleniumRunner.start (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:118:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-02-20 15:56:51] ERROR: BrowserError: unknown error: failed to change window state to normal, current state is maximized
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-43-generic x86_64)
    at SeleniumRunner.start (/home/rajats/.nvm/versions/node/v10.6.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:118:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-02-20 15:56:52] INFO: HTML stored in /home/rajats/Rajat/Projects/git/CxTestApp/18Feb/CxTestApp/test/ui/response/urt1_new/sitespeed-result/www.adobe.com/2019-02-20-15-56-48

Note that this error is reproducible on Ubuntu. I tried with both sitespeed.io 7.x version and latest 8.x version but this problem persists.

This issue is intermittent but being reproducible more than 90% (i.e. 9/10 times).

**Comment by rockmax-rajat** [comment]
This issue do not depends upon what url we are passing. It is reproducible for all urls. However, it works fine without any error around once or twice out of 10 times.

**Comment by soulgalore** [comment]
Hi @rockmax-rajat this looks like a Chrome/Chromedriver problem? If you use latest Chrome no difference? I've seen we haven't updated to latest Chromedriver, but I couldn't see anything related in the release notes there when briefly looked.

And you run it exactly as you say, no extra parameters like running headless etc (just checking)?

Best
Peter

**Comment by rockmax-rajat** [comment]
@soulgalore I have latest Chrome on my system - Version 71.0.3578.80 (Official Build) (64-bit). 
Since this issue is with browser size/state, it is not reproducible when we run with --headless param.

Can you help me as how to run it with latest chrome driver?

**Comment by soulgalore** [comment]
Yeah but there's 72 on Ubuntu right? We got it installed in our Docker containers.  The reason I asked about headless is that when I searched for that error there are others that try to run headless that get that error.

If you just open Chrome on that machine, does the the window start maximized? I wonder if there's a user preferences that kicks in?

If you wanna try latest driver with latest Chrome, download the driver https://sites.google.com/a/chromium.org/chromedriver/downloads  and then use `--browsertime.chrome.chromedriverPath` with the full path to the driver.

Best
Peter

**Comment by rockmax-rajat** [comment]
@soulgalore I tried with latest chromedriver version but the problem persists.

I checked Chrome browser as well and found my browser as latest with no more updates available. Version mentioned in previous comment.

Also, just checked, when I opened Chrome new window, it is being opened as maximized.

**Comment by soulgalore** [comment]
Have a look at the [Docker file](https://hub.docker.com/r/sitespeedio/webbrowsers/dockerfile) how we install Chrome if you wanna try out 72 on Ubuntu. 

To get moving I think you should try running with Docker instead. Then I can try out on Ubuntu later on if I can reproduce, and if I cannot I think you should create an upstream issue with Chromedriver.

Best
Peter

**Comment by soulgalore** [comment]
This happened a long time ago and hopefully works now. If not please let us know.
