### ISSUE TITLE
ERROR: UrlLoadError: Failed to load/verify when trying to test https://xxx.xxxx.net.in/ domain

### ISSUE THREAD

**Issue by parag85** [sitespeedio/sitespeed.io#2403]
Hi

Facing following error when tried to run https://staging.ntp.net.in/ domain

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.9.0 https://staging.ntp.net.in/

Google Chrome 73.0.3683.75 
Mozilla Firefox 66.0
[2019-04-01 05:25:53] INFO: Versions OS: linux 4.15.0-44-generic nodejs: v10.13.0 sitespeed.io: 8.9.0 browsertime: 4.5.3 coach: 3.3.0
[2019-04-01 05:25:54] INFO: Running tests using Chrome - 3 iteration(s)
[2019-04-01 05:25:55] INFO: Testing url https://staging.ntp.net.in/ iteration 1
[2019-04-01 05:26:01] ERROR: UrlLoadError: Failed to load/verify https://staging.ntp.net.in/ uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:225:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[2019-04-01 05:26:19] INFO: HTML stored in /sitespeed.io/sitespeed-result/staging.ntp.net.in/2019-04-01-05-25-53

OS:  Ubuntu 18.04.1 LTS

**Comment by soulgalore** [comment]
Hi @parag85 checkout https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/ I think that can help.

Best
Peter

**Comment by washingon** [comment]
@parag85 check out 8.12.0.  Look like you may be getting a similar error to https://github.com/sitespeedio/sitespeed.io/issues/2416 

See if it works with -b firefox and fails with -b chome:
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.9.0 https://staging.ntp.net.in/ -b firefox
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.9.0 https://staging.ntp.net.in/ -b chrome
