### ISSUE TITLE
sitespeed time out error

### ISSUE THREAD

**Issue by manojs1978** [sitespeedio/sitespeed.io#2464]
i have installed sitespeed.io 8.15.2 and facing below issue while running below command
previously it was working fine but after upgrading to 8.15.2 , i am facing time out error . browser is opening but not nevigating to sitespeed.io website.

 Versions OS: win32 10.0.16299 nodejs: v10.15.3 sitespeed.io: 8.15.2 browsertime: 4.9.1 coach: 3.4.0

sitespeed.io https://www.sitespeed.io

ERROR: TimeoutError: timeout
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57                                                                                                                                                                                               e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57                                                                                                                                                                                               e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)

**Comment by manojs1978** [comment]
hi , i have updated sitespeed.io to new version 9.0.0 still i am facing timeout error. is it machine specific issue or what ?
could you please help me here , i totally stuck here.

scenario:
after installing sitespeed to 9.0.0 on window 10 machine , i am just running below command , still it time outs.
sitespeed.io https://www.sitespeed.io

actual result:
[2019-05-22 09:49:36] ERROR: TimeoutError: timeout
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\\*\*\*\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\*\*\*\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\*\*\*\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.navigate().to(data:text/html;charset=utf-8,)
    at Driver.schedule (C:\\*\*\*AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Navigation.to (C:\*\*\*\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\webdriver.js:1133:25)
    at Driver.get (C:\U\*\*\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\selenium-webdriver\lib\webdriver.js:988:28)
    at Iteration.run (C:\*\*\*\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:137:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-22 09:49:36] ERROR: No data to collect

**Comment by soulgalore** [comment]
Hi @manojs1978 we officially doesn't support running node version directly on Windows (but it would be cool if it worked). Can you try with Docker?

Best
Peter

**Comment by manojs1978** [comment]
Hi @soulgalore
previously it was working well with windows but from last some update it is not working.


i have installed sitespeed with docker ,
it is working with external urls but not working with testing URLs behind proxy servers. i set proxy server as well but failing
command i run:


 docker run  --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io  https://****.com:****/index.html  -b chrome --browsertime.proxy.http=http://*******:**** --browsertime.proxy.https=http:/******:**** --browsertime.chrome.args ignore-certificate-errors 
getting below error:

[2019-05-23 11:28:48] INFO: Testing url https://******:***/indexhtml iteration 1
[2019-05-23 11:28:54] ERROR: UrlLoadError: Failed to load/verify https://******:***/indexhtml uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:232:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-23 11:28:55] INFO: Testing url https://******:***/indexhtml iteration 2
[2019-05-23 11:29:00] ERROR: UrlLoadError: Failed to load/verify https://******:***/indexhtml uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:232:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-23 11:29:01] INFO: Testing url https://******:***/indexhtml iteration 3
[2019-05-23 11:29:07] ERROR: UrlLoadError: Failed to load/verify https://******:***/indexhtml uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:232:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-23 11:29:07] INFO: https://******:***/indexhtml 0 requests, 0 bytes
[2019-05-23 11:29:07] INFO: {


Please help me.

**Comment by soulgalore** [comment]
Do you remember which version you where using (can you rollback an verify that it works with that version). We haven't changed navigating in 9 if I remember correctly, maybe in 6/7 or something like that.

**Comment by manojs1978** [comment]
hi @soulgalore
i am able resolve above issue.
RCA:

on windws machine after deleting chrome.dll and reinstallig chrome, everything is working fine now with latest release as well.
