### ISSUE TITLE
Multi page script fails in single page app

### ISSUE THREAD

**Issue by skhilko** [sitespeedio/sitespeed.io#2491]
I may be doing something wrong, but from what I read in the [docs on SPA](https://www.sitespeed.io/documentation/sitespeed.io/spa/), the following is supposed to work.

### Script (voicerecordpro.js)
```js
module.exports = async function(context, commands) {
  await commands.measure.start("https://voicerecordpro.com/#/recordings");
  await commands.measure.start("https://voicerecordpro.com/#/community");
  return commands.measure.start("https://voicerecordpro.com/#/favorites");
};
```
### Command
```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:9.2.0 voicerecordpro.js --multi --spa -n 1
```
### Result (Error)
```
Google Chrome 74.0.3729.169 
Mozilla Firefox 67.0
[2019-06-01 14:44:30] INFO: Versions OS: linux 5.1.4-arch1-1-ARCH nodejs: v10.15.3 sitespeed.io: 9.2.0 browsertime: 5.1.3 coach: 3.5.7
[2019-06-01 14:44:30] INFO: Running tests using Chrome - 1 iteration(s)
[2019-06-01 14:44:31] INFO: Testing url https://voicerecordpro.com/#/recordings iteration 1
[2019-06-01 14:44:38] INFO: Testing url https://voicerecordpro.com/#/community iteration 1
[2019-06-01 14:44:45] INFO: Testing url https://voicerecordpro.com/#/favorites iteration 1
[2019-06-01 14:44:58] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addMetaToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:138:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:76:19)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:189:7)
[2019-06-01 14:44:58] INFO: HTML stored in /sitespeed.io/sitespeed-result/voicerecordpro_js/2019-06-01-14-44-30
```

Am I doing this right? I appreciate your help!

**Comment by soulgalore** [comment]
Hi @skhilko ! Wow thank you for the great bug report, I really appreciate when you show exactly how you do so I can recreate the issue. It's really valuable and I'll always push issues to the top of my 2do list :)

I got the same when I tried. If I remove the last URL (#favorites) it works for me. At the moment we only support navigation that do a request or rather I think that's needed for the HAR to generate a new page, but I need to look into it. At very least we should find a better way to catch that error. But with your example, it will make it much easier, so thanks! 

I'm gonna move this to Browsertime because it is there it needs to be fixed.
