### ISSUE TITLE
ERROR: Incomplete first view data for WPT test while executing scripted test

### ISSUE THREAD

**Issue by aceey** [sitespeedio/sitespeed.io#2497]
Hi guys!

I'm trying to run a site speed test with sitespeed.io with scripting and using --webpagetest.file function. I'm having error like this ("ERROR: Incomplete first view data for WPT test 190608_BC_a81596dd43c28ac392d4ace4525030bf, run 1")

**Here is my script:**
```logData             0
navigate            https://www.domain.com/secure/login.html?url=https%3A%2F%2Fwww.domain.com%2F
logData             1
execAndWait     document.getElementById("email").value="testonly@gmail.com"
execAndWait     document.getElementById("password").value="test03123"
clickAndWait     id=login-next-button
navigate            https://www.domain.com/path/param.html```


*****Running in my container with*****
docker run --name sitespeed --volumes-from=jenkins --network=host --privileged=true --shm-size=1g --rm -v /tmp/sitespeed.io/:/sitespeed.io sitespeedio/sitespeed.io:9.2.1 --webpagetest.file /sitespeed.io/wptScript.txt --webpagetest.host localhost https://www.domain.com/secure/cart.html --graphite.host localhost --graphite.port 8888 --graphite.httpPort 8888 --graphite.namespace scripting.default --browsertime.browser chrome --browsertime.iterations 1 --webpagetest.location Test --webpagetest.runs 1


*****And here's the console logs*****
Google Chrome 74.0.3729.169 
Mozilla Firefox 67.0
[2019-06-08 09:41:54] INFO: Versions OS: linux 3.10.0-862.el7.x86_64 nodejs: v10.15.3 sitespeed.io: 9.2.1 browsertime: 5.1.3 coach: 3.5.7
[2019-06-08 09:41:56] INFO: Sending url https://www.domain.com/secure/cart.html to test on 10.20.12.31
[2019-06-08 09:41:56] INFO: Running tests using Chrome - 1 iteration(s)
[2019-06-08 09:41:58] INFO: Testing url https://www.domain.com/secure/cart.html iteration 1
[2019-06-08 09:42:29] INFO: https://www.domain.com/secure/cart.html 104 requests, 895.81 kb, backEndTime: 1.45s, firstPaint: 2.94s, firstVisualChange: 2.97s, DOMContentLoaded: 3.45s, Load: 9.56s, speedIndex: 3250, visualComplete85: 3.23s, lastVisualChange: 12.03s, rumSpeedIndex: 3043
[2019-06-08 09:43:37] INFO: Got https://www.domain.com/secure/cart.html analysed with id 190608_BC_a81596dd43c28ac392d4ace4525030bf from 10.20.12.31
[2019-06-08 09:43:37] ERROR: Incomplete first view data for WPT test 190608_BC_a81596dd43c28ac392d4ace4525030bf, run 1
[2019-06-08 09:43:37] ERROR: Metricsfilter: The breakdown is missing from the metrics breakdown.*.requests
[2019-06-08 09:43:37] ERROR: Metricsfilter: The breakdown is missing from the metrics breakdown.*.bytes
[2019-06-08 09:43:40] ERROR: TypeError: Cannot read property 'details' of undefined on line 24
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:84:99)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1767:3)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:352:35)
Build step 'Execute shell' marked build as failure
Finished: FAILURE


Can you please help me, having a hard time in this. 


Thanks in advance.

**Comment by soulgalore** [comment]
Hi @aceey when you look at the result at your WebPageTest instance, does it look ok there?

We had issued like this before check the comments:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/plugins/webpagetest/aggregator.js#L35-L37

So it looks like the SpeedIndex is not valid, what does it looks like in WebPageTest?

Best
Peter

**Comment by aceey** [comment]
Hi @soulgalore thank you for the response, when I do manual run in my webpagetest instance, running the same script it looks okay there and metrics are just totally fine.

Reviewing the screenshots and it looks like these:
![image](https://user-images.githubusercontent.com/42996872/59236429-b97bf580-8c28-11e9-9224-aeb119360290.png)
See the screenshot it shows "Error:Navigation Error" in step 1 and 2. Is there a problem why there's navigation error?

Tabular result:
![image](https://user-images.githubusercontent.com/42996872/59236474-ea5c2a80-8c28-11e9-8812-cd1febb9c467.png)

**Comment by aceey** [comment]
Hi @soulgalore I think this issue should be close. I just fixed the issue on my side. It seems like the logData 1 function must be set right before the cart page after hitting the log in thing. Maybe the reason why incomplete metrics is return is because I navigated to other page since capturing metrics is not yet done on homepage view.
