### ISSUE TITLE
Result HTML not uploaded to S3: ERROR: TypeError: Cannot read property 'numberResources' of undefined

### ISSUE THREAD

**Issue by andyfrancis** [sitespeedio/sitespeed.io#2499]
We regularly see results not being uploaded to S3 for a test - we run multiple servers launched on demand in AWS each writing to their own S3 bucket.  The annotation appears in Grafana, but the results are not actually available in S3.

When this fails we see the following error in the logs just prior to the S3 upload - I can post the rest of our logs if you need;

[2019-06-08 19:25:15] ERROR: TypeError: Cannot read property 'numberResources' of undefined on line 24
at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:52:52)
at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:257:72)
at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:287:37)

- Sitespeed.io version: 9.2.1-plus1
- Docker, Ubuntu
- Config: [sitespeed-mobile-4g-config-redacted.txt](https://github.com/sitespeedio/sitespeed.io/files/3268861/sitespeed-mobile-4g-config-redacted.txt)

**Comment by soulgalore** [comment]
Hi @andyfrancis thanks for the report. Gonna do a release early next week with newest Chrome, I'll make sure I'll have a look before that release.

Best
Peter

**Comment by andyfrancis** [comment]
If you need any further details, or someone to test I'm happy to contribute.

**Comment by soulgalore** [comment]
@andyfrancis I've pushed a new release that at least catches the error. However if I understood correctly, the problem is that GPSI doesn't return any statistics for the page you test, so it seems to be something more that is wrong.

**Comment by andyfrancis** [comment]
I've updated to the new build and now see the following error at the same point;

> [2019-06-10 22:25:29] ERROR: TypeError: Cannot read property 'SPEED' of undefined on line 65
at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:170:80)
at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:266:72)
at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:27:37)
at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:287:37)

**Comment by soulgalore** [comment]
Yeah I guess we don't handle if you don't get anything or an error from GPSI.

**Comment by andyfrancis** [comment]
Yes, it looks that way.  With the request limit resolved, there are no further issues for that error.

**Comment by soulgalore** [comment]
Cool, I'll fixed so that in the next release it at least do not break if that happens.
