### ISSUE TITLE
[Feature request] Add CDP metrics JSHeapUsedSize and JSHeapTotalSize to db

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2514]
I would like to trend JS heap over time as we optimize our product.

**Comment by soulgalore** [comment]
Released 9.4.0 earlier today where this is included!

**Comment by leathej1** [comment]
I am getting an error with this new version:
```SyntaxError: Unexpected token } in JSON at position 931
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/src/app/lib/cli/cli.js:31:34)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)```

**Comment by soulgalore** [comment]
@leathej1 it looks like it comes from when sitespeed.io tries to parse your config.json, are you sure you haven't changed something there and it isn't a valid JSON?

**Comment by leathej1** [comment]
Ah - you are right, of course. I took out a key value pair without removing the comma.

**Comment by leathej1** [comment]
Hmm. But this one just started:
```[2019-06-30 04:33:01] ERROR: Could not parse the trace log from Chrome for url https://myco,xyz/apps/agent/#/customers LHError: NO_NAVSTART
    at Function.compute (/usr/src/app/node_modules/@sitespeed.io/tracium/lib/trace-of-tab.js:90:33)
    at Function.compute (/usr/src/app/node_modules/@sitespeed.io/tracium/lib/main-thread-tasks.js:304:57)
    at Object.computeMainThreadTasks (/usr/src/app/node_modules/@sitespeed.io/tracium/index.js:13:36)
    at parseCpuTrace (/usr/src/app/node_modules/browsertime/lib/chrome/cpu.js:18:29)
    at ChromeDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:266:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by soulgalore** [comment]
Hi @leathej1 did you update from the version released before 9.4? No changes with the tracing in 9.4.

Upstream Tracium has been patched (it seems it started with one of the latest Chrome versions), I can update our version too tomorrow and see if it goes away.

Best
Peter

P.S If you get new errors please create new issues, that makes it easier for me to keep track of things, thanks!

**Comment by leathej1** [comment]
Understood - sorry, I got lazy. Yes, I upgraded from 9.3.4,

**Comment by soulgalore** [comment]
Ok, I,ve pushed one fix in master but not 100% sure it will solve it. Can make a new release tomorrow.
