### ISSUE TITLE
Docker Desktop for Windows/Docker Compose/urls.txt throwing error

### ISSUE THREAD

**Issue by nevesing** [sitespeedio/sitespeed.io#2530]
I am using docker desktop for windows (win 10) and trying to run sitespeed using below command:

docker-compose run sitespeed.io urls.txt

**My YML file:**

version: '3'
services:
    sitespeed.io:
      image: sitespeedio/sitespeed.io:9.3.4
      command: -V
      shm_size: 1g
      volumes:
            - ./sitespeed-result/:/sitespeed.io/sitespeed-result
            - ./urls.txt:/sitespeed.io/urls.txt

**Output:**

Google Chrome 75.0.3770.80
Mozilla Firefox 67.0.1
/usr/src/app/lib/cli/util.js:47
          throw e;
          ^

### Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:491:3)
    at tryReadSync (fs.js:330:20)
    at Object.readFileSync (fs.js:367:19)
    at Object.getURLs (/usr/src/app/lib/cli/util.js:21:14)
    at Object.parseCommandLine (/usr/src/app/lib/cli/cli.js:1257:41)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by soulgalore** [comment]
Hi @nevesing I think you need to have a absolute path when mapping to Docker, something like 

`- /my/full/path/sitespeed-result/:/sitespeed.io/sitespeed-result`

Best
Peter

**Comment by nevesing** [comment]
Same error. I tried like below:

```
volumes:
      - C:/Users/my/user/name/sitespeed-result:/sitespeed.io/sitespeed-result
```

Also i tried to execute docker cmd instead of docker-compose and i am getting same error

`PS C:\Users\my\user\name> docker run -e TZ=America/New_York --rm -v C:/Users/my/user/name:/sitespeed.io sitespeedio/sitespeed.io:9.4.0 C:/Users/my/user/name/urls.txt`

Output: 

`C:/Users/my/user/name/urls.txt does not exist, is the path to the file correct?`

**Comment by soulgalore** [comment]
Hi @nevesing I tried just with docker run and then it worked. In your example you are using your host  path instead of your docker path (C:/Users/my/user/name/urls.txt should be /sitespeed.io/urls.txt or just urls.txt because /sitespeed.io/ is the working dir if I remember correctly.
