### ISSUE TITLE
Error: Could not stop Xvfb

### ISSUE THREAD

**Issue by tufandevrim** [sitespeedio/sitespeed.io#2531]
We just found out a failed test with following logs:
```
[2019-07-01 21:59:34] INFO: [sitespeedio] Versions OS: XXXXXXX.x86_64 nodejs: v10.13.0 sitespeed.io: 9.3.0 browsertime: 5.2.1 coach: 3.6.0
[2019-07-01 21:59:34] WARN: [sitespeedio] --plugins.load is deprecated, use plugins.add instead.
[2019-07-01 21:59:35] INFO: [browsertime] Running tests using Chrome - 1 iteration(s)
[2019-07-01 21:59:36] INFO: [browsertime.command.measure] Testing url https://www.yahoo.com iteration 1
[2019-07-01 22:00:28] INFO: [browsertime] https://www.yahoo.com 290 requests, 1494.91 kb, backEndTime: 810ms, firstPaint: 1.29s, firstVisualChange: 1.73s, DOMContentLoaded: 1.99s, Load: 14.12s, speedIndex: 3399, visualComplete85: 1.83s, lastVisualChange: 19.13s, rumSpeedIndex: 1305
[2019-07-01 22:00:30] ERROR: [sitespeedio.queuehandler] Error: Could not stop Xvfb.
    at /usr/src/app/node_modules/@cypress/xvfb/index.js:106:27
    at suppressedCallback (fs.js:200:5)
    at FSReqWrap.oncomplete (fs.js:141:20)
```
Just reporting it if this is something we can gracefully handle it like retries etc. The test ran via docker cmd.

**Comment by soulgalore** [comment]
Hi @tufandevrim I haven't seen that error before, its from https://github.com/cypress-io/xvfb/blob/605d95236a63516737c0483ae6e8a5cf559cf1cc/index.js 

I wonder, could it be something else running on the same machine where you run sitespeed.io that can interfere?

Best
Peter

**Comment by tufandevrim** [comment]
I don't think anything else would work on my dedicated vm to run only ssio docker one at a time. To be frank I've just seen this once. I'd keep monitoring this issue and let know again if I run into it with some details. I just wanted to know if you have experienced this before or not. Closing it.
