### ISSUE TITLE
multiple try/catch statements in spa/multi script tests throws error

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/sitespeed.io#2532]
I'm trying to handle scenarios in SPA/multi tests where it's possible for a page to not load correctly for whatever reason and I want it to continue to the next test. So, I put a couple try/catch statements in the test script. However, things go smoothly until I (purposely, for now) can't find an element on a page and I get `Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-03-23-11-25/chromeNetlog.json'`.

#### run via docker:  
`docker run -it --rm -v $PWD/:/sitespeed.io/ -v $PWD/config.json:/sitespeed.io/config.json sitespeedio/sitespeed.io:9.3.4 --config config.json multiple_tasks.js --multi --spa`

#### config.json (obfuscated):
```javascript
{
  "browsertime": {
    "browser": "chrome",
    "connectivity": {
      "profile": "cable"
    },
    "iterations": 1,
    "video": true,
    "videoParams": {
      "framerate": 30
    },
    "visualMetrics": true
  },
  "chrome": {
    "collectConsoleLog": true,
    "collectNetLog": true,
    "timeline": true
  },
  "influxdb": {
    "host": "example",
    "database": "example",
    "password": "example",
    "port": 8086,
    "protocol": "https",
    "username": "example",
    "tags": "whatever=example"
  },
  "mobile": false,
  "resultBaseURL": "http://example.s3-website-us-west-2.amazonaws.com",
  "s3": {
     "acl": "public-read",
     "bucketname": "example",
     "key": "example",
     "region": "us-west-2",
     "secret": "example"
  },
  "utc": true
}
```

#### multiple_tasks.js:
I've also got some hack in here to capture pass/fail related to #2512, so beware in case that causes some issue.
```javascript
module.exports = async function(context, commands) {
  
  // successful result
  try {
    await commands.navigate('https://google.com');

    // search should pass
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search');
    await commands.click.bySelector('input.gNO89b');

    // pass/fail test
    await commands.wait.byXpath('//*[@id="resultStats"]', 3000); // pass

    // if it can't be found, this isn't set to true
    await commands.js.run('performance.mark("test_pass");');

  } catch(error) {
    console.log("wtf, google search failed");
    console.log(error);

    await commands.js.run('performance.mark("test_fail");');

  } finally {
    await commands.measure.stop();
  }


  // failing result
  try {
    await commands.navigate('https://google.com');

    // search should pass
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search');
    await commands.click.bySelector('input.gNO89b');

    // pass/fail test
    await commands.wait.byXpath('//*[@id="resultStatsbarf]', 3000); // fail

    // if it can't be found, this isn't set to true
    await commands.js.run('performance.mark("test_pass");');

  } catch(error) {
    await commands.js.run('performance.mark("test_fail");');

  } finally {
    await commands.measure.stop();
  }

  return;
}
```

## Which version I'm using
9.3.4

## OS (if you use Docker, report the base OS)
sitespeedio/sitespeed.io:9.3.4, so whatever that uses

## Browser version (if you don't run Docker)
Google Chrome 75.0.3770.80

## error output
```
➜ docker run -it --rm -v $PWD/:/sitespeed.io/ sitespeedio/sitespeed.io:9.3.4 --config config.json multiple_tasks.js --multi --spa
Google Chrome 75.0.3770.80
Mozilla Firefox 67.0.1
[2019-07-03 23:11:25] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 9.3.4 browsertime: 5.2.6 coach: 3.6.0
[2019-07-03 23:11:25] INFO: Running tests using Chrome - 1 iteration(s)
[2019-07-03 23:11:27] INFO: Navigating to url https://google.com iteration 1
[2019-07-03 23:11:38] INFO: Start to measure google_search
starting next test
[2019-07-03 23:11:42] INFO: Navigating to url https://google.com iteration 1
[2019-07-03 23:11:51] INFO: Start to measure google_search
[2019-07-03 23:11:53] ERROR: Element by xpath //*[@id="resultStatsbarf] was not located in 3000 ms
[2019-07-03 23:11:53] INFO: https://www.google.com/search?source=hp&ei=IDYdXfavCZSu0PEPmfCHgAY&q=test&oq=test&gs_l=psy-ab.12..0l10.8946.8992..9735...0.0..0.208.787.0j1j3......0....1..gws-wiz.....0..0i131.oPNRPvRPVPk has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-03-23-11-25/chromeNetlog.json'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```
clearly, this file doesn't exist `/sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-03-22-22-38/chromeNetlog.json`, but a *similar* gzip file does, though it's deeper:
```
➜ ls sitespeed-result/multiple_tasks_js/2019-07-03-23-11-25/pages/www.google.com/search/query-98c005dc/data/
chromeNetlog-1.json.gz screenshots            video
```

**Comment by petemyron** [comment]
I should also say that running each try/catch individually works as expected (commenting out the other).

**Comment by soulgalore** [comment]
Hi @petemyron first for the pass/fail test: Is it possible to just [run JS and use the result](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#jsrunjavascript) in the script instead of catching/throwing? This is a simplified version but maybe something you can use, I think the scripting code will be easier to follow/use:

```
const secretValue = await commands.js.run('return 12');
if (secretValue === 12) {
// do
} else {

}

```

The error with the net log looks like a bug, let me have a go at fixing it, thanks for reporting!

Best
Peter

**Comment by soulgalore** [comment]
@petemyron I've pushed new version of Browsertime that at least fixes the problem when I tried. I'm gonna let it run for a day and release a sitespeed.io release tomorrow (or late today) with the fix.

**Comment by soulgalore** [comment]
@petemyron try out 9.5.0 hopefully that works for you!

**Comment by petemyron** [comment]
trying it out now, thanks! 

With regards to js.run, even doing `const element = await commands.js.run('document.getElementById(barf)'); // fail` will throw an error, so you can't compare `element` to `null` or whatever.

The error: `ERROR: Could not run JavaScript document.getElementById(resultStatsbarf)`

Here's what I tried:
```javascript
    // pass/fail test
    const element_is_found = false;

    // create a timeout
    var timeout = Date.now() + 3000;
    while (!element_is_found) {
      if (Date.now() < timeout) {
        // const element = await commands.js.run('document.getElementById(resultStats)'); // pass
        const element = await commands.js.run('document.getElementById(resultStatsbarf)'); // fail
        if (element != null) {
          element_is_found = true;
          await commands.measure.stop();
          await commands.js.run('performance.mark("test_pass")');
        }
      } else {
        console.log("timeout");
        await commands.js.run('performance.mark("test_fail")');
        break;
      }
    }
```

**Comment by petemyron** [comment]
regarding 9.5.0, that same multiple_tasks.js in the original post throws a different error:
```
[2019-07-05 21:44:30] ERROR: TypeError: Cannot set property 'screenshot' of undefined
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:181:36)
```

and the results do not upload to influx.

**Comment by soulgalore** [comment]
Hi @petemyron you need to add a return, else you just run the js, not returning the result to your script.

```
const element = await commands.js.run('return document.getElementById("nonExistsingID")');
if (element === null) {
 ...
}
```

For the new error, I need to test it.

Best
Peter

**Comment by petemyron** [comment]
Thanks @soulgalore, adding the `return` possibly fixed the specific `ERROR: Could not run JavaScript document.getElementById(resultStatsbarf)`, though I can't be sure. Results are still not uploaded to influx. 

That other error (`ERROR: TypeError: Cannot set property 'screenshot' of undefined`) might still be causing these other issues:

![image](https://user-images.githubusercontent.com/627937/60840862-46ad5e00-a185-11e9-8e2c-2e1417908e66.png)

![image](https://user-images.githubusercontent.com/627937/60841154-f4b90800-a185-11e9-9116-45e4989a8218.png)

![image](https://user-images.githubusercontent.com/627937/60841217-1a461180-a186-11e9-8bab-742fcd65f95b.png)

**Comment by soulgalore** [comment]
Hi @petemyron you mean the long name of the URL? If you test the same URL twice during a script it will get a new name so they don't collide. You can avoid that by giving each URL an alias (then its easier to understand what you test). Checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measurestartalias (I think we need more docs about alias).

For the screenshot thing I haven't had time to look at that yet.

Best
Peter

**Comment by petemyron** [comment]
Yep, that was the problem: using the same alias between two try/catch blocks 🤦‍♂. This works correctly in 9.5.0, but does not work in 9.3.4. My latest test script now looks like so:

```javascript
module.exports = async function(context, commands) {

  observe = async function(selector, pageName) {
    /* checks for the presence of a CSS selector on the page. Uses page
      name to append its success/failure as a separate measurement than
      the actual page being tested (unfortunately) :/
    */

    try {
      let element = await commands.js.run("return document.querySelector('" + selector + "')");

      if (element != null) {
        await commands.js.run('performance.mark("' + pageName + '_pass");');
      } else {
        await commands.js.run('performance.mark("' + pageName + '_fail");');
      }
    } catch(error) {
      console.log(error);
      await commands.js.run('performance.mark("' + pageName + '_fail");');
    }
  }

  console.log("\nstarting passing test");
  // successful result
  try {
    await commands.navigate('https://google.com');
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search_1');
    await commands.click.bySelector('input.gNO89b'); // click search button

    // pass/fail test
    await observe('#resultStats', 'google_search_1');

  } catch(error) {
    console.log("wtf, google search failed");
    console.log(error);

  } finally {
    await commands.measure.stop();
  }



  console.log("\nstarting failing test");
  // intentionally failing result
  try {
    await commands.navigate('https://google.com');
    await commands.addText.bySelector('test', 'input.gLFyf.gsfi');
    await commands.measure.start('google_search_2');
    await commands.click.bySelector('input.gNO89b'); // click search button

    // pass/fail test
    await observe('#barf', 'google_search_2'); // should fail unless you search for #barf, weirdo...

  } catch(error) {
    console.log("wtf, google search failed");
    console.log(error);

  } finally {
    await commands.measure.stop();
  }

  console.log("\nresults:");
  return;
}
```

and you can then do some really ugly stuff in grafana to show these data points, and further add alerting on the explicit pass/fail results:
![image](https://user-images.githubusercontent.com/627937/61092408-fa6b5380-a3fa-11e9-8345-b83e19dce027.png)

and the results show up on the individual html reports like so:
![image](https://user-images.githubusercontent.com/627937/61092427-13740480-a3fb-11e9-9df5-996acedc649e.png)

Down at the bottom of the Timings Summary ("google_search_2_fail" in this case):
![image](https://user-images.githubusercontent.com/627937/61092444-24247a80-a3fb-11e9-8396-61ca2c5924f5.png)

and the log output will be like so:
```
➜ docker run -it --rm -v $PWD/:/sitespeed.io/ sitespeedio/sitespeed.io:9.5.0 --config config.json multiple_tasks.js --multi --spa
Google Chrome 75.0.3770.80
Mozilla Firefox 67.0.1
[2019-07-11 23:41:26] INFO: Versions OS: linux 4.9.125-linuxkit nodejs: v10.13.0 sitespeed.io: 9.5.0 browsertime: 5.4.1 coach: 3.6.0
[2019-07-11 23:41:27] INFO: Running tests using Chrome - 1 iteration(s)

starting passing test
[2019-07-11 23:41:28] INFO: Navigating to url https://google.com iteration 1
[2019-07-11 23:41:36] INFO: Start to measure google_search_1

starting failing test
[2019-07-11 23:41:40] INFO: Navigating to url https://google.com iteration 1
[2019-07-11 23:41:48] INFO: Start to measure google_search_2

results:
[2019-07-11 23:41:58] INFO: https://www.google.com/search?source=hp&ei=KMknXdDOHIrh-gSfnq3ADw&q=test&oq=test&gs_l=psy-ab.12..0l10.7397.7464..8218...0.0..0.102.379.3j1......0....1..gws-wiz.....0..0i131.Huwl_mZTN78 19 requests, 331.75 kb, backEndTime: 115ms, firstPaint: 238ms, firstVisualChange: 267ms, DOMContentLoaded: 746ms, Load: 1.35s, speedIndex: 373, visualComplete85: 600ms, lastVisualChange: 600ms, rumSpeedIndex: 238
[2019-07-11 23:41:58] INFO: https://www.google.com/search?source=hp&ei=NMknXa_wG4LI-gSZwqyABw&q=test&oq=test&gs_l=psy-ab.12..0l10.7310.7359..7963...0.0..0.95.348.4......0....1..gws-wiz.....0..0i131.Q3LlfvG-ayA 9 requests, 86.54 kb, backEndTime: 95ms, firstPaint: 237ms, firstVisualChange: 66ms, DOMContentLoaded: 320ms, Load: 634ms, speedIndex: 266, visualComplete85: 333ms, lastVisualChange: 333ms, rumSpeedIndex: 237
[2019-07-11 23:42:01] INFO: HTML stored in /sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-11-23-41-26
[2019-07-11 23:42:01] INFO: Uploading /sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-11-23-41-26 to S3 bucket whatever-bucket, this can take a while ...
[2019-07-11 23:42:02] INFO: Finished upload to s3
[2019-07-11 23:42:02] INFO: Find the result at http://whatever-bucket.s3-website-us-west-2.amazonaws.com/multiple_tasks_js/2019-07-11-23-41-26
```

Just to be (ridiculously) thorough, 9.3.4 fails like this:
```
[2019-07-11 23:46:55] INFO: Start to measure google_search_2
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/sitespeed.io/sitespeed-result/multiple_tasks_js/2019-07-11-23-46-32/chromeNetlog.json'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```
