### ISSUE TITLE
Not seeing response bodies in waterfall even though chrome.includeResponseBodies is set to "all"

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#2581]
Dockerized sitespeed.io v 9.8.1

Config:
  "chrome": {
    "cdp.performance": "true",
    "collectConsoleLog": "true",
    "collectLongTasks": "true",
    "includeResponseBodies": "all",
    "timeline": "true"
  }

I have tried both "html" and "all", but neither have the desired result. Firefox exhibits the same result with firefox.includeResponseBodies set to either of those values.

**Comment by soulgalore** [comment]
And you don't get any errors in the log? If Chrome can't match the request it should log an error.

The 'html' works in our continuous tests here: https://s3.amazonaws.com/results.sitespeed.io/en.m.wikipedia.org/2019-08-19-20-55-05/pages/en.m.wikipedia.org/wiki/Barack_Obama/index.html#waterfall so I wonder what it can be.

Best
Peter

**Comment by leathej1** [comment]
Sorry - I didn't realize this was the associated error:
```
[2019-08-19 21:28:57] ERROR: Could not find a matching resource to get the HTML Error: No resource with given identifier found
    at _enqueueCommand (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:90:34)
    at Chrome._handleMessage (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:252:17)
    at WebSocket._ws.on (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.EventEmitter.emit (domain.js:442:20)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:422:14)
    at perMessageDeflate.decompress (/usr/src/app/node_modules/ws/lib/receiver.js:379:23)
    at _decompress (/usr/src/app/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (/usr/src/app/node_modules/ws/lib/permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:480:3)
    at onwrite (_stream_writable.js:471:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:619:8)
```

**Comment by leathej1** [comment]
I believe the issue is that we have a valid vendor specific mime type ('application/vnd.myco.authn-v1.0+json'), and you are looking for a specific pattern in the browsertime code. Maybe a bit of regex would help those of us in this situation.

**Comment by soulgalore** [comment]
Hi @leathej1 sorry for being slow on this. Yes we have the same problem in PageXray when we are identifying mime types. If you have time to do a more intelligent solution that would be great (I can then port it to the other project).

Best
Peter

**Comment by soulgalore** [comment]
This is fixed .. but there seems to be some bugs maybe in CDP for Chrome. Closing this though since the original issue is fixed.
