### ISSUE TITLE
webpagetest runs successfully, but won't collect metrics: Error creating WebPageTest result  TypeError: filterForType[type].push is not a function

### ISSUE THREAD

**Issue by bkarlson** [sitespeedio/sitespeed.io#2642]
All tests run fine, and I can see WPT results on their webiste, but SS is unable to ingest the results, see error below. I tried to figure out what's up, my only thought is some   `"metrics": {
    "filter": [` issue in sitespeed.json, but adding `      "webpagetest.*",` did not help.

Log:

```
[2019-09-16 00:45:41] INFO: Versions OS: linux 4.14.109-80.92.amzn1.x86_64 nodejs: v12.10.0 sitespeed.io: 10.0.2 browsertime: 6.0.3 coach: 4.0.1

ERROR: Error creating WebPageTest result  TypeError: filterForType[type].push is not a function
    at Object.addFilterForType (/sitespeed.io/lib/support/filterRegistry.js:20:27)
    at addCustomMetric (/sitespeed.io/lib/plugins/webpagetest/index.js:67:22)
    at /sitespeed.io/lib/plugins/webpagetest/index.js:184:13
```

**Comment by bkarlson** [comment]
sitespeed.json:

```json
{
  "scripts": [],
  "browsertime": {
    "xvfb": true,
    "delay": 0,
    "browser": "chrome",
    "screenshot": true,
    "screenshotParams": {
      "type": "jpg",
      "png": {
        "compressionLevel": 6
      },
      "jpg": {
        "quality": 50
      },
      "maxSize": 2000
    },
    "viewPort": "1280x768"
  },
  "videoParams": {
    "addTimer": true,
    "filmstripFullSize": false,
    "createFilmstrip": true,
    "framerate": 10,
    "crf": 23,
    "filmstripQuality": 25
  },
  "html": {
    "fetchHARFiles": true
  },
  "gzipHAR": true,
  "skipHAR": true,
  "summary-detail": true,
  "summaryDetail": true,
  "useHash": true,
  "statistics": true,
  "spa": false,
  "pageCompleteCheckInactivity": false,
  "visualMetrics": true,
  "visualElements": true,
  "video": true,
  "firefox": {
    "nightly": false,
    "beta": false,
    "developer": false,
    "acceptInsecureCerts": false,
    "collectMozLog": false,
    "includeResponseBodies": "none"
  },
  "chrome": {
    "timeline": true,
    "collectNetLog": false,
    "collectTracingEvents": false,
    "collectConsoleLog": true,
    "cdp": {
      "performance": true
    },
    "binaryPath": "/usr/bin/google-chrome-stable",
    "args": []
  },
  "headless": false,
  "cacheClearRaw": true,
  "pageCompleteWaitTime": 15000,
  "pageLoadStrategy": "normal",
  "mobile": false,
  "screenshotType": "jpg",
  "coach": true,
  "metrics": {
    "filter": [
      "*-",
      "largestassets.summary.image.0.transferSize",
      "browsertime.pageSummary.statistics.timings.pageTimings",
      "browsertime.pageSummary.statistics.timings.rumSpeedIndex",
      "browsertime.pageSummary.statistics.timings.fullyLoaded",
      "browsertime.pageSummary.statistics.timings.firstPaint",
      "browsertime.pageSummary.statistics.timings.timeToDomContentFlushed",
      "browsertime.pageSummary.statistics.timings.timeToContentfulPaint",
      "browsertime.pageSummary.statistics.timings.timeToFirstInteractive",
      "browsertime.pageSummary.statistics.timings.loadEventEnd",
      "browsertime.pageSummary.statistics.timings.userTimings",
      "browsertime.pageSummary.statistics.timings.paintTiming",
      "browsertime.pageSummary.statistics.visualMetrics.Heading",
      "browsertime.pageSummary.statistics.visualMetrics.LargestImage",
      "browsertime.pageSummary.statistics.visualMetrics.VisualComplete95",
      "browsertime.pageSummary.statistics.visualMetrics.VisualComplete85",
      "browsertime.pageSummary.statistics.visualMetrics.SpeedIndex",
      "browsertime.pageSummary.statistics.visualMetrics.PerceptualSpeedIndex",
      "browsertime.pageSummary.statistics.visualMetrics.FirstVisualChange",
      "browsertime.pageSummary.statistics.custom.*",
      "browsertime.pageSummary.statistics.console.error",
      "browsertime.pageSummary.statistics.console.warning",
      "browsertime.pageSummary.statistics.cpu.categories.*",
      "browsertime.pageSummary.statistics.cpu.events.*",
      "browsertime.pageSummary.statistics.cdp.performance.RecalcStyleCount",
      "browsertime.summary.firstPaint",
      "browsertime.summary.rumSpeedIndex",
      "browsertime.summary.timeToDomContentFlushed",
      "browsertime.summary.fullyLoaded",
      "browsertime.summary.pageTimings",
      "browsertime.summary.userTimings.marks",
      "browsertime.summary.userTimings.measures",
      "browsertime.summary.visualMetrics.Heading",
      "browsertime.summary.visualMetrics.LargestImage",
      "browsertime.summary.visualMetrics.VisualComplete95",
      "browsertime.summary.visualMetrics.VisualComplete85",
      "browsertime.summary.visualMetrics.SpeedIndex",
      "browsertime.summary.visualMetrics.PerceptualSpeedIndex",
      "browsertime.summary.visualMetrics.FirstVisualChange",
      "browsertime.summary.custom.*",
      "coach.summary.score.*",
      "coach.summary.performance.score.*",
      "coach.summary.privacy.score.*",
      "coach.summary.bestpractice.score.*",
      "coach.summary.accessibility.score.*",
      "coach.pageSummary.advice.score",
      "coach.pageSummary.advice.performance.score",
      "coach.pageSummary.advice.privacy.score",
      "coach.pageSummary.advice.bestpractice.score",
      "coach.pageSummary.advice.accessibility.score",
      "coach.pageSummary.advice.info.documentHeight",
      "coach.pageSummary.advice.info.domElements",
      "coach.pageSummary.advice.info.domDepth",
      "coach.pageSummary.advice.info.iframes",
      "coach.pageSummary.advice.info.scripts",
      "coach.pageSummary.advice.info.localStorageSize",
      "pagexray.pageSummary.contentTypes",
      "pagexray.pageSummary.transferSize",
      "pagexray.pageSummary.contentSize",
      "pagexray.pageSummary.requests",
      "pagexray.pageSummary.firstParty",
      "pagexray.pageSummary.thirdParty",
      "pagexray.pageSummary.responseCodes",
      "pagexray.pageSummary.expireStats",
      "pagexray.pageSummary.totalDomains",
      "pagexray.pageSummary.lastModifiedStats",
      "pagexray.pageSummary.cookieStats",
      "pagexray.summary.contentTypes",
      "pagexray.summary.transferSize",
      "pagexray.summary.contentSize",
      "pagexray.summary.requests",
      "pagexray.summary.firstParty",
      "pagexray.summary.thirdParty",
      "pagexray.summary.responseCodes",
      "pagexray.summary.expireStats",
      "pagexray.summary.domains",
      "pagexray.summary.lastModifiedStats",
      "pagexray.summary.cookieStats",
      "thirdparty.pageSummary.category.*.requests.*",
      "thirdparty.pageSummary.category.*.tools.*",
      "webpagetest.*",
      "webpagetest.pageSummary.data.median.firstView.visualComplete",
      "thirdparty.pageSummary.category.*.requests.*",
      "thirdparty.pageSummary.category.*.tools.*",
      "thirdparty.pageSummary.requests.*",
      "lighthouse.pageSummary.categories.seo.score",
      "lighthouse.pageSummary.categories.performance.score",
      "lighthouse.pageSummary.categories.pwa.score",
      "lighthouse.pageSummary.categories.accessibility.score",
      "lighthouse.pageSummary.categories.best-practices.score"
    ]
  }
}

```

**Comment by soulgalore** [comment]
Hi @bkarlson sorry I missed this issue. I would try with other filter setting to try to pinpoint what's produce the error (like first finding out which tool and then which metric).

Best
Peter

**Comment by soulgalore** [comment]
Closing but please get back if this wasn't solved.
