### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined - chrome-har

### ISSUE THREAD

**Issue by abdohafez** [sitespeedio/sitespeed.io#2645]
Greetings,

I'm getting the following error when running sitespeed 

`[2019-09-18 12:03:41] ERROR: [browsertime] TypeError: Cannot read property 'content' of undefined
    at Object.harFromMessages (/usr/src/app/node_modules/chrome-har/index.js:345:28)
    at ChromeDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:380:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-09-18 12:03:41] DEBUG: [browsertime] Kill all processes ffmpeg
[2019-09-18 12:03:41] DEBUG: [browsertime] Closed the browser.`

Docker run

`docker run $DOCKER_SETUP $DOCKER_CONTAINER $NAMESPACE $INTERACTIVE $CONFIG/desktop.json $PRESCRIPT -b $browser $url`

My configuration is as the following:

Sitespeed Version: sitespeed.io:10.0.1-plus1
Base OS: Linux 
Config File:
`{
  "browsertime": {
    "browser": "chrome",
    "chrome": {
      "collectConsoleLog": true,
      "enableTraceScreenshots": true
    },
    "connectivity": {
      "engine": "throttle",
      "profile": "cable"
    },
    "iterations": 3,
    "speedIndex": true,
    "video": true,
    "visualElements": true,
    "visualMetrics": true
  },
  "cpu": true,
  "extends": "secrets.json",
  "gzipHAR": true,
  "html": {
    "fetchHARFiles": true,
    "showScript": true
  },
  "screenshot": {
    "type": "jpg"
  },
  "summary-detail": "true",
  "thirdParty": {
    "cpu": true
  },
  "verbose": true
}`

**Comment by soulgalore** [comment]
Hi @abdohafez,
it looks like there are some content that we don't handle or rather Chrome-har handles correctly. Any chance you can share the URL? Or even better if you can do a run and add `--browsertime.chrome.collectPerfLog ` - that will produce the Chrome log we use to create the HAR. If you can share that file with me, I can reproduce the issue and fix the problem.

Best
Peter

**Comment by abdohafez** [comment]
Thank you for your prompt response. 

Here is a link to the chromePerflog files [https://drive.google.com/file/d/1-mindN5mLAfu178jpchrT5HvDGeVKeRW/view?usp=sharing](url)

I'm also getting the following error also from chrome-har

`ERROR: [browsertime] TypeError: Cannot set property 'receive' of undefined
    at Object.harFromMessages (/usr/src/app/node_modules/chrome-har/index.js:373:29)
    at ChromeDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:380:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

`[plugin.browsertime] Could not find the right index 2 for har for url
 ERROR: [sitespeedio.queuehandler] Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:200:29)`

Thank you again.

**Comment by soulgalore** [comment]
Thank you @abdohafez I've did a fix this weekend, tested earlier today and it works with your traces, gonna do a release hopefully tomorrow.

For the other error I need the user journey so I can reproduce. 

Best
Peter

**Comment by abdohafez** [comment]
Hello @soulgalore, 

I no longer see the errors after the release. I guess they were related.

Thank you very much for your help.
