### ISSUE TITLE
Data not populating in grafana

### ISSUE THREAD

**Issue by shubh1212** [sitespeedio/sitespeed.io#2655]
Below is my code that i am executing, even the job is succeeding successfully and reports are getting generated, but the grafana results are not updating through graphite.
please help: 

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:10.0.2 $f  --multi --outputFolder results/$f --graphite.host graphite.webdriver-timings --graphite.port 2003  --connectivity cable --visualMetrics true --metrics.filterList --metrics.filter *- browsertime.summary.visualMetrics.* --debug

**Comment by guoerwei** [comment]
Hi @soulgalore 

I think I've got a similar issue,
my docker-compose.yml looks like this:

```yml
version: '3'
services:

  sitespeed.io:
    image: sitespeedio/sitespeed.io:9.8.1
    command: -V
    shm_size: 1g
    volumes:
      - ../volumes/sitespeed-result/:/sitespeed.io/sitespeed-result

  graphite:
    image: sitespeedio/graphite:1.1.5-12
    ports:
      - '2003:2003'
      - '8080:80'
    restart: always
    volumes:
      - ../volumes/whisper:/opt/graphite/storage/whisper
      - ../volumes/graphite/graphite.db:/opt/graphite/storage/graphite.db
      - ../volumes/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ../volumes/graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - ../volumes/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf

  grafana:
    image: grafana/grafana:6.3.5
    depends_on:
      - graphite
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=xxx
      - GF_SECURITY_ADMIN_USER=xxx
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    restart: always
    volumes:
      - ../volumes/grafana:/var/lib/grafana

  grafana-setup:
    image: sitespeedio/grafana-bootstrap:10.0.0
    depends_on:
      - grafana
    environment:
      - GF_PASSWORD=xxx
      - GF_USER=xxx
```
I can see many folders are created in `../volumes/whisper`, but they are all empty.

Some error logs from the container:

```
25/09/2019 09:19:10 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/graphite/lib/carbon/writer.py", line 189, in writeForever
    writeCachedDataPoints()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/writer.py", line 142, in writeCachedDataPoints
    state.database.create(metric, archiveConfig, xFilesFactor, aggregationMethod)
  File "/opt/graphite/lib/carbon/database.py", line 145, in create
    self.sparse_create, self.fallocate_create)
  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 528, in create
    fallocate(fh, headerSize, remaining)
  File "/opt/graphite/lib/python3.7/site-packages/whisper.py", line 93, in _py_fallocate
    raise IOError(res, 'fallocate')
builtins.OSError: [Errno 95] fallocate

25/09/2019 09:19:10 :: [console] Error creating stats.gauges.statsd.timestamp_lag: [Errno 95] fallocate
25/09/2019 09:19:10 :: [console] Unhandled Error
Traceback (most recent call last):
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/graphite/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/graphite/lib/carbon/writer.py", line 189, in writeForever
    writeCachedDataPoints()
```

**Comment by soulgalore** [comment]
Hi @guoerwei do you see if you get any metrics at all? I've got that Graphite version up and running on AWS and I can see that it works there. When you are mapping the volumes `../volumes/whisper:/` are you sure it works with relative paths? It could but I've always used absolute.

Best
Peter

**Comment by guoerwei** [comment]
Hi @soulgalore 
Folders are created in `../volumes/whisper/` but no data files at all.
I think there's something wrong with relative paths, it worked when using named volume instead of relative paths, or just use `sitespeedio/graphite:latest` image.

I also tried absolute path like `/tmp/whisper:/opt/graphite/storage/whisper`, and again, getting a lot of folders without any data file.

**Comment by soulgalore** [comment]
If you try without mounting setup files like:
```
    - ../volumes/graphite/graphite.db:/opt/graphite/storage/graphite.db
      - ../volumes/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ../volumes/graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - ../volumes/graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
```

Does it work then? Just trying to nail down the issue.

**Comment by guoerwei** [comment]
still the same, only works when using named volume for whisper

**Comment by soulgalore** [comment]
@guoerwei what's your host OS? I was thinking it could be a permission thing but it can create the directories right?

**Comment by guoerwei** [comment]
macOS 10.14.4
yes, directories were created

**Comment by soulgalore** [comment]
Yep I get the same on OS X.  I think you should ask on https://github.com/graphite-project if you plan to run Graphite on OS X (I've always used Linux for that).

**Comment by soulgalore** [comment]
So the learnings here is that mounting a disk on OS X in Graphite doesn't work.

For your original question @shubh1212 please let me know if it doesn't work for you and we can re-open the issue.
