### ISSUE TITLE
EPERM error on visualmetrics.py

### ISSUE THREAD

**Issue by MaximSergeichik** [sitespeedio/sitespeed.io#2665]
I'm running sitespeed.io 10.1.0 via node on CentOS machine.
The output log is below

`INFO: Versions OS: linux 3.10.0-1062.el7.x86_64 nodejs: v10.16.0 sitespeed.io: 10.1.0 browsertime: 6.1.0 coach: 4.0.1
[2019-10-01 08:28:34] INFO: Running tests using Chrome - 1 iteration(s)
[2019-10-01 08:28:34] INFO: Testing url https://se.com/ iteration 1
[2019-10-01 08:28:49] ERROR: Visual Metrics failed to analyse the video Error: Command failed with exit code 1 (EPERM): /home/user/node_modules/sitespeed.io/node_modules/browsertime/vendor/visualmetrics.py --dir /app/results/debug/native/2019-10-01-08-28-32/pages/se.com/data/filmstrip/1 --video /app/results/debug/native/2019-10-01-08-28-32/pages/se.com/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport -q 75
    at makeError (/home/user/node_modules/sitespeed.io/node_modules/browsertime/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/user/node_modules/sitespeed.io/node_modules/browsertime/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-01 08:28:49] INFO: https://se.com/ 195 requests, backEndTime: 443ms, firstPaint: 773ms, DOMContentLoaded: 1.03s, Load: 2.20s, rumSpeedIndex: 773
[2019-10-01 08:28:49] INFO: Send annotation to Influx: "events title=\"Sitespeed.io\",text=\"<a href='http://results.server.se.com/debug/native/2019-10-01-08-28-32/2019-10-01-08-28-32/pages/se.com/index.html' target='_blank'><img src='http://results.server.se.com/debug/native/2019-10-01-08-28-32/2019-10-01-08-28-32/pages/se.com/data/screenshots/1.png' width=100%></a><p><a href='http://results.server.se.com/debug/native/2019-10-01-08-28-32/2019-10-01-08-28-32/pages/se.com/index.html'>Result</a> - <a href='http://results.server.se.com/debug/native/2019-10-01-08-28-32/2019-10-01-08-28-32/pages/se.com/data/browsertime.har'>Download HAR</a></p>\",tags=\"native,chrome,se_com,_,debug,native\" 1569918530"
[2019-10-01 08:28:51] INFO: HTML stored in /app/results/debug/native/2019-10-01-08-28-32
[2019-10-01 08:28:51] INFO: Find the result at http://results.server.se.com/debug/native/2019-10-01-08-28-32/2019-10-01-08-28-32`

Does this error mean that node js can not run visualmetrics.py script or this script can not access some of the necessary resources?

Cheers,
Maksim

**Comment by soulgalore** [comment]
Hi @MaximSergeichik yes something like that. 

I did a fix some time ago https://github.com/sitespeedio/browsertime/issues/911 where I removed our internal use of OS tmp dir (so we only store files within the directory we creates ourself). But my guess is that https://github.com/WPO-Foundation/visualmetrics also uses the OS tmp dir internally? I think I remember that it used to do that. I wonder should be a common thing, we should be able to find other people with that problem? Else maybe we can do PR to Visual Metrics to make it configurable, but it would be good to know 100% sure first.

If you turn on verbose logging (`--verbose`) you should get a log file with all info from Visual Metrics named somnething like .visualmetrics.log. Can you try that and see if we can see any more detailed information?

Best
Peter

**Comment by MaximSergeichik** [comment]
Hi @soulgalore ,

The root cause of the error is missing libraries for the visualmetrics.py.
There are pyssim and Pillow libs should be installed.

I'm closing the issue.

Cheers,
Maksim
