### ISSUE TITLE
Axe.enable causes stacktrace with graphite.host

### ISSUE THREAD

**Issue by t-pascal** [sitespeedio/sitespeed.io#2670]
Using latest version 10.1.1 in the docker container from master, combining axe.enable with graphite.host causes a stacktrace.

```
# ./start.sh --graphite.statsd=true --graphite.host=localhost --browsertime.axe.enable --cpu --browsertime.iterations=1 https://www.exampl
e.com/
Google Chrome 77.0.3865.75
Mozilla Firefox 69.0
[2019-10-01 20:14:02] INFO: Versions OS: linux 4.15.0-1041-aws nodejs: v10.16.0 sitespeed.io: 10.1.0 browsertime: 6.1.1 coach: 4.0.1
[2019-10-01 20:14:02] INFO: Running tests using Chrome - 1 iteration(s)
[2019-10-01 20:14:02] INFO: Testing url https://www.example.com/ iteration 1
[2019-10-01 20:14:11] INFO: https://www.example.com/ 2 requests, backEndTime: 102ms, firstPaint: 134ms, firstVisualChange: 134ms, DOMContentLoaded: 126ms, Load: 126ms, speedIndex: 134, visualComplete85: 134ms, lastVisualChange: 134ms, rumSpeedIndex: 134
[2019-10-01 20:14:11] ERROR: Error: No data to send to graphite for message:
{
  "uuid": "e5f5710d-9eb8-4dfa-b6f1-465e1b6bb1fc",
  "type": "axe.pageSummary",
  "timestamp": "2019-10-01T20:14:11+00:00",
  "source": "browsertime",
  "data": {
    "violations": {}
  },
  "url": "https://www.example.com/",
  "group": "www.example.com"
}
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:156:9)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-10-01 20:14:11] ERROR: TypeError: Cannot read property 'median' of undefined
    at module.exports (/usr/src/app/lib/plugins/html/setup/summaryBoxes.js:139:41)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:77:26)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:211:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I had statsd=true, but the same happens without (I didn't have a graphite server available at test time, ignore the ECONNREFUSED for now):

```
# ./start.sh --graphite.host=localhost --browsertime.axe.enable --browsertime.iterations=1 https://www.example.com/
Google Chrome 77.0.3865.75
Mozilla Firefox 69.0
[2019-10-01 20:14:44] INFO: Versions OS: linux 4.15.0-1041-aws nodejs: v10.16.0 sitespeed.io: 10.1.0 browsertime: 6.1.1 coach: 4.0.1
[2019-10-01 20:14:44] INFO: Running tests using Chrome - 1 iteration(s)
[2019-10-01 20:14:45] INFO: Testing url https://www.example.com/ iteration 1
[2019-10-01 20:14:54] INFO: https://www.example.com/ 2 requests, backEndTime: 103ms, firstPaint: 134ms, firstVisualChange: 134ms, DOMContentLoaded: 124ms, Load: 125ms, speedIndex: 134, visualComplete85: 134ms, lastVisualChange: 134ms, rumSpeedIndex: 134
[2019-10-01 20:14:54] ERROR: Error: No data to send to graphite for message:
{
  "uuid": "8aca19ab-8303-4706-88f2-9598aaa009f5",
  "type": "axe.pageSummary",
  "timestamp": "2019-10-01T20:14:54+00:00",
  "source": "browsertime",
  "data": {
    "violations": {}
  },
  "url": "https://www.example.com/",
  "group": "www.example.com"
}
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:156:9)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: Error: connect ECONNREFUSED 127.0.0.1:2003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[2019-10-01 20:14:54] ERROR: TypeError: Cannot read property 'median' of undefined
    at module.exports (/usr/src/app/lib/plugins/html/setup/summaryBoxes.js:139:41)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:77:26)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:211:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Also, "median" is missing but even iterations 3 doesn't work (just verifying the same):

```
# ./start.sh --graphite.statsd=true --graphite.host=localhost --browsertime.axe.enable --browsertime.iterations=3 https://www.example.com/
Google Chrome 77.0.3865.75
Mozilla Firefox 69.0
[2019-10-01 20:13:21] INFO: Versions OS: linux 4.15.0-1041-aws nodejs: v10.16.0 sitespeed.io: 10.1.0 browsertime: 6.1.1 coach: 4.0.1
[2019-10-01 20:13:21] INFO: Running tests using Chrome - 3 iteration(s)
[2019-10-01 20:13:22] INFO: Testing url https://www.example.com/ iteration 1
[2019-10-01 20:13:31] INFO: https://www.example.com/ BackEndTime: 105 DomInteractiveTime: 119 DomContentLoadedTime: 119 FirstPaint: 143 PageLoadTime: 119
[2019-10-01 20:13:31] INFO: VisualMetrics FirstVisualChange: 167 SpeedIndex: 167 PerceptualSpeedIndex: 167 LastVisualChange: 167
[2019-10-01 20:13:31] INFO: Testing url https://www.example.com/ iteration 2
[2019-10-01 20:13:40] INFO: https://www.example.com/ BackEndTime: 103 DomInteractiveTime: 123 DomContentLoadedTime: 123 FirstPaint: 133 PageLoadTime: 124
[2019-10-01 20:13:40] INFO: VisualMetrics FirstVisualChange: 134 SpeedIndex: 134 PerceptualSpeedIndex: 134 LastVisualChange: 134
[2019-10-01 20:13:41] INFO: Testing url https://www.example.com/ iteration 3
[2019-10-01 20:13:50] INFO: https://www.example.com/ BackEndTime: 101 DomInteractiveTime: 123 DomContentLoadedTime: 123 FirstPaint: 132 PageLoadTime: 123
[2019-10-01 20:13:50] INFO: VisualMetrics FirstVisualChange: 134 SpeedIndex: 134 PerceptualSpeedIndex: 134 LastVisualChange: 134
[2019-10-01 20:13:50] INFO: https://www.example.com/ 2 requests, backEndTime: 103ms (±0.94ms), firstPaint: 136ms (±2.87ms), firstVisualChange: 145ms (±8.98ms), DOMContentLoaded: 122ms (±1.09ms), Load: 122ms (±1.25ms), speedIndex: 145 (±8.98), visualComplete85: 145ms (±8.98ms), lastVisualChange: 145ms (±8.98ms), rumSpeedIndex: 136 (±2.87) (3 runs)
[2019-10-01 20:13:50] ERROR: Error: No data to send to graphite for message:
{
  "uuid": "5a63acdd-dbdf-49d5-ae2e-0ed9346ed86e",
  "type": "axe.pageSummary",
  "timestamp": "2019-10-01T20:13:50+00:00",
  "source": "browsertime",
  "data": {
    "violations": {}
  },
  "url": "https://www.example.com/",
  "group": "www.example.com"
}
    at Object.processMessage (/usr/src/app/lib/plugins/graphite/index.js:156:9)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-10-01 20:13:50] ERROR: TypeError: Cannot read property 'median' of undefined
    at module.exports (/usr/src/app/lib/plugins/html/setup/summaryBoxes.js:139:41)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:77:26)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:211:35)
    at queue.process.message (/usr/src/app/lib/core/queueHandler.js:211:32)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by soulgalore** [comment]
Hi @t-pascal hmm let me look into it but first there's thing you can do: the cli parameter `--browsertime.axe.enable` should only be `--axe.enable` since it is only implemented in sitespeed.io (all params names browserstime.* is passed on to Browsertime). Do you remember where you got it from, it could be that some docs are wrong somewhere,

Best
Peter

**Comment by t-pascal** [comment]
Sir, you are correct. `--axe.enable` works but `--browsertime.axe.enable` does not. I got it from the docs here: https://www.sitespeed.io/documentation/sitespeed.io/configuration/ which probably comes from here: https://github.com/sitespeedio/sitespeed.io/blame/master/docs/documentation/sitespeed.io/configuration/config.md#L35

So it's merely a documentation issue I suppose, unless there's some reason you want to support both with `--browsertime…` and without. There are a lot of options that work with either one. Maybe investigate/canonicalize all the options that support both methods?

**Comment by t-pascal** [comment]
I find `--cpu` and `--browsertime.cpu` and `--thirdParty.cpu` needlessly confusing, for example. https://github.com/sitespeedio/sitespeed.io/blame/master/docs/documentation/sitespeed.io/configuration/config.md#L72-L73

I also think this is a bug? Sorry! 😄 https://github.com/sitespeedio/sitespeed.io/blame/master/docs/documentation/sitespeed.io/configuration/config.md#L213

Thanks in advance for fixing the docs and sorry to be a pest!

**Comment by soulgalore** [comment]
I've pushed a fix for the config, going out in the next release.

Yeah CPU is confusing `--cpu `and `--browsertime.cpu` means the same. `--thirdParty.cpu` enables sending CPU data for third parties to Graphite, since that can generate a lot of data in Graphite. I'll update the text for the next release.

Is it URL vs Url? It's because of a the behaviour in yargs see https://github.com/sitespeedio/sitespeed.io/issues/2663

**Comment by t-pascal** [comment]
Ah, I got you, URL vs Url, thanks! You're the best.
