### ISSUE TITLE
Unable to start Android session on remote server (Browserstack)

### ISSUE THREAD

**Issue by sk13man** [sitespeedio/sitespeed.io#2712]
sitespeed.io version = 10.2.0
iOS = Catalina 10.15

Trying to run simple test 
`module.exports = async function (context, commands) {
    return  commands.measure.start('https://google.com');
};`

### speedsite.config.json 
`{
  "browsertime":{
    "iterations": 1,
    "selenium": {
      "url": "http://user:key@hub-cloud.browserstack.com/wd/hub",
      "capabilities": {
        "browserName" : "chrome",
        "device" : "SamsungGalaxyS8",
        "realMobile" : "true",
        "browserstack.console":"info",
        "browserstack.networkLogs": true,
        "browserstack.appium_version" : "1.6.5",
        "name": "Sitespeed.io performance audit",
        "enablePerformanceLogging": true
      }
    },

    "visualMetrics": false,
    "video": false,
    "headless": false,
    "screenshot": true
  }
}
`
### Running with NPM script
`    "test:perf": "sitespeed.io ./src/integration/performance/perf.js -n=1 --config=speedtest.config.json --multi",
`

### Got an error 
`[2019-10-22 18:03:30] ERROR: [browsertime] BrowserError: Appium error: unknown error: unhandled inspector error: {"code":-32601,"message":"'Browser.setWindowBounds' wasn't found"}
  (Session info: chrome=76.0.3809.89)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Linux 3.19.8-100.fc20.x86_64 x86_64)
  (Session info: chrome=76.0.3809.89)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Linux 3.19.8-100.fc20.x86_64 x86_64)
    at SeleniumRunner.start (/Users/sk13man/Documents/GitHub/qa_automation_ts/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-22 18:03:33] DEBUG: [browsertime] Closed the browser.
[2019-10-22 18:03:33] ERROR: [browsertime] No data to collect
`
Link to Appium logs - [https://gist.github.com/sk13man/26c640060d184aa35d60105eae22065c](url)

If added android : true to config - got another error 
`[2019-10-22 18:12:18] INFO: Versions OS: darwin 19.0.0 nodejs: v10.16.3 sitespeed.io: 10.2.0 browsertime: 6.1.3 coach: 4.0.2
[2019-10-22 18:12:18] ERROR: TypeError: Cannot read property 'id' of undefined
    at Android.initConnection (/Users/sk13man/Documents/GitHub/qa_automation_ts/node_modules/sitespeed.io/node_modules/browsertime/lib/android/index.js:20:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by soulgalore** [comment]
Hi @sk13man yeah, I think has changed over time. I think a flag to turn off setting the window position should do it.

Best
Peter
