### ISSUE TITLE
"Unknown input format: x11grab" on Windows natively

### ISSUE THREAD

**Issue by SGunase2** [sitespeedio/sitespeed.io#2719]
I currently run sitespeed on windows using Docker just fine. I tried to run it natively using node and installed visual metrics dependency (since I can’t use docker in my use case). Every time I run the script, I receive an error 'Unknown input format: \'x11grab\''. I tried to change 'x11grab' format to windows supported 'gdigrab' by modifying ffmpegRecorder.js file, but the video format is not overridden and I get the same error. 

How I run:
\~\visualmetrics>"~\npm\sitespeed.io.cmd" --config \path\to\config.json \path\to\file.js --multi
 
Error result:
[2019-10-21 15:05:14] INFO: Versions OS: win32 10.0.18362 nodejs: v10.16.3 sitespeed.io: 10.3.0 browsertime: 6.1.4 coach: 4.1.0
[2019-10-21 15:05:15] INFO: Running tests using Chrome - 1 iteration(s)
DevTools listening on ws://127.0.0.1:9222/devtools/browser/12b1189b-9be7-44cc-a512-b0a06cff010e
[2019-10-21 15:05:28] INFO: start script
[2019-10-21 15:05:28] INFO: Navigating to url https://example.com iteration 1
[2019-10-21 15:06:01] INFO: Start to measure page1
page1 failed
{ Error: Command failed: ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 \~\visualmetrics\sitespeed-result\file_js\2019-10-21-22-05-14\x11-tmp.mp4
   at makeError (\~\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\execa\lib\error.js:58:11)
   at handlePromise (\~\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\execa\index.js:112:26)
   at process._tickCallback (internal/process/next_tick.js:68:7)
command:
  'ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 \~\\visualmetrics\\sitespeed-result\\file_js\\2019-10-21-22-05-14\\x11-tmp.mp4',
exitCode: 1,
exitCodeName: 'Unknown system error -1',
stdout: '',
stderr: 'Unknown input format: \'x11grab\'',
all: 'Unknown input format: \'x11grab\'',
failed: true,
timedOut: false,
isCanceled: false,
killed: false,
signal: undefined }
[2019-10-21 15:06:01] ERROR: Error: Command failed: ffmpeg -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 10M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 \~\visualmetrics\sitespeed-result\file_js\2019-10-21-22-05-14\x11-tmp.mp4
   at makeError (\~\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\execa\lib\error.js:58:11)
   at handlePromise (~\npm\node_modules\sitespeed.io\node_modules\browsertime\node_modules\execa\index.js:112:26)
   at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-21 15:06:01] INFO: https://example.com/page1 backEndTime: 77ms, firstPaint: 203ms, DOMContentLoaded: 138ms, Load: 272ms, rumSpeedIndex: 342
[2019-10-21 15:06:02] INFO: Send annotation to Influx: "events title=\"Sitespeed.io\",text=\"<a href='https://example.com/file_js/2019-10-21-22-05-14/pages/example.com/page1/' target='_blank'>Result 1 run</a>\",tags=\"tag1,tag2,tag3" 1571695562"
[2019-10-21 15:06:04] INFO: HTML stored in ~\sitespeed-result\file_js\2019-10-21-22-05-14
[2019-10-21 15:06:04] INFO: Uploading ~\visualmetrics\sitespeed-result\file_js\2019-10-21-22-05-14 to S3 bucket foobucket, this can take a while ...
[2019-10-21 15:06:05] INFO: Finished upload to s3
[2019-10-21 15:06:05] INFO: Find the result at https://example.com/file_js/2019-10-21-22-05-14
 
config(obfuscated):
```{
   "browsertime": {
         "iterations": 1,
         "browser": "chrome",
          "pageCompleteWaitTime": 0
       },

   "influxdb": {
   "host": "influx.foo",
   "database": "foo",
   "password": "foobar",
   "port": 8086,
   "username": "foo",
   "protocol": "https",
   "tags": "tag1=foo1,tag2=foo2,tag3=foo3",
   "resultBaseURL": "https://example.com",

    "s3": {
        "bucketname": "foobucket",
        "key": "",
        "region": "",
        "secret": "",
        "removeLocalResult": true
    },

   "utc": true
}
```
OS: Windows 10 Pro, version 1903
How I run it: "~\sitespeed.io.cmd" --config \path\to\config.json \path\to\file.js --multi
Browser version: Chrome 78, ChromeDriver 78.0.3904.11
Sitespeed.io version: sitespeed.io: 10.3.0

**Comment by soulgalore** [comment]
Hi @SGunase2 we don't support running on Windows see https://www.sitespeed.io/documentation/sitespeed.io/installation/#windows-1.

The reason is that we don't have the skill set within the core team to do it. We did support it a couple of years ago but it took so much extra time debugging Windows issues since none of us are working on Windows.

However we are open to support Windows if we can find a new member that are Windows native :)

Best
Peter

**Comment by SGunase2** [comment]
Hi Peter, 

Thanks for your response. Can you please make this a feature request for windows?

Thanks,
Sahana

**Comment by soulgalore** [comment]
Hi Sahana,
as I said we will not do any Windows specific thing if we don't anyone with the skills to handle it.

Best
Peter

**Comment by soulgalore** [comment]
Closing, we will not make any feature request for Windows outside of Docker until we have a team member that actually do Windows.
