### ISSUE TITLE
Error handling basics

### ISSUE THREAD

**Issue by srijondas** [sitespeedio/sitespeed.io#2729]
I created a script like this, but not sure how to find the error count in grafana. Also this throws an error in Jenkins where I scheduled the docker job ...

module.exports = async function (context, commands) {
  context.log.info('Running test')
  const By = context.selenium.webdriver.By
  const webdriver = context.selenium.driver
  await webdriver.manage().setTimeouts({implicit: 9000})
try{
  await commands.measure.start('prod_loginpage')
  await webdriver.get('https://www.auction.com/login')
  await commands.measure.stop()

  await commands.measure.start('prod_login')
  await webdriver.findElement(By.name('email_INCORRECT_OBJECT_FOR_ERROR_HANDLING_TESTING')).sendKeys('someone@somesite.com')
  await webdriver.findElement(By.name('password')).sendKeys('somepassword')
  await webdriver.findElement(By.css('[data-elm-id=\"auth_toggle_login_login_button\"]')).click()
  await commands.measure.stop()

  await commands.measure.start('prod_pdppage')
  await webdriver.get('https://www.auction.com/details/1000-test-clover-street-irvine-ca-90804-2348749-t_3531')
  await webdriver.findElement(By.css('[data-elm-id=\"bid_button\"]')).click()
  await webdriver.findElement(By.css('[data-elm-id=\"button_confirm\"]')).click() 
  await commands.measure.stop()

  }catch(e){
    await commands.measure.stop()
    commands.error('script error')
    
  }
}

Error on Jenkins ...

Started by timer
[EnvInject] - Loading node environment variables.
Building on master in workspace /backup/sitespeed/Sitespeed_Bid_PROD
[Sitespeed_Bid_PROD] $ /bin/sh -xe /tmp/jenkins1416014417173321038.sh
+ echo /backup/sitespeed/Sitespeed_Bid_PROD
/backup/sitespeed/Sitespeed_Bid_PROD
++ pwd
+ docker run --shm-size=1g --rm -v /backup/sitespeed/Sitespeed_Bid_PROD:/sitespeed.io sitespeedio/sitespeed.io bid_prod.js --multi --graphite.host 10.1.180.94 -b chrome --browsertime.chrome.args no-sandbox --name login
Google Chrome 74.0.3729.131 
Mozilla Firefox 66.0.4
[2019-10-24 22:23:02] INFO: Versions OS: linux 3.10.0-862.3.2.el7.x86_64 nodejs: v10.13.0 sitespeed.io: 9.0.0 browsertime: 5.0.0 coach: 3.4.2
[2019-10-24 22:23:02] INFO: Running tests using Chrome - 3 iteration(s)
[2019-10-24 22:23:04] INFO: Running test
[2019-10-24 22:23:04] INFO: Start to measure prod_loginpage
[2019-10-24 22:23:08] INFO: Start to measure prod_login
[2019-10-24 22:23:17] INFO: https://www.auction.com/login has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2019-10-24 22:23:27] INFO: https://www.auction.com/login BackEndTime: 63 DomInteractiveTime: 1002 DomContentLoadedTime: 1002 FirstPaint: 236 PageLoadTime: 1757
[2019-10-24 22:23:27] INFO: VisualMetrics FirstVisualChange: 233 SpeedIndex: 257 PerceptualSpeedIndex: 237 LastVisualChange: 300
[2019-10-24 22:23:27] INFO: https://www.auction.com/login?browsertime_run=2 BackEndTime: 63 DomInteractiveTime: 1002 DomContentLoadedTime: 1002 FirstPaint: 236 PageLoadTime: 1757
[2019-10-24 22:23:27] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
[2019-10-24 22:23:28] INFO: Running test
[2019-10-24 22:23:28] INFO: Start to measure prod_loginpage
[2019-10-24 22:23:31] INFO: Start to measure prod_login
[2019-10-24 22:23:41] INFO: https://www.auction.com/login has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2019-10-24 22:23:49] INFO: https://www.auction.com/login BackEndTime: 60 DomInteractiveTime: 985 DomContentLoadedTime: 985 FirstPaint: 225 PageLoadTime: 1727
[2019-10-24 22:23:49] INFO: VisualMetrics FirstVisualChange: 233 SpeedIndex: 248 PerceptualSpeedIndex: 236 LastVisualChange: 366
[2019-10-24 22:23:49] INFO: https://www.auction.com/login?browsertime_run=2 BackEndTime: 60 DomInteractiveTime: 985 DomContentLoadedTime: 985 FirstPaint: 225 PageLoadTime: 1727
[2019-10-24 22:23:49] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
[2019-10-24 22:23:49] INFO: Running test
[2019-10-24 22:23:49] INFO: Start to measure prod_loginpage
[2019-10-24 22:23:53] INFO: Start to measure prod_login
[2019-10-24 22:24:02] INFO: https://www.auction.com/login has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2019-10-24 22:24:10] INFO: https://www.auction.com/login BackEndTime: 59 DomInteractiveTime: 991 DomContentLoadedTime: 991 FirstPaint: 245 PageLoadTime: 1757
[2019-10-24 22:24:10] INFO: VisualMetrics FirstVisualChange: 266 SpeedIndex: 278 PerceptualSpeedIndex: 268 LastVisualChange: 300
[2019-10-24 22:24:10] INFO: https://www.auction.com/login?browsertime_run=2 BackEndTime: 59 DomInteractiveTime: 991 DomContentLoadedTime: 991 FirstPaint: 245 PageLoadTime: 1757
[2019-10-24 22:24:10] INFO: VisualMetrics FirstVisualChange: 0 SpeedIndex: 0 PerceptualSpeedIndex: 0 LastVisualChange: 0
[2019-10-24 22:24:10] INFO: https://www.auction.com/login 26 requests, 1439.47 kb, backEndTime: 61ms (±0.98ms), firstPaint: 235ms (±4.72ms), firstVisualChange: 244ms (±8.98ms), DOMContentLoaded: 993ms (±4.06ms), Load: 1.75s (±8.16ms), speedIndex: 261 (±7.26), visualComplete85: 289ms (±9.25ms), lastVisualChange: 322ms (±17.96ms), rumSpeedIndex: 235 (±4.72) (3 runs)
[2019-10-24 22:24:10] INFO: https://www.auction.com/login?browsertime_run=2 25 requests, 1439.36 kb, backEndTime: 61ms (±0.98ms), firstPaint: 235ms (±4.72ms), firstVisualChange: 0ms (±0.00ms), DOMContentLoaded: 993ms (±4.06ms), Load: 1.75s (±8.16ms), speedIndex: 0 (±0.00), visualComplete85: 0ms (±0.00ms), lastVisualChange: 0ms (±0.00ms), rumSpeedIndex: 235 (±4.72) (3 runs)
[2019-10-24 22:24:10] ERROR: Could not find the right index 4 for har for url https://www.auction.com/login 
[2019-10-24 22:24:10] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:196:29)
[2019-10-24 22:24:12] INFO: HTML stored in /sitespeed.io/sitespeed-result/bid_prod_js/2019-10-24-22-23-02
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by soulgalore** [comment]
Hi @srijondas have you tested the script locally?

When you click on an element, you need to wait on the page to finish loading:
```
await webdriver.findElement(By.css('[data-elm-id="button_confirm"]')).click()
await commands.measure.stop()
```

I think in your case when you stop the measurements it could be that the page hasn't loaded yet. If you use the our click and waits we run the page complete check so that the page has time to navigate:
https://www.sitespeed.io/documentation/sitespeed.io/scripting/#clickbyjsandwaitjs

We should document the errors better. If you use the latest Page Timing metrics dashboard, you have section called errors. The graph to the right is the errors from your scripts if I remember correctly:
<img width="1180" alt="Screen Shot 2019-10-25 at 9 49 05 AM" src="https://user-images.githubusercontent.com/540757/67553108-b92e5380-f70c-11e9-9854-e9356e5fdef6.png">

Best
Peter

**Comment by soulgalore** [comment]
Closing but please let me know if you need more information so we can re-open!
