### ISSUE TITLE
Load/verify Error using Firefox Browser

### ISSUE THREAD

**Issue by GodwinBurkhardt** [sitespeedio/sitespeed.io#2764]
Hi I'm new using sitespeed.io. When I use Firefox Browser, I got the following error, when I use then following command:

docker run --cap-add=NET_ADMIN --shm-size=3g --rm -v /config:/config -v /sitespeed.io:/sitespeed.io -v /etc/localtime:/etc/localtime:ro -e MAX_OLD_SPACE_SIZE=3072 sitespeedio/sitespeed.io-autobuild:latest --graphite.namespace sitespeed_io.desktop --config /sitespeed.io/config/desktop.json -b firefox tests/nyc3-1/desktop/urls/desktop.txt

[2019-11-07 16:42:07] INFO: Running tests using Firefox - 3 iteration(s)
[2019-11-07 16:42:10] INFO: Testing url https://en.wikipedia.org/wiki/Sweden iteration 1
[2019-11-07 16:42:10] INFO: Start firefox window recorder.
[2019-11-07 16:43:01] ERROR: UrlLoadError: Failed to load/verify https://en.wikipedia.org/wiki/Sweden uri:data:text/html;charset=utf-8,<html><body></body></html>
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:241:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:200:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:168:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:121:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)

When I use the same command with chrome instead of firefox everything runs well.

Thank you for giving me a hint.

**Comment by soulgalore** [comment]
Hi @GodwinBurkhardt can you try with a simpler example and disable the new Firefox window recorder (remove --firefox.windowRecorder from the configuration) and see if it works? I've seen some bugs that seems related to that (https://github.com/sitespeedio/browsertime/issues/983).

Best
Peter

**Comment by GodwinBurkhardt** [comment]
Thank you for your answer. The docker is started in VM under debain. Removing the firefox.windowRecoder in desktop.json has not solved the problem. The result is the same error. My desktop.json is:
 {
  "extends": "/config/secrets.json",
  "browsertime": {
    "connectivity": {
      "engine": "throttle",
      "profile": "cable"
    },
    "visualElements": true,
    "iterations": 3,
    "browser": "chrome",
    "video": true,
    "visualMetric": true,
    "chrome": {
      "collectConsoleLog": true,
      "enableTraceScreenshots": true
    },
    "firefox": {
      "includeResponseBodies": "all"
    }
  },
  "cpu": true,
  "gzipHAR": true,
  "html": {
    "fetchHARFiles": true,
    "showScript": true,
    "compareURL": "https://compare.sitespeed.io/"
  },
  "screenshot": {
    "type": "jpg"
  }
}
Any idea?

**Comment by soulgalore** [comment]
I'm reopen since it isn't working for you right?

How large instance are you running ? That error normally means that the browser hasn't started navigating to the URL before it times out.

**Comment by GodwinBurkhardt** [comment]
Hi, thank you for your help. The problem was, that we don't use proxy settings in the docker command. First we tested it on unix machine directly and the docker command runs perfect. Then we add the proxy settings "--proxy.http  ... --proxy.https ..." to the command and let run the command on the virtual machine. Then everything is running. You can close the issue.
