### ISSUE TITLE
InvalidArgumentError in Safari 13

### ISSUE THREAD

**Issue by SemyonLosmakov** [sitespeedio/sitespeed.io#2797]
NPM-installed sitespeed.io fails with InvalidArgumentError when Safari 13.0.3 (Version 13.0.3 (14608.3.10.10.1) is used on macOS Mojave (10.14.6 (18G87)).
 
Example:
`sitespeed.io https://www.sitespeed.io/ -n 1 -b safari
[2019-11-22 19:37:03] INFO: Versions OS: darwin 18.7.0 nodejs: v12.13.1 sitespeed.io: 11.2.0 browsertime: 7.1.0 coach: 4.2.0
[2019-11-22 19:37:03] INFO: Running tests using Safari - 1 iteration(s)
[2019-11-22 19:37:04] ERROR: InvalidArgumentError: Could not parse requested URL 'data:text/html;charset=utf-8,<html><body></body></html>'
    at Object.throwDecodedError (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:486:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
    at async Iteration.run (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:144:9)
    at async Engine.runByScript (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:121:20)
    at async Object.analyzeUrl (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/Users/semen_losmakov/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:134:24)
[2019-11-22 19:37:04] ERROR: No data to collect
[2019-11-22 19:37:04] INFO: HTML stored in /Users/semen_losmakov/Work/Tools/ss/sitespeed-result/www.sitespeed.io/2019-11-22-19-37-03`

**Comment by SemyonLosmakov** [comment]
I also tried on macOS Catalina (10.15 (19A583)) on other device, the same error.

Example:
`
sitespeed.io https://www.sitespeed.io/ -n 1  -b safari 
[2019-11-22 19:57:26] INFO: Versions OS: darwin 19.0.0 nodejs: v12.13.0 sitespeed.io: 11.2.0 browsertime: 7.1.0 coach: 4.2.0
[2019-11-22 19:57:26] INFO: Running tests using Safari - 1 iteration(s)
[2019-11-22 19:57:27] ERROR: InvalidArgumentError: Could not parse requested URL 'data:text/html;charset=utf-8,<html><body></body></html>'
    at Object.throwDecodedError (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:486:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
    at async Iteration.run (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:144:9)
    at async Engine.runByScript (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:121:20)
    at async Object.analyzeUrl (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/Users/semenlosmakov/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:134:24)
[2019-11-22 19:57:27] ERROR: No data to collect
[2019-11-22 19:57:28] INFO: HTML stored in /Users/semenlosmakov/sstest/sitespeed-result/www.sitespeed.io/2019-11-22-19-57-26
`

**Comment by soulgalore** [comment]
Thank you @SemyonLosmakov for reporting. This was broken in release some time ago when we changed the start URL. I'm rolling out a fix in a couple of hours.

Best
Peter

**Comment by soulgalore** [comment]
This was fixed in 11.3.0, please let me know that it works for you now @SemyonLosmakov before I close the issue.

Best
Peter

**Comment by SemyonLosmakov** [comment]
After the update it works on both devices.
Thank you, Peter!
