### ISSUE TITLE
Lighthouse fails on 11.3.0-plus1

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2801]
11.3.0-plus1 fails with message about lighthouse.  The only addional option i've added was 
--plugins.add /lighthouse 

[2019-11-25 19:31:26] ERROR: Lighthouse could not test https://www.example.com/path please create an upstream issue: https://github.com/GoogleChrome/lighthouse/issues/new?template=Bug_report.md Error: no known mark: lh:gather:afterPass:OptimizedImages
    at Object.exports.stop (/lighthouse/node_modules/marky/lib/marky.cjs.js:76:13)
    at Function.timeEnd (/lighthouse/node_modules/lighthouse-logger/index.js:128:11)
    at Function.afterPass (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:407:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.runPass (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:665:5)
    at async Function.run (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:573:29)
    at async Function._gatherArtifactsFromBrowser (/lighthouse/node_modules/lighthouse/lighthouse-core/runner.js:215:23)
    at async Function.run (/lighthouse/node_modules/lighthouse/lighthouse-core/runner.js:81:21)
    at async runLighthouse (/lighthouse/runAudit.js:33:19)
    at async runAudit (/lighthouse/runAudit.js:61:19)
    at async Object.processMessage (/lighthouse/index.js:148:22)

**Comment by soulgalore** [comment]
Can you give the full example so I can reproduce? When I tested it worked for me?

```
$ docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:11.3.0-plus1 https://www.sitespeed.io/ -n 1
Google Chrome 78.0.3904.87 
Mozilla Firefox 70.0
[2019-11-25 21:55:26] INFO: Versions OS: linux 4.14.131-linuxkit nodejs: v12.13.0 sitespeed.io: 11.3.0 browsertime: 7.2.2 coach: 4.2.0
[2019-11-25 21:55:28] INFO: Will run Lighthouse tests after Browsertime has finished
[2019-11-25 21:55:28] INFO: Sending url https://www.sitespeed.io/ to test on Page Speed Insights
[2019-11-25 21:55:28] INFO: Running tests using Chrome - 1 iteration(s)
[2019-11-25 21:55:30] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2019-11-25 21:55:31] INFO: Got https://www.sitespeed.io/ analysed from Google Page Speed Insights
[2019-11-25 21:55:47] INFO: https://www.sitespeed.io/ 13 requests, backEndTime: 171ms, firstPaint: 693ms, firstVisualChange: 719ms, DOMContentLoaded: 738ms, Load: 770ms, speedIndex: 751, visualComplete85: 863ms, lastVisualChange: 899ms, rumSpeedIndex: 693
[2019-11-25 21:55:47] INFO: Start collecting Lighthouse result for https://www.sitespeed.io/ iteration 1
[2019-11-25 21:55:58] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2019-11-25-21-55-26
```
