### ISSUE TITLE
Unable to start sitespeed.io on version 11.04

### ISSUE THREAD

**Issue by bodharma** [sitespeedio/sitespeed.io#2809]
Hi!
Started today machine as usual and received fails.
Downgraded to version 11.03 and works fine.
Whats the problem?
According presented changelog - no items related to chrome. Or am I wrong?
Thank you!

Attaching configs and logs.

Configs:
```
version: '2.1'
services:
  sitespeed.io:
    image: sitespeedio/sitespeed.io
    command: https://test-vm/en/some_url_1 https://test-vm/en/some_url_2 https://test-vm/en/some_url_3 --cpu --axe.enable
    shm_size: 1g
    volumes:
      - ./sitespeed-result/:/sitespeed.io/sitespeed-result
```

Logs from machine:
```
[centos@test-dev-02 hidden]$ docker-compose up sitespeed.io
Starting hidden_sitespeed.io_1 ... done
Attaching to hidden_sitespeed.io_1
sitespeed.io_1  | Google Chrome 78.0.3904.87
sitespeed.io_1  | Mozilla Firefox 70.0
sitespeed.io_1  | groupadd: group 'sitespeedio' already exists
sitespeed.io_1  | useradd: user 'sitespeedio' already exists
sitespeed.io_1  | [2019-12-02 16:22:31] INFO: Versions OS: linux 3.10.0-957.27.2.el7.x86_64 nodejs: v12.13.0 sitespeed.io: 11.4.0 browsertime: 7.2.2 coach: 4.2.0
sitespeed.io_1  | [2019-12-02 16:22:31] INFO: Axe plugin activated
sitespeed.io_1  | [2019-12-02 16:22:31] INFO: Running tests using Chrome - 3 iteration(s)
sitespeed.io_1  | [2019-12-02 16:22:32] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:33] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:34] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:34] ERROR: BrowserError: Could not start the browser with 3 tries
sitespeed.io_1  |     at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
sitespeed.io_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
sitespeed.io_1  | [2019-12-02 16:22:34] ERROR: No data to collect
sitespeed.io_1  | [2019-12-02 16:22:35] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:36] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:37] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
sitespeed.io_1  |   (chrome not reachable)
sitespeed.io_1  |   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
sitespeed.io_1  | [2019-12-02 16:22:37] ERROR: BrowserError: Could not start the browser with 3 tries
sitespeed.io_1  |     at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
sitespeed.io_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
sitespeed.io_1  | [2019-12-02 16:22:37] ERROR: No data to collect
^CGracefully stopping... (press Ctrl+C again to force)
Stopping hidden_sitespeed.io_1 ... done
[centos@test-dev-02 hidden]$
```

**Comment by soulgalore** [comment]
Hi @velocyno its between 11.3 and 11.4 right? I cannot see anything related in the changelog (no changes of Chrome nor Chromedriver): https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#1140---2019-11-26

Can you try again to really see that the version is the thing?
Best
Peter

**Comment by velocyno** [comment]
Before posting this issue, reproduced on different machines with specified version 11.3 in image field and everything worked fine.

**Comment by soulgalore** [comment]
Does it work if you try with Firefox?

**Comment by velocyno** [comment]
Using:
```
version: '2.1'
services:
  sitespeed.io:
    image: sitespeedio/sitespeed.io
    command: https://test-vm/image_1 https://test-vm/image_2 https://test-vm/image_3 --cpu --axe.enable --firefox
    shm_size: 1g
    volumes:
      - ./sitespeed-result/:/sitespeed.io/sitespeed-result
```

Get result:

```
[centos@test-dev-02 hidden]$ docker-compose up --build sitespeed.io
Recreating hidden_sitespeed.io_1 ... done
Attaching to hidden_sitespeed.io_1
sitespeed.io_1  | Google Chrome 78.0.3904.87
sitespeed.io_1  | Mozilla Firefox 70.0
sitespeed.io_1  | [2019-12-03 13:22:27] INFO: Versions OS: linux 3.10.0-957.27.2.el7.x86_64 nodejs: v12.13.0 sitespeed.io: 11.4.0 browsertime: 7.2.2 coach: 4.2.0
sitespeed.io_1  | [2019-12-03 13:22:27] INFO: Axe plugin activated
sitespeed.io_1  | [2019-12-03 13:22:27] INFO: Running tests using Chrome - 3 iteration(s)
sitespeed.io_1  | [2019-12-03 13:22:28] INFO: Testing url https://test-vm/image_1 iteration 1
sitespeed.io_1  | [2019-12-03 13:22:47] INFO: https://test-vm/image_1 BackEndTime: 140 DomInteractiveTime: 214 DomContentLoadedTime: 700 FirstPaint: 749 PageLoadTime: 877
sitespeed.io_1  | [2019-12-03 13:22:47] INFO: VisualMetrics FirstVisualChange: 767 SpeedIndex: 787 PerceptualSpeedIndex: 783 ContentfulSpeedIndex: 1480 LastVisualChange: 5700
```

**Comment by soulgalore** [comment]
Is this still an issue?

**Comment by velocyno** [comment]
Hi Peter!
Sorry, missed previous emails.
The issue was resolved.

Kind Regards, Bohdan Lesiv.
