### ISSUE TITLE
Error: PageIndex out of range

### ISSUE THREAD

**Issue by rnemeth1980** [sitespeedio/sitespeed.io#2810]
I get an error at the end of the 3rd iteration, the report created is incomplete, but the recorded video shows the login itself was successful.

After login there is a redirect to the main site.

Docker verion:
`Docker version 18.09.7, build 2d0083d`

OS running in VirtualBox:
`lubuntu 18.04`
`VirtualBox Version 5.2.20 r125813 (Qt5.6.2)`

login.js:
```
module.exports = async function(context, commands) {

try {

  await commands.measure.start('Load');
  await commands.navigate(
    'https://some.url');
  await commands.addText.byId('some@user', 'username');
  await commands.addText.byId('pass', 'password');
  await commands.measure.start('Login');
  await commands.click.byIdAndWait('kc-login');
  return commands.measure.stop();
} catch (e) {
  throw e;
}
};
```

Command:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:11.3.0 login.js --multi`

Log:
```
Google Chrome 78.0.3904.87 
Mozilla Firefox 70.0
[2019-12-03 17:27:14] INFO: Versions OS: linux 4.15.0-70-generic nodejs: v12.13.0 sitespeed.io: 11.3.0 browsertime: 7.2.2 coach: 4.2.0
[2019-12-03 17:27:14] INFO: Running tests using Chrome - 3 iteration(s)
[2019-12-03 17:27:16] INFO: Start to measure Load
[2019-12-03 17:27:16] INFO: Navigating to url https://some.url iteration 1
[2019-12-03 17:27:25] INFO: Start to measure Login
[2019-12-03 17:29:56] INFO: https://some.url BackEndTime: 4546 DomInteractiveTime: 9463 DomContentLoadedTime: 9463 FirstPaint: 7350 PageLoadTime: 10332
[2019-12-03 17:29:56] INFO: VisualMetrics FirstVisualChange: 595 SpeedIndex: 11583 PerceptualSpeedIndex: 7897 ContentfulSpeedIndex: 3571 LastVisualChange: 20568
[2019-12-03 17:29:58] INFO: Start to measure Load
[2019-12-03 17:29:58] INFO: Navigating to url https://some.url iteration 2
[2019-12-03 17:30:07] INFO: Start to measure Login
[2019-12-03 17:33:51] INFO: https://some.url BackEndTime: 2459 DomInteractiveTime: 8385 DomContentLoadedTime: 8385 FirstPaint: 5512 PageLoadTime: 10001
[2019-12-03 17:33:51] INFO: VisualMetrics FirstVisualChange: 573 SpeedIndex: 11235 PerceptualSpeedIndex: 7966 ContentfulSpeedIndex: 4539 LastVisualChange: 22820
[2019-12-03 17:33:54] INFO: Start to measure Load
[2019-12-03 17:33:54] INFO: Navigating to url https://some.url iteration 3
[2019-12-03 17:34:03] INFO: Start to measure Login
[2019-12-03 17:39:14] INFO: https://some.url BackEndTime: 2269 DomInteractiveTime: 9721 DomContentLoadedTime: 9721 FirstPaint: 5964 PageLoadTime: 11251
[2019-12-03 17:39:14] INFO: VisualMetrics FirstVisualChange: 503 SpeedIndex: 13103 PerceptualSpeedIndex: 8823 ContentfulSpeedIndex: 8108 LastVisualChange: 18637
[2019-12-03 17:39:14] INFO: https://some.url 113 requests, backEndTime: 3.09s (±595.55ms), firstPaint: 6.28s (±451.48ms), firstVisualChange: 557ms (±22.65ms), DOMContentLoaded: 9.19s (±334.08ms), Load: 10.53s (±305.30ms), speedIndex: 11974 (±468.29), visualComplete85: 13.52s (±2.09s), lastVisualChange: 20.68s (±986.91ms), rumSpeedIndex: 6275 (±451.48) (3 runs)
[2019-12-03 17:39:14] INFO: login.js 114 requests
[2019-12-03 17:39:15] ERROR: Could not find the right index 4 for har for url https://some.url 
[2019-12-03 17:39:15] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/webcoach/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/webcoach/lib/index.js:130:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:229:29)
[2019-12-03 17:39:29] INFO: HTML stored in /sitespeed.io/sitespeed-result/login_js/2019-12-03-17-27-14

```

Thank you for your support!

**Comment by soulgalore** [comment]
Hi @rnemeth1980 sorry I missed this one.

`await commands.measure.start('Load');` also needs a stop. At the moment you do two starts and one stop, I think that is the problem.

**Comment by rnemeth1980** [comment]
that solved it, thank you @soulgalore for your support!
