### ISSUE TITLE
Error: listen EACCES: permission denied 127.0.0.1:1080

### ISSUE THREAD

**Issue by manojs1978** [sitespeedio/sitespeed.io#2836]
hi sir,
i have just upgraded to sitespeed.io 11.9.3 version.
after upgrading i am getting below error while running this command.

sitespeed.io https://www.sitespeed.io

ERROR:

[2020-01-05 15:17:15] INFO: Versions OS: win32 10.0.17763 nodejs: v10.16.3 sitespeed.io: 11.9.3 browsertime: 7.8.3 coach: 4.3.0
[2020-01-05 15:17:16] ERROR: Error: listen EACCES: permission denied 127.0.0.1:1080
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-01-05 15:17:18] INFO: HTML stored in C:\CYGWIN64\home\***\sitespeed-result\www.sitespeed.io\2020-01-05-15-17-15.

please let  me know is this my machine problem or any thing else

- Exact how you run (the exact parameters)
        sitespeed.io https://www.sitespeed.io
- Which version you are using
sitespeed.io 11.9.3
- OS (if you use Docker, report the base OS)
 windows 10 64 bit
- Browser version (if you don't run Docker)
chrome 79
-->

**Comment by soulgalore** [comment]
Hi @manojs1978 sorry I missed responding in this, I was on vacation.

What was your previous version? Have you checked that nothing is running on port 1080 + can you run old/new version with the same parameters and just verify the upgrade is the problem?

**Comment by soulgalore** [comment]
Closing because didn't get any response.
