### ISSUE TITLE
ERROR: Could not generate url/summary/index for version 12.0.1

### ISSUE THREAD

**Issue by jdmchone** [sitespeedio/sitespeed.io#2881]
Using CentOS 7, and git cloned the latest sitespeed.io version 12.0.1 from 11.9.3. I have everything installed and working (ffmpeg, visualmetrics, chromedriver, chrome 80, firefox 72, etc...). 

When I run a test, i get the following error:
RROR: Could not generate url/summary/index
[2020-02-20 05:30:53] ERROR: TypeError: /root/sitespeed.io/lib/plugins/html/templates/url/metrics/index.pug:32
    30|             td
    31|               a(href=baseHelpURL + 'ContentfulSpeedIndex') Contentful Speed Index
  > 32|             td.number #{h.time.ms(visualMetrics.ContentfulSpeedIndex.toFixed(0))}
    33|           if visualMetrics.LargestImage
    34|             tr
    35|               td

Cannot read property 'toFixed' of null
    at eval (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2958:102)
    at template (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6849:201)
    at Object.renderTemplate (/root/sitespeed.io/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlPage (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:402:16)
    at HTMLBuilder.render (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:311:18)

Not sure what's wrong. All version up to 11.9.3 work, but when i try to use the later version, it doesn't.

**Comment by soulgalore** [comment]
Hi @jdmchone there has been changes on how to calculate ContentfulSpeedIndex and it seems it seems it doesn't work on your machine. You didn't get any error logs before *Could not generate url/summary/index*?

I'll make fix so that will at least not break the HTML, but then I think we need more info to fix the root cause.

**Comment by jdmchone** [comment]
Yes. I did get that error. Below is the full run:
bin/sitespeed.js -n 1 -b firefox https://www.sitespeed.io/
[2020-02-20 05:30:27] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.14.1 sitespeed.io: 12.0.1 browsertime: 8.0.1 coach: 4.4.1
[2020-02-20 05:30:28] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-02-20 05:30:28] INFO: Sending url https://www.sitespeed.io/ to test on Page Speed Insights
[2020-02-20 05:30:28] INFO: Running tests using Firefox - 1 iteration(s)
[2020-02-20 05:30:30] INFO: Got https://www.sitespeed.io/ analysed from Google Page Speed Insights
[2020-02-20 05:30:32] INFO: Testing url https://www.sitespeed.io/ iteration 1
[2020-02-20 05:30:42] INFO: Waiting on har-export-trigger to collect the HAR
[2020-02-20 05:30:45] INFO: https://www.sitespeed.io/ 14 requests, backEndTime: 417ms, firstPaint: 680ms, firstVisualChange: 748ms, DOMContentLoaded: 714ms, Load: 753ms, speedIndex: 748, perceptualSpeedIndex: 748, visualComplete85: 748ms, lastVisualChange: 748ms, rumSpeedIndex: 620
[2020-02-20 05:30:46] INFO: Start collecting Lighthouse result for https://www.sitespeed.io/ iteration 1
[2020-02-20 05:30:53] ERROR: Could not generate url/summary/index
[2020-02-20 05:30:53] ERROR: TypeError: /root/sitespeed.io/lib/plugins/html/templates/url/metrics/index.pug:32
    30|             td
    31|               a(href=baseHelpURL + 'ContentfulSpeedIndex') Contentful Speed Index
  > 32|             td.number #{h.time.ms(visualMetrics.ContentfulSpeedIndex.toFixed(0))}
    33|           if visualMetrics.LargestImage
    34|             tr
    35|               td

Cannot read property 'toFixed' of null
    at eval (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2958:102)
    at template (eval at wrap (/root/sitespeed.io/node_modules/pug/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6849:201)
    at Object.renderTemplate (/root/sitespeed.io/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlPage (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:402:16)
    at HTMLBuilder.render (/root/sitespeed.io/lib/plugins/html/htmlBuilder.js:311:18)
[root@5baf54b83cb8 sitespeed.io]# exit
exit

**Comment by jdmchone** [comment]
Here is the visualmetrics portion of the -verbose debug logging: shows the the ContentfulSpeedIndex is null...but no error as to why:
[2020-02-20 17:21:21] DEBUG: [browsertime.video] Running visualMetrics
[2020-02-20 17:21:21] DEBUG: [browsertime.video] Running visualmetrics.py /root/sitespeed.io/node_modules/browsertime/browsertime/visualmetrics.py --dir /root/sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-17-21-10/pages/sitespeed.io/data/filmstrip/1 --video /root/sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-17-21-10/pages/sitespeed.io/data/video/1.mp4 --orange --perceptual --contentful --force --renderignore 5 --json --viewport -q 75 --logfile /root/sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-17-21-10/pages/sitespeed.io/data/video/1.visualmetrics.log -vvvv
[2020-02-20 17:21:22] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 678, "FirstVisualChange": 672, "LastVisualChange": 706, "VisualProgress": "0=0, 672=81, 706=100", "ContentfulSpeedIndex": null, "videoRecordingStart": 504, "ContentfulSpeedIndexProgress": null, "PerceptualSpeedIndex": 678, "PerceptualSpeedIndexProgress": "0=0, 672=99, 706=100"}
[2020-02-20 17:21:22] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":678,"FirstVisualChange":672,"LastVisualChange":706,"VisualProgress":"0=0, 672=81, 706=100","ContentfulSpeedIndex":null,"videoRecordingStart":504,"ContentfulSpeedIndexProgress":null,"PerceptualSpeedIndex":678,"PerceptualSpeedIndexProgress":"0=0, 672=99, 706=100"}
[2020-02-20 17:21:23] INFO: [browsertime] https://sitespeed.io 14 requests, backEndTime: 420ms, firstPaint: 652ms, firstVisualChange: 672ms, DOMContentLoaded: 623ms, Load: 665ms, speedIndex: 678, perceptualSpeedIndex: 678, visualComplete85: 706ms, lastVisualChange: 706ms, rumSpeedIndex: 652

**Comment by soulgalore** [comment]
Ok! @jdmchone could you re-run with verbose logging  `-vv` then a log file will be created from Visual Metrics that can help us show what goes wrong:
<img width="538" alt="Screenshot 2020-02-20 at 21 03 26" src="https://user-images.githubusercontent.com/540757/74974008-c510f480-5424-11ea-8c28-d66f87929a69.png">

If you can share the log that would be super helpful.

**Comment by jdmchone** [comment]
The one i shared was -vvv, is that too deep?

**Comment by jdmchone** [comment]
[1.visualmetrics.log](https://github.com/sitespeedio/sitespeed.io/files/4233268/1.visualmetrics.log)

**Comment by jdmchone** [comment]
Looks like this is the culprit:

22:19:19.316 - contentfulSpeedIndex: Current Image is /sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-22-19-04/pages/sitespeed.io/data/filmstrip/1/ms_001194.png
22:19:19.331 - Command 'convert /sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-22-19-04/pages/sitespeed.io/data/filmstrip/1/ms_001194.png -canny 2x2+8%+8% -define histogram:unique-colors=true -format %c histogram:info:-' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/share/.config/yarn/global/node_modules/browsertime/browsertime/visualmetrics.py", line 1667, in calculate_contentful_speed_index
    output = subprocess.check_output(command, shell=True).decode('utf-8')
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'convert /sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-22-19-04/pages/sitespeed.io/data/filmstrip/1/ms_001194.png -canny 2x2+8%+8% -define histogram:unique-colors=true -format %c histogram:info:-' returned non-zero exit status 1
22:19:19.332 - Hero elements file is not valid: None
22:19:19.333 - Converting video frames to JPEG
22:19:19.333 - mogrify -format jpg -set colorspace sRGB -quality 75 "/sitespeed.io/sitespeed-result/sitespeed.io/2020-02-20-22-19-04/pages/sitespeed.io/data/filmstrip/1/ms_*.png"
22:19:19.354 - Done Converting video frames to JPEG
