### ISSUE TITLE
Cannot set property 'url' of undefined

### ISSUE THREAD

**Issue by grantis** [sitespeedio/sitespeed.io#2884]
Hi guys, I'm wanting to use sitespeed.io in conjunction with graphite and grafana to capture our sites performance and I'm having trouble set up. Feel like I should have everything to make it work but alas. My problem is sitespeed.io keeps opening the browser and closing right away. 

I'm running my script like such:
`npx sitespeed.io login.js --multi`

```javascript
module.exports = async function(context, commands) {
    try {
        await commands.navigate('https://www.google.com/');
        context.log.info('Done');
    } catch (e) {
        throw e;
    }
}
```

```
[2020-02-21 08:47:05] INFO: Versions OS: darwin 18.7.0 nodejs: v8.16.0 sitespeed.io: 12.0.1 browsertime: 8.0.1 coach: 4.4.0
[2020-02-21 08:47:05] INFO: Running tests using Chrome - 3 iteration(s)
[2020-02-21 08:47:06] ERROR: No page that could be associated with the error:Cannot set property 'url' of undefined
[2020-02-21 08:47:06] ERROR: TypeError: Cannot set property 'url' of undefined
at SeleniumRunner.loadAndWait (/Users/Grant/project/fe/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:204:27)
    at Measure.start (/Users/Grant/project/fe/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:201:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Is this maybe a selenium webdriver problem? Any feedback would be greatly appreciated. Thanks :)

**Comment by soulgalore** [comment]
Hi @grantis I think you need update your NodeJS version. We officially support LTS (12.x) but I think it works with 10.x but it looks like you are using 8. If you can switch to latest 12 and try again. 

Best
Peter

**Comment by soulgalore** [comment]
BTW thanks for reporting, we should add a check for the version so you get a more related error message.

**Comment by grantis** [comment]
Yep changing to Node 12 did the trick. Thank you for your help. 😄

**Comment by hco** [comment]
If someone ends up on this ticket but is already using node 12 (in my case, I am using the docker image sitespeedio/sitespeed.io:12.6.0, which contains node 12):

For me, the reason was that I did a `return commands.measure.stop();` at the end of my script, which was not needed in my case, because all the calls to `commands.measure.start` received an URL.
