### ISSUE TITLE
ERROR: Could not generate url/iteration/index

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#2918]
Getting the following error when running 12.0.1 and 12.1.0.   This is the params:

docker run \
--rm \
-v "$(pwd)":/sitespeed.io \
sitespeedio/sitespeed.io:12.0.1 \
--cookie emailsignupapifeo=10 \
--cookie SDDUZ=07083 \
--cookie SDDCZ=07083 \
--chrome.collectLongTasks true \
--cpu \
--speedIndex true \
reg-bbby-prod-urls-single.txt \
-n 1  \
--graphite.host=10.160.48.92 \
--graphite.httpPort 80 \
--graphite.namespace=sitespeed_io.Reg

[2020-03-11 17:10:41] ERROR: Could not generate url/iteration/index
(node:30) UnhandledPromiseRejectionWarning: TypeError: /usr/src/app/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run
    2| a
    3| h2 CPU
    4|

Cannot read property 'run' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4731:179)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6175:201)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlRunPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:411:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:376:16)
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-03-11 17:10:41] ERROR: TypeError: /usr/src/app/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run
    2| a
    3| h2 CPU
    4|

Cannot read property 'run' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4731:179)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6175:201)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlRunPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:411:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:376:16)
(node:30) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)

**Comment by soulgalore** [comment]
Hi @kmaqsudi it looks like there was a test that did't work, you don't get any error before those errors? I think the key is the URLs you test, if you look at the runs, do you see anything strange?

**Comment by mploquin** [comment]
Hi @soulgalore, i have the same error : 

Google Chrome 85.0.4183.83 
Mozilla Firefox 80.0
[2020-09-24 09:43:24] INFO: Versions OS: linux 5.4.0-48-generic nodejs: v12.16.2 sitespeed.io: 14.4.0 browsertime: 9.4.0 coach: 5.1.1
[2020-09-24 09:43:24] INFO: The following plugins are enabled: assets, axe, browsertime, budget, coach, crux, domains, gcs, graphite, harstorer, html, metrics, pagexray, sustainable, text, thirdparty, tracestorer, webpagetest, /lighthouse, /gpsi
[2020-09-24 09:43:25] INFO: Axe plugin activated
[2020-09-24 09:43:26] INFO: Use the sustainable web plugin
[2020-09-24 09:43:26] INFO: Will run Lighthouse tests after Browsertime has finished
[2020-09-24 09:43:26] INFO: Sending url https://mywebsite to test on Page Speed Insights
[2020-09-24 09:43:26] INFO: Get CrUx data for domain mywebsite
[2020-09-24 09:43:26] INFO: Sending url https://mywebsite to test on https://www.webpagetest.org
[2020-09-24 09:43:27] INFO: Running tests using Chrome - 1 iteration(s)
[2020-09-24 09:43:27] INFO: Get CrUx data for url https://mywebsite
[2020-09-24 09:43:29] INFO: Use Chrome trace categories: -*,disabled-by-default-lighthouse,v8,v8.execute,blink.user_timing,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.stack
[2020-09-24 09:43:29] INFO: Testing url https://mywebsite iteration 1
[2020-09-24 09:43:51] INFO: Got https://mywebsite analysed from Google Page Speed Insights
[2020-09-24 09:43:58] INFO: Got https://mywebsite analysed with id ********** from https://www.webpagetest.org
[2020-09-24 09:43:58] INFO: WebPageTest result at: https://www.webpagetest.org/results.php?test=**********
[2020-09-24 09:43:58] WARN: Couldn't get HAR for id ********** Forbidden (url = https://mywebsite)
[2020-09-24 09:43:59] INFO: https://mywebsite 68 requests, TTFB: 491ms, firstPaint: 1.28s, firstVisualChange: 1.30s, FCP: 1.28s, DOMContentLoaded: 3.94s, LCP: 12.49s, CLS: 0.16, TBT: 756ms, Load: 4.98s, speedIndex: 2.71s, perceptualSpeedIndex: 2.25s, contentfulSpeedIndex: 1.91s, visualComplete85: 5.27s, lastVisualChange: 5.27s
[2020-09-24 09:43:59] INFO: Start collecting Lighthouse result for https://mywebsite iteration 1
[2020-09-24 09:43:59] ERROR: Incomplete first view data for WPT test **********, run 3
[2020-09-24 09:44:13] ERROR: Failing budget Speed Index for https://mywebsite with value 2.711 s max limit 1.500 s
[2020-09-24 09:44:13] ERROR: Failing budget CSS Transfer Size for https://mywebsite with value 208.2 KB max limit 195.3 KB
[2020-09-24 09:44:13] ERROR: Failing budget Image Transfer Size for https://mywebsite with value 560.0 KB max limit 390.6 KB
[2020-09-24 09:44:13] ERROR: Failing budget Font Transfer Size for https://mywebsite with value 316.4 KB max limit 293.0 KB
[2020-09-24 09:44:13] INFO: Budget: 2 working and 4 failing tests
[2020-09-24 09:44:15] ERROR: Could not generate url/iteration/index
[2020-09-24 09:44:15] ERROR: Could not generate url/iteration/index
(node:34) UnhandledPromiseRejectionWarning: TypeError: /usr/src/app/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run 
    2| a
    3| h2 CPU
    4| 

Cannot read property 'run' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4893:179)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6404:7)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlRunPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:447:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:359:16)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:34) UnhandledPromiseRejectionWarning: TypeError: /usr/src/app/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run 
    2| a
    3| h2 CPU
    4| 

Cannot read property 'run' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4893:179)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6404:7)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlRunPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:447:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:359:16)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[2020-09-24 09:44:15] INFO: HTML stored in /sitespeed.io/reports/20200924104319
(node:34) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
(node:34) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
[2020-09-24 09:44:15] INFO: Uploading /sitespeed.io/reports/20200924104319 to Google Cloud Storage bucket **********, this can take a while ...
[2020-09-24 09:44:18] INFO: Finished upload to Google Cloud Storage
[2020-09-24 09:44:18] INFO: Uploaded results on Google Cloud storage are publicly readable
[2020-09-24 09:44:18] INFO: Find the result at https://storage.googleapis.com/**********/www.mywebsite/desktop/cable/20200924104319

**Comment by soulgalore** [comment]
Hi @mploquin when you look at the test at your WebPageTest instance, does it work there?

> [2020-09-24 09:43:59] ERROR: Incomplete first view data for WPT test **********, run 3

signals that something gone wrong on the WebPageTest side. Easiest if you can access the result URL and have a look, can you see something?

**Comment by mploquin** [comment]
I upgraded to sitespeed.io version 15.7.2 and I no longer see this type of error...
