### ISSUE TITLE
All files aren't deleted in the S3 plugin

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#2925]
We have a use case at work where I can see that we don't delete all the files locally in the S3 plugin. ~~The use cases that breaks things, is where we start a search on Google, then clicking on the link to Wikipedia and measure the loading. However, I've seen that the browsers starts to pickup two requests to Google before the Wikipedia request and that creates a different folder structure that isn't deleted (starting with the Google domain)~~. I'll track down the exact use journey so I can recreate it locally.

**Comment by soulgalore** [comment]
Checking the error log it looks like this:
```
[2020-03-16 08:09:35] INFO: https://www.amazon.com 135 requests, backEndTime: 1.51s, firstPaint: 3.25s, firstVisualChange: 3.27s, DOMContentLoaded: 3.28s, Load: 25.36s, speedIndex: 3376, perceptualSpeedIndex: 3510, contentfulSpeedIndex: 4011, visualComplete85: 3.33s, lastVisualChange: 23.07s, rumSpeedIndex: 11459
[2020-03-16 08:09:38] ERROR: Could not read filmstrip dir TypeError: Cannot read property 'time' of undefined
    at Object.getFilmstrip (/usr/src/app/lib/plugins/browsertime/filmstrip.js:152:45)
    at async HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:262:13)
[2020-03-16 08:09:38] ERROR: Could not generate url/summary/index
[2020-03-16 08:09:38] ERROR: TypeError: /usr/src/app/lib/plugins/html/templates/url/metrics/layoutShift.pug:1
  > 1| if browsertime.pageinfo.layoutShift !== undefined
    2|     a#layoutShift
    3|     h3 Detected unexpected layout shifts
    4|     if (browsertime.pageinfo.layoutShift === 0) 

Cannot read property 'layoutShift' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3953:26)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6852:201)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:402:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:311:18)
[2020-03-16 08:09:38] INFO: Find the result at https://s3.amazonaws.com/XYZ/www.google.com/2020-03-16-08-02-14
```

So I guess it could be that HTML error makes it fail. Let me try to make that more solid (+ fix the origin problem).

**Comment by soulgalore** [comment]
So I've changed so that the pug catch missing data and then use allSettle for promises when creating the HTML (for NodeJS versions that supports it). One last step could be fix so we don't throw exceptions if something goes wrong generating the HTML ... but lets do that next step.

**Comment by soulgalore** [comment]
This is fixed ok for now.
