### ISSUE TITLE
[feature request] add commands.wait.bySelector()

### ISSUE THREAD

**Issue by petemyron** [sitespeedio/sitespeed.io#2961]
`commands.click.bySelector()` exists, but not `commands.wait.bySelector`. It's inconvenient and less readable to switch between using xpath and css selectors in a multi-page test script. It would be better to be consistent in test scripts.

example (not actually tested):

```
...
// go to a page
await commands.navigate('https://google.com/', "google_home");

// add some text, this works
await commands.addText.bySelector("whatevs", "input.gLFyf.gsfi");

// click a button by css selector, this works
await commands.click.bySelector("input.gNO89b");

// await page load by selector, fails
await commands.wait.bySelector("#result-stats", 10000);
```

This gives a TypeError:
`TypeError: commands.wait.bySelector is not a function`

---
- Exact how you run (the exact parameters)
`docker run -it --rm --name whatevs --privileged --shm-size=4g sitespeedio/sitespeed.io:12.5.1 --config /sitespeed.io/config.json /sitespeed.io/test.js --multi --spa`

- Which version you are using
12.5.1

- OS (if you use Docker, report the base OS)
OSX 10.13.6, Docker version 19.03.8, build afacb8b

**Comment by soulgalore** [comment]
Hi @petemyron yes I agree, I added a PR for that in https://github.com/sitespeedio/browsertime/pull/1247 but I haven't had time to test it. Have you used Browsertime and could verify that the PR work?

**Comment by petemyron** [comment]
Yes, this works for me, thanks!

I tested with:
```
module.exports = async function(context, commands) {

    // success test
    try {
        page_name = 'google_should_succeed'
        await commands.measure.start(page_name);
        await commands.navigate('https://google.com/', page_name);

        // mark this as a pass if it loads successfully, a hack while missing dynamic influxdb tags
        await commands.js.run('performance.mark("' + page_name + '_passed");');

        // wait by selector
        await commands.wait.bySelector('input[aria-label="Search"');

        context.log.info('... test passed');

    } catch (error) {
        await commands.js.run('performance.mark("' + page_name + '_failed");');
        context.log.info(error);
        context.log.info('... test failed');

    } finally {
        await commands.measure.stop();
    }

    // fail test
    try {
        page_name = 'google_should_fail'
        await commands.measure.start(page_name);
        await commands.navigate('https://google.com/', page_name);

        // mark this as a pass if it loads successfully, a hack while missing dynamic influxdb tags
        await commands.js.run('performance.mark("' + page_name + '_passed");');

        // wait by selector
        await commands.wait.bySelector('#madeup');

        context.log.info('... test passed');

    } catch (error) {
        await commands.js.run('performance.mark("' + page_name + '_failed");');
        context.log.info(error);
        context.log.info('... test failed');

    } finally {
        await commands.measure.stop();
    }
}
```

and got the result:
```
browsertime on  master [⇡!] is 📦 v8.6.1 via ⬢ v12.16.2 on 🐳 v19.03.8 at ☸️  staging took 30s
➜ browsertime ~/workspace/scratch/test_browsertime_bySelector.js --multi --spa -n 1
[2020-04-21 12:57:27] INFO: Running tests using Chrome - 1 iteration(s)
[2020-04-21 12:57:32] INFO: Start to measure google_should_succeed
[2020-04-21 12:57:32] INFO: Navigating to url https://google.com/ iteration 1
[2020-04-21 12:58:10] INFO: ... test passed
[2020-04-21 12:58:11] INFO: Start to measure google_should_fail
[2020-04-21 12:58:11] INFO: Navigating to url https://google.com/ iteration 1
[2020-04-21 12:58:25] ERROR: Element by selector #madeup was not located in 6000 ms
[2020-04-21 12:58:25] INFO: Error: Element by selector #madeup was not located in 6000 ms
    at Wait.bySelector (/Users/pmyron/workspace/browsertime/lib/core/engine/command/wait.js:82:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-04-21 12:58:25] INFO: ... test failed
[2020-04-21 12:58:25] INFO: https://www.google.com/ has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2020-04-21 12:58:25] INFO: https://www.google.com/ 27 requests, backEndTime: 791ms, firstPaint: 969ms, FCP: 969ms, DOMContentLoaded: 1.02s, LCP: 1.09s, Load: 2.03s
[2020-04-21 12:58:25] INFO: https://www.google.com/?browsertime_run=2 8 requests, backEndTime: 388ms, firstPaint: 531ms, FCP: 531ms, DOMContentLoaded: 524ms, LCP: 531ms, Load: 873ms
[2020-04-21 12:58:25] INFO: Wrote data to browsertime-results/Users-pmyron-workspace-scratch-test_browsertime_bySelector.js/2020-04-21T125726-0700
```
