### ISSUE TITLE
Visual Metrics failed to analyse the video Error: Command failed with exit code 1

### ISSUE THREAD

**Issue by pherrymason** [sitespeedio/sitespeed.io#2993]
We are having intermittent errors in our tests. 
They seem with VisualMetrics not being able to process/generate videos, but I don't fully understand the source.  
If you need more information just ask:

```
ERROR: VisualMetrics failed to run Error: Command failed with exit code 1: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py --dir /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5 --video /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4 --orange --perceptual --contentful --force --renderignore 5 --json --viewport -q 75 --logfile /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.visualmetrics.log -vvv
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    at makeError (/usr/src/app/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/src/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.run (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/visualMetrics.js:93:22)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/getVideoMetrics.js:34:21)
    at async Video.postProcessing (/usr/src/app/node_modules/browsertime/lib/video/video.js:94:22)
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:226:34)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:166:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-05-12 11:14:48] ERROR: Log from VisualMetrics: 11:14:48.563 - Processing frames from video /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4 to /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5
11:14:48.637 - Extracting frames from /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4 to /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5
11:14:48.710 - [Errno 2] No such file or directory: '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/video-000000.png'
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py", line 2273, in main
    video_to_frames(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py", line 113, in video_to_frames
    remove_orange_frames(dir, orange_file)
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py", line 280, in remove_orange_frames
    os.remove(frame)
FileNotFoundError: [Errno 2] No such file or directory: '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/video-000000.png'
[2020-05-12 11:14:48] ERROR: Could not run Visual Metrics Error: Command failed with exit code 1: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py --dir /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5 --video /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4 --orange --perceptual --contentful --force --renderignore 5 --json --viewport -q 75 --logfile /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.visualmetrics.log -vvv
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    at makeError (/usr/src/app/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/src/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.run (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/visualMetrics.js:93:22)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/getVideoMetrics.js:34:21)
    at async Video.postProcessing (/usr/src/app/node_modules/browsertime/lib/video/video.js:94:22)
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:226:34)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:166:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-05-12 11:14:48] ERROR: Visual Metrics failed to analyse the video Error: Command failed with exit code 1: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics.py --dir /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5 --video /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4 --orange --perceptual --contentful --force --renderignore 5 --json --viewport -q 75 --logfile /sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.visualmetrics.log -vvv
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/video/5.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:00.07, start: 0.000000, bitrate: 232 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1366x642, 134 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/<OUR-URL>/2020-05-12-11-11-17/pages/<OUR-URL>/data/filmstrip/5/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: png, rgb24, 1366x642, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.774x    
video:5kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    at makeError (/usr/src/app/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/src/app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.run (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/visualMetrics.js:93:22)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/single/getVideoMetrics.js:34:21)
    at async Video.postProcessing (/usr/src/app/node_modules/browsertime/lib/video/video.js:94:22)
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:226:34)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:166:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-05-12 11:14:48] ERROR: TypeError: Cannot read property 'push' of undefined
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:251:31)
[2020-05-12 11:14:48] ERROR: TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:115:31)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:125:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
```

The command we are using is:
```
docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:12.7.1-plus1 <OUR-URL> --config sitespeed.config.json
```

This is our `sitespeed.config.json`:
```
{
  "browsertime": {
    "iterations": 4,
    "browser": "chrome"
  },
  "graphite": {
    "host": <OUR-GRAPHITE-HOST>,
    "port": "32378",
    "statsd": true,
    "namespace": "sitespeed"
  },
  "plugins": {
    "add": ["analysisstorer", "lighthouse"]
  },
  "utc": true,
  "metrics": {
    "filter": [
      "*-",
      "browsertime.pageSummary.statistics.timings.paintTiming.first-contentful-paint.mean",
      "browsertime.pageSummary.statistics.visualMetrics.FirstVisualChange.median",
      "browsertime.pageSummary.statistics.visualMetrics.LastVisualChange.mean",
      "browsertime.pageSummary.statistics.visualMetrics.PerceptualSpeedIndex.median",
      "browsertime.pageSummary.statistics.visualMetrics.VisualComplete85.mean",
      "browsertime.pageSummary.statistics.timings.pageTimings.backEndTime.mean",
      "browsertime.pageSummary.statistics.timings.pageTimings.frontEndTime.mean",
      "browsertime.pageSummary.statistics.timings.pageTimings.domInteractiveTime.mean",
      "lighthouse.pageSummary.audits.first-contentful-paint.score",
      "lighthouse.pageSummary.audits.metrics.details.items.0.firstContentfulPaint",
      "lighthouse.pageSummary.audits.speed-index.score",
      "lighthouse.pageSummary.audits.metrics.details.items.0.speedIndex",
      "lighthouse.pageSummary.audits.first-cpu-idle.score",
      "lighthouse.pageSummary.audits.metrics.details.items.0.firstCPUIdle",
      "lighthouse.pageSummary.audits.interactive.score",
      "lighthouse.pageSummary.audits.metrics.details.items.0.interactive",
      "lighthouse.pageSummary.audits.estimated-input-latency.score",
      "lighthouse.pageSummary.audits.metrics.details.items.0.estimatedInputLatency"
    ]
  },
  "groupAlias": "web"
}
```

**Comment by soulgalore** [comment]
Hi @raulferras hmm it looks like the video wasn't recorded. Do you access one URL or do you use scripting to record multiple steps? If you look at the screenshot, does it look like the browser was able to navigate to the page?

**Comment by raulferras** [comment]
You made me think on something, the site is doing some ajax requests to a protected endpoint (vpn) that might be failing. I will check that and report the result here.

Thanks

**Comment by raulferras** [comment]
Hello again, I've checked and I can confirm the site is accessible, so no problems with VPN are occurring.
Is it possible there's no space free in the hard disk? Or a different error would have triggered?

**Comment by soulgalore** [comment]
Do this happen every time you run or random ?

**Comment by raulferras** [comment]
It does not happen every time, but I don't see any pattern on when it happens, so it is apparently random.

**Comment by bkarlson** [comment]
Had same error message on Ubuntu 20.04 with yarn install of sitespeed.io (no Docker). Culprit was missing python libs, to install:

```
apt-get install python3 python3-pip python-is-python3
pip3 install Pillow image pyssim
```

Everything runs smooth after that.

**Comment by soulgalore** [comment]
We updated the visual metrics script years ago and I hope that fixes the issue. Make sure you follow the installation instructions.
