### ISSUE TITLE
No host available error returned - metrics are still sent to Influxdb

### ISSUE THREAD

**Issue by leathej1** [sitespeedio/sitespeed.io#3015]
Dockerized SS 13.0.3
Command:
`sudo docker run -e MAX_OLD_SPACE_SIZE=4096 --name sitespeed --cap-add=NET_ADMIN --shm-size=4g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.0.3 n
av-crm.js`

The script execution is throwing dozens of the same error, but the metrics are correctly sent to my Influxdb.

Config:
`  "influxdb": {
    "protocol": "http",
    "host": <my ip>,
    "port": "8086",
    "username": "admin",
    "password": "admin",
    "database": "sitespeed",
    "tags": "category=Prod",
    "includeQueryParams": "true",
    "annotationScreenshot": "true"

Repeated errors:
`[2020-05-27 20:17:17] ERROR: Error: No host available
    at Pool.stream (/usr/src/app/node_modules/influx/lib/src/pool.js:228:29)
    at /usr/src/app/node_modules/influx/lib/src/pool.js:165:18
    at new Promise (<anonymous>)
    at Pool.discard (/usr/src/app/node_modules/influx/lib/src/pool.js:164:16)
    at InfluxDB.writePoints (/usr/src/app/node_modules/influx/lib/src/index.js:840:27)
    at InfluxDBSender.send (/usr/src/app/lib/plugins/influxdb/sender.js:26:24)
    at Object.processMessage (/usr/src/app/lib/plugins/influxdb/index.js:125:26)
    at /usr/src/app/lib/core/queueHandler.js:211:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

**Comment by soulgalore** [comment]
It comes from the Influx package we use https://github.com/node-influx/node-influx but I couldn't see anything in their issues. Could it be that your host is going up and down?

**Comment by leathej1** [comment]
This seems to be a symptom of the container having trouble with high JS heap usage. Since I do not see this issue in real time, is there a way to root out memory usage problems when a script runs?

**Comment by zefrs** [comment]
I seem to be having the exact same issue:

ERROR: [sitespeedio.queuehandler] Error: No host available
    at Pool.stream (/usr/src/app/node_modules/influx/lib/src/pool.js:228:29)
    at /usr/src/app/node_modules/influx/lib/src/pool.js:165:18
    at new Promise (<anonymous>)
    at Pool.discard (/usr/src/app/node_modules/influx/lib/src/pool.js:164:16)
    at InfluxDB.writePoints (/usr/src/app/node_modules/influx/lib/src/index.js:840:27)
    at InfluxDBSender.send (/usr/src/app/lib/plugins/influxdb/sender.js:26:24)
    at Object.processMessage (/usr/src/app/lib/plugins/influxdb/index.js:117:26)
    at /usr/src/app/lib/core/queueHandler.js:211:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)

**Comment by soulgalore** [comment]
@leathej1 you can increase the memory for NodeJS: https://www.sitespeed.io/documentation/sitespeed.io/docker/#increase-memory

**Comment by soulgalore** [comment]
Hi @zefrs do you know when it started to appear? We run a couple of tests on dashboard.sitespeed.io where we send the data to InfluxDB but I haven't seen anything there (yet).

**Comment by leathej1** [comment]
Oh, yes - I have done that already. It just runs out of heap with higher
memory. I need to determine why it is running out of memory - this happens
after one step in a script.

**Comment by zefrs** [comment]
Hi @soulgalore , so this may have been an issue on my end (unable to resolve InfluxDB hostname), further investigation are ongoing on my end.

**Comment by amitmalhotra-cell** [comment]
hi @soulgalore 

Sorry to jump in between. I am too facing the exact same error from past few days. 
I have been running this test since past 3 months and it was working fine. I am using default memory size for NodeJS. Do i need to increase memory or is this issue related to influxdb ?

ERROR 
But now i see at first login measurement only , i see first request time out and then No host available. 


ERROR IMAGE
![image](https://user-images.githubusercontent.com/63041681/95321902-54d2b880-08b9-11eb-9703-7451a25d361f.png)
![image](https://user-images.githubusercontent.com/63041681/95321584-df66e800-08b8-11eb-92e3-c6d93ea3af37.png)

**Comment by amitmalhotra-cell** [comment]
My Bad, i checked in my case, it was because influxdb was not reachable as someone accidently removed vpc.
Its working fine now.
