### ISSUE TITLE
Error: Unable to find domain in "" when running a simple test

### ISSUE THREAD

**Issue by logkrish** [sitespeedio/sitespeed.io#3043]
Hi,

Newbie to sitespeed and trying out some basic tests to get the hang of it. When I tried to reach the login page of our website with the commend:

docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:13.3.0 https://ops360server-qa/ -b chrome -n 1

the test fails with the exception:

[2020-06-17 15:15:06] INFO: Testing url https://ops360server-qa/ iteration 1
[2020-06-17 15:15:24] INFO: https://ops360server-qa/ 12 requests, TTFB: 18ms, firstPaint: 220ms, firstVisualChange: 366ms, FCP: 220ms, DOMContentLoaded: 196ms, LCP: 355ms, CLS: 0, Load: 339ms, speedIndex: 509ms, perceptualSpeedIndex: 590ms, contentfulSpeedIndex: 610ms, visualComplete85: 366ms, lastVisualChange: 6.37s
[2020-06-17 15:15:24] ERROR: Error: Unable to find domain in "ops360server-qa"
    at getDomainFromOriginOrURL (/usr/src/app/node_modules/third-party-web/lib/create-entity-finder-api.js:11:9)
    at getRootDomain (/usr/src/app/node_modules/third-party-web/lib/create-entity-finder-api.js:15:18)
    at getEntityInDataset (/usr/src/app/node_modules/third-party-web/lib/create-entity-finder-api.js:24:22)
    at Object.module.exports.getThirdParty (/usr/src/app/node_modules/coach-core/lib/har/thirdParty.js:14:9)
    at Object.processPage (/usr/src/app/node_modules/coach-core/lib/har/privacy/thirdPartyPrivacy.js:14:37)
    at Object.module.exports.runAdvice (/usr/src/app/node_modules/coach-core/lib/har/index.js:24:31)
    at Object.analyseHar (/usr/src/app/node_modules/coach-core/lib/index.js:72:22)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:394:35)
[2020-06-17 15:15:25] INFO: HTML stored in /sitespeed.io/sitespeed-result/ops360server-qa/2020-06-17-15-15-05

Interestingly, when I tried the same on **browsertime** with the following command, that worked fine and I could see in the video that the login page had been loaded

docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:8.14.0 https://ops360server-qa/ -b chrome -n 1

The tests were executed on a linux box. 

I have attached the video from browsertime to the post
[1.zip](https://github.com/sitespeedio/sitespeed.io/files/4793913/1.zip)

Unfortunately this site is not public, so you cannot try it yourself.

Any help on how to troubleshoot this further is much appreacited.

Many Thanks

**Comment by soulgalore** [comment]
Hi, I think this is a bug in how we use https://github.com/patrickhulce/third-party-web. That project do not handle if you use a URL without a domain, I think we have some checks on our side but it looks like it isn't enough. What you can do for now is to change so you use a domain instead of _ops360server-qa_

**Comment by muuvmuuv** [comment]
I have the exact same problem and cannot use a domain because it is a standalone httpd service.

```
❯ docker run --shm-size=1g --net=aqua --rm -v  "$(pwd)/tmp":/sitespeed.io sitespeedio/sitespeed.io:latest -b chrome -n 1 http://webapp
`
``

I would love to see that working without using a domain. Maybe run like a proxy inside the container to forward url requests to a default domain.

**Comment by soulgalore** [comment]
I catched the error in the coach, coming in the next release in two days.
