### ISSUE TITLE
HMTL output paints with blank data after script run failure

### ISSUE THREAD

**Issue by mrobbins** [sitespeedio/sitespeed.io#3070]
When running a Checkout script, an error is thrown when a spinner is present. This error seems to fail in a way that prevents the html output from rendering appropriately. 
The file is there but the data output is blank. 
![image](https://user-images.githubusercontent.com/4596076/86830190-62cb3000-c063-11ea-93fd-b17db36c3aa2.png)
 
The output of the log file :
```
[2020-07-07 17:31:10] INFO: [sitespeedio] Versions OS: linux 3.10.0-957.27.2.el7.x86_64 nodejs: v12.13.0 sitespeed.io: 13.3.2 browsertime: 9.0.0 coach: 5.1.0
[2020-07-07 17:31:10] INFO: [browsertime] Running tests using Chrome - 1 iteration(s)
[2020-07-07 17:31:11] INFO: [browsertime.command.measure] Start to measure Mobile: Blizzard Gear Store Checkout Test Checkout
[2020-07-07 17:31:11] INFO: [browsertime] Mobile: Blizzard Gear Store Checkout Test Load Page
[2020-07-07 17:31:11] INFO: [browsertime.command.measure] Navigating to url https://m.blizzardgearstore.com iteration 1
[2020-07-07 17:31:21] INFO: [browsertime] Checkout attempt #: 1
[2020-07-07 17:31:22] INFO: [browsertime] Click on the Search button
[2020-07-07 17:31:22] INFO: [browsertime] Search for "shirt"
[2020-07-07 17:31:22] INFO: [browsertime] Click on Search
[2020-07-07 17:31:29] INFO: [browsertime] Select a product from the grid
[2020-07-07 17:31:36] INFO: [browsertime] Check if there is a need to select Product Size
[2020-07-07 17:31:36] INFO: [browsertime] Select Product Size
[2020-07-07 17:31:37] INFO: [browsertime] Check if the item is Out of Stock or there is an error popup
[2020-07-07 17:31:37] INFO: [browsertime] No error... Proceeding to checkout cart
[2020-07-07 17:31:37] INFO: [browsertime] Click on the Add to cart button
[2020-07-07 17:31:38] INFO: [browsertime] click checkout button
[2020-07-07 17:31:38] ERROR: [browsertime] Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read property 'click' of null
  (Session info: chrome=83.0.4103.116)
[2020-07-07 17:31:38] ERROR: [browsertime.command.click] Could not click using selector #basketContent > div.ng-scope > div.payment > button
[2020-07-07 17:31:38] ERROR: [browsertime] Error: Could not click using selector #basketContent > div.ng-scope > div.payment > button
    at Click.bySelectorAndWait (/usr/src/app/node_modules/browsertime/lib/core/engine/command/click.js:242:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2020-07-07 17:31:41] ERROR: [browsertime] Couldn't execute script named documentHeight error:JavascriptError: javascript error: Cannot read property 'scrollHeight' of null
  (Session info: chrome=83.0.4103.116)
[2020-07-07 17:31:41] ERROR: [browsertime] Failed to execute user script: JavascriptError: javascript error: Cannot read property 'scrollHeight' of null
  (Session info: chrome=83.0.4103.116)
[2020-07-07 17:31:42] ERROR: [browsertime] Unhandled value type undefined found when adding data for pageinfo 
[2020-07-07 17:31:42] ERROR: [sitespeedio.queuehandler] TypeError: Cannot read property 'layoutShift' of undefined
    at Object.logResultLogLine (/usr/src/app/node_modules/browsertime/lib/support/util.js:90:16)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:210:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:117:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-07-07 17:31:43] INFO: [sitespeedio.plugin.html] HTML stored in /sitespeed.io/sitespeed-result/m_blizzardgearstore_com-Checkout_js/2020-07-07-17-31-10
[2020-07-07 17:31:43] INFO: [sitespeedio.plugin.s3] Uploading /sitespeed.io/sitespeed-result/m_blizzardgearstore_com-Checkout_js/2020-07-07-17-31-10 to S3 bucket <bucket name>, this can take a while ...
```
config file:
```
{
    "browsertime": {
      "timeouts": {
        "browserStart": "40000",
        "pageLoad": "10000",
        "pageCompleteWaitTime": "90000",
        "script": "240000"
      },
      "cacheClearRaw": true,
      "iterations": 1,
      "requestheader": "<restricted header>",
      "video": false,
      "visualMetrics": false,
      "chrome": {
        "args": "disable-application-cache",
        "args": "no-sandbox"
      }
    },
    "resultBaseURL": "https://<server name>/results",
    "s3": {
      "region": "<region>",
      "bucketname": "<bucket name>",
      "removeLocalResult": true
    },    
    "html": {
      "logDownloadLink": true,
      "fetchHARFiles": true,
      "showScript": true
    },
    "graphite": {
      "host": "127.0.0.1",
      "port": 8125,
      "namespace": "<namespace>",
      "statsd": true,
      "annotationSend": false
    },
    "logToFile": true,
    "utc": true,
    "multi": true
  }

```

**Comment by soulgalore** [comment]
Hi @mrobbins thanks for creating the issue, yeah that error should be caught and at least we should have an error in the HTML output. Let me try to reduce to a simpler use case the later this week.

**Comment by soulgalore** [comment]
I added safer check to remove one of the later errors. For the original error, checkout https://www.sitespeed.io/documentation/sitespeed.io/scripting/#error-handling that way you can catch errors in your script and make sure they end up in your output.

**Comment by jdmchone** [comment]
Do you know when this fix will merge into the browsertime master branch? I'm assuming once it's there, we just reinstall sitespeed.io?

**Comment by soulgalore** [comment]
That fix will fix the secondary failure. I think the best thing is to try/catch the script and if there's a failure etc, and your own error.

**Comment by jdmchone** [comment]
Right the second error was the issue I was concerned with. Couldn't figure out why the 'layoutShift' was causing blank HTML pages.

**Comment by soulgalore** [comment]
I think this was fixed.
