### ISSUE TITLE
How To Run various Scenario's in parallel 

### ISSUE THREAD

**Issue by rishabh7774** [sitespeedio/sitespeed.io#3077]
`[2020-07-09 11:47:55] DEBUG: [browsertime.video] Stop screen recording
[2020-07-09 11:47:55] ERROR: [browsertime] TypeError: Cannot read property 'stdin' of undefined
    at /usr/src/app/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:149:15
[2020-07-09 11:47:55] DEBUG: [browsertime] Kill all processes ffmpeg
[2020-07-09 11:47:55] DEBUG: [browsertime] Closed the browser.
[2020-07-09 11:47:55] ERROR: [sitespeedio.queuehandler] TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:116:31)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:178:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:118:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)`

I have 2 scripts User1 And User2 Each containing multiple start/stop. When I run a script without start/stop it is working as expected, but with start/stop it is giving me above error.

Test.js 
const User1=require('../UserFlow.js');
const User2=require('../UserFlow1.js');
module.exports=async function(context,commands) {
    await Promise.all([User1(context,commands),User2(context,commands)]);
};

**Comment by soulgalore** [comment]
Hi @rishabh7774 do you run it in Docker or plain NodeJS?

**Comment by soulgalore** [comment]
Closing since we never got any feedback.
