### ISSUE TITLE
Script is failing due to undefined jquery param

### ISSUE THREAD

**Issue by moud97** [sitespeedio/sitespeed.io#3103]
I am currently trying to execute this part of my script 

```
try{
        await commands.navigate(
            'SomeURL');
        // Logging in 
        await commands.wait.byId('account');
        await commands.addText.byId('asdf','account');
        await commands.addText.byId('asdf@no.mail','username');
        await commands.addText.byId('asdf','password');
        await commands.click.byIdAndWait('btnLogin');
        //Creating
        await commands.wait.byXpath('somexpath"]', 30000);
        await commands.click.byXpath('/somexpath"]');
        await commands.click.byIdAndWait('someID');
        await commands.addText.byId('some text', 'someID');
        await commands.measure.start('Create ');
        await commands.click.byId('Save');
        await commands.measure.stop();

        await commands.click.byXpath('//a[@somexpath]');
        await commands.measure.start('display');
        await commands.click.byXpath('SomeXpath);
        await commands.wait.byXpath('somexpath"]');
        await commands.measure.stop();

        await commands.measure.start('adding');
        await commands.click.byXpathAndWait('//[@id=add]');
        await commands.measure.stop();
```

This returns the following error 
```
`733ms
[2020-07-24 17:05:51] ERROR: [plugin.browsertime] URL generated the following errors in the coach {
  "info": {
    "thirdparty": "Cannot read property 'jquery' of undefined"
  },
  "performance": {
    "jquery": "Cannot read property 'jquery' of undefined"
  }
}
[2020-07-24 17:05:51] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2020-07-24 17:05:51] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2020-07-24 17:05:51] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2020-07-24 17:05:51] DEBUG: [sitespeedio.plugin.html] Render HTML for 3 page(s) 
[2020-07-24 17:05:51] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2020-07-24 17:05:52] DEBUG: [sitespeedio.plugin.html] Render URL run page 1
[2020-07-24 17:05:52] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2020-07-24 17:05:52] DEBUG: [sitespeedio.plugin.html] Render URL run page 1
[2020-07-24 17:05:52] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2020-07-24 17:05:52] ERROR: [sitespeedio.plugin.html] Could not generate url/summary/index
[2020-07-24 17:05:52] ERROR: [sitespeedio.queuehandler] TypeError: /usr/src/app/lib/plugins/html/templates/url/coach/thirdParty.pug:6
    4|     tr
    5|         td JQuery
  > 6|         td.right #{advice.info.thirdparty.jquery?advice.info.thirdparty.jquery:'No'}
    7|     tr
    8|         td Google Analytics
    9|         td.right #{advice.info.thirdparty.ga?'Yes':'No'}

Cannot read property 'jquery' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2957:80)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6989:7)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:431:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:292:18)
Build step 'Execute shell' marked build as failure` 

```
Noting that the third measure statement is measuring clicking a button that lives in the page that the second measure statement is measuring. The button navigates to a different page and the URLs of these pages are different though so I dont believe it has to do with similar URLs. The error is thrown on the third measure statement.

**Comment by soulgalore** [comment]
Hi @moud97 thank you for creating the report! I looked at the code in the Coach and it looks like it could be that the page is overriding the window object, could that be the case? If so, can you share the URL and I can try to fix it in the coach.

**Comment by moud97** [comment]
I unfortunately am unable to share the URL as it’s within an internal region for my company and requires credentials. Is there any alternative approach that would help you resolve it without having the URL? And I’m not sure, I’ve been stumped for a couple days now.

**Comment by soulgalore** [comment]
I'm gonna do a new release of the coach in a couple of weeks and hope I fixed it there. Also you can disable the coach for now to get it to work.

**Comment by soulgalore** [comment]
I think this is fixed now.
