### ISSUE TITLE
Sitespeed.io's CLI command stopped working

### ISSUE THREAD

**Issue by rashnakumar96** [sitespeedio/sitespeed.io#3108]
Sitespeed.io's CLI command stopped working. This command was working a few hours ago but just stopped working. I installed site speed.io on Mac using the command "yarn global add sitespeed.io" and when I run it using the command sitespeed.io https://www.sitespeed.io/. It gives the error: 

ERROR: Could not setup the Chrome Devtools Protocol Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketCloseListener (_http_client.js:400:25)
    at Socket.emit (events.js:322:22)
    at TCP.<anonymous> (net.js:672:12)
[2020-07-27 20:19:37] ERROR: Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketCloseListener (_http_client.js:400:25)
    at Socket.emit (events.js:322:22)
    at TCP.<anonymous> (net.js:672:12)
[2020-07-27 20:19:37] ERROR: No data to collect

**Comment by soulgalore** [comment]
Hi @rashnakumar96 strange. Can you try to restart your computer (if something is running on the port that devtools are using)?
