### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by LukaszTutur** [sitespeedio/sitespeed.io#3117]
I am getting 'TypeError: Cannot read property 'name' of undefined' error while testing some intranet pages (running some simple script).

More information:
- The error started to occur in version 14.2.3 for chrome only, if test is ran with --browser firefox, it works OK
- When error occurs there is no log file produced, /logs/ directory is empty, this is why I can not send a log file :(
- The video file on the other hand if produced in ./pages/www.test.com/data/video/1.mp4 and it shows page properly loaded
- When test is ran with --debug option, there is no additional Error information logged
- When script is ran with measure.start/navigate/stop, the Error tends to occur on measure.stop() (after .log.info('STOP'))

For more information please refer to attached log
[console.log](https://github.com/sitespeedio/sitespeed.io/files/5053281/console.log)
[sitespeed.js.log](https://github.com/sitespeedio/sitespeed.io/files/5053287/sitespeed.js.log)

Is there anything else I can check or provide to get to the bottom of this issue?

**Comment by dejwid** [comment]
I have the same problem with some websites on my macos

```
[2020-08-20 06:49:51] INFO: Versions OS: linux 4.19.76-linuxkit nodejs: v12.18.2 sitespeed.io: 14.2.3 browsertime: 9.2.1 coach: 5.1.0
[2020-08-20 06:49:51] INFO: Running tests using Chrome - 1 iteration(s)
[2020-08-20 06:49:53] INFO: Testing url XXXXXXXX iteration 1
[2020-08-20 06:50:06] ERROR: TypeError: Cannot read property 'name' of undefined
    at /usr/src/app/node_modules/chrome-har/lib/entryFromResponse.js:49:36
    at Array.find (<anonymous>)
    at /usr/src/app/node_modules/chrome-har/lib/entryFromResponse.js:48:51
    at Array.filter (<anonymous>)
    at module.exports (/usr/src/app/node_modules/chrome-har/lib/entryFromResponse.js:46:25)
    at Object.harFromMessages (/usr/src/app/node_modules/chrome-har/index.js:194:17)
    at ChromeDelegate.onCollect (/usr/src/app/node_modules/browsertime/lib/chrome/webdriver/chromeDelegate.js:390:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Measure.collect (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:378:5)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:192:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:174:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-08-20 06:50:06] ERROR: TypeError: Cannot read property 'length' of undefined
    at Collector.perIteration (/usr/src/app/node_modules/browsertime/lib/core/engine/collector.js:116:31)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:178:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
```

**Comment by soulgalore** [comment]
@dejwid upgrade to 14.3.0 and I think it will work, checkout https://github.com/sitespeedio/sitespeed.io/issues/3128

**Comment by LukaszTutur** [comment]
yeap, tested on 14.3.0 and it looks OK now
