### ISSUE TITLE
Install sitespeed.io along with Grafana & Graphite on Ubuntu 

### ISSUE THREAD

**Issue by zzhao2010** [sitespeedio/sitespeed.io#3144]
Hi,
I was trying to install sitespeed.io along with Grafana & Graphite on Ubuntu. However I didn't see data reporting to Grafana.
Below is what I did based on the doc. My Ubuntu VM is running on Azure.

1. curl -O https://raw.githubusercontent.com/sitespeedio/sitespeed.io/main/docker/docker-compose.yml
2. docker-compose up -d

root@sitespeedvm0:~# docker ps
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS              PORTS                                                                                                                     NAMES
3a86b1433655        grafana/grafana:7.1.3           "/run.sh"           2 hours ago         Up 2 hours          0.0.0.0:3000->3000/tcp                                                                                                    sitespeedio_grafana_1
bc3ac4c160d1        sitespeedio/graphite:1.1.5-12   "/entrypoint"       2 hours ago         Up 2 hours          2004/tcp, 2013-2014/tcp, 2023-2024/tcp, 8080/tcp, 0.0.0.0:2003->2003/tcp, 8125-8126/tcp, 8125/udp, 0.0.0.0:8080->80/tcp   sitespeedio_graphite_1

3. docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" --network=host sitespeedio/sitespeed.io:14.4.0 -b firefox https://www.google.com --graphite.host=host.docker.internal

I did not see any data reporting to Grafana.

root@sitespeedvm0:~# hostname
sitespeedvm0 

root@sitespeedvm0:/opt/sitespeedio# docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" --network=host sitespeedio/sitespeed.io:14.4.0 -b firefox https://www.google.com --graphite.host=host.docker.internal
Google Chrome 85.0.4183.83 
Mozilla Firefox 80.0
[2020-09-08 18:16:38] INFO: Versions OS: linux 5.4.0-1023-azure nodejs: v12.16.2 sitespeed.io: 14.4.0 browsertime: 9.4.0 coach: 5.1.1
[2020-09-08 18:16:38] INFO: Running tests using Firefox - 3 iteration(s)
[2020-09-08 18:16:42] INFO: Testing url https://www.google.com iteration 1
[2020-09-08 18:16:51] INFO: Waiting on har-export-trigger to collect the HAR
[2020-09-08 18:16:55] INFO: https://www.google.com TTFB: 364ms DOMContentLoaded: 478ms firstPaint: 494ms Load: 1.29s 
[2020-09-08 18:16:55] INFO: VisualMetrics: FirstVisualChange: 534ms SpeedIndex: 551ms PerceptualSpeedIndex: 538ms ContentfulSpeedIndex: 578ms VisualComplete85: 568ms LastVisualChange: 6.51s
[2020-09-08 18:16:59] INFO: Testing url https://www.google.com iteration 2
[2020-09-08 18:17:09] INFO: Waiting on har-export-trigger to collect the HAR
[2020-09-08 18:17:18] INFO: https://www.google.com TTFB: 311ms DOMContentLoaded: 484ms firstPaint: 459ms Load: 1.17s 
[2020-09-08 18:17:18] INFO: VisualMetrics: FirstVisualChange: 467ms SpeedIndex: 513ms PerceptualSpeedIndex: 472ms ContentfulSpeedIndex: 516ms VisualComplete85: 534ms LastVisualChange: 6.47s
[2020-09-08 18:17:22] INFO: Testing url https://www.google.com iteration 3
[2020-09-08 18:17:32] INFO: Waiting on har-export-trigger to collect the HAR
[2020-09-08 18:17:41] INFO: https://www.google.com TTFB: 321ms DOMContentLoaded: 450ms firstPaint: 440ms Load: 1.22s 
[2020-09-08 18:17:41] INFO: VisualMetrics: FirstVisualChange: 467ms SpeedIndex: 485ms PerceptualSpeedIndex: 471ms ContentfulSpeedIndex: 505ms VisualComplete85: 500ms LastVisualChange: 6.43s
[2020-09-08 18:17:41] INFO: https://www.google.com 17 requests, TTFB: 332ms (±13.27ms), firstPaint: 464ms (±12.91ms), firstVisualChange: 489ms (±18.24ms), DOMContentLoaded: 471ms (±8.55ms), Load: 1.22s (±27.72ms), speedIndex: 516ms (±15.62ms), perceptualSpeedIndex: 494ms (±18.10ms), contentfulSpeedIndex: 533ms (±18.55ms), visualComplete85: 534ms (±16.03ms), lastVisualChange: 6.47s (±17.48ms) (3 runs)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:41] ERROR: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
[2020-09-08 18:17:44] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.google.com/2020-09-08-18-16-38

**Comment by soulgalore** [comment]
Hi @zzhao2010 here's some docs on how to access localhost in Docker:https://www.sitespeed.io/documentation/sitespeed.io/docker/#access-localhost 

In your case I think you should use` --network=host  --graphite.host=localhost` (if you run sitespeed.io on the same server as Graphite).

**Comment by zzhao2010** [comment]
Hi @soulgalore,
I see some datapoint in Page Summary dashboard. However I still didn't see data coming in on other dashboards like page timing one.

**Comment by soulgalore** [comment]
Did you get this to work @zzhao2010 ?

**Comment by merlwein** [comment]
At least it helped me. Thank you ver much. I am a Linux and Ubuntu noob and a happy Windows 10 user. I tried a 1.000 times with Ubunutu, root rights, different ports, passwords etc.! With Docker in Windows everything worked extremely well. With Ubuntu I was close to forget about it - till I found this posting here.
Thanls @soulgalore (and thanks @zzhao2010 for asking the same questin.
