### ISSUE TITLE
Page timing out after 300000 ms with Browsertime but no issues on Lighthouse or WebPageTest

### ISSUE THREAD

**Issue by shaqb** [sitespeedio/sitespeed.io#3155]
Hi there,

I am running the following test: 

`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:15.2.0 https://www.hollandandbarrett.com/shop/product/dr-organic-skin-clear-deep-pore-face-wash-60014163 --browsertime.connectivity.engine tsproxy --browsertime.connectivity.profile 3gfast --browsertime.chrome.args kiosk --browsertime.requestheader "user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A372 PTST/200921.220951" -mobile`

However every time it runs I get the following error: 

```
ERROR: Failed waiting on page https://www.hollandandbarrett.com/shop/product/dr-organic-skin-clear-deep-pore-face-wash-60014163 to finished loading, timed out after 300000 ms BrowserError: Running page complete check 
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
    at /usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:39:38
    at new Promise (<anonymous>)
    at timeout (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:38:5)
    at SeleniumRunner.wait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:169:13)
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:246:20)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:201:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:194:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
[2020-09-30 12:59:41] INFO: URL failed to load, trying 5 more time(s): Failed waiting on page https://www.hollandandbarrett.com/shop/product/dr-organic-skin-clear-deep-pore-face-wash-60014163  to finished loading, timed out after 300000 ms 
[2020-09-30 13:04:42] ERROR: Failed waiting on page https://www.hollandandbarrett.com/shop/product/dr-organic-skin-clear-deep-pore-face-wash-60014163 to finished loading, timed out after 300000 ms BrowserError: Running page complete check 
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
return (function(waitTime) {
    try { 
            var end = window.performance.timing.loadEventEnd;
            var start= window.performance.timing.navigationStart;
            return (end > 0) && (performance.now() > end - start + waitTime);
    } 
    catch(e) {
        return true;
    }
})(arguments[arguments.length - 1]);
 took too long
    at /usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:39:38
    at new Promise (<anonymous>)
    at timeout (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:38:5)
    at SeleniumRunner.wait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:169:13)
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:246:20)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:201:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:194:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)

```
When I run the same test on WebPageTest I get no issues (https://webpagetest.org/result/200930_DiJP_7bbd8368ea5c01ee80d1539fd8630f32/). 

Unfortunately because of the error it doesn't seem to capture any logs, so I have no other output other than the output above.

In addition I am running this on macOS Catalina 10.15.7.

Thanks, and let me know if you would like any more information.

**Comment by soulgalore** [comment]
My guess its something to do with TSProxy. If I run on OS X I usually use Throttle before I run docker and then after stop the throttling. Checkout https://www.sitespeed.io/documentation/sitespeed.io/connectivity/#throttle

**Comment by shaqb** [comment]
Thanks @soulgalore - we're actually using this in an EKS environment so we have to use TSProxy (as I understand from the documentation?).

**Comment by soulgalore** [comment]
Yeah but in the issue you wrote:
> In addition I am running this on macOS Catalina 10.15.7. 

:D 

Can you try with a faster throttling just to see that it work?

**Comment by shaqb** [comment]
😂  fair point!

So I ran with 'cable' --rtt 28 --inkbps 5000 --outkbps 1000, and the same issue I am afraid. I can push it higher?

**Comment by soulgalore** [comment]
Historically there's been so many problem with TSProxy so we removed it, but added it back again after the Mozilla team started testing out and filed a couple of fixes upstream. The problem has been that it throttled too much. I tried to turn on the log with --verbose but it seems that we don't get a log file automatically, so I need to look into it. Let me move the issue and rephrase it.
