### ISSUE TITLE
Error: EISDIR: illegal operation on a directory , even " respective .js file is present in folder

### ISSUE THREAD

**Issue by TusAuto** [sitespeedio/sitespeed.io#3176]

**Comment by TusAuto** [comment]
Running with gitlab-runner 11.6.1 (8d829975)
  on aws-build-runner-scheduler 8616255e
Using Docker executor with image docker ...
Pulling docker image docker ...
Using docker image sha256:6972c414f322dfa40324df3c503d4b217ccdec6d576e408ed10437f508f4181b for docker ...
Running on runner-8616255e-project-122223-concurrent-0 via ip-10-130-141-188...
00:02
Fetching changes...
00:01
HEAD is now at 0240ecf Update .gitlab-ci.yml
Checking out 0240ecf3 as Script_Refacter1...
Skipping Git submodules setup
$ cd script
$ echo $(pwd)
/builds/horizon/platform-tests/browser-performance/script
$ docker run --shm-size=1g  --rm  -v "$(pwd):/sitespeed.io"  sitespeedio/sitespeed.io:latest  "device-page.js"  --multi  --browsertime.headless  -n 1
Google Chrome 86.0.4240.75 
Mozilla Firefox 82.0
internal/fs/utils.js:230
    throw err;
    ^
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.getAliases (/usr/src/app/lib/cli/util.js:95:12)
    at Object.parseCommandLine (/usr/src/app/lib/cli/cli.js:1574:30)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
ERROR: Job failed: exit code 1

**Comment by soulgalore** [comment]
Hi @TusAuto this looks like a GitLab issue on mounting volumes. In this threads there seems to be some workarounds https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1482

**Comment by soulgalore** [comment]
This is not an issue with sitespeed.io as I understand so closing.

**Comment by TusAuto** [comment]
@soulgalore : i have executed locally with pwd and facing issue again. Please guide me
