### ISSUE TITLE
scenarios getting failed

### ISSUE THREAD

**Issue by Icecold777** [sitespeedio/sitespeed.io#3186]
Hello,

I run some checkout scenario which worked perfectly.
There weren't any changes neither from app side nor test script.
but for the last two days it fails with following errors.
Final report looks OK except the last broken transaction.

[2020-11-05 16:14:33] ERROR: Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:83:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:229:29)

[2020-11-05 16:14:35] ERROR: Could not generate url/iteration/index
(node:34) UnhandledPromiseRejectionWarning: TypeError: /usr/src/app/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run 
    2| a
    3| h2 CPU
    4| 

Cannot read property 'run' of undefined
    at eval (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4893:179)
    at template (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6404:7)
    at Object.renderTemplate (/usr/src/app/lib/plugins/html/renderer.js:28:39)
    at HTMLBuilder._renderUrlRunPage (/usr/src/app/lib/plugins/html/htmlBuilder.js:447:16)
    at HTMLBuilder.render (/usr/src/app/lib/plugins/html/htmlBuilder.js:359:16)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please advice what may be wrong

**Comment by soulgalore** [comment]
Hi @Icecold777 usually `Error: PageIndex out of range` means that some navigation didn't happen (the page wasn't loaded). My guess is that the page has changed (someone changed the HTML) so that your script doesn't work anymore.  Can you try the script locally and see that it still works?

**Comment by Icecold777** [comment]
Hah, you are right @soulgalore. Actually script works as expected end-to-end. But the path of one page has been changed and  now there is two pages with /shipping path. I see that browsertime query parameter was added during the measurement but it corrupts html report for some reason. HARs are messed up between transactions.

**Comment by soulgalore** [comment]
If you can provide a reproducible example I can have a look!

**Comment by Icecold777** [comment]
Issue was solved by itself) close it
