### ISSUE TITLE
GCS Upload - socket.timeout

### ISSUE THREAD

**Issue by bro-ee** [sitespeedio/sitespeed.io#3199]
Have a problem uploading data to GCS.

It works well if I analyze 1-2 URLs, but doesn't work for high amount of URLs. For example 15 URLs uploaded well time to time, but usually I get this error (see below)

Information:
- DOCKER_CONTAINER=sitespeedio/sitespeed.io:15.9.0-plus1
- 15 URL's (from 2 different domain)

```
[2020-11-25 20:37:39] ERROR: Could not upload to Google Cloud Storage {"message":"request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET","config":{"method":"POST","url":"https://www.googleapis.com/oauth2/v4/token","data":{"grant_type":"urn:ietf:params:oauth:grant-type:jwt-bearer","assertion":"{REMOVED}"},"headers":{"Content-Type":"application/json","Accept":"application/json"},"responseType":"json","body":"{\"grant_type\":\"urn:ietf:params:oauth:grant-type:jwt-bearer\",\"assertion\":\"{REMOVED}"}"}}
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketOnEnd (_http_client.js:460:9)
    at TLSSocket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by soulgalore** [comment]
Hi @bro-ee do you have anything special in your config for GCS (proxy or something)? I know @beenanner is a GCS user, does it work cleanly for you?

**Comment by bro-ee** [comment]
> Hi @bro-ee do you have anything special in your config for GCS (proxy or something)? I know @beenanner is a GCS user, does it work cleanly for you?

Hi @soulgalore nope. Only required params:
    "projectID": "XXX",
    "key": "/config/XXX.json",
    "bucketname": "XXX",
    "removeLocalResult": true

**Comment by soulgalore** [comment]
Did you ever get it to work @bro-ee ? I did some try and could not reproduce it :(

**Comment by bro-ee** [comment]
> Did you ever get it to work @bro-ee ? I did some try and could not reproduce it :(

Yep I did, but don't know how :dancers:
