### ISSUE TITLE
In Chrome Browser, Client width error is displayed while executing the scripts via Docker Container 

### ISSUE THREAD

**Issue by sathishkg901** [sitespeedio/sitespeed.io#3206]

**Comment by sathishkg901** [comment]
[2020-12-14 10:06:01] ERROR: JavascriptError: javascript error: Cannot read property 'clientWidth' of null
  (Session info: chrome=86.0.4240.75)
  (Session info: chrome=86.0.4240.75)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/setOrangeBackground.js:64:3)
    at async Measure._startVideo (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:82:7)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:176:7)
    at async module.exports (/sitespeed.io/scripts/test.js:23:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:7:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:216:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:117:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:135:26)
[2020-12-14 10:06:02] ERROR: No data to collect
[2020-12-14 10:06:02] INFO: HTML stored in /sitespeed.io/sitespeed-result/test/2020-12-14-10-05-43
Build step 'Execute shell' marked build as failure

**Comment by soulgalore** [comment]
Hi @sathishkg901 sorry that I never got back at this. If this is still an issue can you help me create a reproducible test case, see https://www.sitespeed.io/documentation/sitespeed.io/bug-report/

**Comment by KairatJC** [comment]
Hi, @soulgalore I have the same Issue and can add additional information.
In my case STR:
1. In the prescript, send a request to the API and set the resulting token to cookies using driver.manage().addCookie ()
2. Use a txt file with multiple URLs.

We added logs in step 1 and everything is fine.
It looks like the error appears after the prescript when Sitespeed tries to open URLs in the txt file.

ENV:
Session info: chrome=89.0.4389.82
Versions OS: linux 5.4.0-1029-aws 
nodejs: v12.16.2 
sitespeed.io: 16.9.2 
browsertime: 11.5.0 
coach: 6.1.0

Error stacktrace:
[2021-04-19 12:33:01] ERROR: JavascriptError: javascript error: Cannot read property 'clientWidth' of null
  (Session info: chrome=89.0.4389.82)
  (Session info: chrome=89.0.4389.82)    
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:671:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:729:17)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/setOrangeBackground.js:64:3)
    at async Measure._startVideo (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:83:7)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:190:7)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:192:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:258:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)

**Could you please let me know why this happened? Maybe you have some ideas.**

**Comment by soulgalore** [comment]
Hi @KairatJC thanks for adding info to the issue. So it looks like it happens when you start to measuring page and prepare for recording a video, To get the start of the video a orange layer is inserted, checkout: https://github.com/sitespeedio/browsertime/blob/main/lib/video/screenRecording/setOrangeBackground.js

I wonder, do you navigate to page before you test your page? It could be a generic thing when you use preTest, I'm gonna test it tonight and get back after that, could be use case maybe that we missed.

**Comment by KairatJC** [comment]
@soulgalore  thanks for the reply. Pages tested manually and work fine. We will wait for feedback to continue our performance work. If you need more information, please let me know.

**Comment by soulgalore** [comment]
@KairatJC I couldn't see any generic that is broken in using preScript, I tried running an empty preScript, recording a video etc and it worked. Can you show me the preScript or a generic version so I can try to reproduce?

**Comment by KairatJC** [comment]
@soulgalore 
This is our preScript:
```
const data = require('./data');
const fetch = require('node-fetch');

module.exports = async function (context, commands) {
  const test_url = data[process.env.ENV][process.env.LOCALE].url;
  const userName = data[process.env.ENV][process.env.LOCALE].userName;
  const password = data[process.env.ENV][process.env.LOCALE].password;
  const forwardedHost = data[process.env.ENV][process.env.LOCALE].forwardedHost;
  const driver = context.selenium.driver;
  context.log.info('Set up cookies');
  const url = 'https://ourapi.url/tokenauth';
  const options = {
    method: 'POST',
    headers: {
      'rs-x-forwarded-host': forwardedHost,
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: \`username=${userName}&password=${password}&grant_type=password&locale=${process.env.LOCALE}\`
  };
  const response = await fetch(url, options);
  const token = response.headers
    .get('set-cookie')
    .match(/access_token=(.*?);\s/)[1];
  try {
    context.log.info('Going to the ', test_url);
    await driver.get(test_url);
    context.log.info('Current url is ', await driver.getCurrentUrl());
    context.log.info('Going to add Cookie');
    await driver.manage().addCookie({ name: 'access_token', value: token });
    context.log.info('cookie details => ', await driver.manage().getCookie('access_token'));
  } catch (error) {
    throw e;
  }
};
```
What mean "javascript error"?

**Comment by soulgalore** [comment]
> What mean "javascript error"?

It means when the tool try to run JavaScript in the browser and it throws an exception.

Just so understand, is the "test_url" the same URL that you test in the next step after the preScripting?

**Comment by KairatJC** [comment]
@soulgalore sorry for the long answer.

>  is the "test_url" the same URL that you test in the next step after the preScripting

No, it's typo, and supposed to be the login page. I add this, because without opening url in prescript I got the 
`ERROR: InvalidCookieDomainError: invalid cookie domain`
