### ISSUE TITLE
config.json and urls.txt not working

### ISSUE THREAD

**Issue by gummelhummel** [sitespeedio/sitespeed.io#3209]
we have an error when using urls file with --config config.json.
We get the message:
```
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:15.9.0 urls --config config.json
Google Chrome 87.0.4280.66 
Mozilla Firefox 83.0
[2020-12-11 11:45:55] INFO: Versions OS: linux 5.4.0-56-generic nodejs: v12.16.2 sitespeed.io: 15.9.0 browsertime: 10.9.0 coach: 5.1.1
[2020-12-11 11:45:55] ERROR: Could not parse user script urls with error SyntaxError: Label 'https' has already been declared
https://sitespeed.io
^^^^^

SyntaxError: Label 'https' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.loadScript (/usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:32:16)
    at Engine.runMultiple (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:295:30)
    at Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:117:34)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:135:26)
```
config.json
```
{
    "browsertime": {
        "video": false,
        "visualMetrics": false,
        "screenshot": false,
        "iterations": 2,
        "browser": "chrome",
        "cpu": true,
        "viewPort": "1920x1080"
    },
    "influxdb": {
        "protocol": "https",
        "port": 443,
        "host": "*********",
        "username": "******",
        "password": "********",
        "database": "******",
        "tags": "category=europe-west-1"
    },
    "plugins": {
        "remove": [
            "html"
        ]
    },
    "multi": true,
    "mobile": false
}
```
urls
```
https://sitespeed.io
https://sitespeed.io
```
any ideas what we can do?
Thanks! :)

**Comment by soulgalore** [comment]
Hi @gummelhummel I need to check the docs, I don't remember if passing multiple URLs in a file works with `--multi`. Let me get back.

**Comment by soulgalore** [comment]
I don't think that has ever worked. To test multiple URLs from a file you can use: https://www.sitespeed.io/documentation/sitespeed.io/scripting/#measure-multiple-pages

**Comment by gummelhummel** [comment]
Thank you very much :+1:
