### ISSUE TITLE
--chrome.blockDomainsExcept not working with REPLAY=true 

### ISSUE THREAD

**Issue by SunnyGurnani** [sitespeedio/sitespeed.io#3241]
**Without replay 3rd Party Domains get blocked as expected**
`docker run --cap-add=NET_ADMIN --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.2.1 -n 1 -b chrome --chrome.blockDomainsExcept www.realtor.com https://www.realtor.com
`
![image](https://user-images.githubusercontent.com/943576/104077513-deeb2f80-51ce-11eb-9eb6-5682affed3cf.png)

**With Replay=true domains are not blocked**
`docker run --cap-add=NET_ADMIN --rm -v "$(pwd):/sitespeed.io" -e REPLAY=true -e LATENCY=100 sitespeedio/sitespeed.io:16.2.1 -n 1 -b chrome --chrome.blockDomainsExcept www.realtor.com https://www.realtor.com
`
![image](https://user-images.githubusercontent.com/943576/104077475-bbc08000-51ce-11eb-870f-cb5f91c52d5e.png)

**Comment by soulgalore** [comment]
I think the setup where we route the traffic to WebPageReplay from Chrome collide when you try to block third parties, so to make it work we need to change how we do the blocking in this case.

**Comment by inderpartap** [comment]
@soulgalore If we update the [start.sh-L81](https://github.com/sitespeedio/sitespeed.io/blob/b9703742849a684b5e3a8d1fea1647d2879da455/docker/scripts/start.sh#L81) to have the EXCLUDE set to the URL we are testing (basically blocking 3rd party), it just throws an error during REPLAY `ERROR: Could not load URL https://www.realtor.com UrlLoadError: Could not load https://www.realtor.com is the web page down?`

What could be going wrong here?

**Command:** `docker run --cap-add=NET_ADMIN --rm -v "$(pwd):/sitespeed.io" -e REPLAY=true -e LATENCY=100 perf-sitespeed.io -n 1 -b chrome --chrome.blockDomainsExcept www.realtor.com https://www.realtor.com`

**start.sh L81:** 
`execNode $BROWSERTIME --browsertime.chrome.args host-resolver-rules="MAP * 127.0.0.1, EXCLUDE www.realtor.com" --browsertime.firefox.preference network.dns.forceResolve:127.0.0.1 --browsertime.connectivity.engine throttle --browsertime.connectivity.throttle.localhost --browsertime.connectivity.profile custom --browsertime.connectivity.latency $LATENCY "$@"`

**Logs:**
```
ww.realtor.com 
Google Chrome 87.0.4280.88 
Mozilla Firefox 84.0
Microsoft Edge 89.0.731.0 dev
Start WebPageReplay Record
[2021-02-16 23:56:49] INFO: Running tests using Chrome - 1 iteration(s)
[2021-02-16 23:56:50] INFO: Testing url https://www.realtor.com iteration 1
[2021-02-16 23:57:01] INFO: https://www.realtor.com 232 requests
Stopped WebPageReplay record
Start WebPageReplay Replay
[2021-02-16 23:57:03] INFO: Versions OS: linux 4.19.121-linuxkit nodejs: v12.16.2 sitespeed.io: 16.2.1 browsertime: 11.0.1 coach: 6.0.1
[2021-02-16 23:57:03] INFO: Running tests using Chrome - 1 iteration(s)
[2021-02-16 23:57:07] INFO: Testing url https://www.realtor.com iteration 1
[2021-02-16 23:57:15] INFO: URL failed to load, trying 5 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:17] INFO: URL failed to load, trying 4 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:18] INFO: URL failed to load, trying 3 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:20] INFO: URL failed to load, trying 2 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:21] INFO: URL failed to load, trying 1 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:22] INFO: URL failed to load, trying 0 more time(s): Could not load https://www.realtor.com is the web page down?
[2021-02-16 23:57:22] ERROR: Could not load URL https://www.realtor.com UrlLoadError: Could not load https://www.realtor.com is the web page down?
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:277:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:201:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:218:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:136:26)
[2021-02-16 23:57:22] ERROR: UrlLoadError: Failed to load https://www.realtor.com
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:318:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:201:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:191:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:218:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:124:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:136:26)
[2021-02-16 23:57:23] INFO: https://www.realtor.com 
[2021-02-16 23:57:24] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.realtor.com/2021-02-16-23-57-03
```

**Comment by soulgalore** [comment]
Hi, at the moment `blockDomainsExcept` uses the same functionality we use internally to route the traffic back to the WebPageReplay server, so when you add that switch it collide and it don't work. To fix that we need a code change somewhere but I'm not sure at the moment how to do it the best way.

**Comment by soulgalore** [comment]
I can have a look this weekend to see if I can find an easy fix.

**Comment by inderpartap** [comment]
Thanks a lot, Peter. I can help you with the fix if you could point out what needs to be done.

**Comment by soulgalore** [comment]
@inderpartap yes please. I had a quick check this weekend but couldn't find a good way, but maybe you can. Let me explain how it works:

When we do the testing with WebPageReplay we make sure Chrome changes the traffic for HTTP/HTTPS to go to localhost instead (where we run WebPageReplay), that happens in https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh#L81 
That is needed so the traffic goes back to WebPageReplay. 

When we block URLs we use the same Chrome _host-resolver-rules_ functionality: https://github.com/sitespeedio/browsertime/blob/main/lib/chrome/webdriver/setupChromiumOptions.js#L38-L45 

At the moment those two collides.

**Comment by inderpartap** [comment]
@soulgalore 
This is my solution to the above issue. If we replace [https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh#L81](https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh#L81) with the following code, it would dynamically generate the `execNode` command using the domains provided through the `--chrome.blockDomainsExcept` argument.

Now my question here is that I am assuming `--chrome.blockDomainsExcept` would have values in the form of `*.realtor.com`. What all possible forms could this argument take? What do you suggest would be the best possible method to handle all the variations?
Ex - if the user enters `www.realtor.com` or `http://www.realtor.com`, we would essentially want to keep only the domain and then change it to `*.<domain>`

```
# Add functionality for blocking third-party domains in webpagereplay
  PARAMS=()
  FIRST_PARTY_DOMAINS=()  # create an array of all the first-party domains
  while [[ $# -gt 0 ]]
  do
  key="$1"
  case $key in
      --chrome.blockDomainsExcept) # handle Space-Separated arguments
      FIRST_PARTY_DOMAINS+=("$2")
      PARAMS+=("$1")
      PARAMS+=("$2")
      shift # past argument
      shift # past value
      ;;
      --chrome.blockDomainsExcept=*) # handle Equals-Separated arguments
      FIRST_PARTY_DOMAINS+=(${1#*=})
      PARAMS+=("$1")
      shift # past argument value
      ;;
      *)    # unknown option
      PARAMS+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
  done
  eval set -- "${PARAMS[@]}" # restore positional parameters

  PREFIX="execNode ${BROWSERTIME} --browsertime.chrome.args host-resolver-rules=\""
  SUFFIX="EXCLUDE localhost\" --browsertime.firefox.preference network.dns.forceResolve:127.0.0.1 --browsertime.connectivity.engine throttle --browsertime.connectivity.throttle.localhost --browsertime.connectivity.profile custom --browsertime.connectivity.latency $LATENCY "

  EXEC_STRING=$PREFIX
  if [ ${#FIRST_PARTY_DOMAINS[@]} -eq 0 ]
  then 
    # If chrome.blockDomainsExcept flag was not used
    EXEC_STRING+=" MAP *:${HTTP_PORT} 127.0.0.1:${WPR_HTTP_PORT},"
    EXEC_STRING+=" MAP *:$HTTPS_PORT 127.0.0.1:$WPR_HTTPS_PORT,"
  else
    # If chrome.blockDomainsExcept flag was used
    EXEC_STRING=$PREFIX
    for domain in "${FIRST_PARTY_DOMAINS[@]}"
    do
        EXEC_STRING+=" MAP $domain:${HTTP_PORT} 127.0.0.1:${WPR_HTTP_PORT},"
        EXEC_STRING+=" MAP $domain:${HTTPS_PORT} 127.0.0.1:${WPR_HTTPS_PORT},"
    done
  fi
  EXEC_STRING+=$SUFFIX
  
  eval $EXEC_STRING "$@" # execute the execNode command
```

**Comment by inderpartap** [comment]
This issue was fixed under Browsertime - [https://github.com/sitespeedio/browsertime/pull/1532](https://github.com/sitespeedio/browsertime/pull/1532)
