### ISSUE TITLE
RE: Cannot run sitespeed when using visual metrics on NodeJS

### ISSUE THREAD

**Issue by LuisOsv** [sitespeedio/sitespeed.io#3265]
Hi all I have the following issues when trying to run from Nodejs on Windows.

`PS C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin> node sitespeed.js https://en.wikipedia.org/wiki/Barack_Obama -b firefox --video --visualMetrics -n 1

[2021-01-21 19:47:30] INFO: Versions OS: win32 10.0.19042 nodejs: v15.5.1 sitespeed.io: 16.5.0 browsertime: 11.1.2 coach: 6.0.1
[2021-01-21 19:47:31] INFO: Running tests using Firefox - 1 iteration(s)
[2021-01-21 19:47:36] INFO: Testing url https://en.wikipedia.org/wiki/Barack_Obama iteration 1
[2021-01-21 19:47:36] ERROR: Error: Command failed with exit code 1: ffmpeg -hide_banner -video_size 1366x708 -f gdigrab -framerate 30 -probesize 10M -y -draw_mouse 0 -i desktop -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin\sitespeed-result\en.wikipedia.org\2021-01-21-19-47-30\x11-tmp.mp4
[gdigrab @ 00000250ac70b4c0] Capture area (0,0),(1366,708) extends outside window area (0,0),(1368,703)desktop: I/O error
[gdigrab @ 00000250ac70b4c0] Capture area (0,0),(1366,708) extends outside window area (0,0),(1368,703)desktop: I/O error
    at makeError (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Measure._startVideo (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\command\measure.js:83:7)
    at async Measure.start (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\command\measure.js:176:7)
    at async C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\run.js:9:9
    at async Iteration.run (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:191:9)
    at async Engine.runByScript (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:220:20)
    at async Object.analyzeUrl (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\lib\plugins\browsertime\analyzer.js:124:21)
    at async Object.processMessage (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2021-01-21 19:47:36] ERROR: Error: Command failed with exit code 1: ffmpeg -hide_banner -video_size 1366x708 -f gdigrab -framerate 30 -probesize 10M -y -draw_mouse 0 -i desktop -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin\sitespeed-result\en.wikipedia.org\2021-01-21-19-47-30\x11-tmp.mp4
[gdigrab @ 00000250ac70b4c0] Capture area (0,0),(1366,708) extends outside window area (0,0),(1368,703)desktop: I/O error
[gdigrab @ 00000250ac70b4c0] Capture area (0,0),(1366,708) extends outside window area (0,0),(1368,703)desktop: I/O error
    at makeError (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Measure._startVideo (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\command\measure.js:83:7)
    at async Measure.start (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\command\measure.js:176:7)
    at async C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\run.js:9:9
    at async Iteration.run (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:191:9)
    at async Engine.runByScript (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:220:20)
    at async Object.analyzeUrl (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\lib\plugins\browsertime\analyzer.js:124:21)
    at async Object.processMessage (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2021-01-21 19:47:38] ERROR: No data to collect
[2021-01-21 19:47:38] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\lib\plugins\browsertime\index.js:167:52)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
[2021-01-21 19:47:39] INFO: HTML stored in C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin\sitespeed-result\en.wikipedia.org\2021-01-21-19-47-30`

**Comment by soulgalore** [comment]
Hi @LuisOsv have you installed all the requirements for video/ffmpeg on Windows? I think the GitHub action for Browsertime is good example of how to get it right: https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/windows.yml

**Comment by LuisOsv** [comment]
@soulgalore Yes I did

**Comment by soulgalore** [comment]
Ah sorry, yeah I see now. The error comes from that the window size/ capture area do not match.

> Capture area (0,0),(1366,708) extends outside window area (0,0),(1368,703)

I don't use Windows but my guess is that there's a mismatch somewhere. If you try making the window smaller, do that work?

**Comment by LuisOsv** [comment]
Hi @soulgalore I tried with lower screen resolution and works e.g.1280x720
`PS C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin> node sitespeed.js https://uat-demo.myvistance.com/#/login -b chrome --video --visualMetrics --browsertime.viewPort 1280x720`

**Comment by soulgalore** [comment]
Aha so the default settings it too large then?

**Comment by LuisOsv** [comment]
hi @soulgalore I just ran with Firefox 84.0.1 and I don't face the issue anymore, maybe it was related to old version of browsers?
I can even run with larger viewport using the same version of sitespeed
`PS C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin> node sitespeed.js https://en.wikipedia.org/wiki/Barack_Obama -b firefox --video --visualMetrics --browsertime.viewPort 1920x1080 -n 1
[2021-04-19 05:42:41] INFO: Versions OS: win32 10.0.19042 nodejs: v15.5.1 sitespeed.io: 16.5.0 browsertime: 11.1.2 coach: 6.0.1
[2021-04-19 05:42:41] INFO: Running tests using Firefox - 1 iteration(s)
[2021-04-19 05:42:46] INFO: Testing url https://en.wikipedia.org/wiki/Barack_Obama iteration 1
[2021-04-19 05:43:07] INFO: Waiting on har-export-trigger to collect the HAR
[2021-04-19 05:43:23] INFO: https://en.wikipedia.org/wiki/Barack_Obama 103 requests, TTFB: 198ms, firstPaint: 2.87s, firstVisualChange: 5.63s, FCP: 2.84s, DOMContentLoaded: 3.17s, Load: 3.65s, speedIndex: 5.63s, visualComplete85: 5.63s, lastVisualChange: 7.33s
[2021-04-19 05:43:27] INFO: HTML stored in C:\Users\LSerna07463\AppData\Roaming\npm\node_modules\sitespeed.io\bin\sitespeed-result\en.wikipedia.org\2021-04-19-05-42-41`
