### ISSUE TITLE
Cannot run crux plugin for various urls with the same origin 

### ISSUE THREAD

**Issue by mploquin** [sitespeedio/sitespeed.io#3313]
I wanted to test various URLs with the same origin (https://www.sitespeed.io/ and 
https://www.sitespeed.io/documentation/sitespeed.io/ for example), but when I run the test with the `collect` option set to `ALL or ORIGIN` I got this error:

```
Google Chrome 88.0.4324.96 
Mozilla Firefox 84.0
Microsoft Edge 89.0.767.0 dev
[2021-03-16 10:34:02] INFO: Versions OS: linux 5.8.0-45-generic nodejs: v12.16.2 sitespeed.io: 16.9.2 browsertime: 11.5.0 coach: 6.1.0
[2021-03-16 10:34:02] INFO: Get CrUx data for domain www.sitespeed.io
[2021-03-16 10:34:03] INFO: Get CrUx data for domain www.sitespeed.io
[2021-03-16 10:34:03] INFO: Get CrUx data for url https://www.sitespeed.io/
[2021-03-16 10:34:03] ERROR: Error: Multiple summary messages of type crux.summary and group www.sitespeed.io
    at validateSummaryMessage (/usr/src/app/lib/core/queueHandler.js:77:13)
    at validateMessageFormat (/usr/src/app/lib/core/queueHandler.js:86:3)
    at QueueHandler.postMessage (/usr/src/app/lib/core/queueHandler.js:200:5)
    at Object.processMessage (/usr/src/app/lib/plugins/crux/index.js:128:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by soulgalore** [comment]
Thanks @mploquin I see, I think it could be that I missed that use case (alway testing one URL). What happens is that it keeps trying to get origin data multiple times and passed that on. We should fix so that it only get data for the same origin once.
