### ISSUE TITLE
Chrome crashed when running sitespeed on Windows

### ISSUE THREAD

**Issue by vshklianik** [sitespeedio/sitespeed.io#3389]
Hi! I need to use sitespeedio on windows, I can't use docker for my purposes. I installed the sitespeedio and  necessary dependencies according to these Github actions: [sitespeedio ](https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/windows.yml)and [browsertime](https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/windows.yml).

When I run sitespeed using Edge, everything works.

But when I use chrome, the test does not run and in the open chrome window I see the untitled tab, as I understood it crashed:

```V:\Projects\CLIENTSIDE-V2\sitespeed.io>node bin/sitespeed.js -b chrome -n 1 https://www.sitespeed.io/
[2021-05-23 14:42:35] INFO: Versions OS: win32 10.0.17763 nodejs: v14.17.0 sitespeed.io: 17.5.0 browsertime: 12.6.1 coach: 6.3.3
[2021-05-23 14:42:36] INFO: Running tests using Chrome - 1 iteration(s)

DevTools listening on ws://127.0.0.1:9222/devtools/browser/0998ebe2-4fa0-49b4-9792-ffbf9796cd7d
[2021-05-23 14:43:36] INFO: chrome failed to start, trying 2 more time(s): Failed to start chrome in 60 seconds.
[13956:2256:0523/144336.502:ERROR:tcp_socket_win.cc(352)] bind() returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted. (0x2740)

DevTools listening on ws://[::1]:9222/devtools/browser/ac5ed8f8-946d-47e2-872a-5c24476bdd85
[2021-05-23 14:43:37] INFO: chrome failed to start, trying 1 more time(s): ECONNREFUSED connect ECONNREFUSED 127.0.0.1:54515

DevTools listening on ws://127.0.0.1:9222/devtools/browser/f553aa50-e142-46cb-99ed-03784166565b
[2021-05-23 14:44:13] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited normally.
  (unknown error: unable to discover open pages)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-05-23 14:44:13] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (V:\Projects\CLIENTSIDE-V2\sitespeed.io\node_modules\browsertime\lib\core\seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Iteration.run (V:\Projects\CLIENTSIDE-V2\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:107:7)
    at async Engine.runByScript (V:\Projects\CLIENTSIDE-V2\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:262:20)
    at async Object.analyzeUrl (V:\Projects\CLIENTSIDE-V2\sitespeed.io\lib\plugins\browsertime\analyzer.js:151:21)
    at async Object.processMessage (V:\Projects\CLIENTSIDE-V2\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2021-05-23 14:44:13] ERROR: No data to collect
[2021-05-23 14:44:13] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (V:\Projects\CLIENTSIDE-V2\sitespeed.io\lib\plugins\browsertime\index.js:167:52)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-05-23 14:44:14] INFO: HTML stored in V:\Projects\CLIENTSIDE-V2\sitespeed.io\sitespeed-result\www.sitespeed.io\2021-05-23-14-42-35```

Could you please help me to resolve this issue, thanks!

**Comment by Resolution-of** [comment]
I am not a developer of this app, but faced with that issue too. Don't know how to solve it, but you can use Firefox instead of Chrome. But there are some problems too. For example you need to install Firefox 32-bit (only it)
If it will be useful just write in this issue and I will send you more instructions about this

**Comment by soulgalore** [comment]
Hi @Uladik I. wonder if something else is running on. your computer and the ports collide (_Only one usage of each socket address (protocol/network address/port_). Check if you can find what uses that port 54515, else. try to restart the machine and see if it works.

@Resolution-of is it. the exact same issue (ports collide)? Else another problem with Chrome is that Chrome and Chromedriver versions  needs to exactly match.
