### ISSUE TITLE
Finding button with xpath failing

### ISSUE THREAD

**Issue by PagePerf2021** [sitespeedio/sitespeed.io#3399]
SS,

I'm trying to click on a button via xpath. The xpath works in chrome, but fails in my script below. Also see elements of button. 

<button name="Account_Plan_vod__c.Stakeholder_Navigator_Beta" type="button" class="slds-button slds-button_neutral">Stakeholder Navigator</button>

module.exports = async function(context, commands) {
context.log.info('Info logging from your script');
context.log.error('Error logging from your script');

  await commands.navigate('https://test.salesforce.com/' );

  try {
    await commands.addText.byId('user123', 'username');
    await commands.addText.byId('test123', 'password');
    
// Click on the submit button with id wpLoginAttempt

    await commands.click.byIdAndWait('Login');
// wait on a specific id to appear on the page after you logged in
    await commands.wait.byTime(3000);

    await commands.navigate('https://jflores--jeremy.lightning.force.com/lightning/r/Account_Plan_vod__c/a0C02000000PlNqEAK/view');
    await commands.wait.byTime(3000);

    await commands.measure.start();   
    
    await commands.click.byXpath("//button[contains(.,'Stakeholder Navigator')");

     return commands.measure.stop();
    
    await commands.wait.byTime(3000);
 
    
  } catch (e) {
    // We try/catch so we will catch if the the input fields can't be found
    // The error is automatically logged in Browsertime and re-thrown here
    // We could have an alternative flow ...
    // else we can just let it cascade since it caught later on and reported in
    // the HTML
    throw e;
  }
};

PS C:\Users\SVeio> docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.8.1 account_plan3.js -n 1 --spa --multi
Google Chrome 88.0.4324.96 
Mozilla Firefox 84.0
Microsoft Edge 89.0.767.0 dev
[2021-05-28 17:16:11] INFO: Versions OS: linux 5.4.72-microsoft-standard-WSL2 nodejs: v12.16.2 sitespeed.io: 16.8.1 browsertime: 11.4.0 coach: 6.0.1
[2021-05-28 17:16:11] INFO: Running tests using Chrome - 1 iteration(s)
[2021-05-28 17:16:11] INFO: Info logging from your script
[2021-05-28 17:16:11] INFO: Navigating to url https://test.salesforce.com/ iteration 1
docker : [2021-05-28 17:16:11] ERROR: Error logging from your script
At line:1 char:1
+ docker run --shm-size 2g --rm -v "$(pwd):/sitespeed.io" sitespeedio/s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([2021-05-28 17:...rom your script:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[2021-05-28 17:16:37] INFO: Navigating to url https://jflores--jeremy.lightning.force.com/lightning/r/Account_Plan_vod__c/a0C02000000PlNqEAK/view iteration 1
[2021-05-28 17:16:53] INFO: Start to measure
[2021-05-28 17:16:55] ERROR: Could not add meta data to the HAR, miss page 0
[2021-05-28 17:16:55] INFO: https://jflores--jeremy.lightning.force.com/lightning/r/Account_Plan_vod__c/a0C02000000PlNqEAK/view TTFB: 300ms, firstPaint: 323ms, firstVisualChange: 0ms, FCP: 570ms,
 DOMContentLoaded: 693ms, LCP: 1.80s, CLS: 0.4058, TBT: 376ms, Load: 695ms, speedIndex: 0ms, visualComplete85: 0ms, lastVisualChange: 0ms
[2021-05-28 17:16:55] ERROR: Could not find the right index 0 for har for url https://jflores--jeremy.lightning.force.com/lightning/r/Account_Plan_vod__c/a0C02000000PlNqEAK/view 
[2021-05-28 17:16:55] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:258:31)
[2021-05-28 17:16:55] INFO: HTML stored in /sitespeed.io/sitespeed-result/account_plan3_js/2021-05-28-17-16-11

**Comment by soulgalore** [comment]
Hi @PagePerf2021 I use https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug when I try to debug scripts. For me both looking at the screen (to verify the test get the right element) and add some logging in a couple of steps usually helps me (get the the element, verify we have it, log every step etc).

Best
Peter

**Comment by PagePerf2021** [comment]
Apologies, I re-confirmed my xpath. This finds the correct button in chrome dev tools - await commands.click.byXpathAndWait('//lightning-button//button[@name="Account_Plan_vod__c.Stakeholder_Navigator_Beta"]'); 
I still get this - 
[2021-06-02 04:12:22] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read property 'click' of null
  (Session info: chrome=88.0.4324.96)
[2021-06-02 04:12:22] ERROR: Could not find element by xpath //lightning-button//button[@name="Account_Plan_vod__c.Stakeholder_Navigator_Beta"]
[2021-06-02 04:12:22] ERROR: Error: Could not find element by xpath //lightning-button//button[@name="Account_Plan_vod__c.Stakeholder_Navigator_Beta"]
    at Click.byXpathAndWait (/usr/src/app/node_modules/browsertime/lib/core/engine/command/click.js:149:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-06-02 04:12:22] ERROR: Caught error from Browsertime TypeError: Cannot read property 'split' of null
    at module.exports (/usr/src/app/node_modules/browsertime/lib/support/pathToFolder.js:23:42)
    at Video.stop (/usr/src/app/node_modules/browsertime/lib/video/video.js:64:7)
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:284:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-06-02 04:12:22] ERROR: TypeError: Cannot read property 'split' of null
    at pathFromRootToPageDir (/usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:40)
    at Object.relativeSummaryPageUrl (/usr/src/app/lib/core/resultsStorage/resultUrls.js:30:14)
    at DataCollector._addUrl (/usr/src/app/lib/plugins/html/dataCollector.js:22:31)
    at DataCollector.addErrorForUrl (/usr/src/app/lib/plugins/html/dataCollector.js:94:10)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:58:27)
    at /usr/src/app/lib/core/queueHandler.js:214:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:456:21)
