### ISSUE TITLE
Firefox doesn't work in throttled mode

### ISSUE THREAD

**Issue by jajo-shubham** [sitespeedio/sitespeed.io#3414]
Hey @soulgalore , I recently tried to check web performance while simulating low network conditions. I am unable to run tests on firefox whenever throttle is on. The browser window opens up but it freezes there. 
Command  to reproduce`  bin/sitespeed.js -b firefox https://gmail.com/ --cpu --plugins.remove html --plugins.remove coach --plugins.add analysisstorer --visualMetrics true -n 1  --connectivity.engine throttle -c 4g` 
Logs - 
>[2021-06-25 18:58:40] INFO: Versions OS: darwin 20.4.0 nodejs: v14.16.1 sitespeed.io: 17.8.1 browsertime: 12.9.1 coach: 6.4.0
[2021-06-25 18:58:40] INFO: Changing network interfaces needs sudo rights. Setting connectivity profile 4g
Password:
[2021-06-25 18:59:23] INFO: Running tests using Firefox - 1 iteration(s)
[2021-06-25 19:00:23] INFO: firefox failed to start, trying 2 more time(s): Failed to start firefox in 60 seconds.
[2021-06-25 19:01:23] INFO: firefox failed to start, trying 1 more time(s): Failed to start firefox in 60 seconds.
[2021-06-25 19:02:23] INFO: firefox failed to start, trying 0 more time(s): Failed to start firefox in 60 seconds.
[2021-06-25 19:02:23] ERROR: BrowserError: Could not start firefox with 3 tries
    at SeleniumRunner.start (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at async Iteration.run (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:107:7)
    at async Engine.runByScript (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:267:20)
    at async Object.analyzeUrl (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:151:21)
    at async Object.processMessage (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:150:26)
[2021-06-25 19:02:23] ERROR: No data to collect
[2021-06-25 19:02:24] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (/Users/shubhamjajodia/.nvm/versions/node/v14.16.1/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:167:52)

My best guess is above a certain value of rtt, geckodriver is not responding, though I can be wrong. 
PS: I am using Mac OSX BigSur

**Comment by soulgalore** [comment]
Hi @jajo-shubham thank you for creating the issue. I get the same thing, it works when I use cable connectivity. It seems like adding higher latency make Firefox not work. What's strange is that my feeling of the added latency do not correlate to a 60s timeout, but I haven't looked at the Geckodriver log. I can ask about it the coming week on the Browsertime/Mozilla Element channel (I'm away on holiday this weekend) and if you also could create an issue at https://github.com/mozilla/geckodriver that would be great.

**Comment by soulgalore** [comment]
@jajo-shubham let me file a upstream bug: I just turned on the geckodriver log and this looks like another error I've seen when running Firefox on Android in an environment at work that never get solved. I'll cross reference to this issue.

**Comment by jajo-shubham** [comment]
Hey @soulgalore .. Just checked this.. Thanks for raising the issue.. Do enjoy your holidays 😄
