### ISSUE TITLE
Analysis storer plugin throwing error when graphite is used

### ISSUE THREAD

**Issue by rdaytoncvent** [sitespeedio/sitespeed.io#3505]
When both the analysis storer plugin is enabled and a graphite host is set, the script throws an error due to `data` being undefined. 

I believe the issue began in version 17.8.2.

I have tried the below example with/without using the slug and received the same error.

Example:
`yarn sitespeed.io https://sitespeed.io -n 1 --plugins.add analysisstorer --graphite.host <graphite-host>
`
```
[2021-11-05 17:01:04] INFO: Versions OS: darwin 18.7.0 nodejs: v16.13.0 sitespeed.io: 20.4.1 browsertime: 14.8.0 coach: 6.4.3
[2021-11-05 17:01:04] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2106:5)
    at go$writeFile (/Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/universalify/index.js:7:14)
    at write (/Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/sitespeed.io/lib/core/resultsStorage/storageManager.js:15:13)
    at /Users/rdayton/IdeaProjects/sitespeed-metrics-scripts/node_modules/sitespeed.io/lib/core/resultsStorage/storageManager.js:40:9
```

**Comment by soulgalore** [comment]
Thank you @rdaytoncvent for creating the issue. It seems that I missed to add so we ignore graphite setup messages when storing data. I've made a PR and can release it tomorrow Sunday.

**Comment by soulgalore** [comment]
I released the fix in 20.4.2 a couple of minutes ago.
