### ISSUE TITLE
Analysis storer plugin throwing error when InfluxDB is used

### ISSUE THREAD

**Issue by derekzernach** [sitespeedio/sitespeed.io#3507]
When both the analysis storer plugin is enabled and an InfluxDB host is set, the script throws an error due to data being undefined. Looks similar to this issue.....https://github.com/sitespeedio/sitespeed.io/issues/3505

I have also tested on the latest `20.4.2` tag and get the same result.

```
Google Chrome 95.0.4638.54 
Mozilla Firefox 93.0
Microsoft Edge 93.0.961.10 dev
[2021-11-09 14:17:03] INFO: Versions OS: linux 5.10.47-linuxkit nodejs: v14.17.6 sitespeed.io: 20.3.0 browsertime: 14.7.0 coach: 6.4.3
[2021-11-09 14:17:03] INFO: Will run Lighthouse tests after Browsertime has finished
[2021-11-09 14:17:03] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (fs.js:1487:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9

**Comment by soulgalore** [comment]
Thank you @derekzernach for creating the issue. I made a PR to fix it and can release it later today!

**Comment by soulgalore** [comment]
@derekzernach please try with 20.5.0 and see if it works for you!

**Comment by derekzernach** [comment]
@soulgalore Wow, that was fast!! Looks good on my end, thanks for the quick turnaround!
