### ISSUE TITLE
The "Pages" report in the header says 5 reports analyzed, but only shows the results of 4 measurements. 

### ISSUE THREAD

**Issue by alexvolk001** [sitespeedio/sitespeed.io#3550]
### Your question

I'm running the script. Script is below. It has to do 5 measurements (4 web pages and 1 site search). The script runs, I can see it in Command Prompt window it does all the measurements. But at the end it gives me errors, see below.  In "Page" report header says 5 pages measured, but I can see only 4 results. 
What do I need to change to make it work?

Thank you.
Alex.

==Script==

module.exports = async function(context, commands) {

  await commands.measure.start('https://.net/', 'landingPage');
  //await commands.click.byXpathAndWait('//*[@id="root"]/div/div/div/div[2]/button');
  await commands.measure.start('https://.net/mainlanding', 'mainLandingPage');
  //await commands.click.byXpathAndWait('//*[@id="root"]/div/div[2]/div[1]/a/div[1]');
  await commands.measure.start('https://.net/landing', 'dashboards');
  //await commands.click.byXpathAndWait('//*[@id="root"]/div/div[2]/div[1]/a');
  await commands.measure.start('https://.net/metrics', 'MetricsLive');

//measureing the Site-450
  await commands.click.byXpath('//*[@id="rc_select_0"]');
  await commands.measure.start('Site450');
  await commands.click.byXpathAndWait('/html/body/div[1]/div/div/div[2]/div/div/div/span[2]');
  await commands.measure.stop();
};

==Errors==

[2022-01-31 22:21:38] ERROR: Could not add meta data to the HAR, miss page 4
[2022-01-31 22:13:56] ERROR: Could not find the right index 4 for har for url https://.net/metrics?browsertime_run=2
[2022-01-31 22:13:56] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:264:31)

**Comment by soulgalore** [comment]
Hi @alexvolk001 my guess is that one of the clicks do not generate a new page? How the HAR is generated depends on what browser you use. Firefox generates the HAR through a plugin, for Chrome and Edge it's generated through the trace log. If you run the test on your local computer and watch the screen, do the script do what's intended?

**Comment by alexvolk001** [comment]
Hi, I'm using the Chrome. I'm also suspecting the XPath (I'm planning to do selenium). But usually when XPath is wrong I get an Error message that either element can't be located or something else (don't remember the message). 
I changed the script a little. I broke it in two scripts. Now the first scrip is doing the measurements of the pages, the second one navigates to the same pages and then takes the measurement of "Site450". Below are the results from CMD.
BTW, the measurement of "Site450" will be on the same page "url https://.net/metrics". The URI won't change. Could it be a reason for an error? I can see below this message: https://.net/metrics has been tested before within the same run

==CMD Screen==

Google Chrome 97.0.4692.99
Mozilla Firefox 94.0
Microsoft Edge 97.0.1072.69
[2022-02-01 16:18:22] INFO: Versions OS: linux 5.10.60.1-microsoft-standard-WSL2 nodejs: v16.13.1 sitespeed.io: 21.6.1 browsertime: 14.18.1 coach: 7.0.0
[2022-02-01 16:18:22] INFO: Running tests using Chrome - 1 iteration(s)
[2022-02-01 16:18:24] INFO: Testing url https://.net/ iteration 1
[2022-02-01 16:18:33] INFO: Take after page complete check screenshot
[2022-02-01 16:18:35] INFO: Take cumulative layout shift screenshot
[2022-02-01 16:18:36] INFO: Take largest contentful paint screenshot
[2022-02-01 16:18:37] INFO: Testing url https://.net/mainlanding iteration 1
[2022-02-01 16:18:46] INFO: Take after page complete check screenshot
[2022-02-01 16:18:47] INFO: Take cumulative layout shift screenshot
[2022-02-01 16:18:47] INFO: Take largest contentful paint screenshot
[2022-02-01 16:18:48] INFO: Testing url https://.net/landing iteration 1
[2022-02-01 16:18:57] INFO: Take after page complete check screenshot
[2022-02-01 16:18:58] INFO: Take cumulative layout shift screenshot
[2022-02-01 16:18:58] INFO: Take largest contentful paint screenshot
[2022-02-01 16:18:59] INFO: Testing url https://.net/metrics iteration 1
[2022-02-01 16:19:08] INFO: Take after page complete check screenshot
[2022-02-01 16:19:09] INFO: Take cumulative layout shift screenshot
[2022-02-01 16:19:09] INFO: Take largest contentful paint screenshot
[2022-02-01 16:19:10] INFO: Navigating to url https://.net/ iteration 1
[2022-02-01 16:19:16] INFO: Navigating to url https://.net/mainlanding iteration 1
[2022-02-01 16:19:23] INFO: Navigating to url https://.net/landing iteration 1
[2022-02-01 16:19:30] INFO: Navigating to url https://.net/metrics iteration 1
[2022-02-01 16:19:36] INFO: Start to measure Site450
[2022-02-01 16:19:39] INFO: https://.net/metrics has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2022-02-01 16:19:40] INFO: Take after page complete check screenshot
[2022-02-01 16:19:40] INFO: Take cumulative layout shift screenshot
[2022-02-01 16:19:41] INFO: Take largest contentful paint screenshot
[2022-02-01 16:19:42] INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.
[2022-02-01 16:19:44] INFO: Get visual metrics from the video
[2022-02-01 16:19:47] INFO: Get visual metrics from the video
[2022-02-01 16:19:50] INFO: Get visual metrics from the video
[2022-02-01 16:19:53] INFO: Get visual metrics from the video
[2022-02-01 16:19:55] INFO: Get visual metrics from the video
[2022-02-01 16:19:58] ERROR: Could not add meta data to the HAR, miss page 4
[2022-02-01 16:19:58] INFO: https://.net/ 10 requests, TTFB: 286ms, firstPaint: 988ms, firstVisualChange: 1.00s, FCP: 988ms, DOMContentLoaded: 957ms, LCP: 1.32s, CLS: 0.0007, TBT: 0ms, Load: 1.28s, speedIndex: 1.32s, visualComplete85: 1.33s, lastVisualChange: 1.33s
[2022-02-01 16:19:58] INFO: https://.net/mainlanding 2 requests, TTFB: 192ms, firstPaint: 353ms, firstVisualChange: 366ms, FCP: 353ms, DOMContentLoaded: 324ms, LCP: 353ms, CLS: 0, TBT: 0ms, Load: 451ms, speedIndex: 366ms, visualComplete85: 366ms, lastVisualChange: 466ms
[2022-02-01 16:19:58] INFO: https://.net/landing 6 requests, TTFB: 103ms, firstPaint: 237ms, firstVisualChange: 233ms, FCP: 237ms, DOMContentLoaded: 209ms, LCP: 237ms, CLS: 0.012, TBT: 0ms, Load: 391ms, speedIndex: 243ms, visualComplete85: 233ms, lastVisualChange: 400ms
[2022-02-01 16:19:58] INFO: https://.net/metrics 3 requests, TTFB: 99ms, firstPaint: 273ms, firstVisualChange: 300ms, FCP: 273ms, DOMContentLoaded: 268ms, LCP: 274ms, CLS: 0, TBT: 0ms, Load: 275ms, speedIndex: 300ms, visualComplete85: 300ms, lastVisualChange: 300ms
[2022-02-01 16:19:58] INFO: https://.net/metrics?browsertime_run=2 TTFB: 7ms, firstPaint: 125ms, firstVisualChange: 33ms, FCP: 125ms, DOMContentLoaded: 122ms, LCP: 125ms, CLS: 0, TBT: 0ms, Load: 127ms, speedIndex: 80ms, visualComplete85: 133ms, lastVisualChange: 1.83s
[2022-02-01 16:19:58] ERROR: Could not find the right index 4 for har for url https://.net/metrics?browsertime_run=2
[2022-02-01 16:19:58] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:264:31)
[2022-02-01 16:20:03] INFO: HTML stored in /sitespeed.io/sitespeed-result/whlDashboardsLive_js/2022-02-01-16-18-22
2 pages analysed for whlDashboardsLive.js (1 run, Chrome/desktop/[object Object])
Score: CPS:93, CPS:81, CBPS:100, Coach Overall Score:91 /  / 5 reqs /

**Comment by soulgalore** [comment]
Ok, hmm I wonder if there's a bug when you hit the same URL twice? I tried reproduce with
```
module.exports = async function (context, commands) {
  await commands.measure.start('https://www.sitespeed.io');
  await commands.measure.start('https://www.sitespeed.io/examples/');
  await commands.measure.start('https://www.sitespeed.io');
  await commands.measure.start('https://www.sitespeed.io/documentation/');
  return await commands.measure.start('https://www.sitespeed.io');
};
```
but that worked for me. If you leave out that last step _Site450_  does it work?  Is the  _Site450_ the same URL as the one exact before? I tries with 

```
module.exports = async function (context, commands) {
  await commands.measure.start('https://www.sitespeed.io');
  await commands.measure.start('Second');
  await commands.click.byLinkTextAndWait('Start');
  return commands.measure.stop();
};
```

And that also worked. Any chance you can share a full working example so I can reproduce?

**Comment by alexvolk001** [comment]
It is the same page. The idea of the app is to display all different Metrics in the same page. The application is using ReactJS. Every time I'm selecting a new Site, the new results are displayed in the same page, the url doesn't change. 
I tried again. Only the second part of the script. Navigating to URLs and then performing Site450 metrics test. Result is below. 
I also created the Selenium-Java script. It worked for me. 
Do you have ReactJS related limitations of the application? 
==Results==
Google Chrome 97.0.4692.99
Mozilla Firefox 94.0
Microsoft Edge 97.0.1072.69
[2022-02-01 20:24:22] INFO: Versions OS: linux 5.10.60.1-microsoft-standard-WSL2 nodejs: v16.13.1 sitespeed.io: 21.6.1 browsertime: 14.18.1 coach: 7.0.0
[2022-02-01 20:24:22] INFO: Running tests using Chrome - 1 iteration(s)
[2022-02-01 20:24:23] INFO: Navigating to url https://.net/ iteration 1
[2022-02-01 20:24:30] INFO: Navigating to url https://.net/mainlanding iteration 1
[2022-02-01 20:24:36] INFO: Navigating to url https://.net/landing iteration 1
[2022-02-01 20:24:43] INFO: Navigating to url https://.net/metrics iteration 1
[2022-02-01 20:24:49] INFO: Start to measure Site450
[2022-02-01 20:24:54] INFO: Take after page complete check screenshot
[2022-02-01 20:24:54] INFO: Take cumulative layout shift screenshot
[2022-02-01 20:24:55] INFO: Take largest contentful paint screenshot
[2022-02-01 20:24:56] INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.
[2022-02-01 20:24:58] INFO: Get visual metrics from the video
[2022-02-01 20:25:05] ERROR: Could not add meta data to the HAR, miss page 0
[2022-02-01 20:25:05] INFO: https://.net/metrics TTFB: 299ms, firstPaint: 635ms, firstVisualChange: 67ms, FCP: 635ms, DOMContentLoaded: 627ms, LCP: 635ms, CLS: 0.0003, TBT: 0ms, Load: 637ms, speedIndex: 398ms, visualComplete85: 2.14s, lastVisualChange: 2.14s
[2022-02-01 20:25:05] ERROR: Could not find the right index 0 for har for url https://.net/metrics
[2022-02-01 20:25:05] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:264:31)
[2022-02-01 20:25:06] INFO: HTML stored in /sitespeed.io/sitespeed-result/whlDashboardsLiveSite450_js/2022-02-01-20-24-22

**Comment by alexvolk001** [comment]
Hi @soulgalore, I have modified the script. I excluded some XPath selectors, since elements are dynamic, and replaced them with ID. Also, I included the wait.Time() function to ensure the page fully loaded. I can see the video files with measurements. But also I'm seeing the same errors. It seems those errors preventing the report generation.

Anyway to fix it?

If you have time I can show you app.

==Errors==

[2022-02-02 19:38:02] ERROR: Could not add meta data to the HAR, miss page 0
[2022-02-02 19:38:02] ERROR: Could not add meta data to the HAR, miss page 1
[2022-02-02 19:38:02] ERROR: Could not add meta data to the HAR, miss page 2
[2022-02-02 19:38:02] INFO: https://.net/metrics TTFB: 98ms, firstPaint: 313ms, firstVisualChange: 66ms, FCP: 313ms, DOMContentLoaded: 310ms, LCP: 313ms, CLS: 0.0003, TBT: 0ms, Load: 316ms, speedIndex: 287ms, visualComplete85: 1.43s, lastVisualChange: 1.43s
[2022-02-02 19:38:02] INFO: https://.net/metrics?browsertime_run=2 TTFB: 90ms, firstPaint: 270ms, firstVisualChange: 66ms, FCP: 270ms, DOMContentLoaded: 266ms, LCP: 270ms, CLS: 0.0003, TBT: 0ms, Load: 273ms, speedIndex: 368ms, visualComplete85: 1.83s, lastVisualChange: 1.83s
[2022-02-02 19:38:02] INFO: https://.net/metrics?browsertime_run=3 TTFB: 97ms, firstPaint: 287ms, firstVisualChange: 34ms, FCP: 287ms, DOMContentLoaded: 283ms, LCP: 287ms, CLS: 0.0003, TBT: 0ms, Load: 288ms, speedIndex: 1.23s, visualComplete85: 4.70s, lastVisualChange: 29.60s
[2022-02-02 19:38:02] ERROR: Could not find the right index 0 for har for url https://.net/metrics
[2022-02-02 19:38:02] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:264:31)
[2022-02-02 19:38:04] INFO: HTML stored in /sitespeed.io/sitespeed-result/whlDashboardsLiveSite450_js/2022-02-02-19-34-03

**Comment by alexvolk001** [comment]
I have solved the issue. 
I'm navigating/measuring all the pages before the target page and target measurement. Then I'm placing the navigation url to target page inside the measurement start/stop. 
In this case, the script navigates to the target page and then performs the required action.
The script can measure multiple sites this way.

==Script==

module.exports = async function(context, commands) {
const delayTime =30000;

//Measuring pages
await commands.measure.start('https://.net', 'homePage');
await commands.measure.start('https://.net/mainlanding', 'mainLandingPage');
await commands.measure.start('https://.net/landing', 'dashboards');

//measuring the Site-450 Alaska
  await commands.measure.start('Site450')
  await commands.navigate('.net/metrics?dummy', 'metricsLive450');
  await commands.click.byId('rc_select_0');
  await commands.addText.byXpath('450','//*[@id="rc_select_0"]');
  await commands.click.byId('450');
  await commands.wait.byXpath('//*[@id="root"]/div/div/div[4]/div[1]/div[2]/div[1]/div[1]/span[1]',delayTime);
  await commands.measure.stop();

==Results==
[2022-02-03 15:26:16] INFO: https://.net 10 requests, TTFB: 251ms, firstPaint: 855ms, firstVisualChange: 867ms, FCP: 855ms, DOMContentLoaded: 827ms, LCP: 919ms, CLS: 0.0007, TBT: 0ms, Load: 960ms, speedIndex: 994ms, visualComplete85: 1.00s, lastVisualChange: 1.00s
[2022-02-03 15:26:16] INFO: https://.net/mainlanding 8 requests, TTFB: 97ms, firstPaint: 289ms, firstVisualChange: 300ms, FCP: 289ms, DOMContentLoaded: 253ms, LCP: 289ms, CLS: 0, TBT: 0ms, Load: 306ms, speedIndex: 300ms, visualComplete85: 300ms, lastVisualChange: 300ms
[2022-02-03 15:26:16] INFO: https://.net/landing 13 requests, TTFB: 92ms, firstPaint: 336ms, firstVisualChange: 333ms, FCP: 336ms, DOMContentLoaded: 312ms, LCP: 336ms, CLS: 0.0093, TBT: 0ms, Load: 393ms, speedIndex: 336ms, visualComplete85: 333ms, lastVisualChange: 400ms
[2022-02-03 15:26:16] INFO: https://.net/metrics?dummy 11 requests, TTFB: 104ms, firstPaint: 332ms, firstVisualChange: 400ms, FCP: 332ms, DOMContentLoaded: 328ms, LCP: 332ms, CLS: 0.0003, TBT: 0ms, Load: 333ms, speedIndex: 3.90s, visualComplete85: 9.43s, lastVisualChange: 9.43s
[2022-02-03 15:26:16] INFO: https://.net/metrics?dummy&browsertime_run=2 10 requests, TTFB: 95ms, firstPaint: 337ms, firstVisualChange: 400ms, FCP: 337ms, DOMContentLoaded: 333ms, LCP: 337ms, CLS: 0.0003, TBT: 0ms, Load: 338ms, speedIndex: 857ms, visualComplete85: 400ms, lastVisualChange: 8.77s
[2022-02-03 15:26:16] INFO: https://.net/metrics?dummy&browsertime_run=3 10 requests, TTFB: 97ms, firstPaint: 302ms, firstVisualChange: 333ms, FCP: 302ms, DOMContentLoaded: 298ms, LCP: 302ms, CLS: 0.0003, TBT: 0ms, Load: 304ms, speedIndex: 733ms, visualComplete85: 333ms, lastVisualChange: 11.50s
[2022-02-03 15:26:24] INFO: HTML stored in /sitespeed.io/sitespeed-result/whlDashboardsLiveMetrics_js/2022-02-03-15-23-54
1 page analysed for whlDashboardsLiveMetrics.js (1 run, Chrome/desktop/[object Object])
Score: CPS:79, CPS:81, CBPS:100, Coach Overall Score:83 /  / 10 reqs /

**Comment by soulgalore** [comment]
Thank you @alexvolk001 for sharing how you solved it!
