### ISSUE TITLE
Apple Silicon: chrome failed to start

### ISSUE THREAD

**Issue by GabrielDelepine** [sitespeedio/sitespeed.io#3552]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io/

### What are you trying to accomplish

Using the docker cmd given in the README.md 

On an Apple Silicon computer (arm)

=> install Docker desktop 4.4.2 (Mac with Apple chip version)
=> run the command listed in the README of sitespeedio `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.6.1 https://www.sitespeed.io/`

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:21.6.1 https://www.sitespeed.io/
```

### Relevant log output

```shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Google Chrome 97.0.4692.99 
Mozilla Firefox 94.0
Microsoft Edge 97.0.1072.69 
[2022-02-02 15:57:36] INFO: Versions OS: linux 5.10.76-linuxkit nodejs: v16.13.1 sitespeed.io: 21.6.1 browsertime: 14.18.1 coach: 7.0.0
[2022-02-02 15:57:38] INFO: Running tests using Chrome - 3 iteration(s)
[2022-02-02 15:57:42] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2022-02-02 15:58:42] INFO: chrome failed to start, trying 1 more time(s): Failed to start chrome in 60 seconds.
[2022-02-02 15:59:43] INFO: chrome failed to start, trying 0 more time(s): Failed to start chrome in 60 seconds.
[2022-02-02 15:59:43] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:97:13)
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:108:7)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:285:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:152:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2022-02-02 15:59:43] ERROR: No data to collect
```

**Comment by soulgalore** [comment]
There are some work going on in https://github.com/sitespeedio/docker-browsers/issues/2

**Comment by GabrielDelepine** [comment]
Thanks, I will subscribe to this issue
