### ISSUE TITLE
Sitespeed docker container not working correctly for Apple Silicon (M1, arm64)

### ISSUE THREAD

**Issue by alextiley1** [sitespeedio/sitespeed.io#3553]
Good day.

I recently changed to a new mac with the M1 Apple Chip.

Sitespeed.io via docker no longer seems to be working for this new architecture. Currently the Sitespeed.io docker containers are only built for the `linux/amd64` platform. This platform is not supported on the new Apple M1 arm64 architecture, and I cannot get the docker container to work correctly running `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.8.0 https://www.sitespeed.io/`, the error I get is the following.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Google Chrome 88.0.4324.96
Mozilla Firefox 84.0
Microsoft Edge 89.0.767.0 dev
[2021-02-12 10:10:08] INFO: Versions OS: linux 4.19.104-linuxkit nodejs: v12.16.2 sitespeed.io: 16.8.0 browsertime: 11.4.0 coach: 6.0.1
[2021-02-12 10:10:08] INFO: Running tests using Chrome - 3 iteration(s)
[2021-02-12 10:10:11] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:13] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:15] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:15] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:15] ERROR: No data to collect
[2021-02-12 10:10:17] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:20] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:22] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:22] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:22] ERROR: No data to collect
[2021-02-12 10:10:24] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:26] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:28] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2021-02-12 10:10:28] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-02-12 10:10:28] ERROR: No data to collect
[2021-02-12 10:10:28] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:167:52)
[2021-02-12 10:10:31] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2021-02-12-10-10-08
```

To reproduce this issue on an M1 mac, install the docker preview for M1, then run Sitespeed.io via docker `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:16.8.0 https://www.sitespeed.io/`, you should see the same error as above.

Adding the `--platform linux/amd64` flag to the `docker run` command, as suggested on the [docker preview known issues](https://docs.docker.com/docker-for-mac/apple-m1/) does suppress the architecture miss match error, but the rest of the errors are the errors after the warning are still there as before. This happens for both the initial preview 7 version of Docker for Mac M1, and the latest version 3.1.0(60984).

From what I understand, the dockerfile is only installing chrome, Firefox and edge for amd64, maybe an architecture check could be added to install the arm64 versions if on an arm platform.

To remove the architecture warning, could the docker container be build for multiple platforms using `docker buildx` and pushed to the Sitespeed.io docker hub? 

These are just suggestions to get a conversation going.

Looking forward to your response.

**Comment by soulgalore** [comment]
This weekend I'm gonna push all containers to get all the different levels to work except one thing: I haven't found a way to get Chromium to work. The base container is built upon Ubuntu to be able to run Chrome and Chrome isn't compiled for arm. Chromium is but I can't get pass that it needs snap.

**Comment by soulgalore** [comment]
The magic needs to happen https://github.com/sitespeedio/docker-browsers/blob/main/Dockerfile#L61-L65

**Comment by soulgalore** [comment]
This should work now.

**Comment by icon-fonts** [comment]
I know it now



https://lnkr.fun/4ae4924

**Comment by vijayasankarsoftware** [comment]
#docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io -n 1 --multi login_and_measure.mjs

in the documentation they mentioned it will create browsertime.json and can get datas.
but its creating only browsertime.har file which not contain specific datas.

so, how to generate browsertime.json file
