### ISSUE TITLE
Is sitespeed visualMetrics not supported for windows 11?

### ISSUE THREAD

**Issue by PankajKaushik78** [sitespeedio/sitespeed.io#3577]
### Your question

Hey, I am trying to run sitespeed with --visualMetrics ` node .\sitespeed.io\bin\sitespeed.js -b firefox --firefox.binaryPath "C:\Program Files (x86)\firefox 93.0\firefox.exe" --visualMetrics -n 1 https://google.com` but it is showing the below error. Every thing works fine without --visualMetrics flag. I have tried similar on windows 10 (with same installation steps, and I have not installed using docker) and it is working fine. Can someone help me out here?

```
[2022-02-23 03:37:17] INFO: Versions OS: win32 10.0.22000 nodejs: v14.16.0 sitespeed.io: 23.0.1 browsertime: 15.0.1 coach: 7.1.0
[2022-02-23 03:37:18] INFO: Running tests using Firefox - 1 iteration(s)
[2022-02-23 03:37:22] INFO: Testing url https://google.com iteration 1
[2022-02-23 03:37:39] INFO: Waiting on har-export-trigger to collect the HAR
[2022-02-23 03:37:40] INFO: Take after page complete check screenshot
[2022-02-23 03:37:45] INFO: Get visual metrics from the video
[2022-02-23 03:37:45] ERROR: VisualMetrics failed to run Error: Command failed with exit code 1: python C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py --dir C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\filmstrip\1 --video C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.mp4 --orange --force --renderignore 5 --json --viewport -q 75 --logfile C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.visualmetrics.log -vvv
    at makeError (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\visualMetrics.js:111:22)
    at async module.exports (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\getVideoMetrics.js:34:21)
    at async Video.postProcessing (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\video.js:94:22)
    at async Iteration.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:261:34)
    at async Engine.runByScript (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:266:20)
    at async Object.analyzeUrl (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\analyzer.js:152:21)
    at async Object.processMessage (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2022-02-23 03:37:45] ERROR: Log from VisualMetrics: 03:37:45.711 - Processing frames from video C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.mp4 to C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\filmstrip\1
03:37:45.717 - [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py", line 2447, in main
    video_to_frames(
  File "C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py", line 92, in video_to_frames
    is_mobile = find_recording_platform(video)
  File "C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py", line 219, in find_recording_platform
    proc = subprocess.Popen(command, stderr=subprocess.PIPE, encoding="UTF-8")
  File "C:\Program Files\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

[2022-02-23 03:37:45] ERROR: Could not run Visual Metrics Error: Command failed with exit code 1: python C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py --dir C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\filmstrip\1 --video C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.mp4 --orange --force --renderignore 5 --json --viewport -q 75 --logfile C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.visualmetrics.log -vvv
    at makeError (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\visualMetrics.js:111:22)
    at async module.exports (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\getVideoMetrics.js:34:21)
    at async Video.postProcessing (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\video.js:94:22)
    at async Iteration.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:261:34)
    at async Engine.runByScript (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:266:20)
    at async Object.analyzeUrl (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\analyzer.js:152:21)
    at async Object.processMessage (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2022-02-23 03:37:45] ERROR: Visual Metrics failed to analyse the video Error: Command failed with exit code 1: python C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\browsertime\visualmetrics.py --dir C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\filmstrip\1 --video C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.mp4 --orange --force --renderignore 5 --json --viewport -q 75 --logfile C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17\pages\google_com\data\video\1.visualmetrics.log -vvv
    at makeError (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Windows\SitespeedTest\sitespeed.io\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\visualMetrics.js:111:22)
    at async module.exports (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\postprocessing\visualmetrics\getVideoMetrics.js:34:21)
    at async Video.postProcessing (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\video\video.js:94:22)
    at async Iteration.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:261:34)
    at async Engine.runByScript (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:266:20)
    at async Object.analyzeUrl (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\analyzer.js:152:21)
    at async Object.processMessage (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2022-02-23 03:37:45] ERROR: TypeError: Cannot read property 'push' of undefined
    at Iteration.run (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\iteration.js:285:31)
    at async Engine.runByScript (C:\Windows\SitespeedTest\sitespeed.io\node_modules\browsertime\lib\core\engine\index.js:266:20)
    at async Object.analyzeUrl (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\analyzer.js:152:21)
    at async Object.processMessage (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\index.js:150:26)
[2022-02-23 03:37:45] INFO: https://google.com 35 requests, TTFB: 272ms, firstPaint: 1.50s, FCP: 1.49s, DOMContentLoaded: 2.07s, Load: 3.23s
[2022-02-23 03:37:47] INFO: Could not read filmstrip dir TypeError: Cannot read property 'time' of undefined
    at Object.getFilmstrip (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\filmstrip.js:197:45)
    at async HTMLBuilder.render (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\html\htmlBuilder.js:271:13)
[2022-02-23 03:37:49] INFO: Could not read filmstrip dir TypeError: Cannot read property 'time' of undefined
    at Object.getFilmstrip (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\browsertime\filmstrip.js:197:45)
    at async HTMLBuilder.render (C:\Windows\SitespeedTest\sitespeed.io\lib\plugins\html\htmlBuilder.js:338:13)
[2022-02-23 03:37:53] INFO: HTML stored in C:\Windows\SitespeedTest\sitespeed-result\google.com\2022-02-23-03-37-17
````

**Comment by soulgalore** [comment]
Hi @PankajKaushik78 have you install the dependencies needed for getting Visual Metrics? You can checkout our Windows GitHub Action where we install them: https://github.com/sitespeedio/browsertime/blob/main/.github/workflows/windows.yml

**Comment by PankajKaushik78** [comment]
Thanks for the quick reply @soulgalore. 
Yes I have installed all the dependencies. 
` python ./browsertime/visualmetrics.py --check` This test is also working properly. But when i try to run the complete test, it shows the above error. Wondering why this worked in windows 10 and not in 11 with exact same steps.

**Comment by PankajKaushik78** [comment]
Also `npm install` is throwing this error. Is it happednig because of visual studio? @soulgalore 
```
C:\Windows\SitespeedTest\sitespeed.io-16.2.1\node_modules\sse4_crc32>if not defined npm_config_node_gyp (node "C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2017
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.11.32126.315) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Windows\SitespeedTest\node-v14.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Windows\\SitespeedTest\\node-v14.16.0-win-x64\\node.exe" "C:\\Windows\\SitespeedTest\\node-v14.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\SitespeedTest\sitespeed.io-16.2.1\node_modules\sse4_crc32
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by PankajKaushik78** [comment]
Just tried to run it with older sitespeed version (16.2.1) and it is working fine.
