### ISSUE TITLE
ERROR: Could not find the right index 3 for har for url

### ISSUE THREAD

**Issue by shasaks** [sitespeedio/sitespeed.io#3616]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.chegg.com/study/qa 

### What are you trying to accomplish

Running below script for test

module.exports = async function(context, commands) {
  await commands.measure.start('https://chegg.com/', 'home page');
  await commands.measure.start('https://chegg.com/books', 'books page');
  return commands.measure.start('https://chegg.com/study/qa', 'qna page');
};

### What browser did you use?

Chrome

### How to reproduce

```shell
run this script. Sitespeed version 22.1.2

module.exports = async function(context, commands) {
  await commands.measure.start('https://chegg.com/', 'home page');
  await commands.measure.start('https://chegg.com/books', 'books page');
  return commands.measure.start('https://chegg.com/study/qa', 'qna page');
};
```

### Relevant log output

```shell
[2022-03-31 10:53:55] ERROR: Could not find the right index 3 for har for url https://www.chegg.com/study/qa 
[2022-03-31 10:53:55] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at Object.pickAPage (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/coach-core/lib/index.js:84:12)
    at Object.processMessage (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:264:31)
[2022-03-31 10:53:55] INFO: The server responded with a 400 status code for https://sr.rlcdn.com/448926.html?s=
[2022-03-31 10:53:55] INFO: The server responded with a 400 status code for https://mc.yandex.com/sync_cookie_image_decide?token=9594.5L...
[2022-03-31 10:53:55] INFO: The server responded with a 400 status code for https://sr.rlcdn.com/448926.html?s=
[2022-03-31 10:53:55] INFO: The server responded with a 400 status code for https://sr.rlcdn.com/448926.html?s=
[2022-03-31 10:53:55] INFO: Budget: 3 working, 0 failing tests and 1 errors
[2022-03-31 10:53:57] ERROR: Could not generate url/iteration/index, /root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/lib/plugins/html/templates/url/cpu/index.pug:1
  > 1| - const browsertime = medianRun ? (pageInfo.data.browsertime ? pageInfo.data.browsertime.pageSummary.browserScripts[medianRun.runIndex - 1]: undefined) : pageInfo.data.browsertime.run 
    2| 
    3| small 
    4|     || 
Cannot read properties of undefined (reading 'run')
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2110:5)
    at go$writeFile (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/lib/core/resultsStorage/storageManager.js:15:13)
    at /root/.npm/_npx/aa19780b5aa25e1f/node_modules/sitespeed.io/lib/core/resultsStorage/storageManager.js:104:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by soulgalore** [comment]
Is this the same as #3600 ? I run into the verification page https://github.com/sitespeedio/sitespeed.io/issues/3600#issuecomment-1069178228 when I try to reproduce. Could you please show me exact how you run also?  Thanks!

**Comment by soulgalore** [comment]
Didn't get any response.
