### ISSUE TITLE
Issue with running multiple scripts

### ISSUE THREAD

**Issue by zzhao2010** [sitespeedio/sitespeed.io#3632]
### Your question

I was trying to run multiple scripts. It worked as expected when I was testing using the wikipedia example. Below is my scripts that worked for wikipedia page.
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:24.0.0 --multi login.js wikipedia.js
login.js
```
module.exports = async function(context, commands) {
  const LOGIN_URL = 'https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page';
  const USERNAME = 'xxx';
  const PASSWORD = 'xxx';
  await commands.navigate(LOGIN_URL);
  await commands.addText.byId(USERNAME, 'wpName1');
  await commands.addText.byId(PASSWORD, 'wpPassword1');
  await commands.click.byIdAndWait('wpLoginAttempt');
  context.myId = 10;
  return commands.wait.byId('pt-userpage', 3000);
}
```
wikipedia.js.. **Note: I added extra navigate and click steps below, and it still worked as expected.**
```
const testURL = 'https://en.wikipedia.org/wiki/Barack_Obama'
module.exports = async function(context, commands) {
  const idToUse = context.myId;
  context.log.info('the value is: ', idToUse);
  try {
    context.log.info('Logon Obama page..');
    await commands.navigate(testURL);
    await commands.wait.byTime(1000);
    await commands.measure.start();
    await commands.click.byXpathAndWait('//a[@href="/w/index.php?title=Barack_Obama&action=edit"]');
    return commands.measure.stop();
  } catch (e) {
    throw e;
  }
};
```
However I received exceptions when I started my real test, which has same steps. (I was trying to test salesforce page)
login.js  Note: The login.js script worked as expected. 
```
module.exports = async function(context, commands) {
    const LOGIN = "https://login.salesforce.com/";
    const USERNAME = "xxx";
    const PASSWORD = "xxx";
    await commands.navigate(LOGIN);
    await commands.addText.byId(USERNAME, "username");
    await commands.addText.byId(PASSWORD, "password");
    await commands.click.byIdAndWait("Login");
    return commands.wait.byTime(2000);
}
```
profilePage.js
```
module.exports = async function(context, commands) {
    const test = "https://xxxxx";
    try {
        await commands.navigate(test);
        await commands.wait.byTime(3000);
        context.log.info("Get All Call Report List!");
        await commands.measure.start();
        await commands.click.byXpath('(//td[@role="gridcell" and span/span[contains(text(),"Call Only")]]/preceding-sibling::th[1]/span/a)[1]');
        await commands.wait.byPageToComplete();
        return commands.measure.stop();
  } catch (e) {
    throw e;
  }
};
```

Below is the error msg:
[2022-04-18 18:48:37] INFO: Versions OS: linux 5.10.104-linuxkit nodejs: v16.14.2 sitespeed.io: 24.0.0 browsertime: 16.0.1 coach: 7.1.0
[2022-04-18 18:48:37] INFO: Running tests using Chrome - 1 iteration(s)
**[2022-04-18 18:48:38] INFO: Navigating to url https://login.salesforce.com/ iteration 1**
**[2022-04-18 18:48:58] INFO: Navigating to url https://xxxxxx iteration 1**
[2022-04-18 18:49:08] INFO: Get All Call Report List!
[2022-04-18 18:49:08] INFO: Start to measure
[2022-04-18 18:49:09] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=100.0.4896.60)
[2022-04-18 18:49:09] ERROR: JavascriptError: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=100.0.4896.60)
  (Session info: chrome=100.0.4896.60)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:548:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:474:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:735:17)
    at async SeleniumRunner.runScript (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:387:22)
    at async module.exports (/sitespeed.io/lex-view_call.js:8:9)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:7:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:221:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:266:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:145:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2022-04-18 18:49:09] ERROR: No data to collect
[2022-04-18 18:49:09] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'alias')
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:167:52)
[2022-04-18 18:49:09] ERROR: TypeError: Cannot read properties of null (reading 'split')
    at pathFromRootToPageDir (/usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:40)
    at Object.relativeSummaryPageUrl (/usr/src/app/lib/core/resultsStorage/resultUrls.js:30:14)
    at DataCollector._addUrl (/usr/src/app/lib/plugins/html/dataCollector.js:22:31)
    at DataCollector.addErrorForUrl (/usr/src/app/lib/plugins/html/dataCollector.js:94:10)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:58:27)
    at /usr/src/app/lib/core/queueHandler.js:213:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:466:21)
[2022-04-18 18:49:10] INFO: HTML stored in /sitespeed.io/sitespeed-result/lex-login_js/2022-04-18-18-48-37

**Comment by zzhao2010** [comment]
Note:
I tried to combine this 2 scripts into 1 to test my salesforce page again, and it worked just fine. So I don't understand why the same steps worked for wikipedia, but not for salesforce.

**Comment by soulgalore** [comment]
Hi @zzhao2010 it looks like you tried to click on an element that do not exist. There are some guidelines https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug on how you can debug your script.
