### ISSUE TITLE
Cannot read properties of undefined (reading 'cumulativeLayoutShift')?

### ISSUE THREAD

**Issue by grantyoung** [sitespeedio/sitespeed.io#3649]
### Your question

We're getting the following error today on our daily test pipeline:

```
[2022-05-11 08:27:19] ERROR: Could not generate url/iteration/index, /usr/src/app/lib/plugins/html/templates/url/metrics/index.pug:148
    146|             td
    147|               a(href='#cumulativeLayoutShift') Cumulative Layout Shift (CLS)
  > 148|             td.number #{browsertime.pageinfo.cumulativeLayoutShift.toFixed(2)}
    149|           if browsertime.timings.firstInput !== undefined
    150|             tr 
    151|               td
Cannot read properties of undefined (reading 'cumulativeLayoutShift')
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:104:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Bizarrely this didn't happen yesterday on the same new SiteSpeed version (24.6.0) but it happens each time today and I can't recreate it locally.

Any guidance on what could cause this error to help investigate? Thanks.

**Comment by soulgalore** [comment]
Hi @grantyoung it looks like that the JavaScript that runs in the browser to collect the layout shift data (and other page info data) didn't collect anything, I can add one extra check there but I wonder if you don't get any errors earlier than that?

**Comment by grantyoung** [comment]
> Hi @grantyoung it looks like that the JavaScript that runs in the browser to collect the layout shift data (and other page info data) didn't collect anything, I can add one extra check there but I wonder if you don't get any errors earlier than that?

Funny enough I did have an earlier on second look sorry:

```
[2022-05-11 10:55:13] ERROR: Couldn't execute script named visualElements error:JavascriptError: javascript error: Cannot read properties of null (reading 'getBoundingClientRect')
  (Session info: chrome=101.0.4951.54)
[2022-05-11 10:55:13] ERROR: Failed to execute user script: JavascriptError: javascript error: Cannot read properties of null (reading 'getBoundingClientRect')
  (Session info: chrome=101.0.4951.54)
[2022-05-11 10:55:15] ERROR: Visual Metrics failed to analyse the video TypeError: Cannot read properties of undefined (reading 'visualElements')
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:263:49)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:266:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:152:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2022-05-11 10:55:15] ERROR: TypeError: Cannot read properties of undefined (reading 'push')
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:285:31)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:266:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:152:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:150:26)
[2022-05-11 10:55:15] ERROR: Unhandled value type undefined found when adding data for pageinfo 
[2022-05-11 10:55:15] INFO: <url_redacted> TTFB: 626ms DOMContentLoaded: 1.71s firstPaint: 716ms FCP: 716ms LCP: 1.79s Load: 1.75s 
[2022-05-11 10:55:15] INFO: <url_redacted> 24 requests, TTFB: 837ms (σ211.00ms), firstPaint: 929ms (σ213.00ms), firstVisualChange: 66ms (σ0.00ms), FCP: 929ms (σ213.00ms), DOMContentLoaded: 1.92s (σ210.00ms), LCP: 2.52s (σ728.00ms), CLS: 0.0053 (σ0.00), TBT: 509ms (σ0.00ms), Load: 2.01s (σ254.00ms), speedIndex: 1.18s (σ0.00ms), visualComplete85: 1.17s (σ0.00ms), lastVisualChange: 3.23s (σ0.00ms) (2 runs)
[2022-05-11 10:55:15] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'cumulativeLayoutShift')
    at Object.addToAggregate (/usr/src/app/lib/plugins/browsertime/aggregator.js:55:37)
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:482:26)
 ```

**Comment by soulgalore** [comment]
I see now I recently added automatic supports for getting largest contentful paint from the video but my guess is that its a use case that I missed where Chrome have data in the LCP API but do not have the element, let me fix that ASAP.

**Comment by soulgalore** [comment]
@grantyoung I just pushed  24.7.0 that I hope fixes your problem. I must have been sloppy when I read the LCP API spec and missed that it sometimes do not deliver an element (or its a bug in Chrome, I'll check that later). It will be on the Docker hub when https://github.com/sitespeedio/sitespeed.io/actions/runs/2307148688 is finished.

**Comment by grantyoung** [comment]
> @grantyoung I just pushed 24.7.0 that I hope fixes your problem. I must have been sloppy when I read the LCP API spec and missed that it sometimes do not deliver an element (or its a bug in Chrome, I'll check that later). It will be on the Docker hub when https://github.com/sitespeedio/sitespeed.io/actions/runs/2307148688 is finished.

Many thanks, I'll try to get this checked ASAP.
