### ISSUE TITLE
sitespeed 24.9.0-plus1 throwing the following error for resultsbaseURL

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/sitespeed.io#3668]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.bedbathandbeyond.com/store/s/toaster-oven?ta=typeahead&bx=off&wmSkipPwa

### What are you trying to accomplish

Plus1 image throws the following error during run.  

[2022-05-31 16:05:31] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9
[2022-05-31 16:05:31] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run \
--rm \
-v "$(pwd)":/sitespeed.io \
sitespeedio/sitespeed.io:24.9.0-plus1 \
--plugins.add analysisstorer \
--plugins.add /sitespeed.io/sitespeed.io/plugin-lighthouse/ \
--gpsi.key my_keyfile \
--resultBaseURL "https://storage.googleapis.com/my-storage" \
--mobile true \
--gcs.projectId my_gcp_project \
--gcs.bucketname prdmon-soi \
--gcs.key gcskey.json \
--gcs.removeLocalResult true \
--crux.key my_crux_key \
--crux.formFactor "PHONE" \
--crux.collect "ALL" \
--firstParty "\.bedbathandbeyond\.com" \
--chrome.timeline \
--chrome.collectLongTasks \
--chrome.collectPerfLog \
--screenshot.type "png" \
--visualMetrics \
--visualElements \
--videoParams.createFilmstrip \
--filmstrip.showAll true \
--copyLatestFilesToBase true \
--cpu \
--speedIndex \
--thirdParty.cpu \
-n 3 \
bbby-urls.txt \
--graphite.addSlugToKey true \
--graphite.host 10.1.1.10 \
--graphite.annotationScreenshot \
--graphite.port 2003 \
--slug Bedbath \
--graphite.httpPort 80 \
--graphite.namespace=sitespeed_io.Mobile
```

### Relevant log output

```shell
Google Chrome 102.0.5005.61 
Mozilla Firefox 100.0
Microsoft Edge 101.0.1210.53 
[2022-05-31 16:05:30] INFO: Versions OS: linux 3.10.0-1160.53.1.el7.x86_64 nodejs: v16.15.0 sitespeed.io: 24.9.0 browsertime: 16.7.0 coach: 7.1.2
[2022-05-31 16:05:30] INFO: Using default Lighthouse configuration for mobile
[2022-05-31 16:05:31] INFO: Will run Lighthouse tests after Browsertime has finished
[2022-05-31 16:05:31] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9
[2022-05-31 16:05:31] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9
[2022-05-31 16:05:31] INFO: Get CrUx data for domain www.bedbathandbeyond.com
```

**Comment by soulgalore** [comment]
Hi @kmaqsudi thanks for creating the issue! Hmm I don't recall any changes lately for resultBaseURL so I wonder what it could be. Can you run it at your side with `--verbose`  and then look in the log for **DEBUG: [sitespeedio] Running with options:**  - then all options are logged, can you check that the resultBaseURL is picked up correctly by the cli (check that resultBaseURL has the right value).

**Comment by soulgalore** [comment]
Didn't get any response so closing.
