### ISSUE TITLE
Lighthouse problem when using axe

### ISSUE THREAD

**Issue by dawsze** [sitespeedio/sitespeed.io#3701]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://google.com

### What are you trying to accomplish

When I run sitespeed tests with --axe.enable param lighthouse (I guess) prints ERROR: TypeError [ERR_INVALID_ARG_TYPE].

I've tried do that on local docker (Windows, Linux) and gitlab pipeline but every time with same results. Error is not showing without axe param.

Environments tested on:
- Windows 10 (10.0.19044)
- Ubuntu 18.04.6 LTS (Bionic Beaver)
- Gitlab pipeline runner (Browser-Performance.gitlab-ci.yml template)

Sitespeed docker image tested versions:
- sitespeedio/sitespeed.io:25.2.0-plus1
- sitespeedio/sitespeed.io:25.5.1-plus1

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --shm-size=1g --rm sitespeedio/sitespeed.io:25.5.1-plus1 https://google.com -n 1 --plugins.add analysisstorer --plugins.add /lighthouse --plugins.list --graphite.host=host.docker.internal --graphite.port=9109 --axe.enable --cpu --thirdParty.cpu --visualElements --visualMetrics --visualMetricsPerceptual --visualMetricsContentful
```

### Relevant log output

```shell
#NOTE --verbose flag does not provide any extra informations

docker run --shm-size=1g --rm sitespeedio/sitespeed.io:25.5.1-plus1 https://google.com -n 1 --plugins.add analysisstorer --plugins.add /lighthouse --plugins.list --graphite.host=host.docker.internal --graphite.port=9109 --axe.enable --cpu --thirdParty.cpu --visualElements --visualMetrics --visualMetricsPerceptual --visualMetricsContentful
Google Chrome 103.0.5060.114
Mozilla Firefox 102.0
Microsoft Edge 103.0.1264.51
[2022-07-27 06:15:19] INFO: Versions OS: linux 4.9.93-linuxkit-aufs nodejs: v16.16.0 sitespeed.io: 25.5.0 browsertime: 16.11.3 coach: 7.1.2
[2022-07-27 06:15:19] INFO: The following plugins are enabled: assets, axe, browsertime, budget, coach, domains, graphite, harstorer, html, lateststorer, metrics, pagexray, remove, text, thirdparty, tracestorer, analysisstorer, /lighthouse
[2022-07-27 06:15:19] INFO: Axe plugin activated
[2022-07-27 06:15:19] INFO: Using default Lighthouse configuration for desktop
[2022-07-27 06:15:20] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2123:5)
    at go$writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/usr/src/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/usr/src/app/node_modules/fs-extra/node_modules/universalify/index.js:7:14)
    at write (/usr/src/app/lib/core/resultsStorage/storageManager.js:15:13)
    at /usr/src/app/lib/core/resultsStorage/storageManager.js:40:9
[2022-07-27 06:15:20] INFO: Will run Lighthouse tests after Browsertime has finished
[2022-07-27 06:15:20] INFO: Running tests using Chrome - 1 iteration(s)
[2022-07-27 06:15:20] INFO: Use Chrome trace categories: -*,disabled-by-default-lighthouse,v8,v8.execute,blink.user_timing,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.stack
[2022-07-27 06:15:20] INFO: Testing url https://google.com iteration 1
```

**Comment by soulgalore** [comment]
HI @dawsze thanks for creating the issue. I'll have a look this weekend and check what's going on.

**Comment by soulgalore** [comment]
This will be fixed with the next release, I think on Monday the coming week.
