### ISSUE TITLE
Chrome browser fails to start with sitespeedio/webbrowsers:chrome-104.0-firefox-103.0-edge-103.0 image

### ISSUE THREAD

**Issue by abedarkar** [sitespeedio/sitespeed.io#3750]
Docker Image - sitespeedio/webbrowsers:chrome-104.0-firefox-103.0-edge-103.0
Package.json - "sitespeed.io": "25.11.0"

When below command is executed in pipeline.
./node_modules/sitespeed.io/bin/sitespeed.js  --config config.json   script/apiPortal_Public/pp_apiServices_Page.js --multi -n 1   --cpu --budget.friendlyName pp_apiServices_Page

I am observing below error

[32;1m$ ./node_modules/sitespeed.io/bin/sitespeed.js  --config config.json   script/apiPortal_Public/pp_apiServices_Page.js --multi -n 1   --cpu --budget.friendlyName pp_apiServices_Page[0;m
[2022-11-08 09:24:28] INFO: Versions OS: linux 4.14.294-220.533.amzn2.x86_64 nodejs: v16.16.0 sitespeed.io: 25.11.0 browsertime: 16.15.1 coach: 7.1.2
[2022-11-08 09:24:28] INFO: Running tests using Chrome - 1 iteration(s)
[2022-11-08 09:24:29] INFO: chrome failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2022-11-08 09:24:30] INFO: chrome failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2022-11-08 09:24:31] INFO: chrome failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2022-11-08 09:24:31] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/browser-performance/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:91:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Iteration.run (/browser-performance/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:118:7)
    at async Engine.runByScript (/browser-performance/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:270:20)
    at async Object.analyzeUrl (/browser-performance/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:174:21)
    at async Object.processMessage (/browser-performance/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:150:26)
[2022-11-08 09:24:31] ERROR: No data to collect
[2022-11-08 09:24:31] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'alias')
    at Object.processMessage (/browser-performance/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:167:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-08 09:24:31] ERROR: TypeError: Cannot read properties of null (reading 'split')
    at pathFromRootToPageDir (/browser-performance/node_modules/sitespeed.io/lib/core/resultsStorage/pathToFolder.js:20:40)
    at Object.relativeSummaryPageUrl (/browser-performance/node_modules/sitespeed.io/lib/core/resultsStorage/resultUrls.js:30:14)
    at DataCollector._addUrl (/browser-performance/node_modules/sitespeed.io/lib/plugins/html/dataCollector.js:22:31)
    at DataCollector.addErrorForUrl (/browser-performance/node_modules/sitespeed.io/lib/plugins/html/dataCollector.js:94:10)
    at Object.processMessage (/browser-performance/node_modules/sitespeed.io/lib/plugins/html/index.js:58:27)
    at /browser-performance/node_modules/sitespeed.io/lib/core/queueHandler.js:213:32
    at drainItem (/browser-performance/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/browser-performance/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:466:21)
[2022-11-08 09:24:31] INFO: Budget: 0 working, 0 failing tests and 1 [errors](url)
[Console Logs.txt](https://github.com/sitespeedio/sitespeed.io/files/9959766/Console.Logs.txt)
[chromedriver.log](https://github.com/sitespeedio/sitespeed.io/files/9959785/chromedriver.log)

Note : I am facing this issue when I use sitespeedio docker image. I need to run the tests against chrome browser greater than 103 versions.

**Comment by soulgalore** [comment]
Hi @abedarkar so you go into the docker container and start sitespeed.io manually? Can you try add `--xvfb ` to your parameters, that way the xvfb will be used as your screen, just want to make sure it's used.

Else our start script has some extra hacks: https://github.com/sitespeedio/sitespeed.io/blob/main/docker/scripts/start.sh

**Comment by abedarkar** [comment]
Hi @soulgalore , no our pipelines setup is such , we can't go into the docker container and start sitespeed.io manually nor we can do any manipulation with docker.
We are fetching the image and executing the tests using above mentioned command.

**Comment by soulgalore** [comment]
Hmm I don't fully understand, so you run like this:
`./node_modules/sitespeed.io/bin/sitespeed.js --config ...`

That looks like installed sitespeed.io using npm, so you run your own container? Then check that you follow our start script and included what's needs to be included. Where you able to try add -`-xvfb`?

**Comment by soulgalore** [comment]
I think the best way is to use our Docker containers.
