### ISSUE TITLE
How to configure CI/CD from GitHub actions to influxdb

### ISSUE THREAD

**Issue by Vlad-Kliucharov** [sitespeedio/sitespeed.io#3755]
### Your question

After my test is finished I want to send the result from the docker container to influxDB, when I try to do it like in an example in the documentation I receive code 1.

There is a launch string below:

docker run --shm-size=1g --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js network=my-net --influxdb.host 192.xxx.xxx.xxx --influxdb.port 8086 --influxdb.database siteSpeedDB --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test

AND

Error:
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:21:56] ERROR: Error: No host available
    at Pool.stream (/usr/src/app/node_modules/influx/lib/src/pool.js:235:29)
    at /usr/src/app/node_modules/influx/lib/src/pool.js:166:18
    at new Promise (<anonymous>)
    at Pool.discard (/usr/src/app/node_modules/influx/lib/src/pool.js:[165](https://github.com/Vlad-Kliucharov/Performance-UI/actions/runs/3583650781/jobs/6029336542#step:3:166):16)
    at InfluxDB.writePoints (/usr/src/app/node_modules/influx/lib/src/index.js:854:27)
    at InfluxDBSender.send (/usr/src/app/lib/plugins/influxdb/sender.js:26:24)
    at Object.processMessage (/usr/src/app/lib/plugins/influxdb/index.js:125:26)
    at /usr/src/app/lib/core/queueHandler.js:213:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:466:21)
[2022-11-30 13:21:56] ERROR: Error: No host available
    at Pool.stream (/usr/src/app/node_modules/influx/lib/src/pool.js:235:29)
    at /usr/src/app/node_modules/influx/lib/src/pool.js:[166](https://github.com/Vlad-Kliucharov/Performance-UI/actions/runs/3583650781/jobs/6029336542#step:3:167):18
    at new Promise (<anonymous>)
    at Pool.discard (/usr/src/app/node_modules/influx/lib/src/pool.js:165:16)
    at InfluxDB.writePoints (/usr/src/app/node_modules/influx/lib/src/index.js:854:27)
    at InfluxDBSender.send (/usr/src/app/lib/plugins/influxdb/sender.js:26:24)
    at Object.processMessage (/usr/src/app/lib/plugins/influxdb/index.js:125:26)
    at /usr/src/app/lib/core/queueHandler.js:213:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:466:21)
[[202](https://github.com/Vlad-Kliucharov/Performance-UI/actions/runs/3583650781/jobs/6029336542#step:3:203)2-11-30 13:22:26] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:[270](https://github.com/Vlad-Kliucharov/Performance-UI/actions/runs/3583650781/jobs/6029336542#step:3:271):38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:22:26] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:22:26] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:22:26] ERROR: Error: Request timed out
    at /usr/src/app/node_modules/influx/lib/src/pool.js:270:38
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:66:13)
    at ClientRequest.emit (node:events:527:28)
    at Socket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:539:35)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-11-30 13:22:29] INFO: HTML stored in /sitespeed.io/output/report
Error: Process completed with exit code 1.

PLEASE HELP!!!

**Comment by soulgalore** [comment]
Hi @Vlad-Kliucharov it seems that the server that runs the tests can't reach 192.xxx.xxx.xxx? Try to ping the server before you run your test and see if that works.

**Comment by Vlad-Kliucharov** [comment]
Hi @soulgalore!
I try to ping it and the result is negative, I don't know how to give the rights to my local machine
Maybe there is another way, can I create DB in git action and store the data result there?

**Comment by soulgalore** [comment]
Didn't get any response so closing.
