### ISSUE TITLE
Got an error from HAR Export Trigger

### ISSUE THREAD

**Issue by Derrezed-Fez** [sitespeedio/sitespeed.io#3770]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

www.sitespeed.io

### What are you trying to accomplish

I am running the example command from the installation guide.

### What browser did you use?

Firefox

### How to reproduce

```shell
Run browsertime https://www.sitespeed.io -b firefox
```

### Relevant log output

```shell
PS C:\Users\User\AppData\Roaming\npm> browsertime https://www.sitespeed.io -b firefox --headless                                                      [2023-02-24 22:23:44] INFO: Running tests using Firefox - 3 iteration(s)
[2023-02-24 22:23:47] INFO: Testing url https://www.sitespeed.io iteration 1
[2023-02-24 22:23:57] INFO: Waiting on har-export-trigger to collect the HAR
[2023-02-24 22:23:57] ERROR: Got an error from HAR Export Trigger {"error":"The HAR export trigger returned an empty HAR{\"version\":\"1.2\",\"creator\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"browser\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"pages\":[],\"entries\":[]}"}
[2023-02-24 22:23:57] ERROR: TypeError: Cannot read properties of undefined (reading 'log')
    at Firefox.afterPageCompleteCheck (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/firefox/webdriver/firefox.js:173:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Measure.stop (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/command/measure.js:298:17)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/iteration.js:226:9)
    at async Engine.runByScript (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:104:22)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:195:1
[2023-02-24 22:23:58] INFO: https://www.sitespeed.io
[2023-02-24 22:24:01] INFO: Testing url https://www.sitespeed.io iteration 2
[2023-02-24 22:24:11] INFO: Waiting on har-export-trigger to collect the HAR
[2023-02-24 22:24:11] ERROR: Got an error from HAR Export Trigger {"error":"The HAR export trigger returned an empty HAR{\"version\":\"1.2\",\"creator\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"browser\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"pages\":[],\"entries\":[]}"}
[2023-02-24 22:24:11] ERROR: TypeError: Cannot read properties of undefined (reading 'log')
    at Firefox.afterPageCompleteCheck (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/firefox/webdriver/firefox.js:173:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Measure.stop (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/command/measure.js:298:17)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/iteration.js:226:9)
    at async Engine.runByScript (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:104:22)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:195:1
[2023-02-24 22:24:12] INFO: https://www.sitespeed.io
[2023-02-24 22:24:16] INFO: Testing url https://www.sitespeed.io iteration 3
[2023-02-24 22:24:25] INFO: Waiting on har-export-trigger to collect the HAR
[2023-02-24 22:24:25] ERROR: Got an error from HAR Export Trigger {"error":"The HAR export trigger returned an empty HAR{\"version\":\"1.2\",\"creator\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"browser\":{\"name\":\"Firefox\",\"version\":\"110.0\"},\"pages\":[],\"entries\":[]}"}
[2023-02-24 22:24:25] ERROR: TypeError: Cannot read properties of undefined (reading 'log')
    at Firefox.afterPageCompleteCheck (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/firefox/webdriver/firefox.js:173:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Measure.stop (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/command/measure.js:298:17)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/iteration.js:226:9)
    at async Engine.runByScript (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async run (file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:104:22)
    at async file:///C:/Users/User/AppData/Roaming/npm/node_modules/browsertime/bin/browsertime.js:195:1
[2023-02-24 22:24:26] INFO: https://www.sitespeed.io
[2023-02-24 22:24:26] INFO: https://www.sitespeed.io
[2023-02-24 22:24:26] INFO: Wrote data to browsertime-results\www.sitespeed.io\2023-02-24T222343-0500
PS C:\Users\User\AppData\Roaming\npm>
```

**Comment by soulgalore** [comment]
I could never reproduce this. If you still have that problem I would try with the new bidi HAR functionality: `--firefox.bidihar true`
