### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by divyachandrashekara** [sitespeedio/sitespeed.io#3792]
Team Sitespeed.io,

I am trying to develop script for front end performance testing purpose. I have written JavaScript using sitespeed.io commands available in Sitespeed.io documentation.  On executing the JavaScript I am getting below error. Could you please provide a resolution to solve the error?

------------------Error Message----------------------
[2023-03-20 05:26:07] ERROR: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.addMetrics (/usr/src/app/node_modules/pagexray/lib/sitespeed.js:13:33)
    at Object.convert (/usr/src/app/node_modules/pagexray/lib/index.js:272:17)
    at PageXrayPlugin.processMessage (file:///usr/src/app/lib/plugins/pagexray/index.js:92:40)
    at file:///usr/src/app/lib/core/queueHandler.js:215:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by soulgalore** [comment]
Sorry, need to have a reproducible test case to be able to help. See https://www.sitespeed.io/documentation/sitespeed.io/bug-report/
