### ISSUE TITLE
strange script execution (just stop execution after start measure)

### ISSUE THREAD

**Issue by iamtechnomage** [sitespeedio/sitespeed.io#3807]
### Your question

Hi, try to debug my script.
Can you help me?
Problem:
```
[2023-04-06 09:02:58] INFO: Navigating to url https://creator-spacex.net/ iteration 1
[2023-04-06 09:03:37] INFO: Start to measure CMS editor main page
[2023-04-06 09:05:38] ERROR: ScriptTimeoutError: script timeout
```
in script beyond add make screenshoot
in screens folder creates debug1-debug6, and log "CMS editor main page" writes on console, but next coomand not work
i dont understand what i doing wrong

OTP code erase. if need i will write additional
```
module.exports = async function(context, commands) {
  await commands.navigate(
    'https://creator-spacex.net/'
  );
  await commands.wait.byPageToComplete();
  try {
    await commands.screenshot.take("debug1");
    // wait loading page and fill phone field
    await commands.addText.byXpath('\b\b71001023344', "//div[@data-test='login-input-number']/div/div/input");
    await commands.screenshot.take("debug2");
    // Click on the Send button
    await commands.click.byXpath("//button[@data-test='login-send-code-button']");
    await commands.screenshot.take("debug3");
    // fill OTP code
    await commands.wait.byXpath('//input[@data-index="0"]', 20000);
    await commands.screenshot.take("debug4");
    await commands.addText.byXpath('*', '//input[@data-index="0"]');
    await commands.addText.byXpath('*', '//input[@data-index="1"]');
    await commands.addText.byXpath('*', '//input[@data-index="2"]');
    await commands.addText.byXpath('*', '//input[@data-index="3"]');
    await commands.addText.byXpath('*', '//input[@data-index="4"]');
    await commands.addText.byXpath('*', '//input[@data-index="5"]');
    await commands.screenshot.take("debug5");
    await commands.wait.byXpath('//*[@id="root"]/div[1]/div[1]/section', 20000);
    await commands.screenshot.take("debug6");
    await commands.measure.start('CMS editor main page');
    await commands.screenshot.take("debug7");
    await commands.navigation.refresh();
    await commands.wait.byPageToComplete();
    await commands.wait.byXpath('//*[@id="root"]/div[1]/div[1]/section', 20000);
    await commands.measure.stop();
  } catch (e) {
    throw e;
  }
};
```

stacktrace
```
[2023-04-06 09:05:38] ERROR: ScriptTimeoutError: script timeout
  (Session info: chrome=106.0.5249.119)
  (Session info: chrome=106.0.5249.119)
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:740:17)
    at async module.exports (/usr/src/app/node_modules/browsertime/lib/video/screenRecording/setOrangeBackground.js:26:3)
    at async Measure._startVideo (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:85:7)
    at async Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:208:7)
    at async module.exports (/sitespeed.io/qa-web-performance/test_scripts/cms/cms_editor_main_page.js:27:5)
    at async /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:7:9
    at async Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:227:9)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:274:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:174:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:154:26)
[2023-04-06 09:05:38] ERROR: No data to collect
[2023-04-06 09:05:38] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'alias')
    at Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:171:52)
[2023-04-06 09:05:38] ERROR: TypeError: Cannot read properties of null (reading 'split')
    at pathFromRootToPageDir (/usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:40)
    at Object.relativeSummaryPageUrl (/usr/src/app/lib/core/resultsStorage/resultUrls.js:30:14)
    at DataCollector._addUrl (/usr/src/app/lib/plugins/html/dataCollector.js:22:31)
    at DataCollector.addErrorForUrl (/usr/src/app/lib/plugins/html/dataCollector.js:94:10)
    at Object.processMessage (/usr/src/app/lib/plugins/html/index.js:58:27)
    at /usr/src/app/lib/core/queueHandler.js:213:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by iamtechnomage** [comment]
it's a product bug. 
:)
