### ISSUE TITLE
ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'beforeBrowserStart')

### ISSUE THREAD

**Issue by AlanCodega** [sitespeedio/sitespeed.io#3818]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://example.com

### What are you trying to accomplish

Run docker image (from docker hub ) in Azure pipeline

### What browser did you use?

Chrome

### How to reproduce

```shell
that's our yml file for azure devops pipeline:

trigger:
  branches:
    include:
    - main

parameters:
- name: networkVelocity
  displayName: 'Network Velocity'
  type: string
  default: '3g'
  values:
    - '3g'
    - 'cable'
    - '3gfast'
    - '3gslow'
    - '4g'
    - 'native'
- name: browser
  displayName: 'Browser'
  type: string
  default: 'Chrome'
  values:
    - 'Chrome'
    - 'Firefox'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PerformanceTest
  displayName: 'Performance Test with Sitespeed.io'
  jobs:
  - job: RunSitespeed
    displayName: 'Run Sitespeed.io'
    steps:
    - checkout: self
    - script: |
        TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
        echo "##vso[task.setvariable variable=TIMESTAMP]$TIMESTAMP"
      displayName: 'Create timestamp for artifact folder name'
    - script: |
        docker pull sitespeedio/sitespeed.io:27.3.0
        docker save -o sitespeed-image.tar sitespeedio/sitespeed.io:27.3.0
        docker run --rm -v "$(System.DefaultWorkingDirectory)/sitespeed-result":/sitespeed.io/sitespeed-result sitespeedio/sitespeed.io:27.3.0 https://www.google.com -n 1 --outputFolder sitespeed-result --connectivity.engine throttle --connectivity.profile ${{ parameters.networkVelocity }} --browser ${{ parameters.browser }}
      displayName: 'Run Sitespeed.io Docker container'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/sitespeed-result-${{ parameters.networkVelocity }}-$(TIMESTAMP)'
        artifact: 'sitespeed-result-${{ parameters.networkVelocity }}-$(TIMESTAMP)'
      displayName: 'Publish Sitespeed.io results'
```

### Relevant log output

```shell
d918e14ce219: Pull complete
07fc46e00e2e: Pull complete
afdcdd51af46: Pull complete
Digest: sha256:00c1733fda795f880754b4d380a2ee2433796cc2956fb3cc630c5dec7fa9c962
Status: Downloaded newer image for sitespeedio/sitespeed.io:27.3.0
docker.io/sitespeedio/sitespeed.io:27.3.0
Google Chrome 112.0.5615.49 
Mozilla Firefox 112.0
Microsoft Edge 112.0.1722.39 
[2023-04-21 13:04:07] INFO: Versions OS: linux 5.15.0-1035-azure nodejs: v18.14.2 sitespeed.io: 27.3.0 browsertime: 17.8.0 coach: 7.1.3
[2023-04-21 13:04:08] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'beforeBrowserStart')
    at Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:283:26)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:174:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-04-21 13:04:08] INFO: HTML stored in /sitespeed.io/sitespeed-result
Error: Errors while running:
TypeError: Cannot read properties of undefined (reading 'beforeBrowserStart')
    at start (file:///usr/src/app/bin/sitespeed.js:33:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:64:1
##[error]Bash exited with code '1'.
Finishing: Run Sitespeed.io Docker container
```

**Comment by soulgalore** [comment]
Hi @AlanCodega try to log the input to sitespeed.io, I think something is going there. You can do that by adding the` --verbose` flag. Look for a line that starts with _Running with options ..._ and then all options are logged. I would look for --connectivity.profile and browser and see what kind of values they get.

**Comment by AlanCodega** [comment]
Hi @soulgalore ,
Many thanks for your reply and thanks in advance for your support :)
With pleasure, that's my log (limited):

```
Digest: sha256:00c1733fda795f880754b4d380a2ee2433796cc2956fb3cc630c5dec7fa9c962
Status: Downloaded newer image for sitespeedio/sitespeed.io:27.3.0
docker.io/sitespeedio/sitespeed.io:27.3.0
Google Chrome 112.0.5615.49 
Mozilla Firefox 112.0
Microsoft Edge 112.0.1722.39 
[2023-04-21 13:54:53] INFO: [sitespeedio] Versions OS: linux 5.15.0-1035-azure nodejs: v18.14.2 sitespeed.io: 27.3.0 browsertime: 17.8.0 coach: 7.1.3
[2023-04-21 13:54:53] DEBUG: [sitespeedio] Running with options: {
  "_": [
    "[https://google.com"](https://google.com/)
  ],
  "n": 1,
  "browsertime": {
    "iterations": 1,
    "connectivity": {
      "engine": "throttle",
      "profile": "native"
    },
    "browser": "Chrome",
    "docker": "true",
    "xvfb": true,
    "xvfbParams": {
      "display": 99
    },
    "xvfb-params": {
      "display": 99
    },
    "spa": false,
    "debug": false,
    "limitedRunData": true,
    "limited-run-data": true,
    "android": {
      "gnirehtet": false,
      "rooted": false,
      "batteryTemperatureWaitTimeInSeconds": 120,
      "battery-temperature-wait-time-in-seconds": 120,
      "verifyNetwork": false,
      "verify-network": false
    },
    "gnirehtet": false,
    "timeouts": {
      "pageCompleteCheck": 120000,
      "page-complete-check": 120000
    },
```

**Comment by AlanCodega** [comment]
actually, in the full log, there is 3 connectivity.profile:

in order:
```
"n": 1,
  "browsertime": {
    "iterations": 1,
    "connectivity": {
      "engine": "throttle",
      "profile": "native"
    },
    "browser": "Chrome",
    "docker": "true",
    "xvfb": true,
    "xvfbParams": {
      "display": 99
    },

```

```
"outputFolder": "sitespeed-result",
  "output-folder": "sitespeed-result",
  "connectivity": {
    "engine": "throttle",
    "profile": "3g"
  },
  "browser": "Chrome",
  "b": "Chrome",
  "verbose": 1,
  "v": 1,
  "xvfb": true,
  "debugMessages": false,
  "debug-messages": false,
  "xvfbParams": {
    "display": 99
  },

```

```
],
    "browsertime": {
      "iterations": 1
    },
    "n": 1,
    "outputFolder": "sitespeed-result",
    "connectivity": {
      "engine": "throttle",
      "profile": "3g"
    },
    "browser": "Chrome",
    "verbose": true,
    "$0": "/usr/src/app/bin/sitespeed.js"
  },
```

```
"$0": "/usr/src/app/bin/sitespeed.js",
  "explicitOptions": {
    "_": [
      "[https://google.com"](https://google.com%22/)
    ],
    "browsertime": {
      "iterations": 1
    },
    "n": 1,
    "outputFolder": "sitespeed-result",
    "connectivity": {
      "engine": "throttle",
      "profile": "3g"
    },
    "browser": "Chrome",
    "verbose": true,
    "$0": "/usr/src/app/bin/sitespeed.js"
  },
  "urls": [
    "[https://google.com"](https://google.com%22/)
  ],
  "urlsMetaData": {},
  "slug": "dev_cirrusoft_cloud"
}
[2023-04-21 14:12:01] DEBUG: [browsertime] Running with options: {
  "scripts": [],
  "iterations": 1,
  "delay": 0,
  "videoParams": {
    "framerate": 30,
    "crf": 23,
    "addTimer": true,
    "convert": true,
    "keepOriginalVideo": false,
    "filmstripFullSize": false,
    "filmstripQuality": 75,
    "createFilmstrip": true,
    "thumbsize": 400
  },
  "statistics": true,
  "browser": "Chrome",
  "connectivity": {
    "profile": "native",
    "engine": "throttle"
  },

```

**Comment by soulgalore** [comment]
It looks like the URL is markdown `"[https://google.com"](https://google.com%22/)` I don't think we support that. But it didn't look like that in your configuration, that is strange?

**Comment by AlanCodega** [comment]
I replaced manually for "privacy" :)

**Comment by soulgalore** [comment]
That's not how you make an reproducible issue :)

The problem is that the browser name starts with a capital C, try chrome instead of Chrome. I'll can make a fix for that in the next release.

**Comment by AlanCodega** [comment]
sorry my fault 😅 it was intentionally.
Great, now it's works smooth :)
Many thanks for your support!
Tak su mikke!
