### ISSUE TITLE
Error on using "firstParty" Option in version 27.3.0

### ISSUE THREAD

**Issue by dkd-bismo** [sitespeedio/sitespeed.io#3822]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

local-url

### What are you trying to accomplish

I am trying to run a sitespeed test with "firstParty" option in my config.json. But there is certainly an error / bug coming after I ran the test.

`ERROR: TypeError: options.firstParty.test is not a function
    at AssetsAggregator.addToAggregate (file:///usr/src/app/lib/plugins/assets/aggregator.js:57:53)
    at AssetsPlugin.processMessage (file:///usr/src/app/lib/plugins/assets/index.js:36:31)
    at file:///usr/src/app/lib/core/queueHandler.js:215:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:476:21)`

The option works fine with the version 26. But there is no any notice or instructions for the newest update.

### What browser did you use?

Chrome, Firefox

### How to reproduce

```shell
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:27.3.0 --config config/sitespeed/config.json <url>

Here is the code in config.json:
{
	"name": "sitespeed.io test",
	"outputFolder": "temp/sitespeed",
	"firstParty": ".*<url>*",
	"summary-detail": true,
	"gzipHAR": true,
	"budget": {
		"configPath": "/sitespeed.io/config/sitespeed/budget.json",
		"output": "junit"
	},
	"browsertime": {
		"browser": "chrome",
		"cpu": false,
		"visualMetrics": true,
		"visualElements": true,
		"video": false,
		"chrome": {
			"collectConsoleLog": true,
			"enableTraceScreenshots": true,
			"includeResponseBodies": "html"
		},
		"cookie": "klaro=%7B%22typo3FeCookie%22%3Atrue%2C%22overlay%20configurator%22%3Afalse%2C%22youtube%22%3Afalse%2C%22ga4%22%3Afalse%7D"
	},
	"axe": {
		"enable": false
	},
	"html": {
		"showAllWaterfallSummary": true
	},
	"sustainable": {
		"enable": false
	}
}



Note: we are using local url for testing. The url is accessible. It works fine with version 26
```

### Relevant log output

```shell
`ERROR: TypeError: options.firstParty.test is not a function
    at AssetsAggregator.addToAggregate (file:///usr/src/app/lib/plugins/assets/aggregator.js:57:53)
    at AssetsPlugin.processMessage (file:///usr/src/app/lib/plugins/assets/index.js:36:31)
    at file:///usr/src/app/lib/core/queueHandler.js:215:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:476:21)`
```

**Comment by soulgalore** [comment]
Hi @dkd-bismo thanks for reporting, I'll have a look tonight.

**Comment by soulgalore** [comment]
Hi @dkd-bismo I just released 27.3.1 please verify when you have time that it works in that release!

**Comment by websi** [comment]
With the latest release 29.7.0 we have no problems anymore.

**Comment by soulgalore** [comment]
Thanks
