### ISSUE TITLE
Crawling does not start

### ISSUE THREAD

**Issue by MartinWolfert** [sitespeedio/sitespeed.io#3828]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://sitespeed.martin-wolfert.de

### What are you trying to accomplish

I want to implement crawling in my sitespeed runs (via bash script on the shell)  and added "-d2" parameter

sitespeed.io -n 3 -b chrome --browsertime.visualMetrics https://destination.de --xvfb --connectivity.engine throttle -c cable ${INFLUX} ${SUSTAINABLE} **-d2** --gzipHAR

I installed Sitespeed.io on Ubuntu, using your prebuilt script from https://www.sitespeed.io/documentation/sitespeed.io/installation/

### What browser did you use?

Chrome

### How to reproduce

```shell
Not reproducable from your side as you would need shell access on my cloud server
Removing the "-d2" parameter, the script runs smoothly.
```

### Relevant log output

```shell
sitespeedio@sitespeed:~$ /opt/sitespeed/bin/run-sitespeed.sh
[2023-05-03 13:48:08] INFO: Versions OS: linux 5.15.0-69-generic nodejs: v14.21.3 sitespeed.io: 27.3.0 browsertime: 17.8.0 coach: 7.1.3
Couldn't load plugin crawler: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/support/util' imported from /home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/crawler/index.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'crawler' imported from /home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/core/pluginLoader.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/esm/translators.js:118:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at loadPlugins (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/core/pluginLoader.js:76:37) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by soulgalore** [comment]
Hi @MartinWolfert can you try upgrading to [sitespeed.io  27.3.1](https://github.com/sitespeedio/sitespeed.io/blob/main/CHANGELOG.md#2731---2023-04-28), that should be fixed there. 

Best
Peter

**Comment by MartinWolfert** [comment]
Hi @soulgalore,
worked out! ;)

Thanks from Germany!
