### ISSUE TITLE
Help troubleshoot/debug steps

### ISSUE THREAD

**Issue by PedroMSantosD** [sitespeedio/sitespeed.io#3835]
### Your question

Hi,
can you get guidance on how to troubleshoot; properly document an issue I'm having using latest sitespeed docker image 27.5.1 on google cloud?

Container parameters And received error follows, along with a screenshot of the report on the storage bucket highlighting the error.

Maybe I'm missing a parameter or a requirement I'm not aware of? Maybe proper documentation/ troubleshooting steps can be provided ?
![image](https://github.com/sitespeedio/sitespeed.io/assets/17711131/d02da55b-5580-42ef-b05e-6d6dbf65fb0a)

Container properties:
```
Containers:
  91c8c3e97c55ec9:
    Container ID:  containerd://145a4cc857b76b9b1d2b212fed4c8f59edffce06d78d5bd988c4af1d0e928f9c
    Image:         sitespeedio/sitespeed.io:27.5.1
    Image ID:      docker.io/sitespeedio/sitespeed.io@sha256:0e72973c7aeaf4d894b38b8f444a756eedcf692fd031504dd9acf09392e27790
    Port:          <none>
    Host Port:     <none>
    Args:
      --chrome.includeResponseBodies
      --gzipHAR
      --visualMetrics
      true
      --visualMetricsPerceptual
      true
      --visualMetricsContentful
      true
      --slug
      Ontario-Desktop
      --firstParty
      .*.somedomain.eu/mypage.*
      --graphite.annotationScreenshot
      --graphite.annotationTag
      desktop
      --graphite.host
      graphite
      --graphite.includeQueryParams
      true
      --graphite.namespace
      sitespeed_io.Ontario-Desktop
      --gcs.projectID
      somegcloudproject-12345
      --gcs.key
      /sitespeed.io/secrets/container_key.json
      --gcs.bucketname
      somegcloudbucket
      --gcs.removeLocalResult
      true
      --resultBaseURL
      https://storage.googleapis.com/somegcloudbucket
      --browser
      chrome
      --browsertime.connectivity.profile
      native
      --browsertime.viewPort
      1366x708
      --browsertime.requestheader
      sitespeed:true
      --browsertime.pageLoadStrategy
      none
      https://www.somedomain.eu/mypage
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 09 May 2023 14:37:28 +0000
      Finished:     Tue, 09 May 2023 14:40:57 +0000

```

error message:
```
root@vml-22940:/code# kubectl -n ssio logs -f desktoptest-2rv9c
Google Chrome 113.0.5672.63
Mozilla Firefox 112.0
Microsoft Edge 112.0.1722.64
[2023-05-09 14:37:29] INFO: Versions OS: linux 5.15.65+ nodejs: v18.14.2 sitespeed.io: 27.5.1 browsertime: 17.9.0 coach: 7.1.3
[2023-05-09 14:37:29] INFO: Running tests using Chrome - 3 iteration(s)
[2023-05-09 14:37:31] INFO: Testing url https://www.somedomain.eu/mypage iteration 1
[2023-05-09 14:38:20] INFO: Take after page complete check screenshot
[2023-05-09 14:38:23] INFO: Take cumulative layout shift screenshot
[2023-05-09 14:38:25] INFO: Take largest contentful paint screenshot
[2023-05-09 14:38:30] INFO: Use the visual metrics portable script
[2023-05-09 14:38:30] INFO: Get visual metrics from the video
[2023-05-09 14:38:39] ERROR: VisualMetrics failed to run Error: Command failed with exit code 1: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py --dir /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1 --video /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.mp4 --orange --force --renderignore 5 --json --viewport --viewportretries 60 --viewportminheight 100 --viewportminwidth 100 --perceptual --contentful -q 75 --logfile /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.visualmetrics.log -vvv
ffmpeg version 5.1.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:22.47, start: 0.000000, bitrate: 80 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1366x708, 76 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1366x708, q=2-31, 200 kb/s, 30 fps, 30 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 png
[image2 @ 0x74fde40] The specified filename '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1/viewport.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x74fde40] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.39x
video:24kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 5.1.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:22.47, start: 0.000000, bitrate: 80 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1366x708, 76 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1/viewport.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1366x708, q=2-31, 200 kb/s, 30 fps, 30 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 png
[image2 @ 0x74fde40] The specified filename '/sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1/viewport.png' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0x74fde40] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.39x
video:24kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    at makeError (file:///usr/src/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/src/app/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/visualMetrics.js:129:20)
    at async getVideoMetrics (file:///usr/src/app/node_modules/browsertime/lib/video/postprocessing/visualmetrics/getVideoMetrics.js:33:21)
    at async Video.postProcessing (file:///usr/src/app/node_modules/browsertime/lib/video/video.js:90:22)
    at async Iteration.run (file:///usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:300:34)
    at async Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-05-09 14:38:39] ERROR: Log from VisualMetrics: 14:38:32.017 - Processing frames from video /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.mp4 to /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1
14:38:32.221 - Extracting frames from /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/video/1.mp4 to /sitespeed.io/sitespeed-result/Ontario-Desktop/2023-05-09-14-37-29/pages/www_somedomain_eu/mypage/data/filmstrip/1
14:38:39.773 - module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1921, in main
    metrics = calculate_visual_metrics(
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1235, in calculate_visual_metrics
    value, value_progress = calculate_perceptual_speed_index(progress, dirs)
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1478, in calculate_perceptual_speed_index
    ssim_1 = compute_ssim(first_paint_frame, target_frame)
  File "/usr/local/lib/python3.10/dist-packages/ssim/__init__.py", line 23, in compute_ssim
    return SSIM(image1, gaussian_kernel_1d).ssim_value(image2)
  File "/usr/local/lib/python3.10/dist-packages/ssim/ssimlib.py", line 107, in __init__
    self.img = SSIMImage(img, gaussian_kernel_1d, size)
  File "/usr/local/lib/python3.10/dist-packages/ssim/ssimlib.py", line 60, in __init__
    self.img_gray, self.img_alpha = to_grayscale(self.img)
  File "/usr/local/lib/python3.10/dist-packages/ssim/utils.py", line 40, in to_grayscale
    gray = numpy.asarray(ImageOps.grayscale(img)).astype(numpy.float)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

**Comment by soulgalore** [comment]
Hi @PedroMSantosD thanks for creating the issue and including the log! Visual Metrics is the tool that analyse the video and get the metrics, we can turn on the specific visual metrics log but usually this is symptom of something else that goes wrong. 


Do you get any screenshots/videos can you see that the web site has been accessed? Does is look correct? Best way would be if you could supply the original video that breaks visual metrics, look for `--videoParams.keepOriginalVideo` in  https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#what-else-you-can-do 

If you can supply that, it's easier to troubleshoot/reproduce on my side.

Thanks!
Peter

**Comment by PedroMSantosD** [comment]
Hi @soulgalore , Thanks for your prompt reply;
 I have executed the check with the documented flag;
```
      --browsertime.videoParams.keepOriginalVideo
      true
```
The error persists, and I get this list of videos, non of them matching the 'original' suffix commented on the documentation

```
root@vml-22940:/code# gsutil ls gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/assets.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/detailed.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/domains.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/help.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/index.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/settings.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/toplist.html
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/css/
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/img/
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/js/
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/

root@vml-22940:/code# gsutil ls gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/1.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/1.mp4.failed.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/1.visualmetrics.log
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/2.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/2.mp4.failed.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/2.visualmetrics.log
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/3.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/3.mp4.failed.mp4
gs://somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/data/video/3.visualmetrics.log
```

[logs.txt](https://github.com/sitespeedio/sitespeed.io/files/11439866/logs.txt)
[podConfig.txt](https://github.com/sitespeedio/sitespeed.io/files/11439867/podConfig.txt)

execution logs (attached logs.txt):
updated container parameters (attached parameters.txt)

do you think any of those videos might be useful to you?

Kindly note that 'report' page shows a video that runs without issues on my browser:
https://storage.googleapis.com/somegcloudbucket/Ontario-Desktop/2023-05-10-08-26-30/pages/www_somedomain_eu/index.html#video

**Comment by PedroMSantosD** [comment]
for sake of completenes,
tested version v26.1.0: runs ok
tested version v27.0.0: fails
same nature of error:
```
[2023-05-10 13:52:48] ERROR: Could not run Visual Metrics Error: Command failed with exit code 1: python /usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py --dir /sitespeed.io/sitespeed-result/Ontario-Iphone14/2023-05-10-13-51-37/pages/www_bodog_eu/data/filmstrip/3 --video /sitespeed.io/sitespeed-result/Ontario-Iphone14/2023-05-10-13-51-37/pages/www_bodog_eu/data/video/3.mp4 --orange --force --renderignore 5 --json --viewport --viewportretries 60 --viewportminheight 100 --viewportminwidth 100 --perceptual --contentful -q 75 --logfile /sitespeed.io/sitespeed-result/Ontario-
```
tested version 27.6.1
still errs.

**Comment by soulgalore** [comment]
Hi @PedroMSantosD in 27 we introduced a new version of the Visual Metrics script that do not use ImageMagick, I think it's a bug there. I need the original video though to fix it. 

If I run like this:
`docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.6.1 https://www.sitespeed.io/ --browsertime.videoParams.keepOriginalVideo true -n 1` the original file ends up here:
<img width="812" alt="Screenshot 2023-05-10 at 21 16 23" src="https://github.com/sitespeedio/sitespeed.io/assets/540757/d3b7df63-0149-4cb0-b077-5adff4b4cc6e">

But I wonder then if the 1.mp4.failed.mp4 is the one I can use. I could't access the Google storage, got a "The specified bucket does not exist".

**Comment by PedroMSantosD** [comment]
Hi, I was trying to mask the original details. Kindly use the links in videofiles for download; should be publicly available.
[gcplinks.txt](https://github.com/sitespeedio/sitespeed.io/files/11449671/gcplinks.txt)

Mind letting me know once fixed, so I can remove the attachement?

Best,

**Comment by soulgalore** [comment]
Done thank you @PedroMSantosD

**Comment by PedroMSantosD** [comment]
Do you know if the dockerfile that builds https://hub.docker.com/r/sitespeedio/sitespeed.io/
has been updated to reflect the breaking changes involved on v27.x ?

**Comment by soulgalore** [comment]
Hi @PedroMSantosD not sure what you mean? It works like this: we have a GitHub action that builds the container on releases and add the correct tag and push it to the Docker hub.

**Comment by soulgalore** [comment]
Ah I see. Yep it was added in https://github.com/sitespeedio/docker-visualmetrics-deps/commit/7dc5ecbde976792dff9bf688159081f52868f1e7 . We continuously run tests with the official docker version and there it works, so I don't think that is the issue with missing dependencies.

If you have ImageMagick installed you can still use the old version of Visual Metrics with the switch: `--browsertime.visualMetricsPortable false` - I think I missed pushing the update to the repo were I removed ImageMagick but I get feeling its missing from the container. I'll check tonight that all latest version is pushed.

**Comment by PedroMSantosD** [comment]
Thanks, I am at loss with this issue. If there are any tests you need my helping with, just let me know. I'll run a quick test with recommended switch and latest sitespeed.io; I believe I saw it on the image from dockerhub; still it is pretty strange.

**Comment by soulgalore** [comment]
I'll release a new version tomorrow of the container where I verified that that ImageMagick is included, then you can use the switch and see check if it works. I'll ping the issue when it'd done.

**Comment by gmierz** [comment]
Hi @soulgalore, sorry for the delayed response!

Based on the logs in the first comment, it looks like it's an issue with pyssim:
```
  File "/usr/src/app/node_modules/browsertime/browsertime/visualmetrics-portable.py", line 1478, in calculate_perceptual_speed_index
    ssim_1 = compute_ssim(first_paint_frame, target_frame)
  File "/usr/local/lib/python3.10/dist-packages/ssim/__init__.py", line 23, in compute_ssim
    return SSIM(image1, gaussian_kernel_1d).ssim_value(image2)
  File "/usr/local/lib/python3.10/dist-packages/ssim/ssimlib.py", line 107, in __init__
    self.img = SSIMImage(img, gaussian_kernel_1d, size)
  File "/usr/local/lib/python3.10/dist-packages/ssim/ssimlib.py", line 60, in __init__
    self.img_gray, self.img_alpha = to_grayscale(self.img)
  File "/usr/local/lib/python3.10/dist-packages/ssim/utils.py", line 40, in to_grayscale
    gray = numpy.asarray(ImageOps.grayscale(img)).astype(numpy.float)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

This is likely related to using Python 3.10+ which forces us to upgrade a few packages, and dependencies. Here's the pinned versions we use on 3.7-3.9: https://searchfox.org/mozilla-central/rev/0accfbfb0381e431651b40065c0e08c249100fba/testing/mozharness/mozharness/mozilla/testing/raptor.py#1211-1230

We've only tested these with Python 3.7-3.9, and it's unknown if those pinned versions for 3.8+ would work for 3.10.

**Comment by gmierz** [comment]
@PedroMSantosD if you can, I recommend trying with an older version of Python (3.7-3.9) to see if the original issue still persists.

**Comment by soulgalore** [comment]
Hello @PedroMSantosD the good news is that I could reproduce your issue in 27.6.2 in the Docker container, by copying your video and running the script manually. I released 27.6.3 earlier today with updated dependencies (updated the Ubuntu base image, and re-installed everything) and there it worked for me, so please try to upgrade to 27.6.3.

Best

Peter
