### ISSUE TITLE
ECONNREFUSED when element not found

### ISSUE THREAD

**Issue by srvraja** [sitespeedio/sitespeed.io#3847]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://demoqa.com/

### What are you trying to accomplish

I am trying to run a scripted journey where it is trying to perform the operation in the 'not found element.' Tried for 3 iteration.
In the first iteration, it failed with the error element not found and continued to 2nd iteration and it got failed immediately after launching the 2nd iteration. Below is the used version and followed by the reported error. Also attached the script for your reference.
[trial_journey_issue.txt](https://github.com/sitespeedio/sitespeed.io/files/11488871/trial_journey_issue.txt)

INFO: Versions OS: win32 10.0.14393 nodejs: v16.15.0 sitespeed.io: 25.7.3 browsertime: ^16.13.3 coach: 7.1.2
[2023-05-16 13:34:50] INFO: Running tests using Chrome - 3 iteration(s)

Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:54328
    at ClientRequest.<anonymous> (C:\SitespeedioMain\sitespeed.io-main\node_modules\selenium-webdriver\http\index.js:294:15)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### What browser did you use?

Chrome

### How to reproduce

```shell
Please use the attached script to reproduce
```

### Relevant log output

```shell
INFO: Versions OS: win32 10.0.14393 nodejs: v16.15.0 sitespeed.io: 25.7.3 browsertime: ^16.13.3 coach: 7.1.2
[2023-05-16 13:34:50] INFO: Running tests using Chrome - 3 iteration(s)


[2023-05-16 13:28:53] ERROR: Element by xpath //*[@id="onetrust-accept-btns-handlers"] was not located in 10000 ms
[2023-05-16 13:28:53] ERROR: Error: Element by xpath //*[@id="onetrust-accept-btns-handlers"] was not located in 10000 ms
    at Wait.byXpath (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\command\wait.js:55:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (C:\Sitespeedio\sitespeed-script\1.js:39:4)
    at async C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\run.js:7:9
    at async Iteration.run (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\iteration.js:223:9)
    at async Engine.runByScript (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\index.js:270:20)
    at async Object.analyzeUrl (C:\SitespeedioMain\sitespeed.io-main\lib\plugins\browsertime\analyzer.js:171:21)
    at async Object.processMessage (C:\SitespeedioMain\sitespeed.io-main\lib\plugins\browsertime\index.js:150:26)


     TTFB: 217ms DOMContentLoaded: 1.23s firstPaint: 738ms FCP: 738ms LCP: 1.24s Load: 2.32s TBT: 401ms CLS:0.0093

DevTools listening on ws://127.0.0.1:9226/devtools/browser/094625b4-326f-4519-b580-d86adde6ae19
[1604:4808:0516/132854.101:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[1604:4808:0516/132854.103:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"
[1604:4808:0516/132854.104:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[1604:4808:0516/132854.111:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[1604:4808:0516/132854.111:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[1604:4808:0516/132854.112:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[1604:4808:0516/132854.113:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[1604:4808:0516/132854.113:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[1604:4808:0516/132854.115:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[1604:4808:0516/132854.115:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"
[2023-05-16 13:28:54] INFO: Start to measure ek_homepage_trial
[2023-05-16 13:28:54] INFO: Navigating to url https://www.dummy.com/ iteration 2
C:\SitespeedioMain\sitespeed.io-main\node_modules\selenium-webdriver\http\index.js:294
      onError(new Error(message))
              ^

Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:54328
    at ClientRequest.<anonymous> (C:\SitespeedioMain\sitespeed.io-main\node_modules\selenium-webdriver\http\index.js:294:15)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by srvraja** [comment]
@soulgalore 

Thanks for your time.

I downloaded the latest version(sitespeed v27.6.4, Node.js v18.16.0) and got the below error. Are any other configurations missing?

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at open (node:internal/fs/promises:538:10)
    at readFile (node:internal/fs/promises:909:20)
    at parseCommandLine (file:///C:/SitespeedioMain/sitespeed.io-main/lib/cli/cli.js:2050:13)
    at start (file:///C:/SitespeedioMain/sitespeed.io-main/bin/sitespeed.js:119:22)
    at file:///C:/SitespeedioMain/sitespeed.io-main/bin/sitespeed.js:178:7 {
  code: 'ERR_INVALID_URL_SCHEME'
}

**Comment by srvraja** [comment]
@soulgalore 

the above issue got resolved when i renamed the scripted file from demo.js to demo.cjs.

After execution, i am getting the same error with the updated version.

[2023-05-22 10:14:30] INFO: Versions OS: win32 10.0.14393 nodejs: v18.16.0 sitespeed.io: 25.7.3 browsertime: ^16.13.3 coach: 7.1.2
[2023-05-22 10:14:31] INFO: Running tests using Chrome - 3 iteration(s)
[4300:2448:0522/101431.865:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[4300:2448:0522/101431.881:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"

DevTools listening on ws://127.0.0.1:9222/devtools/browser/9ac46f47-6a57-469c-b6a0-073210ec7d83
[4300:2448:0522/101432.029:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[4300:2448:0522/101432.047:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[4300:2448:0522/101432.053:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[4300:2448:0522/101432.055:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[4300:2448:0522/101432.063:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[4300:2448:0522/101432.079:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[4300:2448:0522/101432.080:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[4300:2448:0522/101432.081:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"
[2023-05-22 10:14:32] INFO: Start to measure homepage_trial
[2023-05-22 10:14:32] INFO: Navigating to url https://www.dummy.com/ iteration 1
[2023-05-22 10:14:42] INFO: Take after page complete check screenshot
[2023-05-22 10:14:44] INFO: Take cumulative layout shift screenshot
[2023-05-22 10:14:46] INFO: Take largest contentful paint screenshot
[2023-05-22 10:14:49] INFO: Start to measure click_on_accept_button
[2023-05-22 10:14:49] ERROR: Couldn't execute script named CUSTOM error:JavascriptError: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=113.0.5672.127)
[2023-05-22 10:14:49] ERROR: Could not find element by xpath //*[@id="onetrust-accept-btns-handlers"]
[2023-05-22 10:14:49] ERROR: Error: Could not find element by xpath //*[@id="onetrust-accept-btns-handlers"]
    at Click.byXpathAndWait (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\command\click.js:159:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (C:\Sitespeedio\sitespeed-script\1.cjs:20:4)
    at async C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\run.js:7:9
    at async Iteration.run (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\iteration.js:223:9)
    at async Engine.runByScript (C:\SitespeedioMain\sitespeed.io-main\node_modules\browsertime\lib\core\engine\index.js:270:20)
    at async Object.analyzeUrl (C:\SitespeedioMain\sitespeed.io-main\lib\plugins\browsertime\analyzer.js:171:21)
    at async Object.processMessage (C:\SitespeedioMain\sitespeed.io-main\lib\plugins\browsertime\index.js:150:26)
[2023-05-22 10:14:49] INFO: https://www.dummy.com/ TTFB: 518ms DOMContentLoaded: 1.99s firstPaint: 1.43s FCP: 1.43s LCP: 1.65s Load: 3.01s TBT: 436ms CLS:0.0047
[2023-05-22 10:14:50] INFO: C:\Sitespeedio\sitespeed-script\1.cjs

DevTools listening on ws://127.0.0.1:9222/devtools/browser/ff1da3aa-36d9-4142-95ce-7d8ddc5f8aaa
[4360:520:0522/101450.835:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[4360:520:0522/101450.838:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[4360:520:0522/101450.839:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[4360:520:0522/101450.841:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[4360:520:0522/101450.842:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[4360:520:0522/101450.843:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[4360:520:0522/101450.844:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[4360:520:0522/101450.845:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"
[4360:520:0522/101450.960:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP cache.pack.google.com 127.0.0.1"
[4360:520:0522/101450.992:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP clients1.google.com 127.0.0.1"
[4360:520:0522/101450.998:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP update.googleapis.com 127.0.0.1"
[4360:520:0522/101451.101:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP redirector.gvt1.com 127.0.0.1"
[4360:520:0522/101451.108:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP laptop-updates.brave.com 127.0.0.1"
[4360:520:0522/101451.113:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP offlinepages-pa.googleapis.com 127.0.0.1"
[4360:520:0522/101451.115:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP edge.microsoft.com 127.0.0.1"
[4360:520:0522/101451.117:ERROR:host_mapping_rules.cc(146)] Failed parsing rule: "MAP optimizationguide-pa.googleapis.com 127.0.0.1"
[2023-05-22 10:14:51] INFO: Start to measure homepage_trial
[2023-05-22 10:14:51] INFO: Navigating to url https://www.dummy.com/ iteration 2
C:\SitespeedioMain\sitespeed.io-main\node_modules\selenium-webdriver\http\index.js:294
      onError(new Error(message))
              ^

Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:57652
    at ClientRequest.<anonymous> (C:\SitespeedioMain\sitespeed.io-main\node_modules\selenium-webdriver\http\index.js:294:15)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by TerryJLU** [comment]
![issue](https://github.com/sitespeedio/sitespeed.io/assets/19278622/8e2f9051-2cbf-4d3c-8a32-b165ad0c633d)
Face the same issue ，It is good with old version 26

**Comment by soulgalore** [comment]
Hi @TerryJLU hmm, I tried the same on a windows GitHub action and there it seems to work: https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/windows.yml#L29-L31

I see NodeJS 18.16.0, can you verify that it's the same version as in node.exe? I guess it is but just wanted to 100% sure.

**Comment by TerryJLU** [comment]
Yes  NodeJS 18.16.0

**Comment by srvraja** [comment]
@soulgalore , 

any chance of looking into 'Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:57652' where the execution got crashed when one of the elements not available in the rendered page?
You can use the attached script to reproduce it. It is happening with latest version as well.

Thanks for your time, please let me know if you need more information.

**Comment by soulgalore** [comment]
@srvraja let me try and add your script to the tests on GitHub action, so I also get that error.

**Comment by soulgalore** [comment]
I updated the PR to try to run with a global install to try to reproduce.

**Comment by soulgalore** [comment]
I could reproduce this on Windows in a GitHub action. When the element do not exists, I get a  ECONNREFUSED but I haven't been able to figure out why.

**Comment by sakpilot** [comment]
@soulgalore ,

Gone through the issue and fix proposed in 33.0.0. https://github.com/sitespeedio/sitespeed.io/issues/4078

Is this(3847) and 4078 issues related?

Thanks

**Comment by srvraja** [comment]
@soulgalore ,

Any luck to overcome this? 

Gone through the issue https://github.com/sitespeedio/sitespeed.io/issues/4078, will the error handling fix this?

Thanks

**Comment by soulgalore** [comment]
I'm not sure, this seems to only happens on Windows. I wonder if people are also seeing this using only Selenium or if it's something on our side? I'm having a problem fixing it since I do not have a windows machine.

**Comment by srvraja** [comment]
@soulgalore 
I have tested from Mac and RHEL8 instances, getting the same error if the object not found in the scripted journey. 

Thanks

**Comment by soulgalore** [comment]
So you get ECONNREFUSED? Ok can you share a minimal example script that I can use to reproduce? Thanks!

**Comment by srvraja** [comment]
Hi, Attaching a script which will do the following. I have tested this in Mac, getting the same ECONNREFUSED error.

1. Navigate to sitespeed.io site
2. click on brand logo with class name
3. click again on brand logo with wrong class name [This step is to simulate 'Trying to click an object which doesn't exist']
[issue_debug.js.zip](https://github.com/sitespeedio/sitespeed.io/files/14498102/issue_debug.js.zip)

**Comment by soulgalore** [comment]
Ah thank you @srvraja for taking the time to make the script! I'll have a look.

**Comment by soulgalore** [comment]
Hi @srvraja in your script you are throwing an error in the catch block, that's what is causing it. I can fix so we catch that better but I also think it's better not to re-throw. Mark your test as an error and then exit.
