### ISSUE TITLE
Error with logToFile param

### ISSUE THREAD

**Issue by guillermovidalf** [sitespeedio/sitespeed.io#3878]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.amazon.com/

### What are you trying to accomplish

Trying to use the latest. sitespeed version, I've added the logtofile parameter but I always receive the same error message. 

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --shm-size=4g --cpus=4 --rm sitespeedio/sitespeed.io:27.9.0-plus1 https://www.amazon.com/ --logToFile
```

### Relevant log output

```shell
Google Chrome 114.0.5735.106
Mozilla Firefox 114.0
Microsoft Edge 114.0.1823.43
TypeError: Cannot read properties of undefined (reading 'push')
    at addHandler (/usr/src/app/node_modules/intel/lib/logger.js:159:20)
    at configure (file:///usr/src/app/lib/core/logging.js:55:5)
    at run (file:///usr/src/app/lib/sitespeed.js:74:3)
    at async start (file:///usr/src/app/bin/sitespeed.js:132:22)
    at async file:///usr/src/app/bin/sitespeed.js:178:1
```

**Comment by soulgalore** [comment]
Hi @guillermovidalf thanks for creating the issue. This happened when we moved to ESM and there were no test case for it. I've added a test case and a fix, if it passes CI I'll release it later today. Thanks for reporting the bug!

**Comment by soulgalore** [comment]
I just released 27.9.1 that should fix this issue.

**Comment by guillermovidalf** [comment]
Thank you for your quick response!
I've tested it but logs are not being written. This is my test:
docker run --shm-size=4g --cpus=4 --rm -v /home/ec2-user/logReports:/logs sitespeedio/sitespeed.io:27.9.1-plus1 https://www.amazon.com/ --logToFile
Connecting to the running container, /logs folder is created but empty. After completing the test and killing the container, the mounted volume is also empty.

**Comment by soulgalore** [comment]
Hi @guillermovidalf the logs will come in the result folder, not _/logs_ (right now you cannot choose where the logs will end up). To get the logs you need to mount /sitespeed.io

For example if I run:
`docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:27.9.1 https://www.sitespeed.io/ -n 1 --logToFile` the file will be in sitespeed-result/www.sitespeed.io/2023-06-13-10-52-26/logs/sitespeed.io.log

**Comment by guillermovidalf** [comment]
It works!
Sorry, I did not understood the documentation.
Thank you

**Comment by soulgalore** [comment]
No problem, I'll improve the documentation for the next release.
