### ISSUE TITLE
Page Index Out of Range

### ISSUE THREAD

**Issue by divyachandrashekara** [sitespeedio/sitespeed.io#3883]
### Your question

Hi Team, We have created a custom JavaScript to measure the front end performance of the application. But the issue is we are getting “PageIndex out of range” error and report is not generated due to this error. Could you please let us know for known solutions on this error?

PFB the runtime snippet:
[2023-06-14 06:26:06] INFO: Take after page complete check screenshot
[2023-06-14 06:26:06] INFO: Take cumulative layout shift screenshot
[2023-06-14 06:26:07] INFO: Take largest contentful paint screenshot
[2023-06-14 06:26:08] INFO: Injecting navigationStart event in the trace log since we could not find any for the most active frame.
[2023-06-14 06:26:10] INFO: Get visual metrics from the video
[2023-06-14 06:26:16] INFO: Get visual metrics from the video
[2023-06-14 06:26:25] INFO: Get visual metrics from the video
[2023-06-14 06:26:28] ERROR: Could not add meta data to the HAR, miss page 2
[2023-06-14 06:26:28] ERROR: Could not find the right index 2 for har for url *****************************************************?browsertime_run=2
[2023-06-14 06:26:28] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:270:27)
[2023-06-14 06:26:32] INFO: HTML stored in /sitespeed.io/sitespeed-result/samplescript_June03_js/2023-06-14-06-24-46
Error: Errors while running:
Error: PageIndex out of range
    at start (file:///usr/src/app/bin/sitespeed.js:33:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:64:1

**Comment by QTSankarRajan** [comment]
@soulgalore  Can you please help me on the above error. We are facing this error when you logout of the application which is using Microsoft AD authentication

**Comment by divyachandrashekara** [comment]
Hi @soulgalore, Please find attached the script which we modified with dummy ULR since the application URL is private ad not accessible outside the client network.

Steps followed to execute the script:
1. Open CLI from sitespped configured path.
2. Execute the below command to run the script for one iteration. After the ‘SaveClocking’ operation, we are getting type error and logout is not being executed.
docker run  -v "%cd%:/sitespeed.io" sitespeed.iopoc:latest -b chrome SitespeedJS.js --multi -n 1

Sitespeed Version: sitespeed.io 27.0.0-alpha.2

[SitespeedJS.txt](https://github.com/sitespeedio/sitespeed.io/files/12301472/SitespeedJS.txt)

**Comment by soulgalore** [comment]
Usually that means that a navigation to a new page didn't happen. If you run the script and watch the browser, do the page navigate/work as you want it to work?

**Comment by divyachandrashekara** [comment]
@soulgalore, Yes, the script is working as expected. As you mentioned navigation to a new page will not happen at the step where we are getting error. Is there any known solution to resolve the error.

**Comment by soulgalore** [comment]
So how do your script work? :) It works as expected but you don't get a navigation? Can you show me the steps and what you are trying to measure?

**Comment by divyachandrashekara** [comment]
@soulgalore, Please find below the workflow:
1. Launch
2. Login
3. Click on a tab
4. Click on Save - here the save operation is completed successfully after save we will not navigate to new window on the same window we get a validation message . Immediately after this we are getting Type error. For javascript to execute successfully is it necessary to navigate to a new page every time ?

**Comment by divyachandrashekara** [comment]
@soulgalore issue is resolved
