### ISSUE TITLE
ERROR: preScript is not a function

### ISSUE THREAD

**Issue by MartinWolfert** [sitespeedio/sitespeed.io#3886]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://sitespeed.martin-wolfert.de

### What are you trying to accomplish

Hi,

I tried the preScript stuff as described in https://www.sitespeed.io/documentation/sitespeed.io/prepostscript/
The following call I use for testing:

/home/sitespeedio/.npm-packages/bin/sitespeed.io -n 3 -b chrome --browsertime.visualMetrics --preScript /opt/sitespeed/bin/domain-testlogin.sh https://domain.de --xvfb --connectivity.engine throttle -c cable --influxdb.host=localhost --influxdb.database=webdetest --influxdb.annotationScreenshot true --resultBaseURL https://sitespeed.martin-wolfert.de/sitespeed-result --sustainable.enable --sustainable.useGreenWebHostingAPI true --sustainable.model swd --sustainable.pageViews 4000000 --gzipHAR --axe.enable

Log output see below ... 

### What browser did you use?

Chrome

### How to reproduce

```shell
You can not reproduce my yourselves because the stuff runs on a protected server
```

### Relevant log output

```shell
[2023-06-16 08:55:15] INFO: Versions OS: linux 5.15.0-72-generic nodejs: v14.21.3 sitespeed.io: 27.4.1 browsertime: 17.9.0 coach: 7.1.3
[2023-06-16 08:55:15] INFO: Axe plugin activated
[2023-06-16 08:55:15] INFO: Use the sustainable web plugin with model swd
[2023-06-16 08:55:16] INFO: Changing network interfaces needs sudo rights. Setting connectivity profile cable
[2023-06-16 08:55:16] INFO: Running tests using Chrome - 3 iteration(s)
[2023-06-16 08:55:17] ERROR: TypeError: preScript is not a function
    at Iteration.run (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:232:15)
    at async Engine.runByScript (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:162:26)
[2023-06-16 08:55:17] ERROR: No data to collect
[2023-06-16 08:55:18] ERROR: TypeError: preScript is not a function
    at Iteration.run (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:232:15)
    at async Engine.runByScript (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:162:26)
[2023-06-16 08:55:18] ERROR: No data to collect
[2023-06-16 08:55:19] ERROR: TypeError: preScript is not a function
    at Iteration.run (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:232:15)
    at async Engine.runByScript (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:162:26)
[2023-06-16 08:55:19] ERROR: No data to collect
[2023-06-16 08:55:19] ERROR: Caught error from Browsertime TypeError: Cannot read property 'alias' of undefined
    at BrowsertimePlugin.processMessage (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:175:40)
[2023-06-16 08:55:19] ERROR: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SustainablePlugin.processMessage (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/plugins/sustainable/index.js:225:32)
    at file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:215:32
    at drainItem (/home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain (/home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at processImmediate (internal/timers.js:464:21)
[2023-06-16 08:55:20] INFO: HTML stored in /opt/sitespeed/sitespeed-result/web.de/2023-06-16-08-55-15
[2023-06-16 08:55:20] INFO: Find the result at https://sitespeed.martin-wolfert.de/sitespeed-result/web.de/2023-06-16-08-55-15/index.html
Error: Errors while running:
TypeError: Cannot read property 'alias' of undefined
Rejected {
  "uuid": "7de23d6d-73d0-4fc3-a2e1-ead4ce293ca7",
  "type": "sitespeedio.summarize",
  "timestamp": "2023-06-16T08:55:19+02:00",
  "source": "queueHandler",
  "data": "{...}"
} for plugin: sustainable
{}
    at start (file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/bin/sitespeed.js:126:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
    at async file:///home/sitespeedio/.npm-packages/lib/node_modules/sitespeed.io/bin/sitespeed.js:158:1
```

**Comment by PedroMSantosD** [comment]
not sure on your issue, but you are passing a .sh file as --preScript; I'm under the impression it should be a .mjs file.

`--preScript /opt/sitespeed/bin/domain-testlogin.sh`

**Comment by soulgalore** [comment]
Hi @MartinWolfert can you share the structure of the preScript?

**Comment by MartinWolfert** [comment]
@PedroMSantosD: sorry for the late response ... and yes, you're right it should be an .mjs file.
So @soulgalore, I get some other errors back. I think these errors are due to the fact that the contents of the script do not match the parameters of the request.
I will work on it and report back here if I continue to have problems with that
