### ISSUE TITLE
Continuously getting PageIndex out of range

### ISSUE THREAD

**Issue by mahesharravally** [sitespeedio/sitespeed.io#3907]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

I'm unable to share

### What are you trying to accomplish

Even the script is fine for JS file followed all the steps properly but we are unable to see the results for few pages and console error is like PageIndex out of range
![Screenshot (309)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/f69da576-a4bb-44ce-ba8b-454069acef95)

for example if i have 6 test cases with name T01 to T06  all are  running properly but But the results are there for only T01 to T04 not other two like T05 and T06 have not found with an errorPageIndex out of range

please see below

[2023-07-17 13:10:03] ERROR: Could not find the right index 6 for har for url https://formbuilder.armtest01.abb.com/applications/64acf15cc1f57807de253b78/pages/64acf15cc1f57807de253b9f?RecipeAction=Edit
[2023-07-17 13:10:03] ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range
    at module.exports.pickAPage (C:\Users\INARMAH2\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\coach-core\lib\har\harCutter.js:18:11)
    at pickAPage (C:\Users\INARMAH2\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\coach-core\lib\index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///C:/Users/INARMAH2/AppData/Roaming/npm/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:271:29)
[2023-07-17 13:10:03] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (C:\Users\INARMAH2\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\coach-core\lib\har\harCutter.js:18:11)
    at pickAPage (C:\Users\INARMAH2\AppData\Roaming\npm\node_modules\sitespeed.io\node_modules\coach-core\lib\index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///C:/Users/INARMAH2/AppData/Roaming/npm/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:488:33)
[2023-07-17 13:10:03] INFO: The server responded with a 401 status code for https://lens.armtest01.abb.com/
[2023-07-17 13:10:03] INFO: The server responded with a 401 status code for https://formbuilder.armtest01.abb.com/api/v1/applications/ne...
[2023-07-17 13:10:03] INFO: The server responded with a 404 status code for https://formbuilder.armtest01.abb.com/user/abb-favicon.ico
[2023-07-17 13:10:03] INFO: The server responded with a 404 status code for https://formbuilder.armtest01.abb.com/applications/64acf15cc...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=undefined:300,400,50...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=ABB+Voice:300,400,50...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=undefined:300,400,50...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=ABB+Voice:300,400,50...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=ABB+Voice:300,400,50...
[2023-07-17 13:10:03] INFO: The server responded with a 400 status code for https://fonts.googleapis.com/css?family=ABB+Voice:300,400,50...
[2023-07-17 13:10:05] INFO: HTML stored in C:\Users\INARMAH2\AppData\Roaming\npm\node_modules\sitespeed.io\sitespeed-result\ARM_Search_Recipe_List_Edit_Click_js\2023-07-17-13-07-36
Error: Errors while running:
Could not get the right page for the HAR, the page is missing
Error: PageIndex out of range
    at start (file:///C:/Users/INARMAH2/AppData/Roaming/npm/node_modules/sitespeed.io/bin/sitespeed.js:146:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///C:/Users/INARMAH2/AppData/Roaming/npm/node_modules/sitespeed.io/bin/sitespeed.js:178:1

please observe screen shots one of the page with test case id T07 is printing the url name with not found HAR file
![Screenshot (310)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/d7cc3147-eb98-4820-b8a9-5b076e87c119)
![Screenshot (311)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/d5e928fc-0bbe-475d-ba49-48c0669aee3f)
![Screenshot (312)](https://github.com/sitespeedio/sitespeed.io/assets/134609751/f423a121-f159-48a7-88d8-d27e387c95f4)

### What browser did you use?

Chrome

### How to reproduce

```shell
Installed Nodejs
Npm
selenium driver 
with git bash to use command line 
INARMAH2@IN-L-7441844 MINGW64 ~/AppData/Roaming/npm/node_modules/sitespeed.io
$ bin\\sitespeed.js C:\\Users\\INARMAH2\\Downloads\\ARM_Search_Recipe_List_Edit_Click.js --chrome.chromedriverPath C:\\Users\\INARMAH2\\Downloads\\chromedriver_win32\\chromedriver.exe --multi -b chrome -n 1
with script with 7seven test cases from T01 to T07 
I'm unable to see T07 Test case  with some error called pageindex out of range
```

**Comment by soulgalore** [comment]
Hi @mahesharravally "PageIndex out of range" usually means that the script didn't navigate to a new page. If you look at the browser when you run your test, can you see that the browser navigate the way you want?

**Comment by soulgalore** [comment]
Never got a response so closing.
