### ISSUE TITLE
[Bug]: Chromium Error: Missing X server or $DISPLAY with --xvfb false

### ISSUE THREAD

**Issue by polarnik** [sitespeedio/sitespeed.io#3910]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://sitespeed.io

### What are you trying to accomplish

I try to start sitespeed with the "default" options

### What browser did you use?

Chrome

### How to reproduce

1) Check out the documentation about the xvfb param:

- https://www.sitespeed.io/documentation/sitespeed.io/configuration/
```
--browsertime.xvfb, --xvfb    Start xvfb before the browser is started  [boolean] [default: false]
```

- https://github.com/sitespeedio/sitespeed.io/blob/main/lib/cli/cli.js#L246-L251
```
    .option('browsertime.xvfb', {
      alias: 'xvfb',
      type: 'boolean',
      default: false,
      describe: 'Start xvfb before the browser is started'
    })
```

- https://github.com/sitespeedio/sitespeed.io/blob/main/docs/documentation/browsertime/configuration/config.md?plain=1
```
--xvfb       Start xvfb before the browser is started  [boolean] [default: false]
```

2) Start the sitespeed docker-file without any configs. 

```bash
docker run --rm \
  -v "$(pwd)/build/sitespeed.io:/sitespeed.io" \
  sitespeedio/sitespeed.io:28.2.0-plus1 \
  --outputFolder "/sitespeed.io/board1" \
  --debugMessages true \
  -vvv \
  --browsertime.iterations 1 \
  --multi \
  --slug "board1" \
  "https://sitespeed.io"
```

We will see `"xvfb": true,`
```
[2023-07-19 06:13:26] DEBUG: [browsertime] Running with options: {
  "scripts": [],
  "iterations": 1,
  "delay": 0,
  "videoParams": {
    "framerate": 30,
    "crf": 23,
    "addTimer": true,
    "convert": true,
    "keepOriginalVideo": false,
    "filmstripFullSize": false,
    "filmstripQuality": 75,
    "createFilmstrip": true,
    "thumbsize": 400
  },
  "statistics": true,
  "browser": "chrome",
  "connectivity": {
    "profile": "native",
    "engine": "external"
  },
  "screenshot": true,
  "screenshotLCP": true,
  "screenshotLS": true,
  "screenshotParams": {
    "type": "png",
    "png": {
      "compressionLevel": 6
    },
    "jpg": {
      "quality": 80
    },
    "maxSize": 2000
  },
  "viewPort": "1366x708",
  "xvfbParams": {
    "display": 99
  },
  "docker": "true",
  "xvfb": true,
  "xvfb-params": {
    "display": 99
  },
  "spa": false,
  "debug": false,
  "limitedRunData": true,
  "limited-run-data": true,
  "android": {
    "gnirehtet": false,
    "rooted": false,
    "batteryTemperatureWaitTimeInSeconds": 120,
    "battery-temperature-wait-time-in-seconds": 120,
    "verifyNetwork": false,
    "verify-network": false
  },
  "gnirehtet": false,
  "timeouts": {
    "pageCompleteCheck": 120000,
    "page-complete-check": 120000
  },
  "pageCompleteWaitTime": 5000,
  "page-complete-wait-time": 5000,
  "pageCompleteCheckInactivity": false,
  "page-complete-check-inactivity": false,
  "pageCompleteCheckPollTimeout": 1500,
  "page-complete-check-poll-timeout": 1500,
  "pageCompleteCheckStartWait": 500,
  "page-complete-check-start-wait": 500,
  "pageLoadStrategy": "none",
  "page-load-strategy": "none",
  "view-port": "1366x708",
  "visualMetricsPortable": true,
  "visual-metrics-portable": true,
  "scriptInput": {
    "longTask": 50
  },
  "script-input": {
    "long-task": 50
  },
  "video-params": {
    "framerate": 30,
    "crf": 23,
    "add-timer": true,
    "convert": true,
    "keep-original-video": false,
    "filmstrip-full-size": false,
    "filmstrip-quality": 75,
    "create-filmstrip": true,
    "thumbsize": 400
  },
  "cjs": false,
  "tcpdump": false,
  "firefox": {
    "includeResponseBodies": "none",
    "include-response-bodies": "none",
    "memoryReport": false,
    "memory-report": false,
    "memoryReportParams": {
      "minizeFirst": false
    },
    "memory-report-params": {
      "minize-first": false
    },
    "geckoProfiler": false,
    "gecko-profiler": false,
    "geckoProfilerParams": {
      "features": "js,stackwalk,leaf",
      "threads": "GeckoMain,Compositor,Renderer",
      "bufferSize": 1000000
    },
    "gecko-profiler-params": {
      "features": "js,stackwalk,leaf",
      "threads": "GeckoMain,Compositor,Renderer",
      "buffer-size": 1000000
    },
    "windowRecorder": false,
    "window-recorder": false,
    "disableSafeBrowsing": true,
    "disable-safe-browsing": true,
    "disableTrackingProtection": true,
    "disable-tracking-protection": true
  },
  "chrome": {
    "timeline": false,
    "cdp": {
      "performance": true
    },
    "ignoreCertificateErrors": true,
    "ignore-certificate-errors": true,
    "includeResponseBodies": "none",
    "include-response-bodies": "none"
  },
  "androidRooted": false,
  "android-rooted": false,
  "androidBatteryTemperatureWaitTimeInSeconds": 120,
  "android-battery-temperature-wait-time-in-seconds": 120,
  "androidVerifyNetwork": false,
  "android-verify-network": false,
  "safari": {
    "ios": false,
    "useTechnologyPreview": false,
    "use-technology-preview": false,
    "useSimulator": false,
    "use-simulator": false
  },
  "headless": false,
  "iqr": false,
  "preWarmServer": false,
  "pre-warm-server": false,
  "preWarmServerWaitTime": 5000,
  "pre-warm-server-wait-time": 5000,
  "screenshot-params": {
    "type": "png",
    "png": {
      "compression-level": 6
    },
    "jpg": {
      "quality": 80
    },
    "max-size": 2000
  },
  "video": true,
  "visualMetrics": true,
  "verbose": 3,
  "mobile": false,
  "screenshotType": "png",
  "coach": true,
  "resultDir": "/sitespeed.io/board1"
}
```

3) Create a json-config file with `  "xvfb": false,`
4) Start sitespeed with the config-file. Or start sitespeed with the param `--xvfb false`

chrome_debug.log:
```
[ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
[ERROR:env.cc(225)] The platform failed to initialize. Exiting.
```

The test doesn't work

### Relevant log output

chrome_debug.log:

```shell
[112:112:0719/063223.876591:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[112:112:0719/063223.877388:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
```

sitespeed log:
```shell
Error: Errors while running:
TypeError: Cannot read properties of undefined (reading 'alias')
    at start (file:///usr/src/app/bin/sitespeed.js:146:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:178:1
```

**Comment by soulgalore** [comment]
Hi @polarnik thank you for creating the issue! I think it's multiple things maybe in your issue? If xvfb do not work, Chrome can't start, and you usually get that in the sitespeed.io log, but it doesn't look that you get it and from the title I see that you get a Chromium error, in our ARM container we have Chromium so either it's that or the error we get is from Lighthouse? Can you share more from your log, preferable the full log so I can see more? 

Thanks 
Peter

**Comment by soulgalore** [comment]
Didn't get anything back so closing.
