### ISSUE TITLE
Upgrading project is launching error and I don't know how to fix it

### ISSUE THREAD

**Issue by fernandatenorio** [sitespeedio/sitespeed.io#3938]
### Your question

Hi
I am creating my performance project, and I am using another project to be my baseline. The problem is that this base project is using speedio version 17.2 and coach version 5.1.1. In my project I upgraded to speedio 26.1 and coach 7.1.2, but I am getting the following exception. The script is able to navigate through the application under test, start measuring, take the screenshot in the final page fully charged, but I guess when it does the measure.stop(), the exception is launched. Also the coach peformance score is 0 and red. In addition, I am able to run my project in speedio version 17.2 and coach version 5.1.1. Do you have any clue what might be happening?

[2023-08-11 18:58:42] INFO: Start to measure "page performance"
[2023-08-11 18:58:42] INFO: Could not set cookie because the URL is unknown
[2023-08-11 18:58:49] INFO: Take after page complete check screenshot
[2023-08-11 18:58:50] INFO: Take cumulative layout shift screenshot
[2023-08-11 18:58:50] ERROR: Couldn't execute script named HIGHLIGHT_LS error:JavascriptError: javascript error: entry.sources is not iterable
  (Session info: headless chrome=81.0.4044.113)
[2023-08-11 18:58:50] ERROR: JavascriptError: javascript error: entry.sources is not iterable
  (Session info: headless chrome=81.0.4044.113)
  (Session info: headless chrome=81.0.4044.113)
    at Object.throwDecodedError (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:740:17)
    at async SeleniumRunner.runScript (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:397:22)
    at async Measure.collect (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:417:7)

<img width="1134" alt="image" src="https://github.com/sitespeedio/coach/assets/13337748/91496990-b034-4cbb-bc5d-59376f9287c6">

**Comment by soulgalore** [comment]
Hi @fernandatenorio I think the problem is that Chromedriver (the webdriver that drivers Chrome( isn't compatible to your Chrome version (81). If you upgrade to a later Chrome version I think it will work.

Best
Peter
