### ISSUE TITLE
I get "ReferenceError: context is not defined" error when trying to access context from a different file

### ISSUE THREAD

**Issue by yourstoryteller** [sitespeedio/sitespeed.io#3948]
### Your question

My goal is to create a different JS file for storing methods. I'm unable to access context and commands from this file. Below is a sample code.
Can somebody please point out what wrong I'm doing?

app.js:
```
import { printContext } from "./pages/login.js";

export default async (context, commands) => {
    try {
        const webdriver = context.selenium.webdriver;
        const driver = context.selenium.driver;
        const By = webdriver.By;

        await commands.measure.start('Login');

        await printContext();

        await commands.measure.stop();

    } catch (e) {
        await commands.measure.stop();
        context.log.error('Error encountered - ' + e);
    }
};
```

login.js:
```
export async function printContext() {
    console.log(context);
}
```

Output:
```
PS C:\Users\shrad\Documents\Automation\sitespeed> docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io app.js --config=config.json --n=1
Google Chrome 115.0.5790.102
Mozilla Firefox 115.0
Microsoft Edge 115.0.1901.183
[2023-08-29 05:53:27] INFO: Versions OS: linux 5.15.90.4-microsoft-standard-WSL2 nodejs: v18.16.0 sitespeed.io: 29.1.2 browsertime: 17.14.1 coach: 7.2.1
[2023-08-29 05:53:28] INFO: Running tests using Chrome - 1 iteration(s)
[2023-08-29 05:53:29] INFO: Start to measure Login
[2023-08-29 05:53:31] INFO: Take after page complete check screenshot
[2023-08-29 05:53:31] INFO: Take cumulative layout shift screenshot
[2023-08-29 05:53:32] INFO: Take largest contentful paint screenshot
[2023-08-29 05:53:32] INFO: Chrome did not report any largest-contentful-paint
[2023-08-29 05:53:33] ERROR: Error encountered - ReferenceError: context is not defined
[2023-08-29 05:53:35] INFO: Use the visual metrics portable script
[2023-08-29 05:53:35] INFO: Get visual metrics from the video
[2023-08-29 05:53:37] ERROR: Could not add meta data to the HAR, miss page 0
[2023-08-29 05:53:37] INFO: data:text/html;charset=utf-8,<html><body></body></html> TTFB: 0ms, firstPaint: 150ms, firstVisualChange: 0ms, DOMContentLoaded: 12ms, CLS: 0, TBT: 0ms, CPUBenchmark: 93ms, Load: 12ms, speedIndex: 0ms, visualComplete85: 0ms, lastVisualChange: 0ms
[2023-08-29 05:53:37] ERROR: Could not find the right index 0 for har for url data:text/html;charset=utf-8,<html><body></body></html>
[2023-08-29 05:53:37] ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:271:29)
[2023-08-29 05:53:37] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:493:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-08-29 05:53:37] INFO: HTML stored in /sitespeed.io/sitespeed-result/app_js/2023-08-29-05-53-27
Error: Errors while running:
Could not get the right page for the HAR, the page is missing
Error: PageIndex out of range
    at start (file:///usr/src/app/bin/sitespeed.js:146:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:178:1
```

**Comment by soulgalore** [comment]
Hi @yourstoryteller the content object isn't global so try pass it on you to your imported function.

```
export async function printContext(context) {
    console.log(context);
}
```

```
 ...
  await printContext(context);
 ...
```

**Comment by yourstoryteller** [comment]
Hi @soulgalore, thanks for your prompt reply.

Is there any workaround for this? I've multiple page JS classes. It would be quite hectic to pass `context` and `commands` every time I would call these methods.

**Comment by soulgalore** [comment]
No.
