### ISSUE TITLE
[Bug] sitespeedio/sitespeed.io:29.3.0-slim doesn't work. BrowserError: Could not start firefox with 3 tries

### ISSUE THREAD

**Issue by polarnik** [sitespeedio/sitespeed.io#3952]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://miro.com

### What are you trying to accomplish

Try to start a test with the sitespeedio/sitespeed.io:**29.3.0-slim** and default settings

### What browser did you use?

Firefox

### How to reproduce

```shell
docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" \
  sitespeedio/sitespeed.io:29.3.0-slim \
  --debug --verbose \
  "https://miro.com"
```

### Log output

```shell
https://gist.github.com/polarnik/e16a66498f960cbd6629d9b0ba5be412

Mozilla Firefox 116.0
[2023-08-30 15:51:17] INFO: Versions OS: linux 5.15.49-linuxkit-pr nodejs: v18.12.1 sitespeed.io: 29.3.0 browsertime: 17.15.0 coach: 7.2.1
[2023-08-30 15:51:18] INFO: Running tests using Firefox - 3 iteration(s)
[2023-08-30 15:51:18] INFO: firefox failed to start, trying 2 more time(s): Command failed: which geckodriver
[2023-08-30 15:51:18] INFO: firefox failed to start, trying 1 more time(s): Command failed: which geckodriver
[2023-08-30 15:51:18] INFO: firefox failed to start, trying 0 more time(s): Command failed: which geckodriver
[2023-08-30 15:51:18] INFO: Firefox is kept open in debug mode
[2023-08-30 15:51:18] ERROR: BrowserError: Could not start firefox with 3 tries
    at SeleniumRunner.start (file:///usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Iteration.run (file:///usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:116:7)
    at async Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-08-30 15:51:18] ERROR: No data to collect
```

**Comment by soulgalore** [comment]
Hi @polarnik thank you for creating the issue. I see now that the slim container isn't built for ARM, are you using a Mac M1? If so, there's a fix so you can run the AMD container instead (just add the slim in the container tag in the example): https://www.sitespeed.io/documentation/sitespeed.io/docker/#running-on-mac-m1-arm

**Comment by polarnik** [comment]
> Hi @polarnik thank you for creating the issue. I see now that the slim container isn't built for ARM, are you using a Mac M1? If so, there's a fix so you can run the AMD container instead (just add the slim in the container tag in the example): https://www.sitespeed.io/documentation/sitespeed.io/docker/#running-on-mac-m1-arm

Hi @soulgalore Thanks! Yes I am using  Mac M1 without the Rosetta tool. I will install the Rosetta tool and try again

**Comment by polarnik** [comment]
All work fine with a key `--platform linux/amd64`

```sh
docker run --shm-size=1g --rm \
  -v "$(pwd)/sitespeed.io:/sitespeed.io" --platform linux/amd64 \
  sitespeedio/sitespeed.io:29.3.0-slim \
  --debug --verbose \
  "https://miro.com"
```

Thanks!
