### ISSUE TITLE
Could not get the right page for the HAR, the page is missing

### ISSUE THREAD

**Issue by dooglewoogle** [sitespeedio/sitespeed.io#3961]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://trademe.co.nz

### What are you trying to accomplish

Hi, I'm trying to measure a react app, and am having trouble when it comes to measuring multiple actions inside one page as seperate things. I see that sitespeed.io is trying to help me ($URL has been tested before within the same run....) but it still fails to generate the report. 

Actions like "input some text > click go" work alright, it's this multistep, "click A > click B > wait for load > click C > wait for load" workflow that seems to be tripping it up. 

Is there something else I can try?

Thanks.

Possibly related to: https://github.com/sitespeedio/sitespeed.io/issues/3907 ?

### What browser did you use?

Other

### How to reproduce

```shell
export default async function (context, commands) {
  // We start by navigating to the login page.

  await commands.navigate(
    'https://www.trademe.co.nz/a/marketplace'
  );
  try {

    await commands.measure.start("Search for plank")  // 
    await commands.addText.byXpath("plank", '/html/body/tm-root/div[1]/main/div/tm-marketplace-landing-page/div[1]/tm-marketplace-header-section/div[2]/div[1]/tm-marketplace-search-form/form/div/tg-input-container/label[2]/span[2]/input')
    await commands.click.byXpathAndWait("/html/body/tm-root/div[1]/main/div/tm-marketplace-landing-page/div[1]/tm-marketplace-header-section/div[2]/div[1]/tm-marketplace-search-form/form/div/div/button")
    await commands.measure.stop();

  
    await commands.measure.start("Click new/used")
    await commands.click.byXpathAndWait("/html/body/tm-root/div[1]/main/div/ng-component/div/tm-marketplace-search-header/div[1]/div/tm-refine-header/div[4]/tm-tags/tm-drop-down-tag[4]/tg-tag/span/button/span")
    await commands.click.byXpathAndWait("/html/body/tm-root/div[1]/main/div/ng-component/div/tm-marketplace-search-header/div[1]/div/tm-refine-header/div[4]/tm-tags/tm-drop-down-tag[4]/div/div[1]/tg-scrollable-container/div/div/tm-refiner-switcher/tm-radio-refiner/tg-radio-group/fieldset/tg-radio-item[3]/label/div/div/span")

    commands.measure.stop();


    await commands.measure.start("Click go")
    await commands.click.byXpathAndWait('/html/body/tm-root/div[1]/main/div/ng-component/div/tm-marketplace-search-header/div[1]/div/tm-refine-header/div[4]/tm-tags/tm-drop-down-tag[4]/div/div[2]/button')
    await commands.measure.stop();
  
  } catch (e) {
    throw e;
  }
  }
```

### Log output

```shell
[2023-09-11 10:51:21] INFO: Versions OS: linux 6.2.15-100.fc36.aarch64 nodejs: v16.18.1 sitespeed.io: 29.1.3 browsertime: 17.14.1 coach: 7.2.1
[2023-09-11 10:51:22] INFO: Running tests using Chrome - 1 iteration(s)
[2023-09-11 10:51:24] INFO: Testing url https://trademe.co.nz iteration 1
[2023-09-11 10:51:55] INFO: Take after page complete check screenshot
[2023-09-11 10:51:56] INFO: Take cumulative layout shift screenshot
[2023-09-11 10:51:57] INFO: Take largest contentful paint screenshot
[2023-09-11 10:51:57] INFO: Navigating to url https://www.trademe.co.nz/a/marketplace iteration 1
[2023-09-11 10:52:12] INFO: Start to measure Search for plank
[2023-09-11 10:52:24] INFO: Take after page complete check screenshot
[2023-09-11 10:52:25] INFO: Take cumulative layout shift screenshot
[2023-09-11 10:52:25] INFO: Take largest contentful paint screenshot
[2023-09-11 10:52:25] INFO: No element attached to the entry in largest-contentful-paint
[2023-09-11 10:52:26] INFO: Start to measure Click new/used
[2023-09-11 10:52:53] INFO: Start to measure Click go
[2023-09-11 10:52:53] INFO: Take after page complete check screenshot
[2023-09-11 10:52:53] INFO: Take cumulative layout shift screenshot
[2023-09-11 10:52:54] INFO: Take largest contentful paint screenshot
[2023-09-11 10:52:54] INFO: No element attached to the entry in largest-contentful-paint
[2023-09-11 10:53:11] INFO: https://www.trademe.co.nz/a/marketplace/building-renovation/search?search_string=plank&condition=used has been tested before within the same run, it will get an extra query parameter named browsertime_run. Make sure to use alias to keep track of the URLs
[2023-09-11 10:53:11] INFO: Take after page complete check screenshot
[2023-09-11 10:53:12] INFO: Take cumulative layout shift screenshot
[2023-09-11 10:53:12] INFO: Take largest contentful paint screenshot
[2023-09-11 10:53:12] INFO: No element attached to the entry in largest-contentful-paint
[2023-09-11 10:53:15] ERROR: Could not add meta data to the HAR, miss page 2
[2023-09-11 10:53:15] ERROR: Could not add meta data to the HAR, miss page 3
[2023-09-11 10:53:15] INFO: https://trademe.co.nz 122 requests, TTFB: 1.59s, firstPaint: 2.63s, FCP: 2.63s, DOMContentLoaded: 5.29s, LCP: 5.86s, CLS: 0.2986, TBT: 440ms, CPUBenchmark: 45ms, Load: 11.42s
[2023-09-11 10:53:15] INFO: https://www.trademe.co.nz/a/marketplace/building-renovation/search?search_string=plank 133 requests, TTFB: 250ms, firstPaint: 2.25s, FCP: 2.25s, DOMContentLoaded: 2.53s, LCP: 2.30s, CLS: 0.1164, TBT: 1.04s, CPUBenchmark: 55ms, Load: 6.97s
[2023-09-11 10:53:15] INFO: https://www.trademe.co.nz/a/marketplace/building-renovation/search?search_string=plank&condition=used TTFB: 250ms, firstPaint: 2.25s, FCP: 2.25s, DOMContentLoaded: 2.53s, LCP: 2.30s, CLS: 0.1164, TBT: 1.31s, CPUBenchmark: 45ms, Load: 6.97s
[2023-09-11 10:53:15] INFO: https://www.trademe.co.nz/a/marketplace/building-renovation/search?search_string=plank&condition=used&browsertime_run=2 TTFB: 250ms, firstPaint: 2.25s, FCP: 2.25s, DOMContentLoaded: 2.53s, LCP: 2.30s, CLS: 0.1164, TBT: 1.31s, CPUBenchmark: 85ms, Load: 6.97s
[2023-09-11 10:53:16] ERROR: Could not find the right index 2 for har for url https://www.trademe.co.nz/a/marketplace/building-renovation/search?search_string=plank&condition=used 
[2023-09-11 10:53:16] ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range
    at module.exports.pickAPage (/usr/local/lib/node_modules/sitespeed.io/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/local/lib/node_modules/sitespeed.io/node_modules/coach-core/lib/index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:271:29)
[2023-09-11 10:53:16] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/local/lib/node_modules/sitespeed.io/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/local/lib/node_modules/sitespeed.io/node_modules/coach-core/lib/index.js:84:12)
    at BrowsertimePlugin.processMessage (file:///usr/local/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:493:33)
[2023-09-11 10:53:17] INFO: HTML stored in /media/psf/Home/projects/orion_sitespeedio/run_scripts/sitespeed-result/trademe.co.nz/2023-09-11-10-51-21
Error: Errors while running:
Could not get the right page for the HAR, the page is missing
Error: PageIndex out of range
    at start (file:///usr/local/lib/node_modules/sitespeed.io/bin/sitespeed.js:146:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
    at async file:///usr/local/lib/node_modules/sitespeed.io/bin/sitespeed.js:178:1
```

**Comment by dooglewoogle** [comment]
Hi, 
Thanks for looking that over. It certainly fixed the problem in this script. This was is a publicly reproducible example for an issue on an non-public site. Fortunately the issue internally has also disappeared, so until or unless it comes back I'm going to close this.
