### ISSUE TITLE
Can not access website with docker image

### ISSUE THREAD

**Issue by dooglewoogle** [sitespeedio/sitespeed.io#3962]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

www.cbc.ca

### What are you trying to accomplish

Hi, I've done my scripting with the local npm version of sitespeed.io, and now I'm trying to transition it to the docker version. However, ssio reports that it cannot access the website. I can run curl on the url, and get a result, so I'm wondering if there is something like network adapter settings I may have misconfigured, not allowing docker to have access.

I have tried running with -p 80:80 -p 443:443, which didn't yield results. 

Also, the --privileged flag is to get around access permissions, see https://github.com/sitespeedio/sitespeed.io/issues/1975

### What browser did you use?

Chrome, Firefox

### How to reproduce

```shell
sudo docker run --privileged --rm -v "$(pwd)/../synth_mon:/sitespeed.io" sitespeedio/sitespeed.io:29.1.3 https://www.cbc.ca -n 1
```

### Log output

```shell
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 115.0.2
[2023-09-12 04:46:02] INFO: Versions OS: linux 6.2.15-100.fc36.aarch64 nodejs: v18.16.0 sitespeed.io: 29.1.3 browsertime: 17.14.1 coach: 7.2.1
[2023-09-12 04:46:03] INFO: Running tests using Chrome - 1 iteration(s)
[2023-09-12 04:46:05] INFO: Testing url https://www.cbc.ca iteration 1
[2023-09-12 04:46:30] INFO: URL failed to load, trying 5 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:31] INFO: URL failed to load, trying 4 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:32] INFO: URL failed to load, trying 3 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:33] INFO: URL failed to load, trying 2 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:34] INFO: URL failed to load, trying 1 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:45] INFO: URL failed to load, trying 0 more time(s): Could not load https://www.cbc.ca is the web page down?
[2023-09-12 04:46:45] ERROR: Could not load URL https://www.cbc.ca UrlLoadError: Could not load https://www.cbc.ca is the web page down?
    at SeleniumRunner.loadAndWait (file:///usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:295:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Measure.start (file:///usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:232:9)
    at async file:///usr/src/app/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:240:9)
    at async Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-09-12 04:46:52] ERROR: UrlLoadError: Failed to load https://www.cbc.ca
    at SeleniumRunner.loadAndWait (file:///usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:336:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Measure.start (file:///usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:232:9)
    at async file:///usr/src/app/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:240:9)
    at async Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-09-12 04:46:52] ERROR: Caught error from Browsertime TypeError: Cannot read properties of undefined (reading 'response')
    at getDocumentRequests (file:///usr/src/app/node_modules/browsertime/lib/support/har/index.js:34:18)
    at getFinalURL (file:///usr/src/app/node_modules/browsertime/lib/support/har/index.js:40:20)
    at getMainDocumentTimings (file:///usr/src/app/node_modules/browsertime/lib/support/har/index.js:200:22)
    at Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:339:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:196:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:162:26)
[2023-09-12 04:46:52] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.cbc.ca/2023-09-12-04-46-02
Error: Errors while running:
TypeError: Cannot read properties of undefined (reading 'response')
    at start (file:///usr/src/app/bin/sitespeed.js:146:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:178:1
```

**Comment by soulgalore** [comment]
Hi @dooglewoogle do you get the same if you try other URLs too? The container should have access to outside per default, that shouldn't be any problem.

**Comment by dooglewoogle** [comment]
Yes, I do. I've tested this on several urls.

**Comment by dooglewoogle** [comment]
Pretty sure now this one was caused by me trying to run docker images inside a virtual machine.
