### ISSUE TITLE
Sitespeed results with waterfall,video and visual metrics for URLs or user journey scripts running MacOS Safari browser

### ISSUE THREAD

**Issue by myanees284** [sitespeedio/sitespeed.io#3974]
### Your question

Hello Team,
When I am trying to run the below command, the user journey works on safari browser. However it generates results with basic information like Performance Score, TTFB and FCP.

node /bin/sitespeed --multi test.js -n 1 -b safari

I do not see any information related to waterfall view, video and visual metrics like First visual change, speedIndex, VisualComplete, lastVisual change etc.

Is there anything I am missing? Please help

**Comment by soulgalore** [comment]
Hi @myanees284 if you install the decencies in https://www.sitespeed.io/documentation/sitespeed.io/installation/#mac then you can add `--video `and `--visualMetrics` and you will get all the visual metrics like first visual change and speed index.

**Comment by myanees284** [comment]
> Hi @myanees284 if you install the decencies in https://www.sitespeed.io/documentation/sitespeed.io/installation/#mac then you can add `--video `and `--visualMetrics` and you will get all the visual metrics like first visual change and speed index.

Hello @soulgalore. Thanks for your reply. I followed the above installation steps and tried to run again by adding the arguments
**node sitespeed.io/bin/sitespeed.js --multi test.js -n 1 -b safari --video --visualMetrics**

I could see the safari browser getting opened and orange screen flashes and disappears leaving me with below error in the console:

`[2023-10-09 22:43:52] INFO: Versions OS: darwin 21.6.0 nodejs: v18.18.0 sitespeed.io: 29.7.0 browsertime: 17.16.0 coach: 8.0.2
[2023-10-09 22:43:52] INFO: Running tests using Safari - 1 iteration(s)
Selenium Manager binary found at /<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/bin/macos/selenium-manager
Driver path: /usr/bin/safaridriver
Browser path: /Applications/Safari.app/Contents/MacOS/Safari
[2023-10-09 22:43:56] INFO: Start to measure HomePage
[2023-10-09 22:43:56] ERROR: TypeError: Cannot read properties of null (reading '1')
    at getScreenOnOSX (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/osx/getScreen.js:30:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildX11FfmpegArguments (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:18:23)
    at async start (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/video/screenRecording/desktop/ffmpegRecorder.js:157:27)
    at async Measure._startVideo (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:85:7)
    at async Measure.start (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:207:7)
    at async module.exports (/<MY_PATH>/sitespeed/test.js:36:5)
    at async file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:240:9)
    at async Engine.runByScript (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:304:20)
    at async analyzeUrl (file:///<MY_PATH>/sitespeed/sitespeed.io/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///<MY_PATH>/sitespeed/sitespeed.io/lib/plugins/browsertime/index.js:173:26)
/<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:524
    let err = new ctor(data.message)
              ^

NoSuchSessionError
    at Object.throwDecodedError (/<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (/<MY_PATH>/sitespeed/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async Screenshot.take (file:///<MY_PATH>/sitespeed/sitespeed.io/node_modules/browsertime/lib/core/engine/command/screenshot.js:9:17) {
  remoteStacktrace: ''
}

Node.js v18.18.0`

**Comment by myanees284** [comment]
I missed to install ffmpeg. 
Now I could get the visual metric details and video. However I do not see waterfalls details
<img width="1181" alt="image" src="https://github.com/sitespeedio/sitespeed.io/assets/44027805/507781f8-a660-4865-b477-a516bacf0b75">

thanks once again

**Comment by soulgalore** [comment]
Hi @myanees284 waterfall/HAR isn't implemented. The reason is that Safari doesn't support it, I wrote about   here: https://github.com/sitespeedio/browsertime/issues/1777#issuecomment-1112565938
