### ISSUE TITLE
"ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range" error is thrown when Selenium script breaks in multiple iterations

### ISSUE THREAD

**Issue by yourstoryteller** [sitespeedio/sitespeed.io#3976]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.wikipedia.org/

### What are you trying to accomplish

Hi, our project is a single-page application and we've integrated sitespeed.io for performance monitoring. I'm using Wikipedia website to demonstrate the bug.

We receive an "ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range" error when any Selenium throws an exception. This error is only thrown when the iterations are set to greater than 1.

**app.js:**
```

export default async (context, commands) => {

    try {

        const webdriver = context.selenium.webdriver;
        const driver = context.selenium.driver;
        const By = webdriver.By;

        const convertToSlug = async (title) => {
            return title.toLowerCase()
                .replace(/ /g, "-")
                .replace(/[^\w-]+/g, "");
        }

        const updateURL = async (text) => {
            const currentURL = await driver.getCurrentUrl();
            const script = 'history.pushState({}, "", "' + currentURL +  + text + '")';
            await driver.executeScript(script);
        }

        // --------------------------------------------------------------------

        // ----- Test 1 : Wikipedia Home ----

        var test = 'Wikipedia Home';
        var url = 'https://www.wikipedia.org/';

        await commands.measure.start(test);

        await driver.get(url);
        await commands.wait.byPageToComplete();

        await commands.measure.stop();
        context.log.info('Completed - ' + test);


        // ----- Test 2 : Search ----

        var test = 'Search';
        var slug = await convertToSlug(test);
        var query = 'Javascript';

        await commands.measure.start(test);
        await updateURL(slug);

        await commands.wait.byId('searchInput', 10000);
        await driver.findElement(By.id('searchInputttttttt')).sendKeys(query);
        await driver.findElement(By.css('button[type="submit"]')).click();

        await commands.measure.stop();
        context.log.info('Completed - ' + test);

    } catch (e) {
        await commands.measure.stop();
        context.log.error('Error encountered - ' + e);
    }

};
```

**config.json**
```
{
    "multi": true,
    "name": "Wikipedia Performance Testing",
    "slug": "Wikipedia-Performance-Testing",
    "outputFolder": "report",
    "logToFile": true,
    "browsertime": {
        "browser": "chrome",
        "iterations": 2,
        "viewPort": "maximize",
        "viewPort-comment-alternative": "1920x1080",
        "headless": false,
        "spa": true,
        "chrome": {
            "collectNetLog": true,
            "collectConsoleLog": true
        }
    },
    "html": {
        "logDownloadLink": true,
        "showAllWaterfallSummary": true,
        "pageSummaryMetrics": [
            "transferSize.total",
            "requests.total",
            "thirdParty.requests",
            "transferSize.javascript",
            "transferSize.css",
            "transferSize.image",
            "score.performance"
        ],
        "summaryBoxes": [
            "score.score",
            "score.accessibility",
            "score.bestpractice",
            "score.privacy",
            "score.performance",
            "timings.firstPaint",
            "timings.firstContentfulPaint",
            "timings.fullyLoaded",
            "timings.pageLoadTime",
            "timings.largestContentfulPaint",
            "timings.FirstVisualChange",
            "timings.LastVisualChange",
            "timings.SpeedIndex",
            "timings.PerceptualSpeedIndex",
            "timings.VisualReadiness",
            "timings.VisualComplete",
            "timings.backEndTime",
            "googleWebVitals.cumulativeLayoutShift",
            "requests.total",
            "requests.javascript",
            "requests.css",
            "requests.image",
            "transferSize.total",
            "transferSize.html",
            "transferSize.javascript",
            "contentSize.javascript",
            "transferSize.css",
            "transferSize.image",
            "thirdParty.transferSize",
            "thirdParty.requests",
            "webpagetest.SpeedIndex",
            "webpagetest.lastVisualChange",
            "webpagetest.render",
            "webpagetest.visualComplete",
            "webpagetest.visualComplete95",
            "webpagetest.TTFB",
            "webpagetest.fullyLoaded",
            "axe.critical",
            "axe.serious",
            "axe.minor",
            "axe.moderate",
            "cpu.longTasksTotalDuration",
            "cpu.longTasks",
            "cpu.totalBlockingTime",
            "cpu.maxPotentialFid",
            "sustainable.totalCO2",
            "sustainable.co2PerPageView",
            "sustainable.co2FirstParty",
            "sustainable.co2ThirdParty"
        ],
        "showScript": true
    },
    "metrics": {
        "list": true
    },
    "plugins": {
        "list": true,
        "add": "analysisstorer",
        "remove-comment": [
            "assets",
            "browsertime",
            "budget",
            "coach",
            "domains",
            "harstorer",
            "html",
            "lateststorer",
            "metrics",
            "pagexray",
            "remove",
            "text",
            "thirdparty",
            "tracestorer",
            "analysisstorer"
        ]
    }
}
```

### What browser did you use?

Chrome

### How to reproduce

```shell
1. Create an app.js file with the above script and config.json file with the above JSON.
2. From the Terminal, navigate to the directory where the app.js is stored (Command - cd <path>)
3. Run command - docker run --rm -v ${pwd}:/sitespeed.io sitespeedio/sitespeed.io app.js --config config.json
```

### Log output

```shell
Google Chrome 117.0.5938.92
Mozilla Firefox 118.0
Microsoft Edge 117.0.2045.40
[2023-10-11 15:22:32] INFO: Versions OS: linux 5.15.123.1-microsoft-standard-WSL2 nodejs: v18.18.0 sitespeed.io: 29.7.0 browsertime: 17.16.0 coach: 8.0.2
[2023-10-11 15:22:32] INFO: The following plugins are enabled: assets, browsertime, budget, coach, domains, harstorer, html, lateststorer, metrics, pagexray, remove, text, thirdparty, tracestorer, analysisstorer
[2023-10-11 15:22:32] INFO: Running tests using Chrome - 2 iteration(s)
[2023-10-11 15:22:32] INFO: Start to measure Wikipedia Home
[2023-10-11 15:22:41] INFO: Take after page complete check screenshot
[2023-10-11 15:22:42] INFO: Take cumulative layout shift screenshot
[2023-10-11 15:22:43] INFO: Take largest contentful paint screenshot
[2023-10-11 15:22:44] INFO: Completed - Wikipedia Home
[2023-10-11 15:22:44] INFO: Start to measure Search
[2023-10-11 15:22:45] INFO: Take after page complete check screenshot
[2023-10-11 15:22:46] INFO: Take cumulative layout shift screenshot
[2023-10-11 15:22:46] INFO: Take largest contentful paint screenshot
[2023-10-11 15:22:47] ERROR: Error encountered - NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="searchInputttttttt"]"}
  (Session info: chrome=117.0.5938.92)
[2023-10-11 15:22:49] INFO: Use the visual metrics portable script
[2023-10-11 15:22:49] INFO: Get visual metrics from the video
[2023-10-11 15:22:51] INFO: Use the visual metrics portable script
[2023-10-11 15:22:51] INFO: Get visual metrics from the video
[2023-10-11 15:22:52] INFO: https://www.wikipedia.org/ TTFB: 277ms DOMContentLoaded: 473ms firstPaint: 470ms FCP: 470ms LCP: 470ms Load: 477ms
[2023-10-11 15:22:52] INFO: VisualMetrics: FirstVisualChange: 468ms SpeedIndex: 478ms VisualComplete85: 501ms LastVisualChange: 501ms
[2023-10-11 15:22:53] INFO: https://www.wikipedia.org/NaN TTFB: 277ms DOMContentLoaded: 473ms firstPaint: 470ms FCP: 470ms LCP: 470ms Load: 477ms
[2023-10-11 15:22:53] INFO: VisualMetrics: FirstVisualChange: 100ms SpeedIndex: 100ms VisualComplete85: 100ms LastVisualChange: 100ms
[2023-10-11 15:22:53] INFO: Start to measure Wikipedia Home
[2023-10-11 15:23:02] INFO: Take after page complete check screenshot
[2023-10-11 15:23:02] INFO: Take cumulative layout shift screenshot
[2023-10-11 15:23:03] INFO: Take largest contentful paint screenshot
[2023-10-11 15:23:04] INFO: Completed - Wikipedia Home
[2023-10-11 15:23:04] INFO: Start to measure Search
[2023-10-11 15:23:05] INFO: Take after page complete check screenshot
[2023-10-11 15:23:06] INFO: Take cumulative layout shift screenshot
[2023-10-11 15:23:07] INFO: Take largest contentful paint screenshot
[2023-10-11 15:23:07] ERROR: Error encountered - NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="searchInputttttttt"]"}
  (Session info: chrome=117.0.5938.92)
[2023-10-11 15:23:10] INFO: Use the visual metrics portable script
[2023-10-11 15:23:10] INFO: Get visual metrics from the video
[2023-10-11 15:23:12] INFO: Use the visual metrics portable script
[2023-10-11 15:23:12] INFO: Get visual metrics from the video
[2023-10-11 15:23:13] INFO: https://www.wikipedia.org/ TTFB: 283ms DOMContentLoaded: 501ms firstPaint: 489ms FCP: 489ms LCP: 489ms Load: 509ms
[2023-10-11 15:23:13] INFO: VisualMetrics: FirstVisualChange: 500ms SpeedIndex: 511ms VisualComplete85: 533ms LastVisualChange: 566ms
[2023-10-11 15:23:13] INFO: https://www.wikipedia.org/NaN TTFB: 283ms DOMContentLoaded: 501ms firstPaint: 489ms FCP: 489ms LCP: 489ms Load: 509ms
[2023-10-11 15:23:13] INFO: VisualMetrics: FirstVisualChange: 0ms SpeedIndex: 0ms VisualComplete85: 0ms LastVisualChange: 0ms
[2023-10-11 15:23:13] INFO: https://www.wikipedia.org/ 7 requests, TTFB: 280ms (σ3.00ms 1.1%), firstPaint: 480ms (σ10.00ms 2.0%), firstVisualChange: 484ms (σ16.00ms 3.3%), FCP: 480ms (σ10.00ms 2.0%), DOMContentLoaded: 487ms (σ14.00ms 2.9%), LCP: 480ms (σ10.00ms 2.0%), CLS: 0 (σ0.00 0%), TBT: 0ms (σ0.00ms 0%), CPUBenchmark: 80ms (σ4.00ms 5.0%), Load: 493ms (σ16.00ms 3.2%), speedIndex: 495ms (σ17.00ms 3.3%), visualComplete85: 517ms (σ16.00ms 3.1%), lastVisualChange: 534ms (σ33.00ms 6.1%) (2 runs)
[2023-10-11 15:23:13] INFO: https://www.wikipedia.org/NaN 7 requests, TTFB: 280ms (σ3.00ms 1.1%), firstPaint: 480ms (σ10.00ms 2.0%), firstVisualChange: 50ms (σ50.00ms 100.0%), FCP: 480ms (σ10.00ms 2.0%), DOMContentLoaded: 487ms (σ14.00ms 2.9%), LCP: 480ms (σ10.00ms 2.0%), CLS: 0 (σ0.00 0%), TBT: 0ms (σ0.00ms 0%), CPUBenchmark: 79ms (σ4.00ms 5.1%), Load: 493ms (σ16.00ms 3.2%), speedIndex: 50ms (σ50.00ms 100.0%), visualComplete85: 50ms (σ50.00ms 100.0%), lastVisualChange: 50ms (σ50.00ms 100.0%) (2 runs)
[2023-10-11 15:23:13] ERROR: Could not find the right index 2 for har for url https://www.wikipedia.org/
[2023-10-11 15:23:13] ERROR: Couldnt get the right page for the HAR Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:85:12)
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:282:29)
[2023-10-11 15:23:13] ERROR: Caught error from Browsertime Error: PageIndex out of range
    at module.exports.pickAPage (/usr/src/app/node_modules/coach-core/lib/har/harCutter.js:18:11)
    at pickAPage (/usr/src/app/node_modules/coach-core/lib/index.js:85:12)
    at BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:504:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-10-11 15:23:13] INFO: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/report/pages/www_wikipedia_org/data/filmstrip/1''
[2023-10-11 15:23:14] INFO: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/report/pages/www_wikipedia_org/data/filmstrip/1''
[2023-10-11 15:23:14] INFO: Could not read filmstrip dir Error: ENOENT: no such file or directory, scandir '/sitespeed.io/report/pages/www_wikipedia_org/data/filmstrip/2''
[2023-10-11 15:23:14] INFO: HTML stored in /sitespeed.io/report
Errors while running:
Could not get the right page for the HAR, the page is missing
Error: PageIndex out of range
Error: Errors while running:
Could not get the right page for the HAR, the page is missing
Error: PageIndex out of range
    at start (file:///usr/src/app/bin/sitespeed.js:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async file:///usr/src/app/bin/sitespeed.js:178:1
```

**Comment by soulgalore** [comment]
Hi @yourstoryteller thanks for adding the issue and an example! 

I think in your example you are missing a wait for page page to complete (`await commands.wait.byPageToComplete();`).

![wait](https://github.com/sitespeedio/sitespeed.io/assets/540757/79afb0c2-7b44-49e6-8580-cda730235cf4)

We need that wait to make sure that the new page for the search result actually is loaded.

Is that the same you have in your original issue or could it be something else?

**Comment by yourstoryteller** [comment]
Hi @soulgalore, thanks for your prompt reply.

It didn't work. The selenium exception (`NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="searchInputttttt"]"}`) is thrown before we wait for the page load. 

Code:
```
await commands.measure.start(test);
await updateURL(slug);

await commands.wait.byId('searchInput', 10000);
await driver.findElement(By.id('searchInputttttt')).sendKeys(query);
await driver.findElement(By.css('button[type="submit"]')).click();
await commands.wait.byPageToComplete();

await commands.measure.stop();
context.log.info('Completed - ' + test);
```

**Comment by soulgalore** [comment]
I think you made a typeo of the id? When I check it should be `searchInput`.

**Comment by yourstoryteller** [comment]
Sorry, I didn't mention earlier, that I'm failing the test explicitly to reproduce the Page Index out-of-range issue. 

We want to understand how to handle the selenium exceptions so that the HTML report is unaffected.

**Comment by soulgalore** [comment]
I see. I think the root if this error (at least 99% of the time) is  that the measure command runs without navigating to a new page (or if you run as a SPA no request is done). I will work on changing the log message and add more documentation so that I easier to understand. If you need to measure something else that a navigation its better to use the stop watch https://www.sitespeed.io/documentation/sitespeed.io/scripting/#stop-watch

I think most errors can be try/catched, can you share the exact error you get?

**Comment by yourstoryteller** [comment]
I will take a look at the stop watch and see if it works. Our project is indeed a SPA & I've set the spa to true in the config. 
Should we use stop watch?

Exact selenium error:
```
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="searchInputttttttt"]"}
  (Session info: chrome=117.0.5938.92)
```

**Comment by yourstoryteller** [comment]
Thanks for clearing the query! We will stick with the measure as every test case covers navigation.

I wanted to fail the test so I passed the non-existing ID and hence Selenium threw `Unable to locate elemen`' which is correct.

It's interesting that when we run this test for a single iteration, the exception is handled (catch block) and we're able to retrieve the metrics. But when the iteration is set to more than 1, we receive `Error: PageIndex out of range` error, as if the catch block doesn't work. 

Catch block:
```
catch (e) {
        await commands.measure.stop();
        context.log.error('Error encountered - ' + e);
    }
```

**Comment by soulgalore** [comment]
> Error: PageIndex out of range 

That error happens later on in the code when we try to match a page with a measurement. 

To handle errors in a script, the best way right now is to be very defensive. Verify that elements exist, that you can access them etc and then after that start your measurements.

One thing that could help in the future I think would be adding something like `commands.measure.cancel()` to cancel the current measurements if something goes wrong. That way you could cancel a measurement in a catch block.

**Comment by yourstoryteller** [comment]
Thank you so much @soulgalore!

**Comment by amitdisha** [comment]
OR @yourstoryteller , you can explicitly perform navigation  to sitespeed page always in case of any error as mentioned in https://github.com/sitespeedio/sitespeed.io/issues/3967#issuecomment-1856019724
