### ISSUE TITLE
How to configure influxDB for sitespeed results

### ISSUE THREAD

**Issue by SquealVth** [sitespeedio/sitespeed.io#3982]
### Your question

We are not using Docker, but using Node and have sitespeed installed on local machine. (Influxdb and Grafana has been installed on the same machine too).

Observed default --influx plugins on sitespeed website (https://www.sitespeed.io/documentation/sitespeed.io/configuration/#the-options) But when used below commands 

```shell
sitespeed.io -n 1 -b chrome https://www.sitespeed.io --influxdb.host localhost --influxdb.port 8086 --influxdb.organisation [NAME OF ORG] --influxdb.token [API TOKEN VALUE]--influxdb.database sitespeed --influxdb.version 2.7.1 
``` 

```shell
sitespeed.io -n 1 -b chrome https://www.sitespeed.io --influxdb.host 192.XXX.XX.XXX --influxdb.port 8086 --influxdb.organisation [NAME OF ORG] --influxdb.token  [API TOKEN VALUE] --influxdb.database sitespeed --influxdb.version 2.7.1 
``` 

We do receive below error - 

```shell
ERROR: Error: A 401 Unauthorized error occurred: {"code":"unauthorized","message":"Unauthorized"}
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/sitespeed.io/node_modules/influx/lib/src/pool.js:50:38)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/usr/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:142
            this.errors.push(rejectionMessage + '\n' + JSON.stringify(err));
                                                            ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'Socket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at /usr/lib/node_modules/sitespeed.io/lib/core/queueHandler.js:142:61
    at eventuateConsume (/usr/lib/node_modules/sitespeed.io/node_modules/eventuate/index.js:31:13)
    at Array.forEach (<anonymous>)
    at Function.eventuate.produce (/usr/lib/node_modules/sitespeed.io/node_modules/eventuate/index.js:30:19)
    at Object.onReject [as reject] (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:45:36)
    at reject (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:85:22)
    at f (/usr/lib/node_modules/sitespeed.io/node_modules/concurrent-queue/node_modules/once/once.js:17:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.9.0
```

**Comment by SquealVth** [comment]
upgrading to the latest site speed resolved the issue
