### ISSUE TITLE
Unable to run the image "sitespeedio/graphite:1.1.5-12" as non-root user

### ISSUE THREAD

**Issue by Msarma93** [sitespeedio/sitespeed.io#3984]
I am facing an issue while deploying the same in a kubernetes cluster.  As checked, the image is configured only to run only as root user which not a good practice. I am looking for a solution here as per the cluster configuration. Kindly help
Started runsvdir, PID is 36
wait for processes to start....
runsv collectd: fatal: unable to open supervise/lock: file does not exist
runsv carbon-aggregator: fatal: unable to open supervise/lock: file does not exist
runsv cron: fatal: unable to open supervise/lock: file does not exist
runsv carbon-relay: fatal: unable to open supervise/lock: file does not exist
runsv carbon: fatal: unable to open supervise/lock: file does not exist
runsv graphite: fatal: unable to open supervise/lock: file does not exist
runsv nginx: fatal: unable to open supervise/lock: file does not exist
runsv redis: fatal: unable to open supervise/lock: file does not exist
runsv statsd: fatal: unable to open supervise/lock: file does not exist
runsv collectd: fatal: unable to open supervise/lock: file does not exist
runsv statsd: fatal: unable to open supervise/lock: file does not exist
runsv carbon: fatal: unable to open supervise/lock: file does not exist
runsv graphite: fatal: unable to open supervise/lock: file does not exist

**Comment by Msarma93** [comment]
Hi Team, Any help on this?

**Comment by soulgalore** [comment]
Hi @Msarma93 try with the official Graphite container: https://github.com/graphite-project/docker-graphite-statsd the and see if that works. Our version only have some configurations like disabling tags and some setup for sitespeed.io metrics, you can find that configuration [here](https://github.com/sitespeedio/docker-graphite-statsd/tree/main/conf/graphite).

**Comment by Msarma93** [comment]
HI @soulgalore Thank you for looking into this. I am facing the same issue with the above image as well.

chmod: /etc/logrotate.d/acpid: Operation not permitted
chmod: /etc/logrotate.d/graphite-statsd: Operation not permitted
chmod: /etc/logrotate.d/nginx: Operation not permitted
chmod: /etc/logrotate.d/redis: Operation not permitted
Started runsvdir, PID is 46
wait for processes to start....
runsv carbon: fatal: unable to open supervise/lock: file does not exist
runsv graphite: fatal: unable to open supervise/lock: file does not exist
runsv nginx: fatal: unable to open supervise/lock: file does not exist
runsv go-carbon: fatal: unable to open supervise/lock: file does not exist
runsv cron: fatal: unable to open supervise/lock: file does not exist
runsv redis: fatal: unable to open supervise/lock: file does not exist
runsv carbon-aggregator: fatal: unable to open supervise/lock: file does not exist
runsv carbon-relay: fatal: unable to open supervise/lock: file does not exist

**Comment by soulgalore** [comment]
I checked Metrics fire it seems they have an example where they use the standard Graphite image:
https://www.metricfire.com/blog/monitoring-kubernetes-with-graphite/#Setting-up-Graphite-Grafana-and-Kubernetes

**Comment by Msarma93** [comment]
Hi @soulgalore . Thank You for looking into this . I did check, and the non root user issue arises from graphite-statsd image which is used as the baseimage. So,  I am looking to move to influxdb and I see influxdb version2 run fine as non-root user.
I have docker container up and running for influxdb:2.7.3. 
Created an organisation with the name Performance_fe and a respective token
While executing the sitespeed run and trying to push data to influxdb, I see an unauthorised error as below. Please correct if I am missing anything here.
 **docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io -n 1 --influxdb.host 172.17.0.2 --influxdb.port 8086 --influxdb.organisation Performance_fe --influxdb.token <token>
Google Chrome 118.0.5993.117 
Mozilla Firefox 119.0
Microsoft Edge 118.0.2088.69 
[2023-10-27 13:45:41] INFO: Versions OS: linux 5.15.64-0-virt nodejs: v20.9.0 sitespeed.io: 30.0.0 browsertime: 17.18.0 coach: 8.0.2
[2023-10-27 13:45:42] INFO: Running tests using Chrome - 1 iteration(s)
[2023-10-27 13:45:44] INFO: Testing url https://www.sitespeed.io iteration 1
[2023-10-27 13:45:54] INFO: Take after page complete check screenshot
[2023-10-27 13:45:56] INFO: Take cumulative layout shift screenshot
[2023-10-27 13:45:57] INFO: Take largest contentful paint screenshot
[2023-10-27 13:46:01] INFO: Use the visual metrics portable script
[2023-10-27 13:46:01] INFO: Get visual metrics from the video
[2023-10-27 13:46:04] INFO: https://www.sitespeed.io 11 requests, TTFB: 473ms, firstPaint: 822ms, firstVisualChange: 836ms, FCP: 822ms, DOMContentLoaded: 940ms, LCP: 963ms, CLS: 0, TBT: 72ms, CPUBenchmark: 68ms, Load: 1.15s, speedIndex: 868ms, visualComplete85: 970ms, lastVisualChange: 970ms
[2023-10-27 13:46:04] ERROR: Error: A 401 Unauthorized error occurred: {"code":"unauthorized","message":"Unauthorized"}
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/influx/lib/src/pool.js:50:38)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
file:///usr/src/app/lib/core/queueHandler.js:149
            this.errors.push(rejectionMessage + '\n' + JSON.stringify(error));
                                                            ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at file:///usr/src/app/lib/core/queueHandler.js:149:61
    at eventuateConsume (/usr/src/app/node_modules/eventuate/index.js:31:13)
    at Array.forEach (<anonymous>)
    at eventuate.produce (/usr/src/app/node_modules/eventuate/index.js:30:19)
    at Object.onReject [as reject] (/usr/src/app/node_modules/concurrent-queue/index.js:45:36)
    at reject (/usr/src/app/node_modules/concurrent-queue/index.js:85:22)
    at f (/usr/src/app/node_modules/concurrent-queue/node_modules/once/once.js:17:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0**

**Comment by soulgalore** [comment]
I think this is non sitespeed.io related so closing.
