### ISSUE TITLE
--plugins.add analysisstorer shows error when used with --s3.bucketname

### ISSUE THREAD

**Issue by amitdisha** [sitespeedio/sitespeed.io#3994]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [x] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io

### What are you trying to accomplish

Need json reports in S3 bucket using --plugins.add analysisstorer

### What browser did you use?

Chrome

### How to reproduce

```shell
prerequiste - you are authenticated with aws account using aws configure

Run command below to reproduce
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.0.0 https://www.sitespeed.io -n 1 --s3.bucketname bucketname --resultBaseURL https://bucketname.s3-ap-northeast-1.amazonaws.com --plugins.add analysisstorer
```

### Log output

```shell
ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2241:5)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at writeFile (node:internal/util:428:12)
    at write (file:///usr/src/app/lib/core/resultsStorage/storageManager.js:26:10)
    at file:///usr/src/app/lib/core/resultsStorage/storageManager.js:53:9
[2023-11-01 07:33:36] INFO: Running tests using Chrome - 1 iteration(s)
[2023-11-01 07:33:37] INFO: Testing url https://www.sitespeed.io iteration 1
[2023-11-01 07:33:46] INFO: Take after page complete check screenshot
[2023-11-01 07:33:46] INFO: Take cumulative layout shift screenshot
[2023-11-01 07:33:46] INFO: Take largest contentful paint screenshot
[2023-11-01 07:33:49] INFO: Use the visual metrics portable script
[2023-11-01 07:33:49] INFO: Get visual metrics from the video
[2023-11-01 07:33:50] INFO: https://www.sitespeed.io 11 requests, TTFB: 398ms, firstPaint: 625ms, firstVisualChange: 634ms, FCP: 625ms, DOMContentLoaded: 786ms, LCP: 688ms, CLS: 0, TBT: 0ms, CPUBenchmark: 52ms, Load: 786ms, speedIndex: 643ms, visualComplete85: 634ms, lastVisualChange: 701ms
[2023-11-01 07:33:52] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2023-11-01-07-33-36
[2023-11-01 07:33:52] INFO: Uploading /sitespeed.io/sitespeed-result/www.sitespeed.io/2023-11-01-07-33-36 to S3 bucket sitespeed-test-reports, this can take a while ...
[2023-11-01 07:33:54] INFO: Find the result at xxxxx/www.sitespeed.io/2023-11-01-07-33-36/index.html
Errors while running:
Rejected {
  "uuid": "5eb32135-6169-4127-b972-e5d4cd2c3fc2",
  "type": "s3.setup",
  "timestamp": "2023-11-01T07:33:36+00:00",
  "source": "s3",
  "data": "{...}"
} for plugin: analysisstorer
{"code":"ERR_INVALID_ARG_TYPE"}
```

**Comment by soulgalore** [comment]
Thank you @amitdisha for creating the bug. There's a couple of messages I've missed to exclude from the plugin, I'll fix that in a couple of minutes and do a release later today.

**Comment by soulgalore** [comment]
Hi @amitdisha I released 30.1.0 earlier today that hopefully fixes the issue.

**Comment by amitdisha** [comment]
Thanks , i will check and get back to you by EOD.

**Comment by amitdisha** [comment]
Thanks , issue is fixed now.
