### ISSUE TITLE
Unable to run sitespeed image as non root user

### ISSUE THREAD

**Issue by Msarma93** [sitespeedio/sitespeed.io#4020]
### Your question

Hi @soulgalore . I am unable to run the sitespeed docker image as non root user. it fails with a permission error. Please help me know if there is any workaround here. 
 docker run --user=1000 --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io https://www.sitespeed.io -b chrome 
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 119.0
groupadd: Permission denied.
groupadd: cannot lock /etc/group; try again later.
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
chroot: cannot change root directory to '/': Operation not permitted

**Comment by soulgalore** [comment]
Hi @Msarma93 just so I understand: you want to change who runs sitespeed.io inside the container or want to run the sitespeed.io container as a user that is not root?

**Comment by soulgalore** [comment]
So you followed the steps in https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user for the user that would like to run the container?

**Comment by soulgalore** [comment]
Yes but I think adding  `--user=1000 ` means that you run a different user inside of the container. The thing is that it's a hack in the container to make sure that the output files from sitespeed.io is of the user of the directory where you run the container. That magic happens in https://github.com/sitespeedio/sitespeed.io/blob/3d8194a092d1de93b3f48fb692e0bb97bc6365fc/docker/scripts/start.sh#L40-L46 

That could maybe be changed if we setup a user first and make sure it have the right privileges, but I don't have any time to test it out, but if you do, I can spend some time trying to help you with different use cases, so we can verify all work before its merged.

**Comment by Msarma93** [comment]
Hi @soulgalore , Created an image to run as non root . Here is the git patch file for the same
[file.patch](https://github.com/sitespeedio/sitespeed.io/files/13749923/file.patch)
I am using the above image as the base image and copying custom scripts but I am unable to run any custom script with the same and seeing the below error.
/start.sh /login_script.js -n $iterations  --browsertime.cacheClearRaw --multi --browsertime.pageCompleteCheck -b firefox
login_script.js is the custom script. Please have a look at it once.

[2023-12-22 08:04:15] INFO: Versions OS: linux 6.4.16-linuxkit nodejs: v20.9.0 sitespeed.io: 30.8.0 browsertime: 19.1.0 coach: 8.0.2
[2023-12-22 08:04:16] ERROR: script.endsWith is not a function
[2023-12-22 08:04:16] ERROR: Caught error from Browsertime TypeError: script.endsWith is not a function
    at loadFile (file:///usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:18:22)
    at loadScript (file:///usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:87:12)
    at Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:263:17)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:173:26)
[2023-12-22 08:04:16] ERROR: TypeError: Cannot read properties of null (reading 'split')
    at pathToFolder (file:///usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:49)
    at Object.relativeSummaryPageUrl (file:///usr/src/app/lib/core/resultsStorage/resultUrls.js:29:14)
    at DataCollector._addUrl (file:///usr/src/app/lib/plugins/html/dataCollector.js:20:31)
    at DataCollector.addErrorForUrl (file:///usr/src/app/lib/plugins/html/dataCollector.js:92:10)
    at HTMLPlugin.processMessage (file:///usr/src/app/lib/plugins/html/index.js:61:27)
    at file:///usr/src/app/lib/core/queueHandler.js:228:32
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/usr/src/app/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by soulgalore** [comment]
Try to have your file end by .mjs or .cjs depending if its a module or common, checkout  https://www.sitespeed.io/documentation/sitespeed.io/scripting/#scripting-basics

**Comment by soulgalore** [comment]
Thanks for creating the patch, it's quite much testing involved to make sure it works, but I will have a go later on. Please feel fre to make a PR if you want.

**Comment by pintiyas** [comment]
Hi!

I was dealing with same problem those days.
 
After lot of tries, upgrade docker to last version solve it.

I hope this helps.

**Comment by Msarma93** [comment]
Hi @pintiyas , Thanks for the suggestion. I still face the same issue with the updated docker version
docker --version
Docker version 24.0.7, build afdd53b

[2024-01-11 20:15:34] ERROR: script.endsWith is not a function
[2024-01-11 20:15:35] ERROR: Caught error from Browsertime TypeError: script.endsWith is not a function
    at loadFile (file:///usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:18:22)
    at loadScript (file:///usr/src/app/node_modules/browsertime/lib/support/engineUtils.js:87:12)
    at Engine.runByScript (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:263:17)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:173:26)
[2024-01-11 20:15:35] ERROR: TypeError: Cannot read properties of null (reading 'split')
    at pathToFolder (file:///usr/src/app/lib/core/resultsStorage/pathToFolder.js:20:49)
    at Object.relativeSummaryPageUrl (file:///usr/src/app/lib/core/resultsStorage/resultUrls.js:29:14)
    at DataCollector._addUrl (file:///usr/src/app/lib/plugins/html/dataCollector.js:20:31)
    at DataCollector.addErrorForUrl (file:///usr/src/app/lib/plugins/html/dataCollector.js:92:10)
    at HTMLPlugin.processMessage (file:///usr/src/app/lib/plugins/html/index.js:61:27)
    at file:///usr/src/app/lib/core/queueHandler.js:228:32
