### ISSUE TITLE
 Measuring INP --- ERROR: StaleElementReferenceError: stale element reference: stale element not found error using Action API

### ISSUE THREAD

**Issue by anonymous73612** [sitespeedio/sitespeed.io#4099]
Hello, I am getting the below error when I run my sitespeed script to measure INP using Action API. Below are the details.

**LOGS**:
Error executing command: Command failed: dotenvx run --env-file=resources/E/config.properties --env-file=resources/E/US.properties -- sitespeed.io tests/ProductPageTest.js --config config.json --budget.configPath budget.json --budget.output json --budget.suppressExitCode true --outputFolder sitespeed-result/ProductPageTest.js/US/
[2024-03-01 12:04:11] ERROR: StaleElementReferenceError: stale element reference: stale element not found
  (Session info: chrome=122.0.6261.94)
  (Session info: chrome=122.0.6261.94)
    at Object.throwDecodedError (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async Actions.perform (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/input.js:1006:5)
    at async ProductPage.measureProductPage (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/pages/ProductPage.js:41:13)
    at async default (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/tests/ProductPageTest.js:12:5)
    at async file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:162:9)
    at async Engine.runByScript (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:308:20)
    at async analyzeUrl (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:173:26)
[2024-03-01 12:04:11] ERROR: Caught error from Browsertime TypeError: result[resultIndex].files.screenshot[runIndex] is not iterable
    at BrowsertimePlugin.processMessage (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:425:76)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Versions**:
    "browsertime": "^21.0.0"
    "sitespeed.io": "^31.0.1"

NOTE: It works fine during the measureProductPage anonymous but fails when it's logged in(when isLoggedIn=true).
The issue here is only with the action API or how it's finding the element, it works fine with a normal click(for ex - commands.click.byXpathAndWait(element)). I have also tried with different elements doing click or sendKeys using Action API but they all work during the first page load and fail in the same session once we navigate to the page again after login with the same stale element error.

I have already tried with startOverButtonElement in both anonymous and logged-in cases but it's the same case. 

**CODE**:
export default async function (context, commands) {
    const browserService = new BrowserService();
    const productPage = new ProductPage();
    await browserService.startHolWebsite(CommonStrings.Country, commands);
    await productPage.measureProductPage(commands);
    await productPage.measureProductPage(commands, true);
}

async measureProductPage(commands, isLoggedIn = false) {
        if (isLoggedIn) {
            await this.loginPage.login(CommonStrings.Email, CommonStrings.Password, commands);
        }
        await commands.measure.start(`Product Page ${isLoggedIn ? 'Logged In' : 'Anonymous'} - ${CommonStrings.Country}`);
        await commands.navigate(CommonStrings.Country_Base_URL + CommonStrings.PRODUCT);
        if (isLoggedIn) {
            const element = commands.element.getByXpath(this.quantityInputElement);
            await commands.action ------> //this is where I am getting the error            
                .getActions()
                .click(element)
                .pause(1000)
                .sendKeys('10')
                .perform();
        } else {
            await commands.action.getActions().click(commands.element.getByCss(this.startOverButtonElement)).perform();
            await commands.action.clear();
        }
        await commands.measure.stop();
    }

**Comment by anonymous73612** [comment]
Yes, I understand this but I want to measure the INP for anonymous and logged-in scenarios so during the logged-in scenario we navigate to the page again and I am trying to locate the element but it's stale now. I have 2 questions here
1.) Why does it work with commands.click.byXpathAndWait(locator)?
2.) I also tried relocating the element with the below code but the same error

async clickElementWithRetry(elementLocator, commands, maxAttempts = 3) {
    let attempts = 0;
    while (attempts < maxAttempts) {
        try {
            let element = await commands.element.getByCss(elementLocator);
            await commands.action.getActions().click(element).perform();
            return; // Success
        } catch (error) {
            if (error.name === 'StaleElementReferenceError') {
                console.log('Stale element error occurred. Retrying...');
                await commands.wait.forTime(1000 * Math.pow(2, attempts)); // Exponential backoff
                attempts++;
            } else {
                throw error; // Re-throw other errors
            }
        }
    }
    throw new Error(`Failed to click element after ${maxAttempts} attempts.`);
}

**Comment by anonymous73612** [comment]
Hello, I also observed another issue while measuring INP,
page 1 > measure INP using Action API > Navigate to page 2 > measure INP using Action API (clicking on a different element)
we get the Stale Element Error:

Could you please check this or provide an alternate solution?
Thank You in advance

**LOGS**
Command outputted an error: StaleElementReferenceError: stale element reference: stale element not found
  (Session info: chrome=122.0.6261.94)
    at Object.throwDecodedError (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async Actions.perform (/Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/input.js:1006:5)
    at async Tools.clickElementByActionAPI (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/utils/Tools.js:53:13)
    at async CategoryPage.measureCategoryPageOverviewLevel3 (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/pages/CategoryPage.js:32:9)
    at async default (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/tests/CategoryPageTest.js:11:5)
    at async file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:162:9)
    at async Engine.runByScript (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:308:20)
    at async analyzeUrl (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:190:19)
    at async BrowsertimePlugin.processMessage (file:///Users/goyalsahil/Desktop/FEPerfTests/hdms-frontend-performance-tests/frontend-performance-tests/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:173:26) {
  remoteStacktrace: '0   chromedriver                        0x00000001031684cc chromedriver + 4162764\n' +
    '1   chromedriver                        0x0000000103160654 chromedriver + 4130388\n' +
    '2   chromedriver                        0x0000000102db7bc0 chromedriver + 293824\n' +
    '3   chromedriver                        0x0000000102dc6770 chromedriver + 354160\n' +
    '4   chromedriver                        0x0000000102dbdaf0 chromedriver + 318192\n' +
    '5   chromedriver                        0x0000000102dbc17c chromedriver + 311676\n' +
    '6   chromedriver                        0x0000000102dbf13c chromedriver + 323900\n' +
    '7   chromedriver                        0x0000000102dbf278 chromedriver + 324216\n' +
    '8   chromedriver                        0x0000000102e045d0 chromedriver + 607696\n' +
    '9   chromedriver                        0x0000000102e03a78 chromedriver + 604792\n' +
    '10  chromedriver                        0x0000000102e466d4 chromedriver + 878292\n' +
    '11  chromedriver                        0x0000000102e3dab0 chromedriver + 842416\n' +
    '12  chromedriver                        0x0000000102df16bc chromedriver + 530108\n' +
    '13  chromedriver                        0x0000000102df2930 chromedriver + 534832\n' +
    '14  chromedriver                        0x000000010312ddf8 chromedriver + 3923448\n' +
    '15  chromedriver                        0x00000001031323cc chromedriver + 3941324\n' +
    '16  chromedriver                        0x0000000103116028 chromedriver + 3825704\n' +
    '17  chromedriver                        0x0000000103132f2c chromedriver + 3944236\n' +
    '18  chromedriver                        0x00000001031086e4 chromedriver + 3770084\n' +
    '19  chromedriver                        0x000000010314f970 chromedriver + 4061552\n' +
    '20  chromedriver                        0x000000010314fae8 chromedriver + 4061928\n' +
    '21  chromedriver                        0x00000001031602d4 chromedriver + 4129492\n' +
    '22  libsystem_pthread.dylib             0x0000000182cee034 _pthread_start + 136\n' +
    '23  libsystem_pthread.dylib             0x0000000182ce8e3c thread_start + 8\n'
}

**Comment by soulgalore** [comment]
I think the Actions API uses lower level code (https://www.selenium.dev/documentation/webdriver/actions_api) when interacting with the page. The other command just runs JavaScript as you would do running directly in the console. For the errors you get, can you try explicit wait for the element? If you look at screen when you run the test does it match what you want to do?

**Comment by anonymous73612** [comment]
I tried waiting for the element but it does not work. Yes, the element is present on the screen when I run the test.
The problem here as I mentioned earlier is, that you get the Stale Element Error when you try to measure INP for the second page or more pages in the same run. It works fine for the 1st page but after that Action API throws the above error.
Is there any alternate solution to measure INP for multiple pages in the same run?

**Comment by anonymous73612** [comment]
Hello, It's kind of important to us to measure INP for user journeys that include multiple pages, any help here would be appreciated.

**Comment by soulgalore** [comment]
Measure INP works as you use click by mouse etc to trigger the correct events? 

```
await commands.measure.start('Go_to_youtube');
await commands.navigate('https://en.wikipedia.org/wiki/YouTube');
await commands.mouse.singleClick.byXpath('//*[@id="toc-Features"]/a'); <--- triggers INP
await commands.wait.byTime(2000);
return commands.measure.stop();
```

I don't fully follow your code, can you share a working example where you get a StaleElementReferenceError so I can run?

**Comment by soulgalore** [comment]
Ah when you run multiple calls to the Action API in Selenium you need clear it between calls. It's in the example https://www.sitespeed.io/documentation/sitespeed.io/scripting/tutorial-04-Interact-with-the-page.html#using-actions commented out:
 
```
  // If you would do more actions after calling .perform()
  // you manually need to clear the action API
  //await commands.action.clear();

```

That's how the API works in Selenium. I'll update the documentation to make that more clear. Not sure if there could be a clever way to auto clear it.

**Comment by anonymous73612** [comment]
I am already using clear action in my code and despite that it does not work and get the same error.
Did you try on your end, does it work for you?

**Comment by soulgalore** [comment]
I think maybe there's a bug in _commands.action.clear()_ when I try with `await commands.action.getActions().clear();` that works. 

This code works for me:
```
module.exports = async function (context, commands) {
  await commands.measure.start('Page 1');
  await commands.navigate('https://en.wikipedia.org/wiki/YouTube');
  const tocFeatures = await commands.element.getByXpath(
    '//*[@id="toc-Features"]/a'
  );

  await commands.action.getActions().click(tocFeatures).perform();
  await commands.wait.byTime(2000);
  await commands.measure.stop();

  await commands.action.getActions().clear();

  await commands.measure.start('Page 2');
  await commands.navigate('https://en.wikipedia.org/wiki/Barack_Obama');
  const tocPresidental = await commands.element.getByXpath(
    '//*[@id="toc-Presidential_campaigns"]/a'
  );
  await commands.action.getActions().click(tocPresidental).perform();
  await commands.wait.byTime(2000);
  await commands.measure.stop();
};
```

Let me check tomorrow what's going on with that shortcut.

**Comment by soulgalore** [comment]
I just rolled out 33.2.0 that makes the shortcut commands.action.clear() work as it should.

**Comment by anonymous73612** [comment]
Thank you, await commands.action.getActions().clear() works for me.
