### ISSUE TITLE
Is Live monitoring of webpage is possible in sitespeed? If so can I get some examples with dependencies.

### ISSUE THREAD

**Issue by MadhanIncred** [sitespeedio/sitespeed.io#4153]
### Your question

RROR: TypeError: Cannot read properties of undefined (reading 'budget')
    at BudgetPlugin.processMessage (file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/plugins/budget/index.js:46:18)
    at file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/core/queueHandler.js:228:32
    at drainItem (/Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:476:21)
[2024-05-14 16:13:13] ERROR: Error: Multiple summary messages of type aggregateassets.summary and group total
    at validateSummaryMessage (file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/core/queueHandler.js:70:11)
    at validateMessageFormat (file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/core/queueHandler.js:88:3)
    at QueueHandler.postMessage (file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/core/queueHandler.js:201:5)
    at AssetsPlugin.processMessage (file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/plugins/assets/index.js:56:19)
    at file:///Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/lib/core/queueHandler.js:228:32
    at drainItem (/Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:96:21)
    at Immediate.drain [as _onImmediate] (/Users/madhanumesh/Desktop/GitLoad/LoadTesting/node_modules/sitespeed.io/node_modules/concurrent-queue/index.js:77:84)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by soulgalore** [comment]
Hi @MadhanIncred you can test a live website using sitespeed.io. For example: `docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:33.6.0 https://www.sitespeed.io/`

**Comment by MadhanIncred** [comment]
[2024-05-14 11:26:10] ERROR: Caught error from Browsertime Error: ENOSYS: function not implemented, mkdir '/sitespeed.io/sitespeed-result/www.sitespeed.io/2024-05-14-11-26-09''

**Comment by soulgalore** [comment]
Hi,here's our guide to create a reproducible bug report: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue

If you follow that its easier for me to help you.

**Comment by soulgalore** [comment]
I could never reproduce so closing.
