### ISSUE TITLE
--preWarmServer parameter causes Android detection error

### ISSUE THREAD

**Issue by ThimoCap** [sitespeedio/sitespeed.io#4181]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io

### What are you trying to accomplish

When using the --preWarmServer parameter with the sitespeedio/sitespeed.io Docker container, the tool attempts to detect an Android phone and fails. This issue does not occur when using the sitespeedio/browsertime container with the same parameters:

`docker run --rm sitespeedio/browsertime:latest https://www.sitespeed.io -n 1 -b chrome --preWarmServer`
```
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 125.0.3
[2024-06-11 12:58:22] INFO: Start pre-testing/warming
[2024-06-11 12:58:22] INFO: Running tests using Chrome - 1 iteration(s)
[2024-06-11 12:58:22] INFO: Testing url https://www.sitespeed.io iteration 1
[2024-06-11 12:58:31] INFO: https://www.sitespeed.io 11 requests
[2024-06-11 12:58:31] INFO: Pre-testing done, closed the browser.
[2024-06-11 12:58:36] INFO: Running tests using Chrome - 1 iteration(s)
[2024-06-11 12:58:37] INFO: Testing url https://www.sitespeed.io iteration 1
[2024-06-11 12:58:51] INFO: Use the visual metrics portable script
[2024-06-11 12:58:51] INFO: Get visual metrics from the video
[2024-06-11 12:58:53] INFO: https://www.sitespeed.io 11 requests, TTFB: 76ms, firstPaint: 196ms, firstVisualChange: 233ms, FCP: 196ms, DOMContentLoaded: 185ms, LCP: 196ms, CLS: 0.0003, TBT: 0ms, CPUBenchmark: 83ms, Load: 198ms, speedIndex: 233ms, visualComplete85: 233ms, lastVisualChange: 233ms
[2024-06-11 12:58:53] INFO: Wrote data to browsertime-results/www.sitespeed.io/2024-06-11T125821+0000
```

### What browser did you use?
Chrome

### How to reproduce
`docker run --rm sitespeedio/sitespeed.io:latest https://www.sitespeed.io -n 1 -b chrome --preWarmServer`

### Log output
```
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 125.0.3
[2024-06-11 13:17:30] INFO: Versions OS: linux 6.6.26-linuxkit nodejs: v20.9.0 sitespeed.io: 34.1.1 browsertime: 22.4.0 coach: 8.0.2
[2024-06-11 13:17:33] ERROR: Caught error from Browsertime Error: No Android phone was found
    at Android._init (file:///usr/src/app/node_modules/browsertime/lib/android/index.js:50:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Engine.start (file:///usr/src/app/node_modules/browsertime/lib/core/engine/index.js:93:7)
    at async preWarmServer (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:58:3)
    at async analyzeUrl (file:///usr/src/app/lib/plugins/browsertime/analyzer.js:187:5)
    at async BrowsertimePlugin.processMessage (file:///usr/src/app/lib/plugins/browsertime/index.js:173:26)
[2024-06-11 13:17:33] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2024-06-11-13-17-30
```

**Comment by soulgalore** [comment]
Hi @ThimoCap thanks for reporting the issue, let me have a look.

**Comment by soulgalore** [comment]
Thank you again @ThimoCap . I released 34.1.2 where it should be fixed. I think I only used preWarm when using Android testing together with WebPageReplay. I'll add a test case for it later this week so it doesn't happen again.

**Comment by ThimoCap** [comment]
Thank you @soulgalore, especially for the very fast fix. I can confirm it works properly now:

`docker run --rm sitespeedio/sitespeed.io:34.1.2 https://www.sitespeed.io -n 1 -b chrome --preWarmServer`

```                                                                                                                                                                                                              ✔  47s  11:28:22
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 125.0.3
[2024-06-12 09:28:56] INFO: Versions OS: linux 6.6.26-linuxkit nodejs: v20.9.0 sitespeed.io: 34.1.2 browsertime: 22.4.0 coach: 8.0.2
[2024-06-12 09:28:56] INFO: Start pre-testing/warminghttps://www.sitespeed.io
[2024-06-12 09:28:56] INFO: Running tests using Chrome - 1 iteration(s)
[2024-06-12 09:28:57] INFO: Testing url https://www.sitespeed.io iteration 1
[2024-06-12 09:29:06] INFO: https://www.sitespeed.io 11 requests
[2024-06-12 09:29:06] INFO: Pre-testing done, closed the browser.
[2024-06-12 09:29:11] INFO: Running tests using Chrome - 1 iteration(s)
[2024-06-12 09:29:13] INFO: Testing url https://www.sitespeed.io iteration 1
[2024-06-12 09:29:23] INFO: Take after page complete check screenshot
[2024-06-12 09:29:23] INFO: Take cumulative layout shift screenshot
[2024-06-12 09:29:24] INFO: Take largest contentful paint screenshot
[2024-06-12 09:29:27] INFO: Use the visual metrics portable script
[2024-06-12 09:29:27] INFO: Get visual metrics from the video
[2024-06-12 09:29:29] INFO: https://www.sitespeed.io 11 requests, TTFB: 72ms, firstPaint: 337ms, firstVisualChange: 344ms, FCP: 337ms, DOMContentLoaded: 327ms, LCP: 381ms, CLS: 0.0004, TBT: 0ms, CPUBenchmark: 71ms, Load: 328ms, speedIndex: 359ms, visualComplete85: 413ms, lastVisualChange: 413ms
[2024-06-12 09:29:30] INFO: HTML stored in /sitespeed.io/sitespeed-result/www.sitespeed.io/2024-06-12-09-28-56
```

One small thing I noticed, the log message of the pre-testing/warmup does not contain a space, resulting in the above output. For your convenience, I've created a super simple PR to fix this problem: https://github.com/sitespeedio/sitespeed.io/pull/4183

**Comment by ThimoCap** [comment]
PR https://github.com/sitespeedio/sitespeed.io/pull/4183 merged, thanks again for resolving the preWarmServer bug!
