### ISSUE TITLE
ERROR: TypeError: Cannot read properties of undefined (reading 'alias')

### ISSUE THREAD

**Issue by sankar-rocketlane** [sitespeedio/sitespeed.io#4204]
### Your question

% sitespeed.io login.mjs --multi --spa -n 1
[2024-07-02 21:24:04] INFO: Start to measure login
[2024-07-02 21:24:23] INFO: Take after page complete check screenshot
[2024-07-02 21:24:40] INFO: Take after page complete check screenshot
[2024-07-02 21:24:40] INFO: Mark run as failure with message: Cannot read properties of undefined (reading 'alias')
[2024-07-02 21:24:40] ERROR: TypeError: Cannot read properties of undefined (reading 'alias')
    at Measure.stop (file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:419:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///Users/sagan/Workspace/Instrumentation/lp/login.mjs:39:9)
    at async file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/run.js:4:7
    at async Iteration.run (file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/iteration.js:162:9)
    at async Engine.runByScript (file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/index.js:308:20)
    at async analyzeUrl (file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/lib/plugins/browsertime/analyzer.js:202:12)
    at async BrowsertimePlugin.processMessage (file:///Users/sagan/.nvm/versions/node/v22.1.0/lib/node_modules/sitespeed.io/lib/plugins/browsertime/index.js:173:26)

**On visiting the error.html i see this error**
TypeError: result[resultIndex].files.screenshot[runIndex] is not iterable (browsertime)

**Comment by sankar-rocketlane** [comment]
Appreciate your help!

**Comment by soulgalore** [comment]
Hi @sankar-rocketlane can you share how I can reproduce the issue as in https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue or explain in detail what you try to do, its easier to help. 
Thanks

**Comment by sankar-rocketlane** [comment]
No worries. Please mark this as closed.

I managed to write sitespeed.io scripting and I didn't see the error anymore there.
