### ISSUE TITLE
analysisstorer plugin throws error

### ISSUE THREAD

**Issue by kanertuncel** [sitespeedio/sitespeed.io#4290]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [ ] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

sitespeed.io

### What are you trying to accomplish

I'm using the same config but since upgrading to v35 analysisstorer plugin throws an error, similar to [https://github.com/sitespeedio/sitespeed.io/issues/3505](url) 

Here is the log:

```
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:35.1.1 https://www.sitespeed.io --config config.json --crux.key [secretkey]
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 130.0.1
[2024-10-09 12:30:50] INFO: Versions OS: linux 6.10.4-linuxkit nodejs: v20.17.0 sitespeed.io: 35.1.1 browsertime: 23.1.1 coach: 8.0.2
[2024-10-09 12:30:51] INFO: Axe version 4.10.0 plugin activated
[2024-10-09 12:30:51] INFO: Use the sustainable web plugin with model 1byte
[2024-10-09 12:30:51] ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2311:5)
    at node:internal/util:432:7
    at new Promise (<anonymous>)
    at writeFile (node:internal/util:418:12)
    at write (file:///usr/src/app/lib/core/resultsStorage/storageManager.js:26:10)
    at file:///usr/src/app/lib/core/resultsStorage/storageManager.js:53:9
[2024-10-09 12:30:51] INFO: Get CrUx data for domain www.sitespeed.io
[2024-10-09 12:30:51] INFO: Running tests using Chrome - 1 iteration(s)
[2024-10-09 12:30:51] INFO: Get CrUx data for url https://www.sitespeed.io
[2024-10-09 12:30:51] INFO: Testing url https://www.sitespeed.io iteration 1
```
-----
and my config.json file looks like
```json
{
    "browsertime": {
      "iterations": 1,
      "browser": "chrome",
      "headlesss": true,
      "screenshot": true,
      "video": true,
      "cacheClearRaw":true
    },
    "plugins": {
      "remove": ["html"],
      "add": ["analysisstorer"]
    },
    "summary": true,
    "summaryDetail": true,
    "sustainable": {
      "enable": true,
      "pageviews": 1
    },
    "crux": {
      "enable": true
    },
    "axe": {
      "enable": true
    }
  }
``` 

If I use `-plus1` image than it stucks after GPSI

```
Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 130.0.1
[2024-10-09 12:29:24] INFO: Versions OS: linux 6.10.4-linuxkit nodejs: v20.17.0 sitespeed.io: 35.1.1 browsertime: 23.1.1 coach: 8.0.2
[2024-10-09 12:29:25] INFO: Axe version 4.10.0 plugin activated
[2024-10-09 12:29:25] INFO: Using default Lighthouse configuration for desktop 
[2024-10-09 12:29:25] INFO: Use the sustainable web plugin with model 1byte
[2024-10-09 12:29:25] INFO: Will run Lighthouse tests after Browsertime has finished 
[2024-10-09 12:29:25] INFO: Sending url https://www.sitespeed.io to test on Page Speed Insights
[2024-10-09 12:29:25] INFO: Get CrUx data for domain www.sitespeed.io
[2024-10-09 12:29:25] INFO: Running tests using Chrome - 1 iteration(s)
[2024-10-09 12:29:25] INFO: Get CrUx data for url https://www.sitespeed.io
[2024-10-09 12:29:25] INFO: Testing url https://www.sitespeed.io iteration 1
[2024-10-09 12:29:33] INFO: Take after page complete check screenshot
[2024-10-09 12:29:34] INFO: Take cumulative layout shift screenshot
[2024-10-09 12:29:34] INFO: Take largest contentful paint screenshot
[2024-10-09 12:29:35] INFO: Configure AXE with {"enable":true}
[2024-10-09 12:29:35] INFO: Run AXE with run options {}
[2024-10-09 12:29:37] INFO: Use the visual metrics portable script
[2024-10-09 12:29:37] INFO: Get visual metrics from the video
[2024-10-09 12:29:38] INFO: https://www.sitespeed.io 11 requests, TTFB: 122ms, firstPaint: 251ms, firstVisualChange: 250ms, FCP: 251ms, DOMContentLoaded: 225ms, LCP: 251ms, CLS: 0.0004, TBT: 0ms, CPUBenchmark: 42ms, Load: 226ms, speedIndex: 250ms, visualComplete85: 250ms, lastVisualChange: 250ms
[2024-10-09 12:29:38] INFO: Start collecting Lighthouse result for https://www.sitespeed.io
[2024-10-09 12:29:45] INFO: Got https://www.sitespeed.io analysed from Google Page Speed Insights 
```

Thanks in advance!

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:35.1.1 https://www.sitespeed.io --config config.json --crux.key
```

### Log output

```shell
ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2311:5)
    at node:internal/util:432:7
    at new Promise (<anonymous>)
    at writeFile (node:internal/util:418:12)
    at write (file:///usr/src/app/lib/core/resultsStorage/storageManager.js:26:10)
    at file:///usr/src/app/lib/core/resultsStorage/storageManager.js:53:9
```

**Comment by soulgalore** [comment]
Thank you @kanertuncel for creating the issue, let me have a look later today and see if I can fix it.

**Comment by soulgalore** [comment]
Hi @kanertuncel can you try 35.1.2, it will be there in a couple of minutes. It fixes the error you get in the log. For the +1 container getting stuck, I couldn't reproduce but please let me know if it happens again.

**Comment by kanertuncel** [comment]
**Thank you veru much** @soulgalore that worked
