### ISSUE TITLE
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:41233/hub

### ISSUE THREAD

**Issue by measureworks** [sitespeedio/sitespeed.io#551]
Hi,

When we run sitespeed on Ubuntu14 sitespeed randomly stops and gives this error. 

/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/proxy/mobproxy.js:87
    throw err;
          ^
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:41233/hub
    at Error (<anonymous>)
    at onResponse (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/http/util.js:87:11)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/http/util.js:42:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/http/index.js:145:7)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at new Driver (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/firefox/index.js:189:36)
    at Builder.build (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:309:14)
    at Object.module.exports.getDriver (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/firefox.js:49:56)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:86:66
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21

**Comment by soulgalore** [comment]
Thanks @measureworks 
and this happens when you firefox right, not Chrome?

Best
Peter

**Comment by measureworks** [comment]
Hi Peter, 

This error also occurs with Firefox.

Kind Regards,
Ingrid

**Comment by soulgalore** [comment]
Closing too old issues. Lets start with new clean sheet for 4.0.
