### ISSUE TITLE
analysisDone is undefined when running without YSlow.

### ISSUE THREAD

**Issue by frvge** [sitespeedio/sitespeed.io#562]
When I run sitespeed on FreeBSD I get the following results. The analysisDone function is defined in the file, but at a later part of the code.

```bash
$ sitespeed.io -u "http://www.sitespeed.io" -d 0 --noYslow
info: OS: freebsd 10.0-RELEASE-p7 sitespeed:3.0.3  phantomJs: java:openjdk version "1.7.0_71" browsertime:0.8.20
info: Will crawl from start point http://www.sitespeed.io with crawl depth 0
info: Will analyze 1 pages

/usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:67
                analysisDone(error, results, analysisErrors);
                ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:67:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at async.eachSeries (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:145:20)
    at _asyncMap (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:248:13)
    at Object.mapSeries (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:231:23)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyze/analyzer.js:62:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:249:17
    at iterate (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:160:25
$
```

This also is the case for Ubuntu ( Linux precise64 3.2.0-37-generic #58-Ubuntu SMP Thu Jan 24 15:28:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux ).

**Comment by tobli** [comment]
Thanks for reporting this Frank! We'll have a fixed version out shortly, hopefully tonight.

Regards
/Tobias

**Comment by tobli** [comment]
Version 3.0.4 was just released with a fix for this.
