### ISSUE TITLE
browsermobproxy fails with error: Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by kanedo** [sitespeedio/sitespeed.io#565]
Hi
I wanted to test your tool and run the following command:
`sitespeed.io -u http://blog.kanedo.net -b chrome -v`

the output was the following: 
```
info: OS: darwin 14.0.0 sitespeed:3.0.5  phantomJs:1.9.8 java:java version "1.6.0_65" browsertime:0.8.20
info: Will crawl from start point http://blog.kanedo.net with crawl depth 1
info: Will analyze 19 pages
info: Starting proxy on port 9092, will wait at most 15000 ms
error: 
```
and the log `browsermobproxy.log` show
s a stacktrace:
```
2015-01-24T10:30:13.352Z - error: [browsermobproxy] stderr:Exception in thread "main" 
2015-01-24T10:30:13.353Z - error: [browsermobproxy] stderr:java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)

2015-01-24T10:30:13.353Z - error: [browsermobproxy] stderr:	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

 ```
Since its apparently an issue with java, my local version is:
```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

I use version 3.0.5 of sitespeed.io

**Comment by soulgalore** [comment]
Hi @kanedo 
thanks for the report. The "Unsupported major.minor" is when a java program is compiled with a newer version of java than try to run it. I know that the BrowserMobProxy "should" be able to be compiled with java 1.6 but the current version had some new dependencies that need 1.7. 

If you can upgrade Java version to 1.7 or newer that will solve the problem for now. I will check later if the BMP project fixed the dependencies so we can build with java 1.6 (however java 1.6 is really old so it is good to upgrade).

Best
Peter

**Comment by kanedo** [comment]
Hi @soulgalore,
upgrading to java 1.7 worked. Thank you!

After this I've run in the problem, that Chromedriver was not installed (which is not a problem since I can install it with homebrew) but it would be cool if you could either check those dependencies when installing or, if that is not possible, write them down in the README.

thanks!
Best
Gabriel

**Comment by soulgalore** [comment]
Hi Gabriel,
hmm strange the chromedriver should be installed automatically. Do you have log from the install or what happend when you tried to run it?

Best
Peter

**Comment by kanedo** [comment]
Hi @soulgalore 
the log from the run:
```
info: Running browsertime for chrome http://blog.kanedo.net
info: Stopping proxy

/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/proxy/mobproxy.js:87
    throw err;
          ^
Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.
    at Error (<anonymous>)
    at new ServiceBuilder (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:51:11)
    at getDefaultService (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:216:22)
    at new Driver (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:470:32)
    at Builder.build (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:303:14)
    at Object.module.exports.getDriver (/usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:31:56)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:86:66
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21
```
where could I find the installation log of a package?

**Comment by raptor235** [comment]
I'm getting the same issue with Java 1.8 

2015-12-14T17:46:13.557Z - error: stderr:Exception 
2015-12-14T17:46:13.557Z - error: stderr:in thread "main" java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)

2015-12-14T17:46:13.558Z - error: stderr:	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by soulgalore** [comment]
Hey @raptor235 ,
ohh sorry missed this. Hmm are you sure that java 1.8 is used? This happens when the Java code is compiled with a newer version than the one running it. Can you verify that sitespeed.io pick up 1.8 (it's showed in the output in the beginning)?

Best
Peter

**Comment by 5vxssbdahves** [comment]
Also encountered the issue with Java 1.8

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Anyone found a solution?
