### ISSUE TITLE
Test doesn't fail on browsertime error

### ISSUE THREAD

**Issue by yesman82** [sitespeedio/sitespeed.io#637]
Tests do not fail when browsertime has an error.

In this case I removed the chrome executable to produce this error. 
The Jenkins job this was running on did not fail.

```
info: [sitespeed] OS: 'linux 3.2.0-4-amd64', Node.js: 'v0.10.37', sitespeed.io: '3.2.6', PhantomJS: '2.0.1-development', java: '1.7.0_75', browsertime: '0.9.4'
info: [sitespeed] Will crawl from start point http://www.toptarif.de with crawl depth 0
info: [sitespeed] Will analyze 1 pages
info: [sitespeed] Running YSlow for http://www.toptarif.de [phantomjs]
info: [sitespeed] Queueing browsertime for http://www.toptarif.de chrome
info: [sitespeed] Running browsertime for chrome http://www.toptarif.de
error: [sitespeed] Error running browsertime: { [UnknownError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.2.0-4-amd64 x86_64)]
  code: 13,
  state: 'unknown error',
  message: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.2.0-4-amd64 x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.2.0-4-amd64 x86_64)\n    at new bot.Error (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)\n    at Object.bot.response.checkResponse (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:158:24\n    at promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)\n    at promise.Callback_.goog.defineClass.notify (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)\n    at promise.Promise.notify_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)\n    at Array.forEach (native)\n    at Object.goog.array.forEach (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)\n    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)\n    at goog.async.run.processWorkQueue [as _onTimeout] (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)\n    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)\n    at new Driver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:791:36)\n    at Builder.build (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:425:14)\n    at Object.module.exports.getDriver (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsers/chrome.js:37:49)\n    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:107:64\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:254:17\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:157:25\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:251:21\n    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:615:34' }
info: [sitespeed] Done analyzing urls
info: [sitespeed] Wrote file www.toptarif.de.html
info: [sitespeed] Wrote file domains.html
info: [sitespeed] Wrote file errors.html
info: [sitespeed] Wrote file assets.html
info: [sitespeed] Wrote file hotlist.html
info: [sitespeed] Wrote file pages.html
info: [sitespeed] Wrote file rules.html
info: [sitespeed] Wrote file index.html
info: [sitespeed] Wrote file detailed-site-summary.html
info: [sitespeed] Wrote results to /var/lib/jenkins/jobs/sitespeed/workspace/sitespeed-result/www.toptarif.de/2015-04-07-16-53-16
info: [sitespeed] The analyze took a few seconds (13 seconds)
```

When browsertime exits with an error sitespeed.io should also exit with an error.

**Comment by soulgalore** [comment]
yep true, thanks @yesman82 for reporting.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
