### ISSUE TITLE
Bad argument exception while executing sitespeed command from command line

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#665]
child_process.js:1129
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1129:26)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at async.parallel.childProcess.exec.timeout (/usr/local/lib/node_modules/sitespeed.io/lib/util/util.js:343:26)
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:570:21
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:249:17
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:46:24)

**Comment by soulgalore** [comment]
hey @badrinathvm ,
could you help me with exact how you run it, so I can see what happens and test myself=

Best
Peter

**Comment by soulgalore** [comment]
hey @badrinathvm ,
if you have more info and it is still an issue, please re-open
