### ISSUE TITLE
Test wont produce results

### ISSUE THREAD

**Issue by kurtcunningham** [sitespeedio/sitespeed.io#671]
When I run the test I can't get it to produce any results. 

I am running: 

```bash
sitespeed.io -u http://www.launchpadlab.com -b chrome
```

It generates the folder but the dashboard that is created just returns a blank list. No data or analytics appear on any of the generated .html pages.

**Comment by soulgalore** [comment]
Hi @kurtcunningham ,
thanks for reporting. Can you share the logs from the run (they are located at the same level as the index.html file) check for <code>sitespeed.io.log</code>,<code>browsertime.log</code>, <code>browsermobproxy.log</code>, either in the issue, a gist or email me (peter[AT]soulgalore[dot]com.

Best
Peter

**Comment by kurtcunningham** [comment]
Sure thing. 

browsermobproxy.log: 

```
2015-05-21T12:00:46.304Z - error: stderr:Exception in thread "main" 
2015-05-21T12:00:46.304Z - error: stderr:java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
2015-05-21T12:00:46.305Z - error: stderr:
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

browsertime.log

```
2015-05-21T12:00:46.071Z - info: Starting proxy on port 2001, will wait at most 15000 ms
```

sitespeed.io.log

```
2015-05-21T12:00:03.827Z - info: [sitespeed] OS: 'darwin 14.3.0', Node.js: 'v0.12.0', sitespeed.io: '3.5.0', PhantomJS: '1.9.8', java: '1.6.0_65', browsertime: '0.9.4'
2015-05-21T12:00:03.944Z - info: [sitespeed] Will crawl from start point http://www.launchpadlab.com with crawl depth 1
2015-05-21T12:00:07.551Z - info: [sitespeed] Will analyze 11 pages
2015-05-21T12:00:07.553Z - info: [sitespeed] Running YSlow for http://www.launchpadlab.com [phantomjs]
2015-05-21T12:00:07.556Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/blog [phantomjs]
2015-05-21T12:00:07.558Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/about [phantomjs]
2015-05-21T12:00:07.560Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/contact [phantomjs]
2015-05-21T12:00:07.562Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/work/content_web [phantomjs]
2015-05-21T12:00:22.294Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/services [phantomjs]
2015-05-21T12:00:22.546Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/work/shift [phantomjs]
2015-05-21T12:00:23.488Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/process [phantomjs]
2015-05-21T12:00:26.386Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/work/md_anderson [phantomjs]
2015-05-21T12:00:27.925Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/work [phantomjs]
2015-05-21T12:00:33.388Z - info: [sitespeed] Running YSlow for http://launchpadlab.com/work/algofast [phantomjs]
2015-05-21T12:01:01.087Z - info: [sitespeed] Done analyzing urls
2015-05-21T12:01:01.325Z - info: [sitespeed] Wrote file assets.html
2015-05-21T12:01:01.325Z - info: [sitespeed] Wrote file hotlist.html
2015-05-21T12:01:01.325Z - info: [sitespeed] Wrote file pages.html
2015-05-21T12:01:01.326Z - info: [sitespeed] Wrote file errors.html
2015-05-21T12:01:01.326Z - info: [sitespeed] Wrote file domains.html
2015-05-21T12:01:01.326Z - info: [sitespeed] Wrote file rules.html
2015-05-21T12:01:01.326Z - info: [sitespeed] Wrote file detailed-site-summary.html
2015-05-21T12:01:01.327Z - info: [sitespeed] Wrote file index.html
2015-05-21T12:01:01.343Z - info: [sitespeed] Wrote results to /Users/kurtcunningham/sitespeed-result/www.launchpadlab.com/2015-05-21-07-00-02
2015-05-21T12:01:01.346Z - info: [sitespeed] The analyze took a minute (57 seconds)
```

**Comment by soulgalore** [comment]
thanks,
ok, see that the Java version is wrong, could it be that you are running java 1.6? I don't think it's specified in the docs sorry, you need to have at least Java 1.7.  

Interesting though it should not give blank pages if the proxy fails, will look into it later. Try to upgrade your Java version and hopefully it will work!

Best
Peter

**Comment by kurtcunningham** [comment]
That worked. Thanks for the help. :+1:

**Comment by cgoldberg** [comment]
perhaps it could check the java version when starting up and exit with a nice error message if java != 1.7

**Comment by soulgalore** [comment]
yes good idea, had it in the old version but missed converting it when moving to nodejs.
