### ISSUE TITLE
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.

### ISSUE THREAD

**Issue by bwinett** [sitespeedio/sitespeed.io#745]
Windows 7. sitespeed.io 3.9.0.  Command run: `sitespeed.io.cmd -u http://tekreddev.tek.com -d 2 -b firefox`

from start of run: `info: OS: 'win32 6.1.7601', Node.js: 'v0.10.32', sitespeed.io: '3.9.0', PhantomJS: '1.9.8', java: '1.7.0_45', browsertime: '0.10.2'`

Looks like it successfully fetched a lot of pages.  Then this:

info: Running browsertime for firefox http://tekreddev.tek.com/service
Fetching http://tekreddev.tek.com/service (1 of 3)
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at C:\Temp\node_modules\sitespeed.io\node_modules\async\lib\async.js:35:31
    at C:\Temp\node_modules\sitespeed.io\node_modules\async\lib\async.js:741:17
    at C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\lib\browsertime.js:94:7
    at webdriver.EventEmitter.emit (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver\events.js:55:17)
    at promise.ControlFlow.abortNow_ (eval at <anonymous> (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:2023:10)
    at webdriver.EventEmitter.emit (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\webdriver\events.js:55:17)
    at goog.defineClass.abort (eval at <anonymous> (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:2192:12)
    at promise.ControlFlow.abortFrame_ (eval at <anonymous> (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:1811:9)
    at promise.Promise.notifyAll_ (eval at <anonymous> (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\base.js:1094:19), <anonymous>:547:16)
    at goog.async.run.processWorkQueue [as _onTimeout] (C:\Temp\node_modules\sitespeed.io\node_modules\browsertime\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
Stopping proxy

**Comment by soulgalore** [comment]
Hi @bwinett 
thanks for reporting, yes error handling is not perfect right now (we are working on it) I'll reference the other issues here.

It seems like there's a timeout somewhere, the page works normally when you access it your browser?

Best
Peter

**Comment by bwinett** [comment]
Thanks for responding.  The page takes a while to come back (in my last attempt, 23 seconds for response, 35 seconds before completion).

**Comment by soulgalore** [comment]
hmm ok, the timeout by default should be 60 seconds if I remember correctly. We wait for the loadEventEnd to happen (that's configurable https://www.sitespeed.io/documentation/browsers/#choose-when-to-end-your-test) or the timeout time. To change the 60s, you do that with the btConfig parameter, I'll can add exactly how later today.

**Comment by benpatterson** [comment]
For posterity, I also encounter this exception. We are using the url file feature, as well as screenshots. This occurred while attempting a screenshot; however I've seen it occur at other times. In my case, admittedly, it appears to be occurring on some of our heavier pages (which implies there are other things beyond size involved on my end).

```
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:43:36
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:694:17
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:173:37
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:94:7
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at promise.ControlFlow.abortNow_ (eval at <anonymous> (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2023:10)
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at goog.defineClass.abort (eval at <anonymous> (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:2192:12)
    at promise.ControlFlow.abortFrame_ (eval at <anonymous> (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:1811:9)
    at promise.Promise.notifyAll_ (eval at <anonymous> (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/base.js:1094:19), <anonymous>:547:16)
```

**Comment by daustin2011** [comment]
Please provide the details on how to set btConfig to override the default timeout of 60 seconds.

**Comment by daustin2011** [comment]
Related: https://github.com/sitespeedio/sitespeed.io/issues/764

**Comment by soulgalore** [comment]
Hey @daustin2011 ,
oopps I checked it now and it's hardcoded to 2 minutes in the current version. Usually if it takes 3 minutes for your page to load (or the loadevenetend) to end it's sonething else thats wrong (if you are not testing using 2g or another slow connection type). In the coming Browsertime 1.0 it's configurable.

Can you show me exactly what happens, lets see if we can fix it.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
