### ISSUE TITLE
Underscores are not allowed on a URL subdomain

### ISSUE THREAD

**Issue by azimut** [sitespeedio/sitespeed.io#768]
There is no  /sitespeed.io/data/error.log file

```
# docker run   --privileged   --rm   -v /sitespeed.io:/sitespeed.io --entrypoint sitespeed.io  sitespeedio/sitespeed.io  -b firefox -n 1 --graphiteHost graphite-none.domain.com --graphiteNamespace sitespeed.io -u http://test_a.domain.com/wordpress2/ 
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
info: OS: 'linux 3.10.0-229.7.2.el7.x86_64', Node.js: 'v4.2.1', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.12.0'
info: Will crawl from start point http://test_a.domain.com/wordpress2/ with crawl depth 1
error: Error from the crawl: The url http://test_a.domain.com/wordpress2/ isn't a valid url

info: Didn't get any URLs
error:  Error: No URLs to analyze
    at Object.module.exports.fineTuneUrls (/usr/lib/node_modules/sitespeed.io/lib/util/util.js:353:18)
    at /usr/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:52:12
    at fn (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:752:34)
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:1252:16
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:697:43
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:1248:30
    at /usr/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:103:5
    at /usr/lib/node_modules/sitespeed.io/lib/crawler/crawler.js:119:18
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:718:13
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:46:16
```

**Comment by soulgalore** [comment]
hey @azimut , thanks for reporting, haven't touched the crawler for long time (https://github.com/sitespeedio/crawler) if you have a couple of minutes it would be super if you could have a look and check what's wrong.

Best
Peter

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
