### ISSUE TITLE
a way to bypass the google ga-audiences call

### ISSUE THREAD

**Issue by une6** [sitespeedio/sitespeed.io#778]
Hi,

sorry i've been emailing directly since i got this weird error when submitting an issue, logging out, etc in github. hope it works now.

but my issue would be that i'm running sitespeed.io using docker on a china box. and i'm getting the ConnectTimeoutException from BrowserMobProxy. i tried to modify the /etc/hosts to point www.google.com to 127.0.0.1 but unfortunately BrowserMobProxy doesn't seem to be looking at /etc/hosts.. I visited BrowserMobProxy's github page and unfortunately they're using a new version now but they have this option allowNativeDnsFallback. 

or if there's a way to totally turn off anything google related in the sitespeed run.. that would be much better as google is totally blocked in china.. i searched through sitespeed.io, browsertime, browsermob-proxy but couldn't see where this google calls are being done at all :(

i'm using this command to run docker now, but the --add-hosts doesn't really help. the new ip for www.google.com is still ignored:
```
sudo docker run --add-host="www.google.com:127.0.0.1" --privileged --rm -v /root:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -b firefox -n 3 --connection cable -r ./temps -u http://www.sitespeed.io --graphiteHost 45.114.117.27 --graphiteNamespace sitespeed.io.china--seleniumServer http://127.0.0.1:4444/wd/hub
```
Error log (browsermobproxy.log):

2015-11-17T02:27:35.442Z - error: stderr:INFO 11/17 02:27:35 n.l.b.p.h.BrowserMo~ - org.apache.http.conn.ConnectTimeoutException: Connect to www.google.com:443 [www.google.com/216.58.221.68] failed: Connection timed out when requesting https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-36116321-1&cid=567229463.1447727127&jid=1231009400&_v=j40&z=1601173305

2015-11-17T02:27:35.761Z - error: stderr:WARN 11/17 02:27:35 n.l.b.p.BrowserMobP~ - IOException while trying to report an HTTP error
java.io.IOException: closed
        at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.prepareOutput(HttpOutputStream.java:444)
        at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.write(HttpOutputStream.java:413)
        at net.lightbody.bmp.proxy.jetty.http.HttpOutputStream.write(HttpOutputStream.java:406)
        at net.lightbody.bmp.proxy.BrowserMobProxyHandler.reportError(BrowserMobProxyHandler.java:312)
        at net.lightbody.bmp.proxy.BrowserMobProxyHandler.access$200(BrowserMobProxyHandler.java:26)
        at net.lightbody.bmp.proxy.BrowserMobProxyHandler$1.reportError(BrowserMobProxyHandler.java:265)
        at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:832)
        at net.lightbody.bmp.proxy.http.BrowserMobHttpClient.execute(BrowserMobHttpClient.java:591)
        at net.lightbody.bmp.proxy.http.BrowserMobHttpRequest.execute(BrowserMobHttpRequest.java:149)
        at net.lightbody.bmp.proxy.BrowserMobProxyHandler.proxyPlainTextRequest(BrowserMobProxyHandler.java:269)
        at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:185)
        at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
        at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
        at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
        at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
        at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
        at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
        at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
        at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
        at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

2015-11-17T02:27:35.762Z - error: stderr:INFO 11/17 02:27:35 n.l.b.p.h.BrowserMo~ - EOFException(java.net.SocketException: Broken pipe) when requesting https://mozorg.cdn.mozilla.net/media/img/firefox/favicon.dc6635050bf5.ico

2015-11-17T02:27:35.762Z - error: stderr:WARN 11/17 02:27:35 n.l.b.p.j.h.HttpCon~ - Invalid length: Content-Length=8318 written=8192 for https://mozorg.cdn.mozilla.net/media/img/firefox/favicon.dc6635050bf5.ico

2015-11-17T02:27:36.084Z - error: stderr:INFO 11/17 02:27:36 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:49182

2015-11-17T02:27:37.759Z - error: stderr:INFO 11/17 02:27:37 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:44312

2015-11-17T02:27:37.984Z - error: stderr:INFO 11/17 02:27:37 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:36877

2015-11-17T02:27:38.157Z - error: stderr:INFO 11/17 02:27:38 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:36250

2015-11-17T02:27:38.258Z - error: stderr:INFO 11/17 02:27:38 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:34853

2015-11-17T02:27:41.250Z - info: Stopped proxy process.

kindly advise.

**Comment by une6** [comment]
hi, 

in addition, since the page www.sitespeed.io itself calls google analytics, we also tried other urls like www.baidu.com, but the error is the same. we had a hunch that it could be the docker sitespeed image which is trying to redownload firefox using mozilla... and mozilla itself has calls to google analytics..

**Comment by soulgalore** [comment]
One way to test is to install sitespeed.io useing npm, then it will run the current installed browser and you can configure it manually. 

Best
Peter

**Comment by une6** [comment]
alright we'll check that out. sorry for the trouble, this is specifically for those tests that can't download or access google or any other performance related links. for our case.. china. sad to say

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
