### ISSUE TITLE
HAR file is not generated

### ISSUE THREAD

**Issue by marcustisater** [sitespeedio/sitespeed.io#780]
After analyzing urls, I get the following error using Docker. I am running on Docker version 1.9.0 on OSX 10.11 

```Catched an uncaught exception:TypeError: Cannot read property 'har' of undefinedTypeError: Cannot read property 'har' of undefined
    at GraphiteCollector._getMeta (/usr/local/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84:15)
    at GraphiteCollector.collect (/usr/local/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:70:22)
    at Object.exports.task (/usr/local/lib/node_modules/sitespeed.io/lib/postTasks/sendToGraphite.js:17:32)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:181:32
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:709:13
    at /usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:227:13
    at _arrayEach (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:78:13)
    at _each (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:69:13)
    at async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:226:9)
    at _parallel (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:708:9)
Stopping proxy```

If you need any more information - feel free to ask.

Thank you,

**Comment by marcustisater** [comment]
running ```sitespeed.io -u http://www.cybercom.com --graphiteHost localhost -m 5 --graphiteNamespace cybercom -b chrome -n 11``` if that makes any diffrence!

**Comment by soulgalore** [comment]
hey @marcustisater , thanks for the bug report, I wonder if there could have been something more earlier in the log? I've tested locally now and for me at least it seems like cybercom.com have some problems (it fails during my runs). However the problem on our side is that we don't handle the errors from the browser/server in a good way and breaks. We got a better version coming out that handles this but its a long story and will ready for testing early next year.

Best
Peter

**Comment by marcustisater** [comment]
Thanks Peter,

I tried with another test and that went better - resolving in a no error.

**Comment by jurajseffer** [comment]
It's happening to me now, for various domains.

```
sudo docker run sitespeedio/sitespeed.io:3.11.1 sitespeed.io -u https://www.google.com/ -b firefox --seleniumServer http://127.0.1:4444/wd/hub --deep 0 --graphiteHost metrics-aggregator-graphite --graphiteNamespace frontend -v
Wed Dec 16 10:29:32 UTC 2015
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 46.0.2490.71
Mozilla Firefox 41.0.2
Starting Xvfb ...
Starting Selenium server ... access it at http://127.0.0.1:4444/wd/hub
info: OS: 'linux 3.16.0-4-amd64', Node.js: 'v4.2.1', sitespeed.io: '3.11.1', PhantomJS: '1.9.8', java: '1.7.0_79', browsertime: '0.12.0'
info: Will analyze 1 page
info: Running YSlow for https://www.google.com/ [phantomjs]
verbose: Done processing url in yslow: https://www.google.com/
Starting proxy on port 2001, will wait at most 15000 ms
info: Done analyzing urls
Catched an uncaught exception:TypeError: Cannot read property 'har' of undefinedTypeError: Cannot read property 'har' of undefined
    at GraphiteCollector._getMeta (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84:15)
    at GraphiteCollector.collect (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:70:22)
    at Object.exports.task (/usr/lib/node_modules/sitespeed.io/lib/postTasks/sendToGraphite.js:17:32)
    at /usr/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:181:32
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:709:13
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:227:13
    at _arrayEach (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:78:13)
    at _each (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:69:13)
    at async.forEachOf.async.eachOf (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:226:9)
    at _parallel (/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:708:9)
Stopping proxy
```

**Comment by soulgalore** [comment]
Hello @jurajseffer 
thanks for reporting, I'll re-open.

Best
Peter

**Comment by rmarx** [comment]
I am seeing the same thing, but only when specifying the --noYslow option

```
node ~/node_modules/sitespeed.io/bin/sitespeed.js -d 0 -v --noYslow --html false --graphiteHost 127.0.0.1 --phantomjsPath ~/node_modules/sitespeed.io/bin/phantomjs-2.1.1-linux-x86_64/bin/phantomjs -b headless -n 1 -u http://google.be

info: OS: 'linux 3.19.0-31-generic', Node.js: 'v4.2.1', sitespeed.io: '3.11.3', PhantomJS: '2.1.1', java: '1.7.0_91', browsertime: '0.12.2'
info: Will analyze 1 page
info: Fetching timing data using phantomjs for http://google.be
info: Done analyzing urls
/home/rmarx/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84
  if (pages[0].har) {
              ^

TypeError: Cannot read property 'har' of undefined
    at GraphiteCollector._getMeta (/home/rmarx/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:84:15)
    at GraphiteCollector.collect (/home/rmarx/node_modules/sitespeed.io/lib/graphite/graphiteCollector.js:70:22)
    at Object.exports.task (/home/rmarx/node_modules/sitespeed.io/lib/postTasks/sendToGraphite.js:17:32)
    at /home/rmarx/node_modules/sitespeed.io/lib/analyzeOneSite.js:181:32
    at /home/rmarx/node_modules/sitespeed.io/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/rmarx/node_modules/sitespeed.io/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/rmarx/node_modules/sitespeed.io/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/rmarx/node_modules/sitespeed.io/node_modules/async/lib/async.js:731:9)
    at AnalyzeOneSite._runPostTasks (/home/rmarx/node_modules/sitespeed.io/lib/analyzeOneSite.js:260:9)
    at /home/rmarx/node_modules/sitespeed.io/lib/analyzeOneSite.js:59:12
```
Just removing --noYslow fixes the problem

**Comment by freme** [comment]
Seems like graphite is relying on data written by Yslow/phantomjs to work. I had Yslow fail but browsertime work and that resulted in the same TypeError.

**Comment by alex-moreno** [comment]
Having the same problem, but it fails always regardless of having or not yslow.

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
