### ISSUE TITLE
Not getting the data for every run.

### ISSUE THREAD

**Issue by sunil-jhamnani** [sitespeedio/sitespeed.io#799]
Hi @soulgalore 
getting this error for the mobile website m.jcpenney.com:

Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:43:36
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:718:17
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/sitespeed.io/node_modules/browsertime/lib/browsertime.js:94:7
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at promise.ControlFlow.abortNow_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2023:10)
    at webdriver.EventEmitter.emit (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at goog.defineClass.abort (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2192:12)
    at promise.ControlFlow.abortFrame_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1811:9)
    at promise.Promise.notifyAll_ (/usr/lib/node_modules/sitespeed.io/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:547:16)
Stopping proxy

and this for the desktop website: www.jcpenney.com

info: Done analyzing urls
info: Couldn't decode URI:http://sales.liveperson.net/hc/1360182/?&visitor=112990572134769&msessionkey=5568804048430813996&siteContainer=Secondary1&site=1360182&cmd=mTagStartPage&lpCallId=384236081503-806917971232&protV=20&lpjson=1&page=http%3A//www.jcpenney.com/&id=160155471&javaSupport=false&visitorStatus=INSITE_STATUS&activePlugin=none&cobrowse=true&pageWindowName=undefined&PV%21lpTagVer=1.5.1&PV%21visitorActive=1&title=JCPenney%3A%20Furniture%2C%20Window%20%26%20Home%20D%E9cor%2C%20Fashion%20Clothing%20%26%20More%20-%20JCPenney&cobrowse=true

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
