### ISSUE TITLE
Couldn't send data to Graphite:Error: read ECONNRESET for host:10.11.12.202 port:2003

### ISSUE THREAD

**Issue by gugansankar** [sitespeedio/sitespeed.io#808]
Hi,

First of all  Thanks for this wonderful project. 

There is no issue on setup. But started to get some error message in log file.

Sometimes it shows below error, some times its running smoothly . Could you please what is the reason behind this error message  ?.

error: Couldn't send data to Graphite:Error: read ECONNRESET for host:10.11.12.202 port:2003
/usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43:36
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at Socket.<anonymous> (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteSender.js:30:7)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1257:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by soulgalore** [comment]
Hi @gugansankar ,
thanks for the kind words. It seems like Graphite is closing the connection. Can you tell me more about your setup? Do you run our Graphite Docker container or your own instance?

Best
Peter

**Comment by gugansankar** [comment]
Hi Peter. I'm using your Graphite Docker container only.

Sometime, I'm getting error message and sometimes I didn't

**Comment by soulgalore** [comment]
Hi @gugansankar 
is it from the example in you cron? Thinking that best case if you do the it less frequent it will automatically work.

Best
Peter

**Comment by jrbeilke** [comment]
Having similar issues with my sitespeed setup (CentOS 7 with Docker running Chrome + Firefox + Xvfb via Selenium).

[32minfo[39m: Done analyzing urls
[32minfo[39m: Sending data to Graphite host:<graphite_ip> port:2003
[31merror[39m: Couldn't send data to Graphite:Error: write EPIPE for host:<graphite_ip> port:2003
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:43:36
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:167:37
    at Socket.<anonymous> (/usr/lib/node_modules/sitespeed.io/lib/graphite/graphiteSender.js:29:7)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
Stopping proxy

AFAICT it seems that the Graphite connection/socket gets stuck and the graphiteSender.js in sitespeed.io fails because it is trying to re-use the socket. (ie. https://github.com/dropwizard/metrics/issues/669)

**Comment by soulgalore** [comment]
Hey @jrbeilke so like sitspeed.io keeps the connection open too long and Graphite closes the connection, we try to open again and fails? With the current version we send soooo much data in some cases, I guess that is the root of all evil or?

**Comment by jrbeilke** [comment]
Yea, may want to close the connection/destroy the socket and open a new connection when writing data to avoid issues (ie. https://github.com/LibertyGlobal/metrics/pull/1)

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by lapa182** [comment]
Hi @soulgalore, I just got the same issue using 4.5.1:

```
[2017-03-08 15:22:15] Render HTML for 217 page(s) 
[2017-03-08 15:25:46] {"cause":{"code":"ECONNRESET"},"isOperational":true,"code":"ECONNRESET"}
    at TLSSocket.onHangUp (_tls_wrap.js:1094:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at TLSSocket.Readable.on (_stream_readable.js:687:35)
    at tickOnSocket (_http_client.js:560:10)
    at onSocketNT (_http_client.js:580:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ClientRequest.onSocket (_http_client.js:572:11)
    at _http_agent.js:164:11
    at oncreate (_http_agent.js:235:5)
    at Agent.createSocket (_http_agent.js:197:5)
    at Agent.addRequest (_http_agent.js:157:10)
    at new ClientRequest (_http_client.js:160:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Request.start (/usr/src/app/node_modules/request/request.js:793:30)
    at Request.write (/usr/src/app/node_modules/request/request.js:1390:10)
    at end (/usr/src/app/node_modules/request/request.js:550:16)
    at Immediate.<anonymous> (/usr/src/app/node_modules/request/request.js:578:7)
From previous event:
    at Object.close (/usr/src/app/lib/plugins/slack/index.js:61:20)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
From previous event:
    at runOptionalFunction (/usr/src/app/lib/sitespeed.js:45:6)
    at runOptionalFunction.then.then.tap (/usr/src/app/lib/sitespeed.js:118:32)
From previous event:
    at loader.loadPlugins.then (/usr/src/app/lib/sitespeed.js:118:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at storageManager.createDataDir.then.then.then.then.then (/usr/src/app/lib/sitespeed.js:102:12)
From previous event:
    at Object.run (/usr/src/app/lib/sitespeed.js:99:8)
    at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:29:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
    at Request.init (/usr/src/app/node_modules/request/request.js:200:10)
    at new Request (/usr/src/app/node_modules/request/request.js:140:8)
    at request (/usr/src/app/node_modules/request/index.js:55:10)
    at Function.post (/usr/src/app/node_modules/request/index.js:63:12)
    at Slack.send (/usr/src/app/node_modules/node-slack/slack.js:38:21)
    at Object.close (/usr/src/app/lib/plugins/slack/index.js:61:20)
    at Promise.resolve.filter.map (/usr/src/app/lib/sitespeed.js:45:49)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
time="2017-03-08T15:25:46Z" level=debug msg="[hijack] End of stdout" 
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/workspace/output to /var/lib/jenkins/jobs/daily_performance_test_www.volkswagen.co.uk_chrome/htmlreports/Sitespeed.io_Report
Triggering a new build of REBOOT_JENKINS_SERVER
Finished: FAILURE

**Comment by soulgalore** [comment]
Hey @lapa182 looking at the trace log this seems to come from Slack and not Graphite as in the original issue? Can you please create a new issue and add some more info on how you run, your setup, does it happen all the time or just once? The more info the better :)

Best
Peter
