### ISSUE TITLE
Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.

### ISSUE THREAD

**Issue by JayboBaker** [sitespeedio/sitespeed.io#811]
I'm trying to run browser timings through Firefox and I'm getting intermittent errors. Happens around once every 4-5 runs. I've tried changing the timeouts in browsertime.js but its not helped. 

I'm using the latest version of sitespeed.io and phantomjs 2.0.

Command output error:

```bash

[32minfo[39m: Running browsertime for firefox https://www.crunch.co.uk/guides/limited-company-beginners-guide/
Fetching https://www.crunch.co.uk/guides/limited-company-beginners-guide/ (1 of 3)

Fetching https://www.crunch.co.uk/guides/limited-company-beginners-guide/ (2 of 3)

Catched an uncaught exception:Error: Callback was already called.Error: Callback was already called.
    at /var/lib/jenkins/workspace/crunch-website-performance/node_modules/async/lib/async.js:43:36
    at /var/lib/jenkins/workspace/crunch-website-performance/node_modules/async/lib/async.js:723:17
    at /var/lib/jenkins/workspace/crunch-website-performance/node_modules/async/lib/async.js:167:37
    at /var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/lib/browsertime.js:95:7
    at webdriver.EventEmitter.emit (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at promise.ControlFlow.abortNow_ (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2023:10)
    at webdriver.EventEmitter.emit (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/events.js:55:17)
    at goog.defineClass.abort (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2192:12)
    at promise.ControlFlow.abortFrame_ (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1811:9)
    at promise.Promise.notifyAll_ (/var/lib/jenkins/workspace/crunch-website-performance/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:547:16)
Stopping proxy

```

**Comment by soulgalore** [comment]
Hi @JayboBaker thanks for the report! 

We have a known problem with handling errors in the current version of Browsertime, it is callback hell .. but the new version is coming though. There will will try again if something fails.

Have you noticed if it happens on the same URL or is it different?
Best
Peter

**Comment by JayboBaker** [comment]
Hi Peter,

I've been testing against a set of URLs and this error occurs intermittently on different ones. 

Regards

James

**Comment by chungmankim** [comment]
I'm getting the same issue

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.
